force-app/zurich-base/main/default/objects/Cover__c/Cover__c.object-meta.xml
<CustomObject>
    <label>Cobertura</label>
    <nameField>
        <label>Nombre de Cobertura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coberturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Cover__c/fields/CoverId__c.field-meta.xml
<CustomField>
    <fullName>CoverId__c</fullName>
    <externalId>true</externalId>
    <label>Cover ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descripción</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to, used to set access with sharing rules</description>
    <label>Entidad legal</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/ParentCoverId__c.field-meta.xml
<CustomField>
    <fullName>ParentCoverId__c</fullName>
    <label>ParentCoverId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/SumInsured__c.field-meta.xml
<CustomField>
    <fullName>SumInsured__c</fullName>
    <label>Capital asegurado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/ItemAge__c.field-meta.xml
<CustomField>
    <fullName>ItemAge__c</fullName>
    <description>Product age in months</description>
    <inlineHelpText>Product age in months</inlineHelpText>
    <label>Antigüedad</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/ItemId__c.field-meta.xml
<CustomField>
    <fullName>ItemId__c</fullName>
    <description>Unique identifier or an insured product</description>
    <externalId>true</externalId>
    <label>Item Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Test_CoverUtil.cls
/**
 * Clases de test para CoverUtil
 **
 * @author nbizkarra
 * @date 27/04/2020
 */

@isTest(SeeAllData = false)
public with sharing class Test_CoverUtil
{
    @testSetup
    static void makeData()
    {}

    @IsTest
    static void test_createCovers()
    {
        Map<String, Cover__c> subCoversToInsertQuote = new Map<String, Cover__c>();
        Map<String, Cover__c> updateCover = new Map<String, Cover__c>();
        Map<String, Cover__c> mapCovers = new Map<String, Cover__c>();

        OrderItem item = new OrderItem(itemId__c = '7777', ItemAge__c = 2);
        List<Cover__c> listCovers = new List<Cover__c>();
        Cover__c cover = new Cover__c(
            CoverId__c = '1',
            ParentCoverId__c = null,
            Name = 'Robo',
            Description__c = 'Cobertura por robo',
            SumInsured__c = 1000
            );
        listCovers.add(cover);
        Cover__c cover2 = new Cover__c(
            CoverId__c = '2',
            ParentCoverId__c = '1',
            Name = 'Sub-Robo',
            Description__c = 'SubCobertura por robo',
            SumInsured__c = 150
            );
        listCovers.add(cover2);

        String LegalEntity = Label.GeneralInsurance;
        User recordOwner = SystemUtil.RecordOwnerSelector();
        Test.startTest();
        //covers no existen en Salesforce
        CoverUtil.addCovers(
            item,
            listCovers,
            subCoversToInsertQuote,
            mapCovers,
            updateCover,
            LegalEntity,
            recordOwner
            );
        System.assert (
            updateCover != null &&
            subCoversToInsertQuote != null,
            'Test_CoverUtil: Error al insertar covers y subcovers nuevas'
            );

        Test.stopTest();
    }

    @IsTest
    static void test_updateCover()
    {
        Map<String, Cover__c> subCoversToInsertQuote = new Map<String, Cover__c>();
        Map<String, Cover__c> updateCover = new Map<String, Cover__c>();
        Map<String, Cover__c> mapCovers = new Map<String, Cover__c>();

        OrderItem item = new OrderItem(itemId__c = '7777', ItemAge__c = 2);
        List<Cover__c> listCovers = new List<Cover__c>();
        Cover__c cover = new Cover__c(
            CoverId__c = '1',
            ParentCoverId__c = null,
            Name = 'Robo',
            Description__c = 'Cobertura por robo',
            SumInsured__c = 1000,
            LegalEntity__c = Label.GeneralInsurance
            );
        listCovers.add(cover);

        cover.CoverId__c = item.itemId__c + '-' + cover.Name;
        insert cover;

        SET<String> keys = new Set<String>();
        keys.add(cover.CoverId__c);
        mapCovers = SystemUtil.CoversSelector(keys);

        String LegalEntity = Label.GeneralInsurance;
        User recordOwner = SystemUtil.RecordOwnerSelector();
        Test.startTest();

        //covers  existen en Salesforce
        CoverUtil.addCovers(
            item,
            listCovers,
            subCoversToInsertQuote,
            mapCovers,
            updateCover,
            LegalEntity,
            recordOwner
            );
        System.assert (
            updateCover != null,
            'Test_CoverUtil: Error al insertar covers y subcovers existentes'
            );

        Test.stopTest();
    }
}