force-app/zurich-base/main/default/objects/Cover__c/Cover__c.object-meta.xml
<CustomObject>
    <label>Cobertura</label>
    <nameField>
        <label>Nombre de Cobertura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coberturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Cover__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to, used to set access with sharing rules</description>
    <label>Entidad legal</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/PolicyProduct__c.field-meta.xml
<CustomField>
    <fullName>PolicyProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto asegurado</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Coberturas</relationshipLabel>
    <relationshipName>Coberturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/PolicyNum__c.field-meta.xml
<CustomField>
    <fullName>PolicyNum__c</fullName>
    <externalId>true</externalId>
    <label>Número de la póliza</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/QuoteEntry__c.field-meta.xml
<CustomField>
    <fullName>QuoteEntry__c</fullName>
    <externalId>true</externalId>
    <label>Quote entry</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/TransportType__c.field-meta.xml
<CustomField>
    <fullName>TransportType__c</fullName>
    <description>KLINC: Indica el producto de movilidad escogido</description>
    <label>Transport Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SEGWAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies if the product is active in the policy</description>
    <inlineHelpText>Specifies if the product is active in the policy</inlineHelpText>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nintendo</fullName>
            </value>
            <value>
                <fullName>Micro</fullName>
            </value>
            <value>
                <fullName>Raycool</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>Moma Bikes</fullName>
            </value>
            <value>
                <fullName>Urban Fox</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
            <value>
                <fullName>E-Twow</fullName>
            </value>
            <value>
                <fullName>LG</fullName>
            </value>
            <value>
                <fullName>Nilox</fullName>
            </value>
            <value>
                <fullName>Huawei</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Segway</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>MSI</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoría</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Laptop</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Game Console</fullName>
            </value>
            <value>
                <fullName>Smartphone</fullName>
            </value>
            <value>
                <fullName>GoPro</fullName>
            </value>
            <value>
                <fullName>ELECTRIC BIKE</fullName>
            </value>
            <value>
                <fullName>Electric Scooter</fullName>
            </value>
            <value>
                <fullName>Smartwatch</fullName>
            </value>
            <value>
                <fullName>Insured Person</fullName>
            </value>
            <value>
                <fullName>Airpods</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/ItemId__c.field-meta.xml
<CustomField>
    <fullName>ItemId__c</fullName>
    <description>Unique identifier or an insured product</description>
    <externalId>true</externalId>
    <label>Item Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/itemModel__c.field-meta.xml
<CustomField>
    <fullName>itemModel__c</fullName>
    <label>Modelo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/TransportType__c.field-meta.xml
<CustomField>
    <fullName>TransportType__c</fullName>
    <description>KLINC: Indica el producto de movilidad escogido</description>
    <label>Transport Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ELECTRIC BIKE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PricebookEntry/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <externalId>true</externalId>
    <label>ProductID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <description>Field to be used as external ID of the product</description>
    <externalId>true</externalId>
    <label>ProductID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/OrderItemUtil.cls
/**
 * @author nbizkarra
 * @date 08/04/2020
 **/
public class OrderItemUtil
{
    /**
     * Método que inserta o actualiza el producto asegurado y sus objetos relacionados.
     * @author nbizkarra
     * @date 08/04/2020
     **/
    public static void createOrderItem(
        Order order,
        List<Orderitem> listOrderItems,
        Map<String, OrderItem> mapOrderItem,
        Map<String, PricebookEntry> mapProducts,
        Map<String, Product2> productsToInsert,
        Map<String, PricebookEntry> pricebookEntryToInsert,
        Pricebook2 Pricebook,
        Map<String, OrderItem> orederItemsToInsert,
        List<Cover__c> listCovers,
        Map<String, Cover__c> subCoversToInsertQuote,
        Map<String, Cover__c> mapCovers,
        Map<String, Cover__c> updateCover,
        User recordOwner
        )
    {
        
        //crear mapa con covers de cada OrderItem
        Map<String, List<Cover__c> > receivedCovers = new Map<String, List<Cover__c> >();
        if (listCovers != null)
        {
            for (Cover__c cover : listCovers)
            {
                if ( receivedCovers.containsKey(cover.PolicyProduct__r.ItemId__c) )
                {
                    List<Cover__c> existingItemId = receivedCovers.get( cover.PolicyProduct__r.ItemId__c );
                    existingItemId.add(cover);
                    receivedCovers.put(cover.PolicyProduct__r.ItemId__c, existingItemId);
                }
                else
                {
                    receivedCovers.put( cover.PolicyProduct__r.ItemId__c, new List<Cover__c> { cover } );
                }
            }
        }
        
        
        if (listOrderItems != null)
        {
            for (OrderItem item : listOrderItems)
            {
                //get the list of covers for this order item
                List<Cover__c> covers = new List<Cover__c>();
                covers = receivedCovers.get(item.ItemId__c);

                OrderItem orderItemSF = mapOrderItem.get(item.ItemId__c);
                if (orderItemSF != null)
                {
                    
                    item.Id = orderItemSF.Id;

                    // mantener solo el external ID de la poliza
                    if (item.Order.PolicyNum__c != null)
                    {
                        item.Order.QuoteEntry__c = null;
                    }
                }
                else
                {
                    
                    //if order Item doesn't exist, relate product2
                    PricebookEntry productSF;
                    //Search product by product name
                    if (item.itemModel__c != null)
                    {
                        //GI insurance
                        productSF = mapProducts.get(item.itemModel__c);
                    }
                     // nts (nbizkarra) - 27/abr/2021 - Multiproduct
                    else if (item.TransportType__c != null){
                        
                        productSF = mapProducts.get(item.TransportType__c);
                    }
                    else
                    {
                        //life insurance: category: insured person
                        productSF = mapProducts.get(item.Category__c);
                    }

                    if (productSF != null)
                    {
                        
                        item.PricebookEntryId = productSF.Id;
                    }
                    else
                    {
                        
                        createProduct( item, productsToInsert, pricebookEntryToInsert, Pricebook );
                        PricebookEntry pricebookRef;

                        if (item.itemModel__c != null)
                        {
                            //GI insurance
                            pricebookRef = new PricebookEntry( ProductID__c = item.itemModel__c );
                        }
                        // nts (nbizkarra) - 27/abr/2021 - Multiproduct
                        else if (item.TransportType__c != null){
                            
                            pricebookRef = new PricebookEntry( ProductID__c = item.TransportType__c );

                        }
                        else if (item.Category__c != null)
                        {
                            //life
                            pricebookRef = new PricebookEntry( ProductID__c = item.Category__c );
                            item.itemModel__c = item.Category__c;
                        }
                        else
                        {
                            //if mandatory value empty in life
                            pricebookRef = new PricebookEntry( ProductID__c = 'Insured Person' );
                            item.itemModel__c = 'Insured Person';
                        }
                        item.PricebookEntry = pricebookRef;
                    }

                    item.Active__c = true;
                    item.UnitPrice = 0;
                    item.Quantity = 1;
                    item.ServiceDate = order.EffectiveDate + 1;
                }
                CoverUtil.addCovers(
                    item,
                    covers,
                    subCoversToInsertQuote,
                    mapCovers,
                    updateCover,
                    order.LegalEntity__c,
                    recordOwner
                    );
                
                orederItemsToInsert.put(item.ItemId__c, item);
            }
        }
    }

    /**
     * Método que crea un producto nuevo cuando no existe en Salesforce.
     * @author nbizkarra
     * @date 08/04/2020
     **/
    public static void createProduct(
        OrderItem item,
        Map<String, Product2> productsToInsert,
        Map<String, PricebookEntry> pricebookEntryToInsert,
        Pricebook2 Pricebook
        )
    {
        
        String productID;

        if (item.itemModel__c != null)
        {
            productID = item.itemModel__c;
        }
        // nts (nbizkarra) - 27/abr/2021 - Multiproduct
        else if (item.TransportType__c != null){
                        
            productID = item.TransportType__c;
        }
        else if (item.Category__c != null)
        {
            productID = item.Category__c;
        }
        else
        {
            productID = 'Insured Person';
        }

        PricebookEntry pricebookEntry = new PricebookEntry(
            UnitPrice = 0,
            ProductID__c = productID,
            Pricebook2Id = Pricebook.Id,
            IsActive = true
            );
        Product2 prodRef = new Product2(ProductID__c = productID);
        pricebookEntry.Product2 = prodRef;

        if ( !pricebookEntryToInsert.containsKey(pricebookEntry.ProductID__c) )
        {
            pricebookEntryToInsert.put(pricebookEntry.ProductID__c, pricebookEntry);
        }

        Product2 newProduct = new Product2(
            ProductID__c = productID,
            Name = productID,
            Family = item.Category__c,
            Brand__c = item.Brand__c,
            IsActive = true
            );

        if ( !productsToInsert.containsKey(newProduct.ProductID__c) )
        {
            productsToInsert.put(newProduct.ProductID__c, newProduct);
        }
    }

    /**
     * Método que desactiva un producto de la póliza
     * @author nbizkarra
     * @date 08/04/2020
     **/
    public static void deactivateOldProduct(
        Order policy,
        List<Orderitem> listOrderItems,
        Map<String, OrderItem> orederItemsToInsert
        )
    {
        
        Map<String, OrderItem> mapReceivedItems = new Map<String, OrderItem>();

        for (Orderitem ordItem : listOrderItems)
        {
            //mapa con los items recibidos
            // mapReceivedItems.put(renameItemId(policy, ordItem.ItemId__c), ordItem);
            mapReceivedItems.put(ordItem.ItemId__c, ordItem);
        }

        for (OrderItem itemSF : policy.OrderItems)
        {
            OrderItem receivedItem = mapReceivedItems.get(itemSF.ItemId__c);
            if (receivedItem == null)
            {
                //El producto no se ha recibido, marcar active=false
                
                itemSF.Active__c = false;
                orederItemsToInsert.put(itemSF.ItemId__c, itemSF);
            }
        }
    }
}