force-app/zurich-base/main/default/objects/KPI__c/KPI__c.object-meta.xml
<CustomObject>
    <description>SDM: KPIs de mediadores</description>
    <label>KPI</label>
    <nameField>
        <label>KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/KPI__c/fields/CalcMonth__c.field-meta.xml
<CustomField>
    <fullName>CalcMonth__c</fullName>
    <label>Mes Cálculo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/KPI__c/fields/CalcYear__c.field-meta.xml
<CustomField>
    <fullName>CalcYear__c</fullName>
    <description>Año en el que se realizan los cálculos</description>
    <inlineHelpText>Año en el que se realizan los cálculos</inlineHelpText>
    <label>Año Cálculo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/KPI__c/fields/Intermediary__c.field-meta.xml
<CustomField>
    <fullName>Intermediary__c</fullName>
    <label>Intermediario</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KPIs</relationshipLabel>
    <relationshipName>KPIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/zurich-base/main/default/objects/KPI__c/fields/Temporalidad__c.field-meta.xml
<CustomField>
    <fullName>Temporalidad__c</fullName>
    <label>Temporalidad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>YTD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-sdm-app/main/default/classes/KPIsSelector.cls
/**
 * Clase selector del objeto KPI__c
 *
 * Proyecto: SDM (Sales Digital Management)
 *
 * @author nts (agonzalezisasi)
 * @date 28/07/2021
 */
public with sharing class KPIsSelector extends RecordsSelector {
    public static final String TEMPORALIDAD_YTD = 'YTD';
    public static final String TEMPORALIDAD_MONTH = 'Mensual';
    public static final String FIELD_MONTH = 'CalcMonth__c';

    /**
     * Constructor
     */
    public KPIsSelector() 
    {
        super(KPI__c.getSObjectType());
    }

    /**
     * Recupera los KPIs asociados a los mediadores datos.
     * En la consulta incluye los campos que se pasan como parametro
     * 
     * SDM-729 - Se modifica el proceso para reducir el numero de KPIs devueltos cada vez. Añadiendo tanto el tipo
     * de temporalidad (mensual, anual), como el año y mes de los kpis a recuperar.
     * 
     * @author nts (agonzalezisasi)
     * @date 28/07/2021
     * 
     * @param {List<ID> intermediaries} lista de ids mediadores
     * @param {List<String> tempoTypes} Tipos de temporalidad
     * @param {String theYear} año de calculo
     * @param {String theMonth} mes de calculo
     * @param {Set<String> fields} lista de campos de KPI
     * @return {List<KPI__c>} lista de KPIs encontrados
     */
    public List<KPI__c> findByIntermediaryIds(
        List<ID> intermediaries, List<String> tempoTypes, 
        String theYear, String theMonth,
        Set<String> fields)
    {
        List<KPI__c> result = null;

        if( intermediaries != null && !intermediaries.isEmpty() 
            && tempoTypes != null && !tempoTypes.isEmpty()
            && String.isNotBlank(theYear) && String.isNotBlank(theMonth)
            && fields != null && !fields.isEmpty() ) 
        {
            this.baseQuery.selectFields(fields);
            this.baseQuery.addConditionIn(KPI__c.Intermediary__c, intermediaries);
            this.baseQuery.addConditionIn(KPI__c.Temporalidad__c, tempoTypes);
            this.baseQuery.addConditionEq(KPI__c.CalcYear__c, theYear);
            this.baseQuery.addConditionEq(KPI__c.CalcMonth__c, theMonth);

            result = (List<KPI__c>)this.baseQuery.run();
        }

        return result;
    }

    /**
     * Recupera el ultimo mes que hay KPIs de tipo anual para el año en curso
     *
     * @author nts (agonzalezisasi)
     * @date 27/10/2021
     *
     * @return {String} el ultimo mes
     */
    public String findThisYearsLastMonth()
    {
        Integer thisYear = Date.today().year();

        if( Test.isRunningTest() ) thisYear = 2021;

        this.baseQuery.selectFields(new List<Schema.SObjectField> {
                KPI__c.CalcMonth__c
            });
        this.baseQuery.addConditionEq(KPI__c.Temporalidad__c, TEMPORALIDAD_YTD);
        this.baseQuery.addConditionEq(KPI__c.CalcYear__c, String.valueOf(thisYear));
        this.baseQuery.groupBy(FIELD_MONTH);

        
        // Como el campo mes es string. hay que convertirlos a integer para saber cual es el mayor numericamente
        // Ej.: 10,8,11,5
        Integer thisMonth = 0;
        List<AggregateResult> months = (List<AggregateResult>)this.baseQuery.run();
        for(AggregateResult agr: months) {
            Integer intValue = Integer.valueOf(agr.get(FIELD_MONTH));
            if( intValue > thisMonth ) thisMonth = intValue;
        }
        String result = (thisMonth != 0 ? String.valueOf(thisMonth) : null);

        return result;
    }
}