force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Scope_Setting__mdt/Scope_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Información sobre los scopes de Zurich Empresas para crear los registros en función del campo BusinessCode recibido en el formulario web</description>
    <label>Scope Setting</label>
    <pluralLabel>Scope Settings</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope_Setting__mdt/fields/Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Sandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sandbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Scope_Setting__mdt/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Scope_Setting__mdt/fields/Scope_Name__c.field-meta.xml
<CustomField>
    <fullName>Scope_Name__c</fullName>
    <label>Scope Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/classes/ScopeSettingsSelector.cls
public class ScopeSettingsSelector
{
    Boolean isSandbox;

    public ScopeSettingsSelector()
    {
        if( Test.isRunningTest() )
        {
            isSandbox = true;
        }
        else
        {
            isSandbox = [SELECT Id, isSandbox FROM Organization LIMIT 1].isSandbox;
        }
    }

    /**
     * Obtiene una lista de metadatos de scope
     *
     * @author adelgado
     * @date 09/12/2020
     * @return Listado scope settings recuperados
     */
    public List<Scope_Setting__mdt> selectAll()
    {
        if(isSandbox)
        {
            return [SELECT BusinessCode__c, Scope__c, Scope_Name__c FROM Scope_Setting__mdt WHERE Sandbox__c = true];
        }
        else
        {
            return [SELECT BusinessCode__c, Scope__c, Scope_Name__c FROM Scope_Setting__mdt WHERE Sandbox__c = false];
        }
    }

    /**
     * Obtiene una lista de metadatos de scope a partir de una lista de códigos de negocio
     *
     * @author adelgado
     * @date 09/12/2020
     * @param  businessCodes Listado de códigos de negocio
     * @return Listado scope settings recuperados
     */
    public List<Scope_Setting__mdt> selectByBusinessCode(Set<String> businessCodes)
    {
        if(isSandbox)
        {
            return [SELECT BusinessCode__c, Scope__c, Scope_Name__c FROM Scope_Setting__mdt WHERE Sandbox__c = true AND BusinessCode__c IN : businessCodes];
        }
        else
        {
            return [SELECT BusinessCode__c, Scope__c, Scope_Name__c FROM Scope_Setting__mdt WHERE Sandbox__c = false AND BusinessCode__c IN : businessCodes];
        }
    }

}