force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/fields/TechnicalIncidence__c.field-meta.xml
<CustomField>
    <fullName>TechnicalIncidence__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[ZE]Campo que indica si una cuenta tiene alguna incidencia técnica</description>
    <label>Technical incidence</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/classes/TechnicalIncidenceControllerTest.cls
/**
 * @description       : 
 * @author            : jjuaristi
 * @group             : 
 * @last modified on  : 08-10-2021
 * @last modified by  : jjuaristi
**/
@isTest(SeeAllData=false)
public with sharing class TechnicalIncidenceControllerTest
{
    
    @TestSetup
    static void createScenario()
    {
        List<Account> accounts = TestDataFactory.generateAccounts('001', 'Customer', 10);
        insert accounts;

        List<Scope__c> scopes = TestDataFactory.generateScopesForEachAccount(accounts, 'ZE', 1);
        for(Scope__c s : scopes)
        {
            s.TechnicalIncidence__c = true;
        }

        insert scopes;
    }

    @isTest
    static void test_getScope_ok()
    {
        test.startTest();
        Account account = [SELECT Id FROM Account LIMIT 1];
        Boolean check = TechnicalIncidenceController.getScope(account.Id);
        test.stopTest();
        System.assertEquals(true, check);
    }

    @isTest
    static void test_getScope_ko()
    {
        test.startTest();
        try{
            Boolean check = TechnicalIncidenceController.getScope(null);
        }catch(Exception e) {
            System.assertEquals(true, e.getTypeName().contains('AuraHandledException'), 'AuraException sent to the component');   
        }
        test.stopTest();        
    }
}