force-app/zurich-base/main/default/objects/Special_Condition__c/Special_Condition__c.object-meta.xml
<CustomObject>
    <label>Condición especial</label>
    <nameField>
        <label>Condition Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condiciones especiales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Special_Condition__c/fields/TerritorialDirection__c.field-meta.xml
<CustomField>
    <fullName>TerritorialDirection__c</fullName>
    <label>Territorial Direction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Special_Condition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/classes/SpecialConditionsSelectorTest.cls
@IsTest
public with sharing class SpecialConditionsSelectorTest {
    
    @IsTest
    static void test_findAgreements_OK()
    {
        List<Special_Condition__c> agreements = new List<Special_Condition__c>();
        Special_Condition__c agreement = new Special_Condition__c();
        agreement.TerritorialDirection__c =  'DT Madrid';
        agreement.Type__c = 'Agreement';
        agreements.add(agreement);
        insert(agreements);

        List<Special_Condition__c> retrievedAgreements = new SpecialConditionsSelector().findAgreements('235', 'DT Madrid');
        system.assertEquals(agreements.size(), retrievedAgreements.size());
    }
}