force-app/zurich-base/main/default/objects/CustomerWarning__c/CustomerWarning__c.object-meta.xml
<CustomObject>
    <label>Customer Warning</label>
    <nameField>
        <label>Customer Warning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Warnings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/RelatedAccount__c/RelatedAccount__c.object-meta.xml
<CustomObject>
    <label>Related Account</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Related Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/RelatedAccount__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/RelatedAccount__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <label>Warning</label>
    <referenceTo>CustomerWarning__c</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>RelatedAccounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/classes/RelatedAccountsSelectorTest.cls
@IsTest
public with sharing class RelatedAccountsSelectorTest {
    @IsTest
    static void test_findRelatedAccountsByIdentifier_OK()
    {
        List<CustomerWarning__c> warnings = new List<CustomerWarning__c>();
        CustomerWarning__c warning = new CustomerWarning__c();
        warning.StartDate__c = System.today();
        warning.Description__c = 'Descripción';
        warnings.add(warning);
        insert(warnings);

        RelatedAccount__c relation = new RelatedAccount__c();
        relation.Warning__c = warning.Id;
        relation.Identifier__c = '1122334455';
        insert(relation);

        List<RelatedAccount__c> retrievedRelations = new RelatedAccountsSelector().findRelatedAccountsByIdentifier('1122334455');
        system.assertEquals(warnings.size(), retrievedRelations.size());
    }
}