force-app/zurich-base/main/default/objects/CampaignMember/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <formula>TEXT(Campaign.Scope__c)</formula>
    <label>Scope</label>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/HashedId__c.field-meta.xml
<CustomField>
    <fullName>HashedId__c</fullName>
    <label>HashedId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <defaultValue>&quot;Z&quot;</defaultValue>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scope</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/HashedId__c.field-meta.xml
<CustomField>
    <fullName>HashedId__c</fullName>
    <description>A hash generated when an scope is created to be used in the Preference center. So the client can unsubscribe from emails.</description>
    <label>HashedId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/Scope.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z</fullName>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>ZE</fullName>
        <label>Zurich Empresas</label>
    </customValue>
    <customValue>
        <fullName>ZEO</fullName>
        <label>Zurich Empresas Orange</label>
    </customValue>
    <customValue>
        <fullName>ZEB</fullName>
        <label>Zurich Empresas Brokers</label>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
        <label>Zurich Ventas</label>
    </customValue>
    <customValue>
        <fullName>ZDA</fullName>
        <label>Zurich ZDA</label>
    </customValue>
    <masterLabel>Scope</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Test_PreferenceCentreProcessController.cls
@isTest(SeeAllData = false)
public with sharing class Test_PreferenceCentreProcessController
{
    @isTest
    static void doUpdate_testNull()
    {
        Contact c = new Contact();
        c.LastName = null;

        Test.startTest();
        PreferenceCentreProcessController.doUpdate(c);
        Test.stopTest();

        List<Error_Log__c> errorRecords = [SELECT Id FROM Error_Log__c];
        System.assertEquals( 1, errorRecords.size() );
    }

    @isTest
    static void doInsert_testNull()
    {
        List<CampaignMember> members = new List<CampaignMember>();
        CampaignMember c = new CampaignMember();
        c.CampaignId = null;
        members.add(c);
        Test.startTest();
        PreferenceCentreProcessController.doInsert(members);
        Test.stopTest();

        List<Error_Log__c> errorRecords = [SELECT Id FROM Error_Log__c];
        System.assertEquals( 1, errorRecords.size() );
    }

    @isTest
    static void doDelete_testNull()
    {
        List<CampaignMember> members = new List<CampaignMember>();
        CampaignMember c = new CampaignMember();
        c.CampaignId = null;
        members.add(c);

        Test.startTest();
        PreferenceCentreProcessController.doDelete(members);
        Test.stopTest();

        List<Error_Log__c> errorRecords = [SELECT Id FROM Error_Log__c];
        System.assertEquals( 1, errorRecords.size() );
    }

    /**
     * Test the select to Scope
     */
    @isTest
    static void test_getScopeData()
    {
        System.Debug('- - - - - Test_PreferenceCentreProcessController.test_getScopeData - - - - -');

        String hashid = '123456';

        List<Account> accounts = TestDataFactory.generateAccounts(Label.GeneralInsurance, 'Customer', 1);
        insert accounts;
        List<Scope__c> scopes = TestDataFactory.generateScopesForEachAccount(accounts, 'ZE', 1);
        scopes[0].HashedId__c = hashid;
        insert scopes;

        test.startTest();
        Scope__c scope = PreferenceCentreProcessController.getScopeData(hashid);
        test.stopTest();

        System.Debug('---------------- Results');
        System.assertNotEquals(null, scope, 'The scope should not be null');
        
    }
}