force-app/zurich-base/main/default/objects/AdminSetup__mdt/AdminSetup__mdt.object-meta.xml
<CustomObject>
    <label>AdminSetup</label>
    <pluralLabel>AdminSetup</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/AdminSetup__mdt/fields/WS_Source_IBA_Multi_Partner__c.field-meta.xml
<CustomField>
    <fullName>WS_Source_IBA_Multi_Partner__c</fullName>
    <description>The value of the Source field in the Webservice metadata to get the parser info for IBA Multi-Partner</description>
    <label>WS Source IBA Multi-Partner</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalRequest__c/ExternalRequest__c.object-meta.xml
<CustomObject>
    <description>Request sent by an external system that will be inserted in the processing queue.</description>
    <label>External request</label>
    <nameField>
        <displayFormat>ER{YY}{MM}{DD}{00000}</displayFormat>
        <label>External request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Indicates the country of the external system</description>
    <inlineHelpText>Indicates the country of the external system</inlineHelpText>
    <label>País</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>Indicates the type of information is being sent to Salesforce</description>
    <inlineHelpText>Indicates the type of information is being sent to Salesforce</inlineHelpText>
    <label>Entidad</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Error_Log_Response__c.field-meta.xml
<CustomField>
    <fullName>Error_Log_Response__c</fullName>
    <description>This field will store any error in the response to IBA (via middleware). Check AdminSetup metadata to see the Endpoint configurations.</description>
    <label>Error Log Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Json__c.field-meta.xml
<CustomField>
    <fullName>Json__c</fullName>
    <description>Contains the json message with all data to pass to Salesforce</description>
    <inlineHelpText>Contains the json message with all data to pass to Salesforce</inlineHelpText>
    <label>Json</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Indicates which external system sends data to Salesforce</description>
    <inlineHelpText>Indicates which external system sends data to Salesforce</inlineHelpText>
    <label>Origen</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the request has been processed</description>
    <inlineHelpText>Indicates if the request has been processed</inlineHelpText>
    <label>Procesado</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/ProcessResult__c.field-meta.xml
<CustomField>
    <fullName>ProcessResult__c</fullName>
    <description>Result of the request process</description>
    <inlineHelpText>Result of the request process</inlineHelpText>
    <label>Resultado del proceso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indicates the number of retries when sending the processing response to the external system</description>
    <label>Reintentos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the processing result has been sent to the external system</description>
    <label>Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/TimeStamp__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp__c</fullName>
    <label>Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/classes/Test_Batch_ResponseExternalRequest.cls
/**
 * Clases de test para Batch_ResponseExternalRequest
 **
 * @author nbizkarra
 * @date 05/04/2020
 *
 * @update nts (agonzalezisasi) - 27/oct/2020 - Include Multi-Partner logic and some corrections
 */
@isTest
public class Test_Batch_ResponseExternalRequest
{
    @TestSetup
    static void makeData()
    {
        // Es nesecesario indicar que el standard pricebook está activo para que el procesamiento no falle
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
            );
        // update standardPricebook;
    }

    @isTest
    static void testBatch()
    {
        List<ExternalRequest__c> ers = new List<ExternalRequest__c>();

        // IBA (spain)
        ExternalRequest__c er = new ExternalRequest__c(
            Timestamp__c = DateTime.now(),
            Origin__c = 'IBA',
            Country__c = 'Spain',
            Entity__c = 'test',
            Error_Log__c = '',
            Json__c = '{Test}',
            Processed__c = true,
            Sent__c = false,
            ProcessResult__c = 'OK',
            Retry__c = 0
            );
        ers.add(er);

        // IBA (not spain)
        er = new ExternalRequest__c(
            Timestamp__c = DateTime.now(),
            Origin__c = 'IBA',
            Country__c = 'France',
            Entity__c = 'test',
            Error_Log__c = '',
            Json__c = '{Test}',
            Processed__c = true,
            Sent__c = false,
            Retry__c = 0
            );
        ers.add(er);

        AdminSetup__mdt adminSetup = SystemUtil.getAdminSetupMetadata();
        String WS_SOURCE_IBA_MULTI_PARTNER = adminSetup.WS_Source_IBA_Multi_Partner__c;
        // IBA (multi-partner)
        er = new ExternalRequest__c(
            Timestamp__c = DateTime.now(),
            Origin__c = WS_SOURCE_IBA_MULTI_PARTNER,
            Country__c = 'Spain',
            Entity__c = 'test',
            Error_Log__c = '',
            Json__c = '{Test}',
            Processed__c = true,
            Sent__c = false,
            Retry__c = 0
            );
        ers.add(er);

        insert ers;

        // Set mock class
        Test.setMock( HttpCalloutMock.class, new Mock_IBA_ResponseGenerator() );

        // Test
        Test.startTest();
        Id BatchInstanceId = Database.executeBatch(
            new Batch_ResponseExternalRequest(),
            10
            );
        Test.stopTest();

        // Check results
        List<ExternalRequest__c> ersResult = [SELECT id, Sent__c FROM ExternalRequest__c];
        for( ExternalRequest__c e: ersResult)
        {
            System.assertEquals(true, e.Sent__c);
        }
    }

    /**
     * For testing process result NO ok, status request no 200 and for coverage
     * @change: nts (agonzalezisasi) - 11/dic/2020 - Include response error log 
     */
    @isTest
    static void testBatch_nok()
    {
        ExternalRequest__c er = new ExternalRequest__c(
            Timestamp__c = DateTime.now(),
            Origin__c = 'IBA',
            Country__c = 'Spain',
            Entity__c = 'test',
            Error_Log__c = '',
            Json__c = '{Test KO}',
            Processed__c = true,
            Sent__c = false,
            Retry__c = 0,
            ProcessResult__c = 'KO'
            );

        insert er;

        Test.setMock( HttpCalloutMock.class, new Mock_IBA_ResponseGenerator() );

        Test.startTest();
        Batch_ResponseExternalRequest b = new Batch_ResponseExternalRequest('select'); // for coverage
        b = new Batch_ResponseExternalRequest();
        Id BatchInstanceId = Database.executeBatch( b, 10 );
        Test.stopTest();
        // Check results
        List<ExternalRequest__c> ersResult = [SELECT id, Retry__c, Error_Log_Response__c FROM ExternalRequest__c];
        for( ExternalRequest__c e: ersResult)
        {
            System.assertEquals(1, e.Retry__c);
            System.assertNotEquals(null, e.Error_Log_Response__c);
        }
    }

    /**
     * For testing Schedule
     */
    @isTest
    static void testBatch_schedule()
    {
        Batch_ResponseExternalRequest m = new Batch_ResponseExternalRequest();
        String sch = '20 30 8 10 2 ?';

        Test.startTest();
        String jobID = system.schedule('Response External Request', sch, m);
        Test.stopTest();
        
    }
}