force-app/zurich-base/main/default/objects/AdminSetup__mdt/AdminSetup__mdt.object-meta.xml
<CustomObject>
    <label>AdminSetup</label>
    <pluralLabel>AdminSetup</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/AdminSetup__mdt/fields/IBA_Auth_token__c.field-meta.xml
<CustomField>
    <fullName>IBA_Auth_token__c</fullName>
    <label>IBA Authorization token</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/AdminSetup__mdt/fields/IBA_EMEA_Authorization_token__c.field-meta.xml
<CustomField>
    <fullName>IBA_EMEA_Authorization_token__c</fullName>
    <label>IBA EMEA Authorization token</label>
    <type>TextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/AdminSetup__mdt/fields/IBA_EMEA_endpoint__c.field-meta.xml
<CustomField>
    <fullName>IBA_EMEA_endpoint__c</fullName>
    <label>IBA EMEA endpoint</label>
    <type>TextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/AdminSetup__mdt/fields/IBA_EMEA_Non_Country__c.field-meta.xml
<CustomField>
    <fullName>IBA_EMEA_Non_Country__c</fullName>
    <description>The name of the country that is not considered for a request to be IBA EMEA</description>
    <label>IBA EMEA Non Country</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/AdminSetup__mdt/fields/IBA_endpoint__c.field-meta.xml
<CustomField>
    <fullName>IBA_endpoint__c</fullName>
    <label>IBA endpoint</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/AdminSetup__mdt/fields/IBA_Multi_Partner_Authorization_token__c.field-meta.xml
<CustomField>
    <fullName>IBA_Multi_Partner_Authorization_token__c</fullName>
    <label>IBA Multi-Partner Authorization token</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/AdminSetup__mdt/fields/IBA_Multi_Partner_endpoint__c.field-meta.xml
<CustomField>
    <fullName>IBA_Multi_Partner_endpoint__c</fullName>
    <label>IBA Multi-Partner endpoint</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/AdminSetup__mdt/fields/IBA_Multi_Partner_Origin__c.field-meta.xml
<CustomField>
    <fullName>IBA_Multi_Partner_Origin__c</fullName>
    <description>The text to be in the origin field of the External Request to be considered from IBA Multi-Partner</description>
    <label>IBA Multi-Partner Origin</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalRequest__c/ExternalRequest__c.object-meta.xml
<CustomObject>
    <description>Request sent by an external system that will be inserted in the processing queue.</description>
    <label>External request</label>
    <nameField>
        <displayFormat>ER{YY}{MM}{DD}{00000}</displayFormat>
        <label>External request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Indicates the country of the external system</description>
    <inlineHelpText>Indicates the country of the external system</inlineHelpText>
    <label>País</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>Indicates the type of information is being sent to Salesforce</description>
    <inlineHelpText>Indicates the type of information is being sent to Salesforce</inlineHelpText>
    <label>Entidad</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Json__c.field-meta.xml
<CustomField>
    <fullName>Json__c</fullName>
    <description>Contains the json message with all data to pass to Salesforce</description>
    <inlineHelpText>Contains the json message with all data to pass to Salesforce</inlineHelpText>
    <label>Json</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Indicates which external system sends data to Salesforce</description>
    <inlineHelpText>Indicates which external system sends data to Salesforce</inlineHelpText>
    <label>Origen</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/ProcessResult__c.field-meta.xml
<CustomField>
    <fullName>ProcessResult__c</fullName>
    <description>Result of the request process</description>
    <inlineHelpText>Result of the request process</inlineHelpText>
    <label>Resultado del proceso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indicates the number of retries when sending the processing response to the external system</description>
    <label>Reintentos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the processing result has been sent to the external system</description>
    <label>Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/TimeStamp__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp__c</fullName>
    <label>Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/classes/Batch_ResponseExternalRequest.cls
/**
 * Batch that responds to external system with the result of the processing
 * @Autor: nbizkarra (04/05/2020)
 * 
 * @change: nts (agonzalezisasi) - 26/oct/2020 - Include Multi-Partner
 **/

global class Batch_ResponseExternalRequest implements Database.Batchable<sObject>, Database.Stateful, Schedulable, Database.AllowsCallouts {
    public String query;
  
    global Batch_ResponseExternalRequest() {
    }
  
    global Batch_ResponseExternalRequest(String p_query) {
      if (!String.isBlank(p_query)) {
        query = p_query;
      }
    }
  
    global Database.QueryLocator start(Database.BatchableContext BC) {
      if (query == null || query == '') {
        query = SystemUtil.getProcessedExternalRequests();
      }
  
      return Database.getQueryLocator(query);
    }
  
    global void execute(SchedulableContext SC) {
      Database.executeBatch(new Batch_ResponseExternalRequest(query), 10);
    }
  
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
      if (scope != null && !scope.isEmpty()) {
        // Scope
        List<ExternalRequest__c> listExternalRequest = (List<ExternalRequest__c>) scope;
        // Metadata configuration
        AdminSetup__mdt adminSetup = SystemUtil.getAdminSetupMetadata();
        // JSON
        String json;
  
        try {
          // For each External Request
          for (ExternalRequest__c ExtReq : listExternalRequest) {
            String errorCode = Label.ErrorCodeSuccess;
            if (ExtReq.ProcessResult__c != 'OK') {
              errorCode = Label.ErrorCodeFail;
            }
  
            json = SystemUtil.createJSON(
              ExtReq.ID,
              errorCode,
              ExtReq.Error_Log__c,
              Datetime.now(),
              ExtReq.Origin__c,
              ExtReq.Country__c,
              ExtReq.Entity__c,
              ExtReq.Timestamp__c,
              ExtReq.Json__c
            );
  
            System.debug('**** JSON: ' + json);
            if( !String.isBlank(json) ) {
                Http http = new Http();
                HttpRequest request = new HttpRequest();
                System.debug('**** COUNTRY [' + ExtReq.Country__c + ']');
                System.debug('**** ORIGIN [' + ExtReq.Origin__c + ']');
  
                // nts (agonzalezisasi) - 26/oct/2020 - Include Multi-Partner
                // IBA Endpoint & Authorization Token
                String endPoint = adminSetup.IBA_endpoint__c;
                String authToken = adminSetup.IBA_Auth_token__c;
                if( ExtReq.Origin__c == adminSetup.IBA_Multi_Partner_Origin__c ) {
                    endPoint = adminSetup.IBA_Multi_Partner_endpoint__c;
                    authToken = adminSetup.IBA_Multi_Partner_Authorization_token__c;
                } else if( ExtReq.Country__c != adminSetup.IBA_EMEA_Non_Country__c ) {
                    endPoint = adminSetup.IBA_EMEA_endpoint__c;
                    authToken = adminSetup.IBA_EMEA_Authorization_token__c;
                }
  
                // Endpoint
                request.setEndpoint( endPoint );
                // Method
                request.setMethod('PUT');
                // Header: Content-Type
                request.setHeader('Content-Type', 'application/json');
                //request.setHeader('Ocp-Apim-Subscription-Key', adminSetup.IBA_Auth_token__c);
                // Header: Authorization
                request.setHeader( 'Authorization', authToken );
                // Body
                request.setBody(json);
                // SetTimeout
                request.setTimeout(30000);
  
                // Response
                HttpResponse response = new HttpResponse();
  
                System.debug('**** REQUEST: ' + request);
                response = http.send(request);
                
                // Respuesta a mi respuesta. Status Code
                if (response.getStatusCode() == 200) {
                  ExtReq.Sent__c = true;
                } else {
                  ExtReq.Retry__c = ExtReq.Retry__c + 1;
                }
            } else {
                //System.debug('Error creando Json de respuesta');
                ErrorLogUtil.commitError(Label.Error, Label.ErrorJSON + ' ' + ExtReq.Id, 'Batch_ResponseExternalRequest');
            }
          }
  
          update listExternalRequest;
        } catch (Exception e) {
          ErrorLogUtil.commitError(e, 'Batch_ResponseExternalRequest');
        }
      }
    }
  
    global void finish(Database.BatchableContext BC) {
    }
  }