force-app/zurich-base/main/default/objects/ContactPointAddress/fields/ScopeId__c.field-meta.xml
<CustomField>
    <fullName>ScopeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OCS</description>
    <label>Scope Name</label>
    <referenceTo>Scope__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>ContactPointAddresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/classes/ContactPointAddressUtil.cls
public class ContactPointAddressUtil
{
    /**
     * Método que controla la generación del scope correspondiente
     * Actualmente solo se generá scope para ContactPointAddress que provengan de INFO
     *
     * @author adelgado
     * @date 07/12/2020
     */
    public static void generateScope(List<ContactPointAddress> newList)
    {
        List<ContactPointAddress> cpaToGenerateScope = new List<ContactPointAddress>();

        for(ContactPointAddress contactPointAddress : newList)
        {
            if( String.isNotBlank(contactPointAddress.INFOContactPointNumber__c) && contactPointAddress.ScopeId__c == null && contactPointAddress.ParentId != null)
            {
                cpaToGenerateScope.add(contactPointAddress);
            }
        }

        if( !cpaToGenerateScope.isEmpty() )
        {
            GenerateScopeUtil.generateScopeEvents('ParentId', null, cpaToGenerateScope);
        }
    }
}