force-app/zurich-base/main/default/objects/RelatedAccount__c/RelatedAccount__c.object-meta.xml
<CustomObject>
    <label>Related Account</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Related Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/RelatedAccount__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/classes/RelatedAccountsSelector.cls
public with sharing class RelatedAccountsSelector extends RecordsSelector
{
    public RelatedAccountsSelector() 
    {
        super(RelatedAccount__c.getSObjectType());
    }

    /**
     * Método que devuelve los registros a partir de un identificador de cuenta
     * @author jjuaristi@seidor.es
     * @date 29/12/2022
     * @params identifier identificador de la cuenta (CIF o código de mediador), field Campo con el que comparar el identificador
     * @return relaciones entre avisos y la cuenta a buscar
     */
    public List<RelatedAccount__c> findRelatedAccountsByIdentifier ( String identifier)
    {
        if( identifier != null && identifier != '' )
        {
            this.baseQuery.selectReadableFields();
    
            this.baseQuery.addConditionEq(RelatedAccount__c.Identifier__c, identifier);
            return (List<RelatedAccount__c>) this.baseQuery.run();
        }
        else
        {
            return new List<RelatedAccount__c>();
        }
    }
}