force-app/zurich-base/main/default/objects/PlanComercial__c/PlanComercial__c.object-meta.xml
<CustomObject>
    <description>SDM: Utilizado para representar el plan de negocio realizado por los directores.</description>
    <label>Plan Comercial</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/AccumulateType__c.field-meta.xml
<CustomField>
    <fullName>AccumulateType__c</fullName>
    <description>SDM: tipo de acumulado con el que se quiere comparar dentro del objeto KPI</description>
    <label>Accumulate type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
                <label>Current month</label>
            </value>
            <value>
                <fullName>YTD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDM: usuario, de tipo RN o consultor, al que irá asociado el registro. Se utiliza de cara a que un Director pueda generar planes para los usuarios de los que es responsable.</description>
    <label>Assigned to</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Solo se puede asignar planes comerciales a usuarios de SDM</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>SDM RN</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>SDM Director</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PlanComercial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>SDM: fecha en la que finaliza el plan de acción (solo aplicable a tipo acumulado YTD)</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <description>SDM: indicador (campo) del KPI con el que se quiere comparar el objetivo</description>
    <label>Indicator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>PoliciesPN</fullName>
                <label>Pólizas PN</label>
            </value>
            <value>
                <fullName>PoliciesInForce</fullName>
                <label>Pólizas en vigor</label>
            </value>
            <value>
                <fullName>Portfolio</fullName>
                <label>Cartera</label>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
            <value>
                <fullName>Ratio_Claim</fullName>
                <label>% Sin Total</label>
            </value>
            <value>
                <fullName>Ratio_PNIncrease</fullName>
                <label>% Crec PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesPNIncreas</fullName>
                <label>% Crec Pólizas PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesInForceIncrease</fullName>
                <label>% Crec Pólizas vigor vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PortIncrease</fullName>
                <label>% crecimiento cartera</label>
            </value>
            <value>
                <fullName>Totaldiscount</fullName>
                <label>% Dto. Total</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Intermediary__c.field-meta.xml
<CustomField>
    <fullName>Intermediary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>SDM: mediador sobre el que se quiere realizar la búsqueda de KPIs para el cálculo de las cifras realas para su comparación con el objetivo</description>
    <label>Intermediary</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La cuenta debe ser un agente</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador, Intermediary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planes Comerciales</relationshipLabel>
    <relationshipName>PlanComercial</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>SDM: productos del que se quiere obtener la información de los KPIs</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autos</fullName>
                <label>Cars</label>
            </value>
            <value>
                <fullName>Hogar</fullName>
                <label>Home</label>
            </value>
            <value>
                <fullName>Inmuebles</fullName>
                <label>Estate</label>
            </value>
            <value>
                <fullName>Accidentes</fullName>
                <label>Accidents</label>
            </value>
            <value>
                <fullName>Comercios</fullName>
                <label>Commerce</label>
            </value>
            <value>
                <fullName>Patrimoniales</fullName>
                <label>Patrimonial</label>
            </value>
            <value>
                <fullName>Resp. Civil</fullName>
                <label>Civil liability</label>
            </value>
            <value>
                <fullName>Vida riesgo individual</fullName>
                <label>Individual risk life</label>
            </value>
            <value>
                <fullName>Vida riesgo colectivo</fullName>
                <label>Collective risk life</label>
            </value>
            <value>
                <fullName>Todos</fullName>
                <label>All</label>
            </value>
            <value>
                <fullName>Resto</fullName>
            </value>
            <value>
                <fullName>Communitdades</fullName>
                <label>Communities</label>
            </value>
            <value>
                <fullName>Resto Particulares</fullName>
                <isActive>false</isActive>
                <label>Rest Individuals</label>
            </value>
            <value>
                <fullName>Resto PYMEs</fullName>
                <isActive>false</isActive>
                <label>Rest of SMEs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>SDM: segmento del que se quiere obtener la información de los KPIs</description>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Individuals</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>SMEs</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Large companies</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Life risk</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>All products</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>SDM: fecha en la que comienza el plan de acción (solo aplicable a tipo acumulado YTD)</description>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-sdm-app/main/default/classes/PlanComercialSDMBatch.cls
/**
 * Batch que se encarga de relizar los siguientes automatismos para los Mediadores del proyecto SDM (Sales Digital 
 * 
 * @author nts (agonzalezisasi)
 * @date 05/07/2021
 *
 */
global class PlanComercialSDMBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable
{
    private static final String CLASS_NAME = 'PlanComercialSDMBatch';
    private String query;
    
    @TestVisible
    private Boolean testUnknownError;

    private PlanComercialSDM sdm;

    /**
     * Constructor
     */
    global PlanComercialSDMBatch()
    {
        sdm = new PlanComercialSDM();
    }

    
    /**
     * Constructor. Use a custom query
     */
    global PlanComercialSDMBatch(String p_query)
    {
        this();

        query = p_query;
    }

    //------------------------------------------------------------------------- batchable methods

    /**
     * Start. Execute the query locator for the batch
     */
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        if( String.isBlank(query) ) {
            Date todayValue = System.today();
            
            if( Test.isRunningTest() ) todayValue = Date.newInstance(2021, 9, 10);

            // SDM-729 - Añadimos la ordenacion por tipo acumulado (YTD, Mensual) para que, en la medida de lo posible, 
            // los lotes sean solo de planes mensuales o anuales. Para minimizar el numero de KPIs recuperados
            return Database.getQueryLocator([
                SELECT Id, CreatedById, AssignedTo__c, StartDate__c, EndDate__c,
                       Indicator__c, Intermediary__c, Product__c, Segment__c, AccumulateType__c
                FROM PlanComercial__c
                WHERE StartDate__c <= :todayValue AND EndDate__c >= :todayValue
                ORDER BY AccumulateType__c
            ]);
        } else {
            return Database.getQueryLocator(query);
        }
    }

    /**
     * Execute. The method for each batch
     */
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        if ( scope != null && !scope.isEmpty() ) {
            try {
                

                if( Test.isRunningTest() && testUnknownError != null && testUnknownError ) 
                    throw new PlanComercialSDMBatchException('Unknown Error');                    

                List<PlanComercial__c> plans = (List<PlanComercial__c>)scope;

                sdm.calculateRealKPI(plans);

                
            } catch (Exception e) {
                ErrorLogUtil.commitError(e, CLASS_NAME);
            }
        }
    }

    /**
     * Finish. The postprocesing method
     */
    global void finish(Database.BatchableContext BC)
    {}

    
    //------------------------------------------------------------------------- schedulable methods

    public static String createStandardSchedule(String jobName, String timeExpression, String query)
    {
        if( String.isBlank(jobName) ) jobName = 'SDM Automatismos Plan Comercial';
        if( Test.isRunningTest() ) jobName = 'Test ' + jobName;

        if( String.isBlank(timeExpression) ) timeExpression = '0 0 07 * * ?';
        
        return System.schedule(jobName, timeExpression, new PlanComercialSDMBatch(query));
    }

    /**
     * Execute. The method for the scheduled batch
     */
    global void execute(SchedulableContext SC)
    {
        // SDM-729 - Se reduce el numero de planes a procesar cada vez para minimizar el numero de KPIs a considerar en cada
        // lote del batch
        Database.executeBatch(new PlanComercialSDMBatch(query), 20);
    }

    private class PlanComercialSDMBatchException extends Exception {}
}