force-app/zurich-base/main/default/objects/Asset/fields/AddressAdditionalInfo__c.field-meta.xml
<CustomField>
    <fullName>AddressAdditionalInfo__c</fullName>
    <description>OCS</description>
    <label>Address Additional Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/AddressName__c.field-meta.xml
<CustomField>
    <fullName>AddressName__c</fullName>
    <description>OCS</description>
    <label>Address Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/AddressNumber__c.field-meta.xml
<CustomField>
    <fullName>AddressNumber__c</fullName>
    <description>OCS</description>
    <label>Address Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/AddressType__c.field-meta.xml
<CustomField>
    <fullName>AddressType__c</fullName>
    <description>OCS</description>
    <label>Address Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>OCS</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/INFOInsuredObjectCode__c.field-meta.xml
<CustomField>
    <fullName>INFOInsuredObjectCode__c</fullName>
    <description>(OCS): Concatenación de los campos de Número de póliza y Secuencial</description>
    <externalId>true</externalId>
    <label>INFO Insured Object Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>(OCS): Contiene el modelo del vehículo/dispositivo asegurado</description>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/PolicyId__c.field-meta.xml
<CustomField>
    <fullName>PolicyId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS): Relación con la póliza</description>
    <label>Policy Number</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Insured Objects</relationshipLabel>
    <relationshipName>PolicyNumbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <description>(OCS): Contiene el número de matrícula del vehículo/embarcación asegurado</description>
    <label>Registration number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Client_Identification__mdt/Client_Identification__mdt.object-meta.xml
<CustomObject>
    <description>Metadato que contiene los campos que son obligatorios para la búsqueda de clientes que vienen desde Thunder</description>
    <label>Client Identification</label>
    <pluralLabel>Client Identifications</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/Client_Identification__mdt/fields/Identification__c.field-meta.xml
<CustomField>
    <fullName>Identification__c</fullName>
    <label>Identification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/CommercialCode__c.field-meta.xml
<CustomField>
    <fullName>CommercialCode__c</fullName>
    <description>(OCS). Identifica el código comercial del producto en INFO</description>
    <formula>ProductId__r.CommercialCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commercial Code</label>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>(OCS). Identifica la fecha de vencimiento de la póliza</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/MovementStartDate__c.field-meta.xml
<CustomField>
    <fullName>MovementStartDate__c</fullName>
    <description>(OCS). Identifica la fecha de efecto de un movimiento</description>
    <label>Movement Start Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/PolicyStatus__c.field-meta.xml
<CustomField>
    <fullName>PolicyStatus__c</fullName>
    <description>(OCS). Indica si la póliza está Cancelada, rehabilitada, saneada…</description>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/PolicyVersion__c.field-meta.xml
<CustomField>
    <fullName>PolicyVersion__c</fullName>
    <description>(OCS). Campo oculto usado en la integración para parsear el valor y copiarlo al campo Nombre del objeto Versión de Póliza</description>
    <label>Policy Version</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica el producto para el que se realiza la póliza. En la web se (OCS) Identifica como Tipo de Registro</description>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>(OCS). Identifica la fecha de efecto o inicio de la póliza</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/TechnicalCode__c.field-meta.xml
<CustomField>
    <fullName>TechnicalCode__c</fullName>
    <description>(OCS). Identifica el código técnico del producto en INFO</description>
    <formula>ProductId__r.TechnicalCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Technical Code</label>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/PolicyVersion__c/PolicyVersion__c.object-meta.xml
<CustomObject>
    <description>This entity represents all the changes that a policy can suffer such as activation and deactivation of a On Demand non-life policy, change of a product, policy activation and so on.</description>
    <label>Versión de póliza</label>
    <nameField>
        <label>Versión de póliza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versiones de póliza</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PolicyVersion__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Indicates when finishes that version of policy</description>
    <label>Fecha fin</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/PolicyVersion__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Indicates when starts that version of policy</description>
    <label>Fecha inicio</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/CommercialCode__c.field-meta.xml
<CustomField>
    <fullName>CommercialCode__c</fullName>
    <description>(OCS). Identificador del producto dentro del código técnico</description>
    <label>Commercial Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <description>Field to be used as external ID of the product</description>
    <externalId>true</externalId>
    <label>ProductID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/TechnicalCode__c.field-meta.xml
<CustomField>
    <fullName>TechnicalCode__c</fullName>
    <description>(OCS). Identificador del tipo de producto</description>
    <label>Technical Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/classes/ClientIdentificationService.cls
public with sharing class ClientIdentificationService
{

    public static Set<String> currentReceivedFields = new Set<String>(); // Campos que nos envían desde el JSON
    public static Set<String> requiredFieldsMetadataSet = new Set<String>(); // Campos obligatorios

    public static final String INVALID_FIELD_STATUSCODE = 'INVALID_FIELD';
    public static final String EMPTY_FIELD_STATUSCODE = 'EMPTY_FIELD';

    public ClientIdentificationService()
    {}

    public static String processData(Client receivedData, String finding)
    {
        switch on finding {
            // 1 - POST /people: Procesa la búsqueda de clientes
            when 'findByPolicyNumber' {
                return getByPolicyNumber(receivedData);
            }
            when 'findByPhone' {
                return getByPhone(receivedData);
            }
            when else {
                return 'error';
            }
        }
    }

    public static String getByPolicyNumber(Client receivedData)
    {
        if ( String.isBlank(receivedData.nationalID) || String.isBlank(receivedData.policyNumber) )
        {
            throw new ClientIdentificationException(
                      EMPTY_FIELD_STATUSCODE,
                      'A required field is empty'
                      );
        }

        AccountsSelector accountsSelector = new AccountsSelector();
        PoliciesSelector policiesSelector = new PoliciesSelector();
        AssetsSelector assetsSelector = new AssetsSelector();

        SearchResult resultado = new SearchResult();
        resultado.isValidPolicy = false;

        // jgarciamartinez - 18/08/2022 - campos nuevos añadidos a petición de cliente
        resultado.existsNationalID = false;
        resultado.existsPolicy = false;

        // Comprobamos si existe una poliza asignada al DNI que nos envían:
        // 1.- Obtenemos el ID del Account
        List<Account> cuentasEncontradas = accountsSelector.findByNationalId(new List<String> { receivedData.nationalID }, '');
        List<Policy__c> polizaEncontrada = new List<Policy__c>();

        if( !cuentasEncontradas.isEmpty() )
        {
            resultado.existsNationalID = true;
            polizaEncontrada = policiesSelector.selectByInfoPolicyNumberAndNationalId(new List<String> { receivedData.nationalID },new List<String> { receivedData.policyNumber });
        }
        else
        {
            resultado.existsNationalID = false;
            polizaEncontrada = policiesSelector.selectByNumber(receivedData.policyNumber);
        }

        if( !polizaEncontrada.isEmpty() )
        {
            resultado.existsPolicy = true;
            if(polizaEncontrada[0].PolicyStatus__c == 'V')
            {
                resultado.isValidPolicy = true;
            }
        }

        // Tan solo si los tres flags son true les vamos a pasar los valores
        if (resultado.existsNationalID && resultado.existsPolicy && resultado.isValidPolicy)
        {
            resultado.policyEndDate = polizaEncontrada[0].EndDate__c;
            resultado.policyStartDate = polizaEncontrada[0].MovementStartDate__c;
            resultado.policyVersion = polizaEncontrada[0].policyVersion__c;
            
            List<String> listaPolizas = new List<String>();
            for (Policy__c p : polizaEncontrada)
            {
                listaPolizas.add(p.id);
            }
            
            List<Asset> obtainedAssets = assetsSelector.selectByPolicyID(listaPolizas);
            if(!obtainedAssets.isEmpty())
            {
                resultado.policyInfoInsuredObject = obtainedAssets[0].INFOInsuredObjectCode__c;
            }

            List<Product2> obtainedProduct = new ProductsSelector(
                    new Set<String> {'Id', 'Name', 'CommercialCode__c', 'TechnicalCode__c'}
                    ).selectByID(polizaEncontrada[0].ProductId__c);
            if(!obtainedProduct.isEmpty())
            {
                resultado.technicalCode = obtainedProduct[0].TechnicalCode__c;
            }

        } 

        return resultado.toString();

    }


    public static String getByPhone(Client receivedData)
    {
        SearchResultLong resultado = new SearchResultLong();
        List<InsuredObject> listaObjetos = new List<InsuredObject>();
        resultado.objects = listaObjetos;

        // Comprobamos si los datos nos vienen rellenos
        if ( String.isBlank(receivedData.nationalID) || String.isBlank(receivedData.phoneNumber) || String.isBlank(receivedData.groupDescription) )
        {
            System.debug('++++ :' + receivedData.nationalID);
            System.debug('++++ :' + receivedData.phoneNumber);
            System.debug('++++ :' + receivedData.groupDescription);

            throw new ClientIdentificationException(
                      EMPTY_FIELD_STATUSCODE,
                      'A required field is empty'
                      );
        }

        // Si todo bien, buscamos account por DNI + Telefono

        AccountsSelector accountsSelector = new AccountsSelector();
        PoliciesSelector policiesSelector = new PoliciesSelector();
        AssetsSelector assetsSelector = new AssetsSelector();

        // Con el ID del account conseguido, sacamos las pólizas
        List<Account> cuentasEncontradas = accountsSelector.findByNationalIdAndPhoneNumber(new List<String> { receivedData.nationalID }, '', new List<String> { receivedData.phoneNumber });

        if(!cuentasEncontradas.isEmpty())
        {
            resultado.nationalID = receivedData.nationalID;
            resultado.phoneNumber = receivedData.phoneNumber;

            List<Policy__c> polizasEncontradas = policiesSelector.selectByHolderAndGroupDescription(cuentasEncontradas[0].id, receivedData.groupDescription);
            if(!polizasEncontradas.isEmpty())
            {
                System.debug('++++ Entra en if');
                Map<Id, Policy__c> mapaPolizas = new Map<Id, Policy__c>();
                List<Id> listaPolIds = new List<Id>();
                for(Policy__c pol : polizasEncontradas)
                {
                    listaPolIds.add(pol.id);
                    mapaPolizas.put(pol.id, pol);
                }

                List<Asset> listaAssets = assetsSelector.selectByPolicyID(listaPolIds);
                for(Asset a : listaAssets)
                {
                    InsuredObject obj = new InsuredObject();

                    // Datos correspondientes al Asset
                    obj.name = a.Name;
                    obj.registrationNumber = a.RegistrationNumber__c;
                    obj.model = a.Model__c;
                    obj.addressType = a.AddressType__c;
                    obj.addressName = a.AddressName__c; 
                    obj.addressNumber = a.AddressNumber__c;
                    obj.addressAdditionalInfo = a.AddressAdditionalInfo__c;
                    obj.city = a.City__c;

                    // Datos correspondientes a la poliza como tal
                    obj.policyInfoInsuredObject = a.INFOInsuredObjectCode__c;
                    obj.policyEndDate = mapaPolizas.get(a.PolicyId__c).EndDate__c;
                    obj.policyStartDate = mapaPolizas.get(a.PolicyId__c).StartDate__c;
                    obj.policyVersion= mapaPolizas.get(a.PolicyId__c).PolicyVersion__c;

                    listaObjetos.add(obj);
                }

                resultado.objects = listaObjetos;
            }
        }
        return resultado.toString();
    }

    //#region Métodos auxiliares
    /**
     * Método que carga el set de campos que hemos recibido desde el JSON
     *
     * @author arcortazar
     * @date 09/06/2022
     */
    public static void setCurrentFields(String field)
    {
        currentReceivedFields.add(field.toLowerCase());
    }

    /**
     * Método que valida que no falte ninguno de los campos requeridos
     *
     * @return List<String> fieldsNotFound listado de campos no encontrado en el JSON
     * @author rlopez
     * @date 21/10/2020
     */

     public static void validateReceivedInformation(Client receivedData, String identificationType)
     {
        // Obtenemos los campos que son mandatorios
        List<Client_Identification__mdt> allFieldsMetadataSet = Client_Identification__mdt.getAll().values();
        List<Client_Identification__mdt> requiredFieldsMetadataSet = new List<Client_Identification__mdt>();
        for (Client_Identification__mdt m : allFieldsMetadataSet)
        {
            if(m.Identification__c.equals('All') || m.Identification__c.contains(identificationType))
            {
                requiredFieldsMetadataSet.add(m);
            }
        }

        // Comprobamos que entre los recibidos están los mandatorios
        List<String> fieldsNotFound = new List<String>();
        for (Client_Identification__mdt field : requiredFieldsMetadataSet)
        {
            if ( !currentReceivedFields.contains( field.Label.toLowercase() ) )
            {
                fieldsNotFound.add( field.Label.toLowercase() );
            }
        }

        // Si no están, lanzamos excepción
        if( !fieldsNotFound.isEmpty() )
        {
            throw new ClientIdentificationException(
                      INVALID_FIELD_STATUSCODE,
                      'The following fields are missing: ' +
                      fieldsNotFound.toString()
                      );
        }
    }

    //#endregion


    //#region Inner Classes
    /**
     * Representa la información del cliente que llega desde Thunder
     *
     * @author arcortazar
     * @created date: 09/06/2022
     */
    public class Client
    {
        public Client()
        {}

        public String fullName {
            get;
            set {
                setCurrentFields('fullName');
                fullName = value;
            }
        }

        public String nationalID {
            get;
            set {
                setCurrentFields('nationalID');
                nationalID = value;
            }
        }
        public String policyNumber {
            get;
            set {
                setCurrentFields('policyNumber');
                policyNumber = value;
            }
        }
        
        public String phoneNumber {
            get;
            set {
                setCurrentFields('phoneNumber');
                phoneNumber = value;
            }
        }

        public String groupDescription {
            get;
            set {
                setCurrentFields('groupDescription');
                groupDescription = value;
            }
        }

        public override String toString()
        {
            return JSON.serialize(this);
        }
    }

    /**
     * Representa los resultados de búsqueda del CRM
     *
     * @author arcortazar
     * @created date: 09/06/2022
     */
    public class SearchResult
    {
        public Boolean isValidPolicy;
        // jgarciamartinez - 18/08/2022 - campos nuevos añadidos a petición de cliente
        public Boolean existsNationalID;
        public Boolean existsPolicy;
        public Date policyEndDate;
        public Date policyStartDate;
        public String policyVersion;
        public String policyInfoInsuredObject;

        // arcortazar - 31/01/2023 - [OCS-5874]
        public String technicalCode;

        public override String toString()
        {
            return JSON.serialize(this);
        }
    }
   
    public class SearchResultLong
    {
        public String nationalID;
        public String phoneNumber;
        public List<InsuredObject> objects;

        public override String toString()
        {
            return JSON.serialize(this);
        }
    }

    public class InsuredObject 
    {
        public Date policyEndDate;
        public Date policyStartDate;
        public String policyVersion;
        public String policyInfoInsuredObject;
        public String technicalCode;

        public String name;
        public String registrationNumber;
        public String model;
        public String addressType;
        public String addressName;
        public String addressNumber;
        public String addressAdditionalInfo;
        public String city;

        public override String toString()
        {
            return JSON.serialize(this);
        }
    }


    //#endregion

    //#region Excepciones

    @TestVisible
    public class ClientIdentificationException extends Exception
    {
        public String statusCode;
        public String message
        {
            get
            {
                return this.getMessage();
            }
        }

        /**
         * Constructor por defecto
         * @author arcortazar
         * @created date: 09/06/2022
         */
        public ClientIdentificationException(String statusCode, String message)
        {
            this.setMessage(message);
            this.statusCode = statusCode;
        }
    }

    //#endregion
}