force-app/zurich-base/main/default/objects/Case/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Marca para indicar la acción a realizar (ZDA)</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Notificación</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Recotización</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Contactar</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Contratar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <label>Type N2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alta</fullName>
            </value>
            <value>
                <fullName>Anulación</fullName>
            </value>
            <value>
                <fullName>Apoyo Captación</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Asistencia en Viaje</fullName>
            </value>
            <value>
                <fullName>Backoffice</fullName>
            </value>
            <value>
                <fullName>Banca Seguros</fullName>
            </value>
            <value>
                <fullName>Cambio de intermediario</fullName>
            </value>
            <value>
                <fullName>Cambio mediador</fullName>
            </value>
            <value>
                <fullName>Campaña</fullName>
            </value>
            <value>
                <fullName>Cancelacion</fullName>
            </value>
            <value>
                <fullName>Características / Coberturas</fullName>
            </value>
            <value>
                <fullName>Catálogo virtual</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Coberturas</fullName>
            </value>
            <value>
                <fullName>Comentario</fullName>
            </value>
            <value>
                <fullName>Como abro un siniestro</fullName>
            </value>
            <value>
                <fullName>Como abro un siniestro de Dispositivo</fullName>
                <label>Cómo abro un siniestro de Dispositivo</label>
            </value>
            <value>
                <fullName>Como abro un siniestro de Movilidad</fullName>
                <label>Cómo abro un siniestro de Movilidad</label>
            </value>
            <value>
                <fullName>Como abro un siniestro de Vida</fullName>
                <label>Cómo abro un siniestro de Vida</label>
            </value>
            <value>
                <fullName>Como contrato mi seguro</fullName>
            </value>
            <value>
                <fullName>Como firmo mi seguro</fullName>
            </value>
            <value>
                <fullName>Como renuevo mi seguro</fullName>
            </value>
            <value>
                <fullName>Como valido mi seguro</fullName>
            </value>
            <value>
                <fullName>Comparativa Cotización</fullName>
            </value>
            <value>
                <fullName>Comparativa Gestión Cartera</fullName>
            </value>
            <value>
                <fullName>Consulta</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Contraseña App</fullName>
            </value>
            <value>
                <fullName>Contratacion</fullName>
                <label>Contratación</label>
            </value>
            <value>
                <fullName>Gestión de recibos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalJobQueueBatch__mdt/ExternalJobQueueBatch__mdt.object-meta.xml
<CustomObject>
    <label>External Job Queue Batch</label>
    <pluralLabel>External Job Queue Batch</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalJobQueueBatch__mdt/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
                <default>true</default>
                <label>INFO</label>
            </value>
            <value>
                <fullName>MI_ZURICH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalJobQueueBatch__mdt/fields/Retries__c.field-meta.xml
<CustomField>
    <fullName>Retries__c</fullName>
    <label>Retries</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/ExternalRequest__c.object-meta.xml
<CustomObject>
    <description>Request sent by an external system that will be inserted in the processing queue.</description>
    <label>External request</label>
    <nameField>
        <displayFormat>ER{YY}{MM}{DD}{00000}</displayFormat>
        <label>External request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UPSERT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/ContentFormat__c.field-meta.xml
<CustomField>
    <fullName>ContentFormat__c</fullName>
    <label>Content Format</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JSON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>Indicates the type of information is being sent to Salesforce</description>
    <inlineHelpText>Indicates the type of information is being sent to Salesforce</inlineHelpText>
    <label>Entidad</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/NumRetry__c.field-meta.xml
<CustomField>
    <fullName>NumRetry__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of retries. Whenever it is processed it sums 1.</description>
    <inlineHelpText>Number of retries. Whenever it is processed it sums 1.</inlineHelpText>
    <label>Número de reintentos</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Indicates which external system sends data to Salesforce</description>
    <inlineHelpText>Indicates which external system sends data to Salesforce</inlineHelpText>
    <label>Origen</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the request has been processed</description>
    <inlineHelpText>Indicates if the request has been processed</inlineHelpText>
    <label>Procesado</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/ProcessResult__c.field-meta.xml
<CustomField>
    <fullName>ProcessResult__c</fullName>
    <description>Result of the request process</description>
    <inlineHelpText>Result of the request process</inlineHelpText>
    <label>Resultado del proceso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/recordTypes/INFO.recordType-meta.xml
<RecordType>
    <fullName>INFO</fullName>
    <active>true</active>
    <label>INFO</label>
</RecordType>

force-app/zurich-base/main/default/objects/ExternalRequestError__c/ExternalRequestError__c.object-meta.xml
<CustomObject>
    <description>Specific object to store integration with external systems errors</description>
    <label>External Request Error</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Requests Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalRequestError__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Upsert</fullName>
                <default>true</default>
                <label>Upsert</label>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequestError__c/fields/ContentFormat__c.field-meta.xml
<CustomField>
    <fullName>ContentFormat__c</fullName>
    <label>Content Format</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JSON</fullName>
                <default>true</default>
                <label>JSON</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequestError__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequestError__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/Transformer__mdt/Transformer__mdt.object-meta.xml
<CustomObject>
    <label>Transformer</label>
    <pluralLabel>Transformers</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/Transformer__mdt/fields/OriginEntity__c.field-meta.xml
<CustomField>
    <fullName>OriginEntity__c</fullName>
    <label>Origin entity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/classes/ExternalRequestHandlerUtilTest.cls
/**
 * @description       : Clase de test para la clase ExternalRequestHandlerUtil
 * @author            : aberuete
 * @group             : 
 * @last modified on  : 05-17-2023
 * @last modified by  : aberuete
**/
@isTest
private with sharing class ExternalRequestHandlerUtilTest 
{
    private static final Integer NUM_ER_FORM_INC = 5;
    private static final Integer NUM_ER_NATURAL_ACCOUNT = 5;

    @TestSetup
    private static void makeData()
    {
        List<ExternalRequest__c> externalRequestList = new List<ExternalRequest__c>();

         //FORM_INC
         externalRequestList.addAll( TestDataFactory.generateExternalRequest(MiZurichHandler.HANDLER_ORIGIN, 'FORM_INC', NUM_ER_FORM_INC));

         //Personas físicas
         externalRequestList.addAll(TestDataFactory.generateExternalRequest(INFOHandler.HANDLER_ORIGIN, 'NATURAL_ACCOUNT', NUM_ER_NATURAL_ACCOUNT));

         insert externalRequestList;
    }  

    /**
     * Test que comprueba que se obtiene la información necesaria para poder procesar las external request pendientes correctamente
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_prepareExternalRequestToProcess()
    {
        Transformer transformer = new Transformer(INFOHandler.HANDLER_ORIGIN);

        Set<String> objects = new Set<String>();

        for (Transformer__mdt setting : TransformerSelector.selectMetadataByOrigin(INFOHandler.HANDLER_ORIGIN) )
        {
            objects.add(setting.OriginEntity__c);
        }
        
        Test.startTest();
        ExternalRequestHandlerUtil.prepareExternalRequestToProcess(transformer, INFOHandler.HANDLER_ORIGIN);
        Test.stopTest();

        System.assertEquals(objects.size(),ExternalRequestHandlerUtil.recordsToUpsertByEntity.size(),'No se ha generado correctamente el mapa por entidades');
        System.assertEquals(objects.size(),ExternalRequestHandlerUtil.recordsToDeleteByEntity.size(),'No se ha generado correctamente el mapa por entidades');
        System.assertNotEquals(null,ExternalRequestHandlerUtil.maxRetries,'El número máximo de intentos no debería ser nulo');
        System.assertEquals(false,ExternalRequestHandlerUtil.entitiesByPrirority.isEmpty(),'El mapa de entidades por prioridad no debería estar vacío');
        System.assertEquals(false,ExternalRequestHandlerUtil.entityIndexes.isEmpty(),'La lista de prioridades de entidades no debería estar vacía');
        System.assertEquals(false,ExternalRequestHandlerUtil.mapRobotHegeoFieldsMapping.isEmpty(),'El mapa de tipificaciones no debería estar vacío');
    }

    /**
     * Test que comprueba que se procesan correctamente las external request procedentes de MiZurich y se insertan los registros de la entidad en salesforce
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_persists_upsert_MiZurich_OK()
    {
        Transformer transformer = new Transformer(MiZurichHandler.HANDLER_ORIGIN);

        List<ExternalRequest__c> externalRequestList = new ExternalRequestsSelector(new List<Schema.SObjectField>
                                                                                    { ExternalRequest__c.Entity__c,
                                                                                      ExternalRequest__c.Action__c,
                                                                                      ExternalRequest__c.Payload__c,
                                                                                      ExternalRequest__c.ContentFormat__c,
                                                                                      ExternalRequest__c.NumRetry__c,
                                                                                      ExternalRequest__c.Origin__c,
                                                                                      ExternalRequest__c.CreatedDate}).selectByOrigin(new Set<String> {MiZurichHandler.HANDLER_ORIGIN});
    
        Test.startTest();
        MiZurichHandler.prepare(transformer, externalRequestList);
        MiZurichHandler.process(externalRequestList);
        ExternalRequestHandlerUtil.persistExternalRequest('MiZurichHandler');
        Test.stopTest();

        List<Case> caseList = [SELECT Id FROM Case];

        System.assertEquals(NUM_ER_FORM_INC, caseList.size(), 'No se han insertado todos los registros de caso');
        
    }

     /**
     * Test que comprueba que se procesan correctamente las external request procedentes de INFO y se insertan los registros de la entidad en salesforce
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_persists_upsert_INFO_OK()
    {
        Transformer transformer = new Transformer(INFOHandler.HANDLER_ORIGIN);

        List<ExternalRequest__c> externalRequestList = new ExternalRequestsSelector(new List<Schema.SObjectField>
                                                                                    { ExternalRequest__c.Entity__c,
                                                                                      ExternalRequest__c.Action__c,
                                                                                      ExternalRequest__c.Payload__c,
                                                                                      ExternalRequest__c.ContentFormat__c,
                                                                                      ExternalRequest__c.NumRetry__c,
                                                                                      ExternalRequest__c.Origin__c,
                                                                                      ExternalRequest__c.CreatedDate}).selectByOrigin(new Set<String> {INFOHandler.HANDLER_ORIGIN});
    
        Test.startTest();
        INFOHandler.prepare(transformer, externalRequestList);
        INFOHandler.process(externalRequestList);
        ExternalRequestHandlerUtil.persistExternalRequest('INFOHandler');
        Test.stopTest();

        List<Account> accountList = [SELECT Id FROM Account];

        System.assertEquals( NUM_ER_NATURAL_ACCOUNT,accountList.size(),'No se han insertado todos los registros de cuenta');
    }

    /**
     * Test que comprueba que se procesan correctamente las external request procedentes de INFO y se borran los registros de la entidad en salesforce
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_persists_delete_OK()
    {
        Transformer transformer = new Transformer(INFOHandler.HANDLER_ORIGIN);

        List<ExternalRequest__c> externalRequestList = new ExternalRequestsSelector(new List<Schema.SObjectField>
                                                                                    { ExternalRequest__c.Entity__c,
                                                                                      ExternalRequest__c.Action__c,
                                                                                      ExternalRequest__c.Payload__c,
                                                                                      ExternalRequest__c.ContentFormat__c,
                                                                                      ExternalRequest__c.NumRetry__c,
                                                                                      ExternalRequest__c.Origin__c,
                                                                                      ExternalRequest__c.CreatedDate}).selectByOrigin(new Set<String> {INFOHandler.HANDLER_ORIGIN});

        INFOHandler.prepare(transformer, externalRequestList);
        INFOHandler.process(externalRequestList);
        INFOHandler.persists(externalRequestList);
        INFOHandler.manageResult(null, externalRequestList);

        List<ExternalRequest__c> externalRequestListUpserted = new ExternalRequestsSelector(new List<Schema.SObjectField>
                                                                                            { ExternalRequest__c.Entity__c,
                                                                                              ExternalRequest__c.Action__c,
                                                                                              ExternalRequest__c.Payload__c,
                                                                                              ExternalRequest__c.ContentFormat__c,
                                                                                              ExternalRequest__c.NumRetry__c,
                                                                                              ExternalRequest__c.Origin__c,
                                                                                              ExternalRequest__c.CreatedDate}).selectByOrigin(new Set<String> {INFOHandler.HANDLER_ORIGIN});

        List<ExternalRequest__c> externalRequestToDelete = new List<ExternalRequest__c>();

        for(ExternalRequest__c externalRequest : externalRequestListUpserted)
        {
            externalRequest.Processed__C = false;
            externalRequest.Action__C = 'DELETE';
            externalRequestToDelete.add(externalRequest);   
        }

        update externalRequestToDelete;

        Test.startTest();
        INFOHandler.prepare(transformer, externalRequestToDelete);
        INFOHandler.process(externalRequestToDelete);
        ExternalRequestHandlerUtil.persistExternalRequest('INFOHandler');
        Test.stopTest();

        List<Account> accountList = [SELECT Id FROM Account]; 
        System.assertEquals(0, accountList.size(), 'No se han borrado todos los registros de cuentas');
    }

     /**
     * Test que comprueba que se procesan y actualizan correctamente las external request 
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_manageResult_OK()
    {
        Transformer transformer = new Transformer(MiZurichHandler.HANDLER_ORIGIN);

        List<ExternalRequest__c> externalRequestList = new ExternalRequestsSelector(new List<Schema.SObjectField>
                                                                                    { ExternalRequest__c.Entity__c,
                                                                                      ExternalRequest__c.Action__c,
                                                                                      ExternalRequest__c.Payload__c,
                                                                                      ExternalRequest__c.ContentFormat__c,
                                                                                      ExternalRequest__c.NumRetry__c,
                                                                                      ExternalRequest__c.Origin__c,
                                                                                      ExternalRequest__c.CreatedDate}).selectByOrigin(new Set<String> {MiZurichHandler.HANDLER_ORIGIN});

        Test.startTest();
        MiZurichHandler.prepare(transformer, externalRequestList);
        MiZurichHandler.process(externalRequestList);
        MiZurichHandler.persists(externalRequestList);
        ExternalRequestHandlerUtil.manageResultExternalRequest(null, externalRequestList, 'MiZurichHandler');
        Test.stopTest();

        List<ExternalRequest__c> externalRequestListUpdated = new ExternalRequestsSelector(new List<Schema.SObjectField>
                                                                                           { ExternalRequest__c.Entity__c,
                                                                                             ExternalRequest__c.Action__c,
                                                                                             ExternalRequest__c.Payload__c,
                                                                                             ExternalRequest__c.ContentFormat__c,
                                                                                             ExternalRequest__c.NumRetry__c,
                                                                                             ExternalRequest__c.Origin__c,
                                                                                             ExternalRequest__c.CreatedDate}).selectProcessedByOrigin(new Set<String> {MiZurichHandler.HANDLER_ORIGIN});

        List<ExternalRequestError__c> externalRequestErrors = [
            SELECT Id
            FROM ExternalRequestError__c
            WHERE Origin__c = :MiZurichHandler.HANDLER_ORIGIN
        ];

        Integer totalExternalRequests = NUM_ER_FORM_INC;

        System.assertEquals(totalExternalRequests,externalRequestListUpdated.size(),'No se han procesado todas las external request');
       
        System.assertEquals(0, externalRequestErrors.size(),'Se han insertado external request erróneas en la entidad External Request Error');
    }

    /**
     * Test que comprueba que se procesan y actualizan correctamente las external request y en caso de error se generan correctamente los externalRequestError
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_manageResult_ERROR()
    {
        Transformer transformer = new Transformer(MiZurichHandler.HANDLER_ORIGIN);

        List<ExternalRequest__c> externalRequestList = new ExternalRequestsSelector(new List<Schema.SObjectField>
                                                                                    { ExternalRequest__c.Entity__c,
                                                                                      ExternalRequest__c.Action__c,
                                                                                      ExternalRequest__c.Payload__c,
                                                                                      ExternalRequest__c.ContentFormat__c,
                                                                                      ExternalRequest__c.NumRetry__c,
                                                                                      ExternalRequest__c.Origin__c,
                                                                                      ExternalRequest__c.CreatedDate}).selectByOrigin(new Set<String> {MiZurichHandler.HANDLER_ORIGIN});

        externalRequestList.get(0).Payload__c = null;

        Test.startTest();
        MiZurichHandler.prepare(transformer, externalRequestList);
        MiZurichHandler.process(externalRequestList);
        MiZurichHandler.persists(externalRequestList);
        ExternalRequestHandlerUtil.manageResultExternalRequest(null, externalRequestList, 'MiZurichHandler');
        Test.stopTest();

        List<ExternalRequest__c> externalRequestListUpdated = new ExternalRequestsSelector(new List<Schema.SObjectField>
                                                                                           { ExternalRequest__c.Entity__c,
                                                                                             ExternalRequest__c.Action__c,
                                                                                             ExternalRequest__c.Payload__c,
                                                                                             ExternalRequest__c.ContentFormat__c,
                                                                                             ExternalRequest__c.NumRetry__c,
                                                                                             ExternalRequest__c.Origin__c,
                                                                                             ExternalRequest__c.CreatedDate}).selectProcessedByOrigin(new Set<String> {MiZurichHandler.HANDLER_ORIGIN});

        List<ExternalRequestError__c> errors = [SELECT Id FROM ExternalRequestError__c];

        Integer totalExternalRequests = NUM_ER_FORM_INC;
        
        System.assertEquals(totalExternalRequests,externalRequestListUpdated.size(),'No se han procesado todas las external request');
    }

    /**
     * Test que comprueba que se actualiza correctamente la información de la external request
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_setExternalRequest()
    {
        ExternalRequestHandlerUtil.externalRequestResultList = new List<ExternalRequest__c>();

        ExternalRequestHandlerUtil.maxRetries = (Integer) new ExternalJobQueueBatchesSelector
        (
            new List<Schema.SObjectField> {ExternalJobQueueBatch__mdt.Retries__c}
        ).selectByOrigin(new Set<String> {MiZurichHandler.HANDLER_ORIGIN}).get(0).Retries__c;

        List<ExternalRequest__c> externalRequestList = new ExternalRequestsSelector(new List<Schema.SObjectField>
                                                                                    { ExternalRequest__c.Entity__c,
                                                                                      ExternalRequest__c.Action__c,
                                                                                      ExternalRequest__c.Payload__c,
                                                                                      ExternalRequest__c.ContentFormat__c,
                                                                                      ExternalRequest__c.NumRetry__c,
                                                                                      ExternalRequest__c.Origin__c,
                                                                                      ExternalRequest__c.CreatedDate}).selectByOrigin(new Set<String> {MiZurichHandler.HANDLER_ORIGIN});
        externalRequestList[0].NumRetry__c = 2;

        Test.startTest();
        ExternalRequestHandlerUtil.setExternalRequest(externalRequestList[0], false, 'OK', null, true);
        Test.stopTest();

        System.assertEquals(false, ExternalRequestHandlerUtil.externalRequestResultList.isEmpty(), 'La lista no debería estar vacía');
        System.assertEquals(true, ExternalRequestHandlerUtil.externalRequestResultList[0].Processed__c, 'Debería estar procesada la external request');
        System.assertEquals('OK', ExternalRequestHandlerUtil.externalRequestResultList[0].ProcessResult__c, 'El resultado del procesamiento de la external requets debería ser OK');
    }

    /**
     * Test que comprueba que se rellena correctamente el mapa de entidades por prioridad
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_fillEntitiesByPriorityMap()
    {
        ExternalRequestHandlerUtil.entitiesByPrirority = new Map<Decimal, String>();
        ExternalRequestHandlerUtil.entityIndexes = new List<Decimal>();

        Test.startTest();
        ExternalRequestHandlerUtil.fillEntitiesByPriorityMap();
        Test.stopTest();

        System.assertEquals(false, ExternalRequestHandlerUtil.entitiesByPrirority.isEmpty(), 'El mapa de prioridades por entidades no debería estar vacío');
        System.assertEquals(false, ExternalRequestHandlerUtil.entityIndexes.isEmpty(), 'La lista de prioridades no debería estar vacía');
    }

     /**
     * Test que comprueba que antes de insertar la external request se rellena el campo index que contiene la prioridad de la entidad para ser procesada
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_setERIndex()
    {
        ExternalRequestHandlerUtil.entitiesByPrirority = new Map<Decimal, String>();
        ExternalRequestHandlerUtil.entityIndexes = new List<Decimal>();

        List<ExternalRequest__c> externalRequestList = TestDataFactory.generateExternalRequest(MiZurichHandler.HANDLER_ORIGIN, 'FORM_INC', 1);
        externalRequestList[0].Index__c = null;

        Test.startTest();
        insert externalRequestList;
        Test.stopTest();

        ExternalRequest__c externalRequestAfterInsert = [Select id,Index__c from ExternalRequest__c where id =: externalRequestList[0].id ];

        System.assertNotEquals(null, externalRequestAfterInsert.Index__c, 'El indice no debería ser nulo');
    }

    /**
     * Test que comprueba que se rellena correctamente el mapa de tipificaciones
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_fillMapRobotHegeoFieldsMapping()
    {
        ExternalRequestHandlerUtil.mapRobotHegeoFieldsMapping = new Map<String, Map<String, Map<String,String>>> ();

        Test.startTest();
        ExternalRequestHandlerUtil.fillMapRobotHegeoFieldsMapping();
        Test.stopTest();

        System.assertEquals(false, ExternalRequestHandlerUtil.mapRobotHegeoFieldsMapping.isEmpty(), 'El mapa de tipificaciones no debería estar vacío');
    }

    /**
     * Test que comprueba que se obtiene correctamente la tipificación del caso y se actualizan sus valores
     **
     * @author aberuete
     * @date 17/05/2023
     */
    @isTest
    private static void test_fillTypificationIntoCase()
    {
        Case caseRecord = new Case ();
        ExternalRequestHandlerUtil.mapRobotHegeoFieldsMapping = new Map<String, Map<String, Map<String,String>>> ();
        ExternalRequestHandlerUtil.fillMapRobotHegeoFieldsMapping();

        String infoType = 'source type';
        String infoSubtype = 'source subtype';
        Map<String, Object> recordValuesMap = new Map<String, Object> {
                                                'miZurich_inputForm2' => infoType,
                                                'miZurich_inputForm3' => infoSubtype
                                                };
        Map<String,String> subtypeAndtype3 = new Map<String,String>();
        Map<String, Map<String,String>> mapTipification = new Map<String, Map<String,String>> ();
        subtypeAndtype3.put('Gestión de recibos','Anulación');
        mapTipification.put ('Gestión Económica', subtypeAndtype3);
        ExternalRequestHandlerUtil.mapRobotHegeoFieldsMapping.put(infoType + infoSubtype,mapTipification);                    

        Test.startTest();
        caseRecord = ExternalRequestHandlerUtil.fillTypificationIntoCase (recordValuesMap, 'miZurich_inputForm2', 'miZurich_inputForm3', caseRecord);
        Test.stopTest();

        System.assertEquals('Gestión Económica', caseRecord.Type, 'El tipo de la tipificación no es correcto');
        System.assertEquals('Gestión de recibos', caseRecord.SubType__c, 'El subtipo de la tipificación no es correcto');
        System.assertEquals('Anulación', caseRecord.TypeN3__c, 'El tipo 3 de la tipificación no es correcto');
    }
}