force-app/zurich-base/main/default/objects/Case/fields/ClaimNumber__c.field-meta.xml
<CustomField>
    <fullName>ClaimNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número de siniestro</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/DateReg__c.field-meta.xml
<CustomField>
    <fullName>DateReg__c</fullName>
    <description>Claim creation date</description>
    <label>Fecha creación de siniestro</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/InsuredObjectId__c.field-meta.xml
<CustomField>
    <fullName>InsuredObjectId__c</fullName>
    <description>Hidden field to save the value received from IBA</description>
    <label>InsuredObjectId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad Legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Policy to which is related to</description>
    <label>Póliza</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/PolicyNum__c.field-meta.xml
<CustomField>
    <fullName>PolicyNum__c</fullName>
    <externalId>true</externalId>
    <label>Número de póliza</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/SourceCountry__c.field-meta.xml
<CustomField>
    <fullName>SourceCountry__c</fullName>
    <label>Source Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Siniestro</businessProcess>
    <label>Siniestro</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generates to identify a customer. As for life and non-life is the same number, for life record type, it will have prefix LIFE-XXX and for non-life GI-XXX</description>
    <externalId>true</externalId>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <description>A customer or lead DNI</description>
    <label>DNI</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to</description>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MasterPolicyDesc__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyDesc__c</fullName>
    <description>Not visible field in the page layout and used to copy its value to account Name field after parsing it in the parser.</description>
    <label>Masterpolicy description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MasterPolicyNum__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyNum__c</fullName>
    <label>Masterpolicy Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/SourceCountry__c.field-meta.xml
<CustomField>
    <fullName>SourceCountry__c</fullName>
    <label>Source Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Cover__c/Cover__c.object-meta.xml
<CustomObject>
    <label>Cobertura</label>
    <nameField>
        <label>Nombre de Cobertura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coberturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Cover__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to, used to set access with sharing rules</description>
    <label>Entidad legal</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <label>Nombre de Descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Discount__c/fields/DiscountIdNumber__c.field-meta.xml
<CustomField>
    <fullName>DiscountIdNumber__c</fullName>
    <label>DiscountIdNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/Discount__c/fields/DiscountPct__c.field-meta.xml
<CustomField>
    <fullName>DiscountPct__c</fullName>
    <label>Porcentaje descuento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Discount__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Póliza</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Descuentos</relationshipLabel>
    <relationshipName>Descuentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/Caseworker__c.field-meta.xml
<CustomField>
    <fullName>Caseworker__c</fullName>
    <inlineHelpText>Used to identify offline policies. If value != Klinc__life or Klinc__gi, the policy will be marked offline</inlineHelpText>
    <label>Caseworker</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <label>Customer Num</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/MasterPolicyDescr__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyDescr__c</fullName>
    <label>Masterpolicy description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/MasterPolicyNum__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyNum__c</fullName>
    <label>Masterpolicy Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/PolicyContractSerial__c.field-meta.xml
<CustomField>
    <fullName>PolicyContractSerial__c</fullName>
    <label>Versión de póliza</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/PolicyContractStartDate__c.field-meta.xml
<CustomField>
    <fullName>PolicyContractStartDate__c</fullName>
    <label>Fecha inicio versión póliza</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/PolicyNum__c.field-meta.xml
<CustomField>
    <fullName>PolicyNum__c</fullName>
    <externalId>true</externalId>
    <label>Número de la póliza</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/QbLastPage__c.field-meta.xml
<CustomField>
    <fullName>QbLastPage__c</fullName>
    <label>Página Q&amp;B</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/QuoteEntry__c.field-meta.xml
<CustomField>
    <fullName>QuoteEntry__c</fullName>
    <externalId>true</externalId>
    <label>Quote entry</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/SourceCountry__c.field-meta.xml
<CustomField>
    <fullName>SourceCountry__c</fullName>
    <label>Source Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/UpdateReason__c.field-meta.xml
<CustomField>
    <fullName>UpdateReason__c</fullName>
    <label>Motivo de actualización</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>tbd</fullName>
            </value>
            <value>
                <fullName>Policy cancelation (including lapse and regret)</fullName>
            </value>
            <value>
                <fullName>Policy activation</fullName>
            </value>
            <value>
                <fullName>Policy MTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nintendo</fullName>
            </value>
            <value>
                <fullName>Micro</fullName>
            </value>
            <value>
                <fullName>Raycool</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>Moma Bikes</fullName>
            </value>
            <value>
                <fullName>Urban Fox</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
            <value>
                <fullName>E-Twow</fullName>
            </value>
            <value>
                <fullName>LG</fullName>
            </value>
            <value>
                <fullName>Nilox</fullName>
            </value>
            <value>
                <fullName>Huawei</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Segway</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>MSI</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoría</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Laptop</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Game Console</fullName>
            </value>
            <value>
                <fullName>Smartphone</fullName>
            </value>
            <value>
                <fullName>GoPro</fullName>
            </value>
            <value>
                <fullName>ELECTRIC BIKE</fullName>
            </value>
            <value>
                <fullName>Electric Scooter</fullName>
            </value>
            <value>
                <fullName>Smartwatch</fullName>
            </value>
            <value>
                <fullName>Insured Person</fullName>
            </value>
            <value>
                <fullName>Airpods</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/ItemAge__c.field-meta.xml
<CustomField>
    <fullName>ItemAge__c</fullName>
    <description>Product age in months</description>
    <inlineHelpText>Product age in months</inlineHelpText>
    <label>Antigüedad</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/ItemId__c.field-meta.xml
<CustomField>
    <fullName>ItemId__c</fullName>
    <description>Unique identifier or an insured product</description>
    <externalId>true</externalId>
    <label>Item Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Mock_Parser.cls
/**
 * Global class to specify the response expected from the Parser
 * @Autor: nbizkarra (04/05/2020)
 *
 * @update nts (agonzalezisasi) - 26/oct/2020 - Include Mult-Partner logic
 **/
//@isTest
global class Mock_Parser
{
    public static Boolean isIBA_MultiPart = false;
    public static Boolean isIBA_EMEA = false;

    /**
     * MockParser
     */
    static global Map<String, SObject> MockParser(String Entity)
    {
        Map<String, SObject> recordsMap = new Map<String, SObject>();

        if ( Entity.equals('Claim') )
        {
            Case claim = new Case(
                ClaimNumber__c = '797',
                PolicyNum__c = '8989',
                CustomerNum__c = '3123',
                LegalEntity__c = Label.GeneralInsurance,
                DateReg__c = Date.valueOf('2020-01-02'),
                InsuredObjectId__c = '123456789',
                SourceCountry__c = 'Spain'
                );
            if( isIBA_EMEA )
                claim.SourceCountry__c = 'France';
            if( isIBA_MultiPart )
                claim.Partner__c = 'Orange Seguros';

            //Order policyRef=new Order(PolicyNum__c=claim.PolicyNum__c);
            //claim.Policy__r=policyRef;

            recordsMap.put(claim.ClaimNumber__c, (SObject) claim);
        }
        else if ( Entity.equals('Customer') )
        {
            
            if (ExternalRequestUtil.actualRequest.entity__c == 'QuoteEntry')
            {
                Contact lead = new Contact(
                    Email = 'nora@test.com',
                    MobilePhone = '11111111',
                    Status__c = Label.Lead,
                    Birthdate = Date.valueOf('1990-01-01'),
                    FirstName = 'Nora',
                    LastName = '', // Bizkarra // for coverage
                    CustomerNum__c = '9999',
                    LegalEntity__c = Label.GeneralInsurance,
                    SourceCountry__c = 'Spain'
                    );
                if( isIBA_EMEA )
                    lead.SourceCountry__c = 'France';
                if( isIBA_MultiPart )
                {
                    lead.Partner__c = 'Orange Seguros';
                    lead.Status__c = Label.Customer;
                    lead.MasterPolicyNum__c = '666';
                }
                recordsMap.put(lead.CustomerNum__c, (SObject) lead);
            }
            else
            {
                Contact customer = new Contact(
                    DNI__c = '443485723A',
                    Email = 'edu@test.com',
                    MobilePhone = '456456456',
                    Birthdate = Date.valueOf('1990-01-01'),
                    FirstName = 'Eduardo',
                    LastName = 'Sanchez',
                    CustomerNum__c = '3123',
                    LegalEntity__c = Label.GeneralInsurance,
                    MasterPolicyNum__c = '3344',
                    MasterPolicyDesc__c = 'Nestle',
                    SourceCountry__c = 'Spain'
                    );
                if( isIBA_EMEA )
                    customer.SourceCountry__c = 'France';
                if( isIBA_MultiPart )
                    customer.Partner__c = 'Orange Seguros';

                customer.Status__c = Label.Customer;
                recordsMap.put(customer.CustomerNum__c, (SObject) customer);
            }
        }
        else if ( Entity.equals('Policy') )
        {
            Order policy = new Order(
                EffectiveDate = Date.valueOf('1990-01-02'),
                CustomerNum__c = '3123',
                LegalEntity__c = Label.GeneralInsurance,
                PolicyNum__c = '1111',
                PolicyContractSerial__c = '1111-6',
                PolicyContractStartDate__c = Date.valueOf('2020-05-02'),
                UpdateReason__c = '',
                MasterPolicyNum__c = '789789',
                MasterPolicyDescr__c = 'Rastreator',
                Caseworker__c = 'Klinc_life',
                QuoteEntry__c = '10000',
                SourceCountry__c = 'Spain'
                );
            if( isIBA_EMEA )
                policy.SourceCountry__c = 'France';
            if( isIBA_MultiPart )
                policy.Partner__c = 'Orange Seguros';

            recordsMap.put(policy.PolicyNum__c, (SObject) policy);
        }
        else if ( Entity.equals('QuoteEntry') )
        {
            //Quote from the web
            Order quote = new Order(
                QbLastPage__c = Label.Q_LastStep_v1,
                EffectiveDate = Date.valueOf('1994-01-01'),
                CustomerNum__c = '9999',
                LegalEntity__c = Label.GeneralInsurance,
                QuoteEntry__c = '9090',
                SourceCountry__c = 'Spain'
                );
            if( isIBA_EMEA )
                quote.SourceCountry__c = 'France';
            if( isIBA_MultiPart )
                quote.Partner__c = 'Orange Seguros';

            recordsMap.put(quote.QuoteEntry__c, (SObject) quote);
        }
        return recordsMap;
    }

    /**
     * MockParserSecondLevel
     */
    static global Map<String, List<SObject> > MockParserSecondLevel(
        String Entity
        )
    {
        Map<String, List<SObject> > secLvlRecordsMap = new Map<String, List<SObject> >();
        List<SObject> listaDescuentos = new List<SObject>();
        List<SObject> listaItems = new List<SObject>();

        Discount__c disc = new Discount__c(
            Name = 'Primavera 2020',
            DiscountPct__c = 50,
            DiscountIdNumber__c = 1111
            );
        if( isIBA_MultiPart )
            disc.Partner__c = 'Orange Seguros';

        OrderItem item = new OrderItem(
            itemId__c = '7777',
            ItemAge__c = 2,
            Category__c = 'Smartphone',
            Brand__c = 'Samsung',
            itemModel__c = 'Samsung Galaxy'
            );
        if( isIBA_MultiPart )
            item.Partner__c = 'Orange Seguros';

        OrderItem item2 = new OrderItem(
            itemId__c = '6666',
            ItemAge__c = 2,
            Category__c = 'Smartphone',
            Brand__c = 'Apple',
            itemModel__c = 'IphoneX'
            );
        if( isIBA_MultiPart )
            item2.Partner__c = 'Orange Seguros';

        if ( Entity.equals('Quote') )
        {
            // Order quoteRef = new Order(QuoteEntry__c = '9090', SourceCountry__c = 'Spain');
            // if( isIBA_EMEA ) quoteRef.SourceCountry__c = 'France';
            // if( isIBA_MultiPart ) quoteRef.Partner__c = 'Orange Seguros';

            //Descuento
            disc.Policy__r = new Order(QuoteEntry__c = '9090');
            listaDescuentos.add( (SObject) disc );
            secLvlRecordsMap.put('Discount__c', listaDescuentos);

            //orderItem
            item.Order = new Order(QuoteEntry__c = '9090');
            item2.Order = new Order(QuoteEntry__c = '9090');
            listaItems.add( (SObject) item );
            listaItems.add( (SObject) item2 );
            secLvlRecordsMap.put('OrderItem', listaItems);
        }
        else if ( Entity.equals('Policy') )
        {
            // Order policyRef = new Order(PolicyNum__c = '1111');
            // if( isIBA_EMEA ) policyRef.SourceCountry__c = 'France';
            // if( isIBA_MultiPart ) policyRef.Partner__c = 'Orange Seguros';

            //Descuento
            disc.Policy__r = new Order(PolicyNum__c = '1111');
            listaDescuentos.add( (SObject) disc );
            secLvlRecordsMap.put('Discount__c', listaDescuentos);

            //OrderItem
            item.Order = new Order(PolicyNum__c = '1111');
            item2.Order = new Order(PolicyNum__c = '1111');
            listaItems.add( (SObject) item );
            listaItems.add( (SObject) item2 );
            secLvlRecordsMap.put('OrderItem', listaItems);
        }

        return secLvlRecordsMap;
    }

    /**
     * MockParserThirdLevel
     */
    static global Map<String, List<SObject> > MockParserThirdLevel(String Entity)
    {
        Map<String, List<SObject> > thrLvlRecordsMap = new Map<String, List<SObject> >();
        List<SObject> listaObjetos = new List<SObject>();
        List<SObject> listaObjetos2 = new List<SObject>();

        Cover__c cover = new Cover__c(
            CoverId__c = '1',
            ParentCoverId__c = null,
            Name = 'Robo',
            Description__c = 'Cobertura por robo',
            SumInsured__c = 1000,
            SourceCountry__c = 'Spain'
            );
        if( isIBA_MultiPart )
            cover.Partner__c = 'Orange Seguros';

        Cover__c subcover = new Cover__c(
            CoverId__c = '2',
            ParentCoverId__c = '1',
            Name = 'Sub-Robo',
            Description__c = 'SubCobertura por robo',
            SumInsured__c = 150,
            SourceCountry__c = 'Spain'
            );
        if( isIBA_MultiPart )
            subcover.Partner__c = 'Orange Seguros';

        Cover__c cover2 = new Cover__c(
            CoverId__c = '3',
            ParentCoverId__c = null,
            Name = 'Perdida',
            Description__c = 'Cobertura por perdida',
            SumInsured__c = 1000,
            SourceCountry__c = 'Spain'
            );
        if( isIBA_MultiPart )
            cover2.Partner__c = 'Orange Seguros';

        Cover__c subcover2 = new Cover__c(
            CoverId__c = '4',
            ParentCoverId__c = '3',
            Name = 'Sub-Perdida',
            Description__c = 'SubCobertura por perdida',
            SumInsured__c = 150,
            SourceCountry__c = 'Spain'
            );
        if( isIBA_MultiPart )
            subcover2.Partner__c = 'Orange Seguros';

        // OrderItem itemRef = new OrderItem(itemId__c = '7777');

        cover.PolicyProduct__r =  new OrderItem(itemId__c = '7777');
        subcover.PolicyProduct__r =  new OrderItem(itemId__c = '7777');
        cover2.PolicyProduct__r =  new OrderItem(itemId__c = '7777');
        subcover2.PolicyProduct__r =  new OrderItem(itemId__c = '7777');

        listaObjetos.add( (SObject) cover );
        listaObjetos.add( (SObject) subcover );
        listaObjetos.add( (SObject) cover2 );
        listaObjetos.add( (SObject) subcover2 );
        //el key deberia ser el external id de item
        thrLvlRecordsMap.put('7777', listaObjetos);

        // OrderItem itemRef2 = new OrderItem(itemId__c = '6666');

        Cover__c cover3 = new Cover__c(
            CoverId__c = '1',
            ParentCoverId__c = null,
            Name = 'Robo',
            Description__c = 'Cobertura por robo',
            SumInsured__c = 1000,
            SourceCountry__c = 'Spain'
            );
        if( isIBA_MultiPart )
            cover3.Partner__c = 'Orange Seguros';

        Cover__c subcover3 = new Cover__c(
            CoverId__c = '2',
            ParentCoverId__c = '1',
            Name = 'Sub-Robo',
            Description__c = 'SubCobertura por robo',
            SumInsured__c = 150,
            SourceCountry__c = 'Spain'
            );
        if( isIBA_MultiPart )
            subcover3.Partner__c = 'Orange Seguros';

        cover3.PolicyProduct__r = new OrderItem(itemId__c = '6666');
        subcover3.PolicyProduct__r = new OrderItem(itemId__c = '6666');


        listaObjetos2.add( (SObject) cover3 );
        listaObjetos2.add( (SObject) subcover3 );
        //el key deberia ser el external id de item
        thrLvlRecordsMap.put('6666', listaObjetos2);

        return thrLvlRecordsMap;
    }
}