force-app/zurich-base/main/default/objects/Case/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad Legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Case/recordTypes/OCSInquiry.recordType-meta.xml
<RecordType>
    <fullName>OCSInquiry</fullName>
    <active>true</active>
    <businessProcess>OCS</businessProcess>
    <description>OCS</description>
    <label>OCS Inquiry</label>
</RecordType>

force-app/zurich-base/main/default/objects/EmailMessage/fields/GenesysInteractionId__c.field-meta.xml
<CustomField>
    <fullName>GenesysInteractionId__c</fullName>
    <description>Id. de interacción en Genesys Cloud. Se permite vacío ya que no todos los Email se enrutarán en Genesys Cloud</description>
    <externalId>true</externalId>
    <label>Genesys Interaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/GenesysCloudEmailStatusActionTest.cls
@isTest
public with sharing class GenesysCloudEmailStatusActionTest
{
    @isTest
    static void test_genesysCloudEmailStatusActionTest_ok()
    {
        //creamos el caso y el email relacionado
        Case relatedCase = new Case();
        relatedCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('OCSInquiry').getRecordTypeId();
        relatedCase.LegalEntity__c = Label.GeneralInsurance;
        insert relatedCase;

        EmailMessage emailMessage = new EmailMessage();
        emailMessage.Status = '3';
        emailMessage.ParentId = relatedCase.Id;
        emailMessage.FromAddress = 'jgarciamartinez@nts-solutions.com';
        emailMessage.FromName = 'Javi Garcia';
        emailMessage.Subject = 'Prueba';
        emailMessage.GenesysInteractionId__c = '1788029f-ad65-41ea-bc5f-ce41673fe109';
        insert emailMessage;

        List<EmailMessage> listaTemp = new List<EmailMessage>();
        listaTemp.add(emailMessage);

        List<List<EmailMessage> > listaInput = new List<List<EmailMessage> >();
        listaInput.add(listaTemp);

        Test.startTest();
        List<List<String>> inserciones = GenesysCloudEmailStatusAction.execute(listaInput);
        Test.stopTest();

        List<String> listaStatus = new List<String>();
        if (inserciones.size() > 0)
        {
            listaStatus = inserciones.get(0);
        }

        System.assertEquals( 1, listaStatus.size() );
    }
}