force-app/zurich-base/main/default/objects/Case/fields/SourceArea__c.field-meta.xml
<CustomField>
    <fullName>SourceArea__c</fullName>
    <description>OCS</description>
    <label>Source Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generic end customer</fullName>
            </value>
            <value>
                <fullName>End customer partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Partner dome</fullName>
            </value>
            <value>
                <fullName>Mediator</fullName>
            </value>
            <value>
                <fullName>Zurich Business Client</fullName>
            </value>
            <value>
                <fullName>Generic Internal</fullName>
            </value>
            <value>
                <fullName>SDC (Customer Defense Service)</fullName>
            </value>
            <value>
                <fullName>INFO note</fullName>
                <label>Other third parties</label>
            </value>
            <value>
                <fullName>TNPS Customer Survey</fullName>
            </value>
            <value>
                <fullName>Insurance Banking</fullName>
            </value>
            <value>
                <fullName>TPA&apos;s</fullName>
            </value>
            <value>
                <fullName>KLINK end customer</fullName>
            </value>
            <value>
                <fullName>Processing Center</fullName>
            </value>
            <value>
                <fullName>Commercial Team</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <label>Type N2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alta</fullName>
            </value>
            <value>
                <fullName>Anulación</fullName>
            </value>
            <value>
                <fullName>Apoyo Captación</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Asistencia en Viaje</fullName>
            </value>
            <value>
                <fullName>Backoffice</fullName>
            </value>
            <value>
                <fullName>Banca Seguros</fullName>
            </value>
            <value>
                <fullName>Cambio de intermediario</fullName>
            </value>
            <value>
                <fullName>Cambio mediador</fullName>
            </value>
            <value>
                <fullName>Campaña</fullName>
            </value>
            <value>
                <fullName>Cancelacion</fullName>
            </value>
            <value>
                <fullName>Características / Coberturas</fullName>
            </value>
            <value>
                <fullName>Catálogo virtual</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Coberturas</fullName>
            </value>
            <value>
                <fullName>Comentario</fullName>
            </value>
            <value>
                <fullName>Como abro un siniestro</fullName>
            </value>
            <value>
                <fullName>Como abro un siniestro de Dispositivo</fullName>
                <label>Cómo abro un siniestro de Dispositivo</label>
            </value>
            <value>
                <fullName>Como abro un siniestro de Movilidad</fullName>
                <label>Cómo abro un siniestro de Movilidad</label>
            </value>
            <value>
                <fullName>Como abro un siniestro de Vida</fullName>
                <label>Cómo abro un siniestro de Vida</label>
            </value>
            <value>
                <fullName>Como contrato mi seguro</fullName>
            </value>
            <value>
                <fullName>Como firmo mi seguro</fullName>
            </value>
            <value>
                <fullName>Como renuevo mi seguro</fullName>
            </value>
            <value>
                <fullName>Como valido mi seguro</fullName>
            </value>
            <value>
                <fullName>Comparativa Cotización</fullName>
            </value>
            <value>
                <fullName>Comparativa Gestión Cartera</fullName>
            </value>
            <value>
                <fullName>Consulta</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Contraseña App</fullName>
            </value>
            <value>
                <fullName>Contratacion</fullName>
                <label>Contratación</label>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/TypeN3__c.field-meta.xml
<CustomField>
    <fullName>TypeN3__c</fullName>
    <description>Tercer nivel de tipificación</description>
    <label>Type N3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subtype__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abrir</fullName>
            </value>
            <value>
                <fullName>Acceso Descargas</fullName>
            </value>
            <value>
                <fullName>Activation failure</fullName>
                <isActive>false</isActive>
                <label>Activation failure</label>
            </value>
            <value>
                <fullName>Actividad comercial</fullName>
            </value>
            <value>
                <fullName>Agravación del riesgo</fullName>
            </value>
            <value>
                <fullName>Ajuste de cotización</fullName>
            </value>
            <value>
                <fullName>Ajuste oferta</fullName>
                <isActive>false</isActive>
                <label>Ajuste oferta</label>
            </value>
            <value>
                <fullName>Alegaciones SDC</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
            <value>
                <fullName>Annulment</fullName>
                <isActive>false</isActive>
                <label>Annulment</label>
            </value>
            <value>
                <fullName>Anotación Embargo</fullName>
            </value>
            <value>
                <fullName>Anulación</fullName>
            </value>
            <value>
                <fullName>Atención deficiente tramitador</fullName>
            </value>
            <value>
                <fullName>A vencimiento</fullName>
            </value>
            <value>
                <fullName>Ayuda Acceso</fullName>
            </value>
            <value>
                <fullName>Ayuda Descargas</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Bank data</fullName>
                <isActive>false</isActive>
                <label>Bank data</label>
            </value>
            <value>
                <fullName>Bloqueo / Desbloqueo</fullName>
            </value>
            <value>
                <fullName>Bloqueo usuario/contraseña</fullName>
            </value>
            <value>
                <fullName>Cambio datos Riesgo</fullName>
            </value>
            <value>
                <fullName>Cambio de Actividad</fullName>
            </value>
            <value>
                <fullName>Cambio de intermediario</fullName>
            </value>
            <value>
                <fullName>Cambio de mediador</fullName>
            </value>
            <value>
                <fullName>Cambio de Riesgo</fullName>
            </value>
            <value>
                <fullName>Cambio de Roles</fullName>
            </value>
            <value>
                <fullName>Cambio Idioma en póliza</fullName>
            </value>
            <value>
                <fullName>Cambios intermediarios</fullName>
            </value>
            <value>
                <fullName>Cambio Tomador</fullName>
            </value>
            <value>
                <fullName>Campaña</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Case/recordTypes/USPInquiry.recordType-meta.xml
<RecordType>
    <fullName>USPInquiry</fullName>
    <active>true</active>
    <businessProcess>USP</businessProcess>
    <description>Tipo de registro para los casos creados por el equipo de USP</description>
    <label>USP Inquiry</label>
</RecordType>

force-app/zurich-base/main/default/classes/RemoveDuplicatesActionTest.cls
@isTest
public with sharing class RemoveDuplicatesActionTest 
{
    
    @isTest
    static void test_removeDuplicates_OK()
    {
        Id caseUspRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('USPInquiry').getRecordTypeId();
        Case casoPrueba= new Case(RecordTypeId=caseUspRecordType,Subject='Test caso',Status='New',Origin='Phone',
                                  SourceArea__c='Partner',Type='Venta',Subtype__c='Apoyo Captación',TypeN3__c='Con oferta');
        Case casoDiferente= new Case(RecordTypeId=caseUspRecordType,Subject='Test caso2',Status='New',Origin='Phone',
                                  SourceArea__c='Partner',Type='Venta',Subtype__c='Apoyo Captación',TypeN3__c='Con oferta');
        List<Case> listaCasosRepetidos=new List<Case>();

        //Este bucle tiene como función repetir el caso para ver si se elimina en el método
        for (Integer i=0; i<4;i++)
        {
            listaCasosRepetidos.add(casoPrueba);
        }

        listaCasosRepetidos.add(casoDiferente);

        String fieldApi='Subject';

        RemoveDuplicatesAction.FlowInputs flowInput= new RemoveDuplicatesAction.FlowInputs();
		flowInput.listToRemove=listaCasosRepetidos;
        flowInput.fieldApiName=fieldApi;
        List<List<Case>> listaReturn= new List<List<Case>>();
        List<RemoveDuplicatesAction.FlowInputs> listFlowInputs= new List<RemoveDuplicatesAction.FlowInputs>();
        listFlowInputs.add(flowInput);

        Test.startTest();
        listaReturn= RemoveDuplicatesAction.removeDuplicates(listFlowInputs);
        Test.stopTest();
        
        System.assertEquals(2, listaReturn[0].size());
    }
}