force-app/zurich-base/main/default/objects/User/fields/Notified__c.field-meta.xml
<CustomField>
    <fullName>Notified__c</fullName>
    <formula>IF( NotifyDate__c  =  TODAY(), true, false)</formula>
    <label>Notified</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/User/fields/NotifyDate__c.field-meta.xml
<CustomField>
    <fullName>NotifyDate__c</fullName>
    <label>Notify Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/User/fields/NotifyType__c.field-meta.xml
<CustomField>
    <fullName>NotifyType__c</fullName>
    <label>Notify Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Campaña</fullName>
            </value>
            <value>
                <fullName>Salto de tramo</fullName>
            </value>
            <value>
                <fullName>Formación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/classes/UsersSelector.cls
/**
 * @description       : 
 * @author            : aberuete
 * @group             : 
 * @last modified on  : 02-13-2023
 * @last modified by  : aberuete
**/
public with sharing class UsersSelector extends RecordsSelector 
{
    public UsersSelector() 
    {
        super(User.getSObjectType());
    }

    public List<User> findById (Set<Id> userIds)
    {
        this.baseQuery.selectFields
        (
            new List<Schema.SObjectField>
            {
                User.Id,
                User.NotifyType__c,
                User.NotifyDate__c,
                User.Notified__c
            }
        );

        return (List<User>) this.baseQuery.byId(userIds).run();
    }
}