force-app/zurich-base/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalJobQueueBatch__mdt/ExternalJobQueueBatch__mdt.object-meta.xml
<CustomObject>
    <label>External Job Queue Batch</label>
    <pluralLabel>External Job Queue Batch</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalJobQueueBatch__mdt/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
                <default>true</default>
                <label>INFO</label>
            </value>
            <value>
                <fullName>MI_ZURICH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalJobQueueBatch__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>100</fullName>
                <default>true</default>
                <label>100</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalJobQueueBatch__mdt/fields/Retries__c.field-meta.xml
<CustomField>
    <fullName>Retries__c</fullName>
    <label>Retries</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/ExternalRequest__c.object-meta.xml
<CustomObject>
    <description>Request sent by an external system that will be inserted in the processing queue.</description>
    <label>External request</label>
    <nameField>
        <displayFormat>ER{YY}{MM}{DD}{00000}</displayFormat>
        <label>External request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UPSERT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/ContentFormat__c.field-meta.xml
<CustomField>
    <fullName>ContentFormat__c</fullName>
    <label>Content Format</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JSON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>Indicates the type of information is being sent to Salesforce</description>
    <inlineHelpText>Indicates the type of information is being sent to Salesforce</inlineHelpText>
    <label>Entidad</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/NumRetry__c.field-meta.xml
<CustomField>
    <fullName>NumRetry__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of retries. Whenever it is processed it sums 1.</description>
    <inlineHelpText>Number of retries. Whenever it is processed it sums 1.</inlineHelpText>
    <label>Número de reintentos</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Indicates which external system sends data to Salesforce</description>
    <inlineHelpText>Indicates which external system sends data to Salesforce</inlineHelpText>
    <label>Origen</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the request has been processed</description>
    <inlineHelpText>Indicates if the request has been processed</inlineHelpText>
    <label>Procesado</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/ProcessResult__c.field-meta.xml
<CustomField>
    <fullName>ProcessResult__c</fullName>
    <description>Result of the request process</description>
    <inlineHelpText>Result of the request process</inlineHelpText>
    <label>Resultado del proceso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/classes/ExternalJobQueueBatch.cls
/**
 * Clase batch encargada de procesar las external request de los diferentes sistemas de origen integrados con el CRM
 **
 * @author adelgado
 * @date 13/10/2020
 */
global class ExternalJobQueueBatch implements Database.Batchable<sObject>, Schedulable {
  global String query;
  global String origin;
  global String classHandler;
  global Integer maxRetries;
  global Id jobId;
  global Boolean onlyThisOrigin = false;

  private static Map<String, ExternalJobQueueBatch__mdt> settingsByOrigin {
    get {
      if (settingsByOrigin == null) {
        settingsByOrigin = new Map<String, ExternalJobQueueBatch__mdt>();

        for (ExternalJobQueueBatch__mdt setting : [
          SELECT
            Origin__c,
            HandlerClassName__c,
            Priority__c,
            Retries__c,
            Active__c
          FROM ExternalJobQueueBatch__mdt
        ]) {
          settingsByOrigin.put(setting.Origin__c, setting);
        }
      }

      return settingsByOrigin;
    }
    private set;
  }

  global ExternalJobQueueBatch() {
  }

  global ExternalJobQueueBatch(String origin) {
    this.origin = origin;

    if (settingsByOrigin.containsKey(origin)) {
      maxRetries = (Integer) settingsByOrigin.get(origin).Retries__c;
      classHandler = settingsByOrigin.get(origin).HandlerClassName__c;

      query = 'SELECT Origin__c, Entity__c, Action__c, Payload__c, ContentFormat__c, NumRetry__c, ProcessResult__c, CreatedDate, Processed__c, Error_Log__c FROM ExternalRequest__c ';
      query += 'WHERE Origin__c = :origin AND Processed__c = false AND NumRetry__c < :maxRetries ORDER BY CreatedDate, NumRetry__c';
    }
  }

  global void execute(SchedulableContext SC) {
    jobId = database.executeBatch(new ExternalJobQueueBatch(), 200);
  }

  global Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(query);
  }

  global void execute(
    Database.BatchableContext bc,
    List<ExternalRequest__c> externalRequest
  ) {
    try {
      // 1 - Obtener el handler correspondiente al sistema de origen
      ISystem systemHandler = (ISystem) Type.forName(classHandler)
        .newInstance();

      // 2 - Preparar la información necesaria para procesar las external request
      systemHandler.prepare(externalRequest);

      // 3 - Convertir los registros del origen en registros Salesforce
      systemHandler.process(externalRequest);

      // 4 - Realizar las operaciones DML sobre los registros de Salesforce generados
      systemHandler.persists(externalRequest);

      // 5 - Actualizar las external request con el resultado correspondiente
      systemHandler.manageResult(jobId, externalRequest);
    } catch (Exception e) {
      ErrorLogUtil.commitError(e, 'ExternalJobQueueBatch');
    }
  }

  global void finish(Database.BatchableContext bc) {
    /*if(!onlyThisOrigin)
    {
      List<String> originCondition = new List<String>();
      String query = 'SELECT Id FROM ExternalRequest__c WHERE Processed__c = false AND (';

      for(String origin : settingsByOrigin.KeySet())
      {
        if(settingsByOrigin.get(origin).Active__c)
        {
          originCondition.add('(Origin__c = \'' + origin + '\' AND NumRetry__c < ' + settingsByOrigin.get(origin).Retries__c + ')');
          activeOrigin = true;
        }
      }

      if(activeOrigin)
      {
        List<sObject> pendingExternalRequest = Database.query(query + String.join(originCondition, ' OR ') + ') LIMIT 1');

        if(!pendingExternalRequest.isEmpty())
        {
          Id classId = [SELECT Id FROM ApexCLass WHERE Name = 'ExternalJobQueueBatch'].Id;

          List<AsyncApexJob> jobs = [SELECT Id FROM AsyncApexJob WHERE Id != :jobId AND Status NOT IN ('Completed', 'Aborted', 'Failed') AND ApexClassId = :classId AND JobType = 'BatchApex'];

          if (jobs.isEmpty()) 
          {
            database.executeBatch(new ExternalJobQueueBatch(), 200);
          }
        }
      }
    }*/
  }
}