force-app/zurich-base/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalJobQueueBatch__mdt/ExternalJobQueueBatch__mdt.object-meta.xml
<CustomObject>
    <label>External Job Queue Batch</label>
    <pluralLabel>External Job Queue Batch</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalJobQueueBatch__mdt/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
                <default>true</default>
                <label>INFO</label>
            </value>
            <value>
                <fullName>MI_ZURICH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/ExternalRequest__c.object-meta.xml
<CustomObject>
    <description>Request sent by an external system that will be inserted in the processing queue.</description>
    <label>External request</label>
    <nameField>
        <displayFormat>ER{YY}{MM}{DD}{00000}</displayFormat>
        <label>External request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UPSERT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/ContentFormat__c.field-meta.xml
<CustomField>
    <fullName>ContentFormat__c</fullName>
    <label>Content Format</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JSON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>Indicates the type of information is being sent to Salesforce</description>
    <inlineHelpText>Indicates the type of information is being sent to Salesforce</inlineHelpText>
    <label>Entidad</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/NumRetry__c.field-meta.xml
<CustomField>
    <fullName>NumRetry__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of retries. Whenever it is processed it sums 1.</description>
    <inlineHelpText>Number of retries. Whenever it is processed it sums 1.</inlineHelpText>
    <label>Número de reintentos</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Indicates which external system sends data to Salesforce</description>
    <inlineHelpText>Indicates which external system sends data to Salesforce</inlineHelpText>
    <label>Origen</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the request has been processed</description>
    <inlineHelpText>Indicates if the request has been processed</inlineHelpText>
    <label>Procesado</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/ProcessResult__c.field-meta.xml
<CustomField>
    <fullName>ProcessResult__c</fullName>
    <description>Result of the request process</description>
    <inlineHelpText>Result of the request process</inlineHelpText>
    <label>Resultado del proceso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/classes/ExternalJobPriorityQueueBatch.cls
/**
 * Clase batch encargada de procesar las external request de forma directa para priorizar su procesado
 * Actualmente procesa la entidad NOTE
 *
 * @author nts (agonzalezisasi)
 * @date 12/02/2021
 */
global class ExternalJobPriorityQueueBatch implements Database.Batchable<sObject>
{
    private String query;
    private String origin;
    private String classHandler;

    private Transformer transformer;

    // Constructors
    
    global ExternalJobPriorityQueueBatch(String origin)
    {
        this.origin = origin;

        getSettingsByOrigin(origin);
    }

    global ExternalJobPriorityQueueBatch(String origin, String query)
    {
        this(origin);
        
        this.query = query;
    }

    // Start
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        if( String.isBlank(query) ) {
            String exReqRecordTypeId = Schema.SObjectType.ExternalRequest__c.getRecordTypeInfosByDeveloperName().get(origin).getRecordTypeId();
            query = 'SELECT Id FROM ExternalRequest__c ';
            query += ' WHERE RecordTypeId = \'' + exReqRecordTypeId + '\' AND Processed__c = false';
            query += ' AND Entity__c IN ' + INFOHandler.PriorityEntitiesToString;
        }

        return Database.getQueryLocator(query);
    }

    // Execute
    global void execute(Database.BatchableContext bc, List<ExternalRequest__c> externalRequestScope)
    {
        Set<Id> externalRequestIds = new Set<Id>();

        try {
            // 1 - Recuperar los ids de los registros recuperados en el inicio del batch
            for(ExternalRequest__c externalRequest : externalRequestScope) {
                externalRequestIds.add(externalRequest.Id);
            }

            // 2 - Recuperar la información necesaria de las external request
            List<ExternalRequest__c> externalRequests = new ExternalRequestsSelector(
                new List<Schema.SObjectField> {
                    ExternalRequest__c.Origin__c,
                    ExternalRequest__c.Entity__c,
                    ExternalRequest__c.Action__c,
                    ExternalRequest__c.Payload__c,
                    ExternalRequest__c.ContentFormat__c,
                    ExternalRequest__c.NumRetry__c,
                    ExternalRequest__c.ProcessResult__c,
                    ExternalRequest__c.CreatedDate,
                    ExternalRequest__c.Processed__c,
                    ExternalRequest__c.Error_Log__c
                }
            ).selectById(externalRequestIds);

            // 3 - Obtener el handler correspondiente al sistema de origen
            ISystem systemHandler = (ISystem) Type.forName(classHandler).newInstance();

            // 4 - Preparar la información necesaria para procesar las external request
            systemHandler.prepare(transformer, externalRequests);

            // 5 - Convertir los registros del origen en registros Salesforce
            systemHandler.process(externalRequests);

            // 6 - Realizar las operaciones DML sobre los registros de Salesforce generados
            systemHandler.persists(externalRequests);

            // 7 - Actualizar las external request con el resultado correspondiente
            systemHandler.manageResult(bc.getJobId(), externalRequests);
        }
        catch (Exception e) {
            ErrorLogUtil.commitError(e, 'ExternalJobPriorityQueueBatch');
        }
    }

    // Finish
    global void finish(Database.BatchableContext bc)
    {
        System.debug('---------- finish - origin: ' + origin);
        // check if there are more Priority entities to process..
        String exReqRecordTypeId = Schema.SObjectType.ExternalRequest__c.getRecordTypeInfosByDeveloperName().get(origin).getRecordTypeId();
        String queryNum = 'SELECT count() FROM ExternalRequest__c '; 
        queryNum += ' WHERE RecordTypeId = \'' + exReqRecordTypeId + '\' AND Processed__c = false';
        queryNum += ' AND Entity__c IN ' + INFOHandler.PriorityEntitiesToString;

        Integer num = Database.countQuery(queryNum);
        // if there are any, execute the batch again...
        if( num > 0 ) {
            //if( !Test.isRunningTest() )
            ExternalJobQueueBatchController.checkExternalJobPriorityQueueBatch();
        }
    }

    /**
     * Obtiene la configuración correspondiente al sistema de origen de las external request
     **
     * @author adelgado
     * @date 17/11/2020
     * @param origin Origen de las external request
     * @return
     */
    private void getSettingsByOrigin(String origin)
    {
        List<ExternalJobQueueBatch__mdt> settings = new ExternalJobQueueBatchesSelector(
            new List<Schema.SObjectField>{ExternalJobQueueBatch__mdt.HandlerClassName__c}
        ).selectByOrigin(new Set<String> {origin});

        if( settings != null && !settings.isEmpty() ) {
            classHandler = settings.get(0).HandlerClassName__c;
            transformer = new Transformer(origin);
        }
    }
}