force-app/zurich-base/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PlanComercial__c/PlanComercial__c.object-meta.xml
<CustomObject>
    <description>SDM: Utilizado para representar el plan de negocio realizado por los directores.</description>
    <label>Plan Comercial</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Actual_KPI__c.field-meta.xml
<CustomField>
    <fullName>Actual_KPI__c</fullName>
    <description>SDM: el resultado de KPI calculado de forma automática para el plan de acción a través de todos los criterios establecidos en el mismo</description>
    <label>Actual KPI</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-sdm-app/main/default/classes/PlanComercialSDMBatchTest.cls
/**
 * Test para la clase PlanComercialSDMBatch
 *
 * @author nts (agonzalezisasi)
 * @date 27/07/2021
 */
@isTest
private class PlanComercialSDMBatchTest
{
    /**
     * Metodo comun para todas los metodos de test. Inicializa los datos de prueba
     *
     * @author nts (agonzalezisasi)
     * @date 27/07/2021
     */
    @TestSetup
    static void makeData() 
    {
        TestDataFactorySDM.PlanComercialSetupData();
    }

    /**
     * Test del metodo execute del batch
     *
     * @author nts (agonzalezisasi)
     * @date 27/07/2021
     */
    @isTest
    static void execute()
    {
        PlanComercialSDMBatch batch = new PlanComercialSDMBatch();

        Test.startTest();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();

        // Comprobacion del restulado -----------------------------------------
        List<PlanComercial__c> checkPlans = [
            SELECT Id, Actual_KPI__c FROM PlanComercial__c
            WHERE Actual_KPI__c != null
        ];
        System.assertEquals(4, checkPlans.size(), 'Deberia haber 4 planes');
    }

    /**
     * Test del error desconocido en el execute
     *
     * @author nts (agonzalezisasi)
     * @date 27/07/2021
     */
    @isTest
    static void execute_ko()
    {
        String query = 'SELECT Id FROM Account';
        PlanComercialSDMBatch batch = new PlanComercialSDMBatch(query); // para cobertura
        batch.testUnknownError = true;

        Test.startTest();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();

        List<Error_Log__c> errorLogs = [SELECT Id FROM Error_Log__c];
        System.assertEquals(false, errorLogs.isEmpty(), 'Deberia haber Error Logs');
    }
    
    /**
	 * Test of the batch scheduling
	 */
	@isTest 
	static void schedule() {
		Test.startTest();
        PlanComercialSDMBatch.createStandardSchedule(null, null, null);
		Test.stopTest();
	}
}