force-app/zurich-base/main/default/objects/AccountRelationship__c/AccountRelationship__c.object-meta.xml
<CustomObject>
    <label>Cuenta Relacionada</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuentas Relacionadas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/AccountRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Lead</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BusinessCustomer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Relationships</relationshipLabel>
    <relationshipName>Accounts_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>OCS</description>
    <label>Siniestro</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Siniestros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <description>(OCS). Puntero a la póliza vinculada</description>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/fields/PolicyHolder__c.field-meta.xml
<CustomField>
    <fullName>PolicyHolder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Puntero al tomador de la póliza vinculada</description>
    <label>Policy holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Entity in which to register relevant data of policies contracted by the Customer with competitors of Zurich.</description>
    <label>Competitor</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Competitor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nombre del cliente del que se está registrando la competencia</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor</relationshipLabel>
    <relationshipName>Competitors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/Propensity__c.field-meta.xml
<CustomField>
    <fullName>Propensity__c</fullName>
    <label>Propensity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/PolicyHolder__c.field-meta.xml
<CustomField>
    <fullName>PolicyHolder__c</fullName>
    <description>(OCS). Identifica el tomador de la póliza</description>
    <label>Policy Holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Policy Holder)</relationshipLabel>
    <relationshipName>PoliciesHolder</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Propensity__c/Propensity__c.object-meta.xml
<CustomObject>
    <label>Propensión</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propensiones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Propensity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Nombre del cliente para identificar a qué cliente se refiere la propensión</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account</relationshipLabel>
    <relationshipName>Propensiones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Propensity__c/fields/Propensity__c.field-meta.xml
<CustomField>
    <fullName>Propensity__c</fullName>
    <description>Propensity type</description>
    <label>Propensity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-ventas-app/main/default/classes/ZRMExportCustomerInfoController.cls
global with sharing class ZRMExportCustomerInfoController {
    public Account account { get; set; }
    public List<Opportunity> opportunities { get; set; }
    public List<Policy__c> policies { get; set; }
    public List<Claim__c> claims { get; set; }
    public List<Propensity__c> propensities { get; set; }
    public List<Competitor__c> competitors { get; set; }
    public List<AccountRelationship__c> accountsRelationships { get; set; }
    public List<CampaignMember> campaignMembers { get; set; }
    public String accountPhone { get; set; }
    public String accountEmail { get; set; }

    public ZRMExportCustomerInfoController(ApexPages.StandardController controller) {
        account = (Account)controller.getRecord();
        loadRelatedData();
    }

    public void loadRelatedData() {


        // Obtenemos los datos que cuelgan del cliente directamente
        List<Account> accountRelatedData = (new AccountsSelector()).selectAccountAndRelatedInfo(new List<String>{account.Id});
        opportunities = accountRelatedData.get(0).Opportunities;
        policies = accountRelatedData.get(0).PoliciesHolder__r;
        claims = accountRelatedData.get(0).Claims__r;
        propensities = accountRelatedData.get(0).Propensiones__r;
        competitors = accountRelatedData.get(0).Competitors__r;
        accountsRelationships = accountRelatedData.get(0).Accounts_Relationships__r;

        // Obtengo la información de las campañas del cliente
        campaignMembers = getAccountCampaignsData(account);

        // Obtengo la información de contacto del cliente
        Map<String, String> contactData = getAccountContactData(accountRelatedData.get(0));
        accountPhone = contactData.get('phone');
        accountEmail = contactData.get('email');
    }





    public Map<String, String> getAccountContactData(Account account) {
        Map<String, String> result = new Map<String, String>();
        String phone = '';
        String email = '';
        
        // obtengo el registro de email (solo deberia haber uno)
        for(ContactPointEmail emailPrimary: account.ContactPointEmails)  {
            email = emailPrimary.EmailAddress;
            break;
        }

        // obtengo el registro de email (solo deberia haber uno)
        for(ContactPointPhone phonePrimary: account.ContactPointPhones)  {
            phone = phonePrimary.TelephoneNumber;
            break;
        }

        result.put('phone', phone);
        result.put('email', email);

        return result;
    }

    public List<CampaignMember> getAccountCampaignsData(Account account) {
        List<CampaignMember> result = new List<CampaignMember>();
        List<String> accountIdsList = new List<String>();
        CampaignMembersSelector.ProperCampaignMembersSelector selector = new CampaignMembersSelector.ProperCampaignMembersSelector();

        accountIdsList.add(account.Id);

        result = selector.selectCrossSellingCampaingsFromAccount(accountIdsList);

        return result;
    }
}