force-app/zurich-base/main/default/objects/ExternalRequest__c/ExternalRequest__c.object-meta.xml
<CustomObject>
    <description>Request sent by an external system that will be inserted in the processing queue.</description>
    <label>External request</label>
    <nameField>
        <displayFormat>ER{YY}{MM}{DD}{00000}</displayFormat>
        <label>External request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/ExternalRequest__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Indicates which external system sends data to Salesforce</description>
    <inlineHelpText>Indicates which external system sends data to Salesforce</inlineHelpText>
    <label>Origen</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ExternalRequest__c/recordTypes/INFO.recordType-meta.xml
<RecordType>
    <fullName>INFO</fullName>
    <active>true</active>
    <label>INFO</label>
</RecordType>

force-app/zurich-base/main/default/classes/ExternalRequestsSelectorTest.cls
@isTest
private class ExternalRequestsSelectorTest
{
    @TestSetup
    static void makeData()
    {
        List<ExternalRequest__c> externalRequestList = TestDataFactory.generateExternalRequest('INFO', 'NATURAL_ACCOUNT', 10);
        insert externalRequestList;
    }

    /**
     * Test origen nulo
     *
     * @author adelgado
     * @date 29/10/2020
     */
    @isTest
    static void test_selectByOrigin_null()
    {
        Test.startTest();
        List<ExternalRequest__c> selectedExtReq = new ExternalRequestsSelector(new List<Schema.SObjectField> {ExternalRequest__c.Origin__c}).selectByOrigin(null);
        Test.stopTest();

        System.assertEquals(true, selectedExtReq.isEmpty(), 'Se han obtenido external request erróneas');
    }

    /**
     * Test origen correcto
     *
     * @author adelgado
     * @date 29/10/2020
     */
    @isTest
    static void test_selectByOrigin_ok()
    {
        Test.startTest();
        List<ExternalRequest__c> selectedExtReq = new ExternalRequestsSelector(new List<Schema.SObjectField> {ExternalRequest__c.Origin__c}).selectByOrigin(new Set<String> {'INFO'});
        Test.stopTest();

        System.assertEquals(10, selectedExtReq.size(), 'No se han obtenido external request');
    }

    /**
     * Test origen correcto con límite  de registros
     *
     * @author adelgado
     * @date 29/10/2020
     */
    @isTest
    static void test_selectByOrigin_ok_limit()
    {
        Test.startTest();
        List<ExternalRequest__c> selectedExtReq = new ExternalRequestsSelector(new List<Schema.SObjectField> {ExternalRequest__c.Origin__c}).setLimit(1).selectByOrigin(new Set<String> {'INFO'});
        Test.stopTest();

        System.assertEquals(1, selectedExtReq.size(), 'No se han obtenido external request');
    }
}