force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/LeadAssignmentConfiguration__c.object-meta.xml
<CustomObject>
    <description>Permite configurar la lógica de asignación de leads directamente desde producción.</description>
    <label>Lead Assignment Configuration</label>
    <nameField>
        <displayFormat>LA-{0000000}</displayFormat>
        <label>Lead Assignment Configuration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads Assignment Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/fields/AssignmentType__c.field-meta.xml
<CustomField>
    <fullName>AssignmentType__c</fullName>
    <description>Criterio de asignación.</description>
    <inlineHelpText>Indica el criterio de asignación de leads a mediadores (Directa, por provincia, etc.)</inlineHelpText>
    <label>Assignment type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Province</fullName>
            </value>
            <value>
                <fullName>Municipality</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/fields/AssignTo__c.field-meta.xml
<CustomField>
    <fullName>AssignTo__c</fullName>
    <label>Assign to</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/fields/ForumOrigin__c.field-meta.xml
<CustomField>
    <fullName>ForumOrigin__c</fullName>
    <description>Formulario de origen de los datos.</description>
    <inlineHelpText>La correspondencia de nombre debe ser exacta.</inlineHelpText>
    <label>Forum origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Idioma del lead</description>
    <label>Language</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Código de provincia</description>
    <inlineHelpText>Coincide con los dos primeros dígitos del código postal. Si el código postal comienza por 0, el código de provincia también deberá comenzar por cero.</inlineHelpText>
    <label>PostalCode</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Provincia de los leads que serán asignados al mediador indicado.</description>
    <label>Province</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/fields/ProvinceCode__c.field-meta.xml
<CustomField>
    <fullName>ProvinceCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>ProvinceCode</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/fields/ZIPRanges__c.field-meta.xml
<CustomField>
    <fullName>ZIPRanges__c</fullName>
    <description>Asignación de rangos de códigos postales de leads a mediadores.</description>
    <inlineHelpText>Formato json:

Cada dupla contiene el último Código Postal del rango, seguido del código de mediador receptor.

Con un único rango: {&quot;02999&quot;: &quot;123456789&quot;}, los códigos postales entre 02000 y 02999 se asignarán al mediador con código 123456789

Con varios rangos: {&quot;08020&quot;: &quot;111111111&quot;, &quot;08999&quot;: &quot;222222222&quot;}. los códigos postales entre 00000 y 08020 se asignarán al mediador con código 111111111, los que estén entre 08021 y 08999, a 222222222.</inlineHelpText>
    <label>ZIPRanges</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/recordTypes/ForumOriginAssignment.recordType-meta.xml
<RecordType>
    <fullName>ForumOriginAssignment</fullName>
    <active>true</active>
    <label>ForumOriginAssignment</label>
</RecordType>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/recordTypes/LanguageAssignment.recordType-meta.xml
<RecordType>
    <fullName>LanguageAssignment</fullName>
    <active>true</active>
    <description>Se utiliza para indicar a qué mediador se deben asignar los leads en función de su idioma.</description>
    <label>Language Assignment</label>
</RecordType>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/recordTypes/MunicipalityAssignment.recordType-meta.xml
<RecordType>
    <fullName>MunicipalityAssignment</fullName>
    <active>true</active>
    <label>MunicipalityAssignment</label>
</RecordType>

force-app/zurich-base/main/default/objects/LeadAssignmentConfiguration__c/recordTypes/ProvinceAssignment.recordType-meta.xml
<RecordType>
    <fullName>ProvinceAssignment</fullName>
    <active>true</active>
    <description>Se utiliza para indicar a qué mediador se deben asignar los leads de cada provincia.</description>
    <label>Province Assignment</label>
</RecordType>

force-app/zurich-base/main/default/classes/LeadAssignmentConfigurationsSelector.cls
/**
 * @description       : Clase selectora del sobject LeadAssignmentConfiguration
 * @author            : jlnavarroq
 * @group             :
 * @last modified on  : 11/10/2024
 * @last modified by  : jlnavarroq
 **/

 public with sharing class LeadAssignmentConfigurationsSelector extends RecordsSelector {

    public RecordsSelector.Scope relatedRecordsScope;
    
    public LeadAssignmentConfigurationsSelector()
    {
        super( LeadAssignmentConfiguration__c.getSObjectType() );
    }

    //#region RECORD TYPES
    public static final String RT_Forum_Origin_Assignment   = GlobalConfigUtil.getGlobalConfigurationValue('AccountLeadAssignmentForumRT');
    public static final String RT_Language_Assignment       = GlobalConfigUtil.getGlobalConfigurationValue('AccountLeadAssignmentLanguageRT');
    public static final String RT_Municipality_Assignment   = GlobalConfigUtil.getGlobalConfigurationValue('AccountLeadAssignmentMunicipalRT');
    public static final String RT_Province_Assignment       = GlobalConfigUtil.getGlobalConfigurationValue('AccountLeadAssignmenProvinceRT');
     
    public ID rtForumOriginId {
        get {
            return Schema.SObjectType.LeadAssignmentConfiguration__c.getRecordTypeInfosByDeveloperName().get(RT_Forum_Origin_Assignment)?.getRecordTypeId();
        }
    }
     
     public ID rtLanguageAssignmentId {
        get {
            return Schema.SObjectType.LeadAssignmentConfiguration__c.getRecordTypeInfosByDeveloperName().get(RT_Language_Assignment)?.getRecordTypeId();
        }
    }
     
     public ID rtMunicipalityAssignmentId {
        get {
            return Schema.SObjectType.LeadAssignmentConfiguration__c.getRecordTypeInfosByDeveloperName().get(RT_Municipality_Assignment)?.getRecordTypeId();
        }
    }
     
     public ID rtProvinceAssignmentId {
        get {
            return Schema.SObjectType.LeadAssignmentConfiguration__c.getRecordTypeInfosByDeveloperName().get(RT_Province_Assignment)?.getRecordTypeId();
        }
    }
    
    // Recupera campos del RecordType ForumOriginAssignment de LeadAssignmentConfiguratio
    public List<LeadAssignmentConfiguration__c> getForumOriginAssignments() {
        return getLeadAssignmentConfiguratioByRT( RT_Forum_Origin_Assignment );
    }

    // Recupera campos del RecordType LanguageAssignment de LeadAssignmentConfiguratio
    public List<LeadAssignmentConfiguration__c> getLanguageAssignments() {
        return getLeadAssignmentConfiguratioByRT( RT_Language_Assignment );
    }

    // Recupera campos del RecordType MunicipalityAssignment de LeadAssignmentConfiguratio
    public List<LeadAssignmentConfiguration__c> getMunicipalityAssignments() {
        return getLeadAssignmentConfiguratioByRT( RT_Municipality_Assignment );
    }

    // Recupera campos del RecordType ProvinceAssignment de LeadAssignmentConfiguratio
    public List<LeadAssignmentConfiguration__c> getProvinceAssignments() {
        return getLeadAssignmentConfiguratioByRT( RT_Province_Assignment );
    }

    private List<LeadAssignmentConfiguration__c> getLeadAssignmentConfiguratioByRT(String rt) {
            
        if( rt == RT_Forum_Origin_Assignment ){
            // Agregar los campos a seleccionar
            this.baseQuery.selectFields
            (
                new List<Schema.SObjectField>
                {
                    LeadAssignmentConfiguration__c.AssignTo__c,
                    LeadAssignmentConfiguration__c.AssignmentType__c,
                    LeadAssignmentConfiguration__c.ForumOrigin__c
                }
            );
            // Agregar la condición para filtrar por RecordTypeId
        	this.baseQuery.addConditionEq('RecordTypeId', rtForumOriginId);
        }
        if( rt == RT_Language_Assignment ){
            // Agregar los campos a seleccionar
            this.baseQuery.selectFields
            (
                new List<Schema.SObjectField>
                {
                    LeadAssignmentConfiguration__c.AssignTo__c,
                    LeadAssignmentConfiguration__c.Language__c
                }
            );
            // Agregar la condición para filtrar por RecordTypeId
        	this.baseQuery.addConditionEq('RecordTypeId', rtLanguageAssignmentId);
        }
        if( rt == RT_Municipality_Assignment ){
            // Agregar los campos a seleccionar
            this.baseQuery.selectFields
            (
                new List<Schema.SObjectField>
                {
                    LeadAssignmentConfiguration__c.ProvinceCode__c,
                    LeadAssignmentConfiguration__c.ZIPRanges__c
                }
            );
            // Agregar la condición para filtrar por RecordTypeId
        	this.baseQuery.addConditionEq('RecordTypeId', rtMunicipalityAssignmentId);
        }
        if( rt == RT_Province_Assignment ){
            // Agregar los campos a seleccionar
            this.baseQuery.selectFields
            (
                new List<Schema.SObjectField>
                {
                    LeadAssignmentConfiguration__c.AssignTo__c,
                    LeadAssignmentConfiguration__c.PostalCode__c,
                    LeadAssignmentConfiguration__c.Province__c
                }
            );
            // Agregar la condición para filtrar por RecordTypeId
        	this.baseQuery.addConditionEq('RecordTypeId', rtProvinceAssignmentId);
        }  

        // Ejecutar la query
        return this.baseQuery.run();
    }
     
    
    
}