force-app/zurich-base/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Entity in which to register relevant data of policies contracted by the Customer with competitors of Zurich.</description>
    <label>Competitor</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Competitor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nombre del cliente del que se está registrando la competencia</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor</relationshipLabel>
    <relationshipName>Competitors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Competitor__c/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Atributo que informa del código de mediador de la cuenta a la que se asocia la competencia</description>
    <label>Mediador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competencias (Mediador)</relationshipLabel>
    <relationshipName>Competencias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Competitor__c/fields/IntermediaryIdOld__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryIdOld__c</fullName>
    <description>Guarda temporalmente el Id del mediador para calcular la visibilidad</description>
    <label>IntermediaryIdOld</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/zurich-ventas-app/main/default/classes/CompetitorSelector.cls
public with sharing class CompetitorSelector {
    

    public List<Competitor__c> findCompetitorsToGiveVisibility(List<String> accountIdList, Set<String> intermediaryIdList) {
        List<Competitor__c> result = new List<Competitor__c>();

        result = new List<Competitor__c>([SELECT Id, IntermediaryId__c, IntermediaryIdOld__c 
                                        FROM Competitor__c
                                        WHERE Account__c IN :accountIdList
                                        AND IntermediaryIdOld__c IN: intermediaryIdList]);

        return result;
    }


    public List<Competitor__c> findCompetitorsToDenyVisibility(List<String> accountIdList, Set<String> intermediaryIdList) {
        List<Competitor__c> result = new List<Competitor__c>();

        result = new List<Competitor__c>([SELECT Id, IntermediaryId__c, IntermediaryIdOld__c 
                                        FROM Competitor__c
                                        WHERE Account__c IN :accountIdList
                                        AND IntermediaryId__c IN: intermediaryIdList]);

        return result;
    }
}