force-app/zurich-base/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Entity in which to register relevant data of policies contracted by the Customer with competitors of Zurich.</description>
    <label>Competitor</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Competitor__c/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Atributo que informa del código de mediador de la cuenta a la que se asocia la competencia</description>
    <label>Mediador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competencias (Mediador)</relationshipLabel>
    <relationshipName>Competencias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Competitor__c/fields/IntermediaryIdOld__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryIdOld__c</fullName>
    <description>Guarda temporalmente el Id del mediador para calcular la visibilidad</description>
    <label>IntermediaryIdOld</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/zurich-ventas-app/main/default/classes/CompetitorUtil.cls
public with sharing class CompetitorUtil {
    
    /**
     * Metodo que vuelve a dar visibilidad sobre los registros de competencia para los clientes que se da visibilidad
     * 
     *
     * @author dmunoz
     * @date 12/02/2024 
     */
    public static void recalculateVisibilityCompetitorSetVisibility(List<String> accountIdList, Set<String> intermediaryIdList) {
        CompetitorSelector selector = new CompetitorSelector();
        List<Competitor__c> competitorsToUpdate = new List<Competitor__c>();
        
        List<Competitor__c> competitorsToActivate = selector.findCompetitorsToGiveVisibility(accountIdList, intermediaryIdList);        

        Competitor__c aux;
        for (Competitor__c competitor: competitorsToActivate) {
            aux = new Competitor__c();
            aux.Id = competitor.Id;
            aux.IntermediaryId__c = competitor.IntermediaryIdOld__c;
            aux.IntermediaryIdOld__c = null;
            competitorsToUpdate.add(aux);
        }
        if (!competitorsToUpdate.isEmpty()) {
            update competitorsToUpdate;
        }
    }


    /**
     * Metodo que quita visibilidad sobre los registros de competencia para los clientes que se resta visibilidad
     * 
     *
     * @author dmunoz
     * @date 12/02/2024 
     */
    public static void recalculateVisibilityCompetitorDenyVisibility(List<String> accountIdList, Set<String> intermediaryIdList) {
        CompetitorSelector selector = new CompetitorSelector();
        List<Competitor__c> competitorsToUpdate = new List<Competitor__c>();
        
        List<Competitor__c> competitorsToActivate = selector.findCompetitorsToDenyVisibility(accountIdList, intermediaryIdList);        

        Competitor__c aux;
        for (Competitor__c competitor: competitorsToActivate) {
            aux = new Competitor__c();
            aux.Id = competitor.Id;
            aux.IntermediaryIdOld__c = competitor.IntermediaryId__c;
            aux.IntermediaryId__c = null;
            competitorsToUpdate.add(aux);
        }
        if (!competitorsToUpdate.isEmpty()) {
            update competitorsToUpdate;
        }
    }
}