force-app/zurich-base/main/default/objects/Contact/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generates to identify a customer. As for life and non-life is the same number, for life record type, it will have prefix LIFE-XXX and for non-life GI-XXX</description>
    <externalId>true</externalId>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to</description>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/recordTypes/LeadGI.recordType-meta.xml
<RecordType>
    <fullName>LeadGI</fullName>
    <active>true</active>
    <label>Lead no vida</label>
</RecordType>

force-app/zurich-base/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Test_Batch_DeleteLeads.cls
/**
 * Clases de test para Batch_DeleteLeads
 **
 * @author nbizkarra
 * @date 27/04/2020
 */
@isTest
private class Test_Batch_DeleteLeads {
  /**
   * Create test data
   **
   * @author nbizkarra
   * @date 27/04/2020
   */
  @TestSetup
  static void test_CreateData() {
    Contact lead = new Contact(
      Email = 'edu@test.com',
      Birthdate = Date.valueOf('1990-01-01'),
      FirstName = 'Edu',
      LastName = 'Sanchez',
      CustomerNum__c = 'GI-3123',
      LegalEntity__c = Label.GeneralInsurance,
      RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.LeadGI)
    );
    insert lead;
  }

  /** 
    * El campo 'lastmodified' de los registros de lead
    no son más antiguos que 7 días, no se elimina ningún regitro.
    **
    * @author nbizkarra
    * @date 27/04/2020
    */

  @isTest
  static void test_NoEliminarLead() {
    Integer numContact = [SELECT COUNT() FROM Contact];
    System.assertEquals(1, numContact);

    String query = 'SELECT Id FROM Error_Log__c WHERE LastModifiedDate < LAST_N_DAYS:7';
    Test.startTest();
    Id BatchInstanceId = database.executeBatch(
      new Batch_DeleteLeads(query),
      200
    );
    Test.stopTest();

    numContact = [SELECT COUNT() FROM Contact];

    System.assertEquals(1, numContact);
  }

  /**
    * Este método de test llama al Batch a través de una query personalizada.
    y elimina todos los registros existentes de lead.
    * *
    * @author nbizkarra
    * @date 27/04/2020
    */

  @isTest
  static void test_EliminarLead() {
    Integer numContact = [SELECT COUNT() FROM Contact];
    System.assertEquals(1, numContact);

    String query = 'SELECT Id FROM Contact  ';

    Test.startTest();
    Id BatchInstanceId = database.executeBatch(
      new Batch_DeleteLeads(query),
      200
    );
    Test.stopTest();

    numContact = [SELECT COUNT() FROM Contact];
    System.assertEquals(0, numContact);
  }
}