force-app/zurich-base/main/default/objects/RoutingTeamQueueConfig__mdt/RoutingTeamQueueConfig__mdt.object-meta.xml
<CustomObject>
    <label>Routing Team Queue Configuration</label>
    <pluralLabel>Routing Team Queues Configuratio</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/RoutingTeamQueueConfig__mdt/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <description>Cola de casos asociada a un equipo de enrutamiento</description>
    <label>Queue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/RoutingTeamQueueConfig__mdt/fields/RoutingTeam__c.field-meta.xml
<CustomField>
    <fullName>RoutingTeam__c</fullName>
    <description>Equipo de Enrutamiento</description>
    <label>Routing Team</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/classes/RoutingTeamQueueConfigUtil.cls
/**
 * Clase utils para la gestión de la custom metadata  RoutingTeamQueueConfig__mdt, cuyo objetivo es mapear las colas de casos
 * con el equipo de enrutamiento correspondiente
 * @author fjbelmonte
 * @date 24/10/2024
 */
public with sharing class RoutingTeamQueueConfigUtil {
 
    /**
     * Devuelve en forma de mapa todas las colas con su correspondiente equipo de enrutamiento
     * @author fjbelmonte
     * @date 24/10/2024
     * @return  Mapa con los valores de la mdt
     */
    public static Map<String, String> getRoutingTeamQueueConfigValues()
    {
        Map<String, String> mConfigValues = new Map<String, String>();
        
        //Get de todos los registros del CMT
        Map<String, RoutingTeamQueueConfig__mdt> mConfigs = RoutingTeamQueueConfig__mdt.getAll();
        // Agregar los valores al mapa
        for (RoutingTeamQueueConfig__mdt config : mConfigs.values()) {
            mConfigValues.put(config.Queue__c, config.RoutingTeam__c);
        }
        return mConfigValues;
    }
}