force-app/zurich-base/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objetivos</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Objective__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <label>Indicador</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>Portfolio</fullName>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Producto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autos</fullName>
            </value>
            <value>
                <fullName>Hogar</fullName>
            </value>
            <value>
                <fullName>Inmuebles</fullName>
            </value>
            <value>
                <fullName>Accidentes</fullName>
            </value>
            <value>
                <fullName>Comercios</fullName>
            </value>
            <value>
                <fullName>Patrimoniales</fullName>
            </value>
            <value>
                <fullName>Resp. Civil</fullName>
            </value>
            <value>
                <fullName>Vida riesgo individual</fullName>
            </value>
            <value>
                <fullName>Vida riesgo colectivo</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
            <value>
                <fullName>Resto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segmento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulares</fullName>
            </value>
            <value>
                <fullName>PYMEs</fullName>
            </value>
            <value>
                <fullName>Grandes empresas</fullName>
            </value>
            <value>
                <fullName>Vida riesgo</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Año</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zona</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zonas_Plan_Comercial</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/PlanComercial__c.object-meta.xml
<CustomObject>
    <description>SDM: Utilizado para representar el plan de negocio realizado por los directores.</description>
    <label>Plan Comercial</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/AccumulateType__c.field-meta.xml
<CustomField>
    <fullName>AccumulateType__c</fullName>
    <description>SDM: tipo de acumulado con el que se quiere comparar dentro del objeto KPI</description>
    <label>Accumulate type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
                <label>Current month</label>
            </value>
            <value>
                <fullName>YTD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDM: usuario, de tipo RN o consultor, al que irá asociado el registro. Se utiliza de cara a que un Director pueda generar planes para los usuarios de los que es responsable.</description>
    <label>Assigned to</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Solo se puede asignar planes comerciales a usuarios de SDM</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>SDM RN</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>SDM Director</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PlanComercial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SDM: permite cerrar manualmente el plan de acción, para cambiar el estado del plan, y dejar de generar notificaciones y tareas.</description>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>SDM: permite a los usuarios incluir información relevante sobre el plan generado</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>SDM: fecha en la que finaliza el plan de acción (solo aplicable a tipo acumulado YTD)</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <description>SDM: indicador (campo) del KPI con el que se quiere comparar el objetivo</description>
    <label>Indicator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>PoliciesPN</fullName>
                <label>Pólizas PN</label>
            </value>
            <value>
                <fullName>PoliciesInForce</fullName>
                <label>Pólizas en vigor</label>
            </value>
            <value>
                <fullName>Portfolio</fullName>
                <label>Cartera</label>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
            <value>
                <fullName>Ratio_Claim</fullName>
                <label>% Sin Total</label>
            </value>
            <value>
                <fullName>Ratio_PNIncrease</fullName>
                <label>% Crec PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesPNIncreas</fullName>
                <label>% Crec Pólizas PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesInForceIncrease</fullName>
                <label>% Crec Pólizas vigor vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PortIncrease</fullName>
                <label>% crecimiento cartera</label>
            </value>
            <value>
                <fullName>Totaldiscount</fullName>
                <label>% Dto. Total</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>SDM: productos del que se quiere obtener la información de los KPIs</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autos</fullName>
                <label>Cars</label>
            </value>
            <value>
                <fullName>Hogar</fullName>
                <label>Home</label>
            </value>
            <value>
                <fullName>Inmuebles</fullName>
                <label>Estate</label>
            </value>
            <value>
                <fullName>Accidentes</fullName>
                <label>Accidents</label>
            </value>
            <value>
                <fullName>Comercios</fullName>
                <label>Commerce</label>
            </value>
            <value>
                <fullName>Patrimoniales</fullName>
                <label>Patrimonial</label>
            </value>
            <value>
                <fullName>Resp. Civil</fullName>
                <label>Civil liability</label>
            </value>
            <value>
                <fullName>Vida riesgo individual</fullName>
                <label>Individual risk life</label>
            </value>
            <value>
                <fullName>Vida riesgo colectivo</fullName>
                <label>Collective risk life</label>
            </value>
            <value>
                <fullName>Todos</fullName>
                <label>All</label>
            </value>
            <value>
                <fullName>Resto</fullName>
            </value>
            <value>
                <fullName>Communitdades</fullName>
                <label>Communities</label>
            </value>
            <value>
                <fullName>Resto Particulares</fullName>
                <isActive>false</isActive>
                <label>Rest Individuals</label>
            </value>
            <value>
                <fullName>Resto PYMEs</fullName>
                <isActive>false</isActive>
                <label>Rest of SMEs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>SDM: segmento del que se quiere obtener la información de los KPIs</description>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Individuals</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>SMEs</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Large companies</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Life risk</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>All products</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/SendNotifications__c.field-meta.xml
<CustomField>
    <fullName>SendNotifications__c</fullName>
    <description>SDM: se permite definir al usuario cúando quiere que se le mande notificación. Vacío para no mandar notificación</description>
    <label>Send notifications</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Indicator__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Above threshold</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Below threshold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/SentNotifications__c.field-meta.xml
<CustomField>
    <fullName>SentNotifications__c</fullName>
    <description>SDM: se almacena información de qué notificaciones se han mandado para este plan de acción,</description>
    <label>Sent notifications</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>KPI reached</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Week left</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Plan closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>SDM: fecha en la que comienza el plan de acción (solo aplicable a tipo acumulado YTD)</description>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zonas_Plan_Comercial</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/recordTypes/AnualPlan.recordType-meta.xml
<RecordType>
    <fullName>AnualPlan</fullName>
    <active>true</active>
    <description>sdm: plan comercial anual generado a partir del DT</description>
    <label>Anual Plan</label>
</RecordType>

force-app/zurich-base/main/default/globalValueSets/Zonas_Plan_Comercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>11 BARCELONA</fullName>
    </customValue>
    <customValue>
        <fullName>12 CATALUNYA ANDORRA</fullName>
    </customValue>
    <customValue>
        <fullName>13 BARCELONA GRANDES BROKERS</fullName>
    </customValue>
    <customValue>
        <fullName>21 LEVANTE NORTE</fullName>
    </customValue>
    <customValue>
        <fullName>22 BALEARES</fullName>
    </customValue>
    <customValue>
        <fullName>23 CENTRO ARAGÓN</fullName>
    </customValue>
    <customValue>
        <fullName>24 LEVANTE SUR</fullName>
    </customValue>
    <customValue>
        <fullName>31 MADRID</fullName>
    </customValue>
    <customValue>
        <fullName>41 SUR ORIENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>42 CANARIAS</fullName>
    </customValue>
    <customValue>
        <fullName>43 SUR OCCIDENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>51 NORTE ORIENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>52 NORTE OCCIDENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>61 CENTRALIZADOS</fullName>
    </customValue>
    <customValue>
        <fullName>Todos</fullName>
    </customValue>
    <customValue>
        <fullName>21 LEVANTE</fullName>
        <isActive>false</isActive>
        <label>21 LEVANTE</label>
    </customValue>
    <description>Valores de zona a usar como eje para planes comerciales</description>
    <masterLabel>Zonas Plan Comercial</masterLabel>
</GlobalValueSet>

force-app/zurich-sdm-app/main/default/classes/PlanesComercialesAnualesUtil.cls
/**
 * Clase utilidad que contiene los métodos necesarios para generar y actualizar planes mensuales
 * 
 * @author nts (dmunoz)
 * @date 23/02/2023
 *
 */
public with sharing class PlanesComercialesAnualesUtil {    
    
    /**
     * Metodo principal de generar planes anuales a partir de objetivos usado desde SDMInsertPlansAsyncBatch
     * @param mapObjetivos: objetivos modificados
     * @return void
     * @author dmunoz
     * @date 24/02/2023
     */
    public static List<PlanComercial__c> generateAnualPlansFromObjectives(Map<String, Map<String, Objective__c>> objectivesMap, List<String> validEmailList) {
        List<PlanComercial__c> result = new List<PlanComercial__c>();

        // recupero los ids de los usuarios piloto     
        List<User> validUserIdsList = getIdsValidUser(validEmailList);

        Map<String, Objective__c> retentionObjectives = objectivesMap.get('RetentionObjectives'); // retencion
        Map<String, Objective__c> accidentObjectives = objectivesMap.get('AccidentObjectives'); // siniestralidad        

        List<PlanComercial__c> retentionPlansList = generateAnualPlans(retentionObjectives, validUserIdsList); // generar planes anuales retencion
        List<PlanComercial__c> accidentPlansList = generateAnualPlans(accidentObjectives, validUserIdsList); // generar planes anuales siniestralidad

        // añado todos los elementos a la lista resultado para que se inserten a la vez
        result.addAll(retentionPlansList);
        result.addAll(accidentPlansList);

        return result;
    }


    /**
     * Metodo principal de generar planes anuales a partir de objetivo usado desde SDMUpdatePlansAsyncBatch
     * @param mapObjetivos: objetivos modificados
     * @return void
     * @author dmunoz
     * @date 24/02/2023
     */
    public static List<PlanComercial__c> generateAnualPlansFromUpdateObjectives(Map<String, Objective__c> objetivosToUpdateActiveAnual, List<String> validEmailList) {
        List<PlanComercial__c> result = new List<PlanComercial__c>();

        // recupero los ids de los usuarios piloto
        List<User> validUserIdsList = getIdsValidUser(validEmailList);  

        result = generateAnualPlans(objetivosToUpdateActiveAnual, validUserIdsList);

        return result;
    }


    /********************************************************* Metodos auxiliares generateAnualPlansFromObjectives **********************************************************************************/

    /**
     * Metodo para generar los planes anuales de retencion y/o de siniestralidad
     * @param objectivesMap: mapa de objetivos filtrados
     * @param validUserIdsList: lista de ids usuario
     * @author dmunoz
     * @date 23/02/2023
     */
    private static List<PlanComercial__c> generateAnualPlans(Map<String, Objective__c> objectivesMap, List<User> validUserIdsList) {
        List<PlanComercial__c> result = new List<PlanComercial__c>();        

        for (Objective__c obj: objectivesMap.values()) {
            for (User user: validUserIdsList) {
                if ('Ratio_Retention'.equals(obj.Indicator__c)) {
                    result.add(calculateRetentionPlan(obj, user));
                } else if ('Ratio_Claim'.equals(obj.Indicator__c)) {
                    result.add(calculateAccidentPlan(obj, user));
                }
            }
        }

        return result;
    }


    /**
     * Metodo para generar los planes anuales de retencion
     * @param obj: objetivo
     * @param user: usuario piloto
     * @author dmunoz
     * @date 23/02/2023
     */
    private static PlanComercial__c calculateRetentionPlan(Objective__c obj, User user) {

        PlanComercial__c plan = calculateAnualPlan(obj, user);
        plan.Name = 'Retención Anual Zurich ' + obj.Segment__c + ' ' + obj.Zone__c;

        return plan;
    }


    /**
     * Metodo para generar los planes anuales de retencion
     * @param obj: objetivo
     * @param user: usuario piloto
     * @author dmunoz
     * @date 23/02/2023
     */
    private static PlanComercial__c calculateAccidentPlan(Objective__c obj, User user) {

        PlanComercial__c plan = calculateAnualPlan(obj, user);
        plan.Name = 'Siniestralidad Anual Zurich ' + obj.Segment__c + ' ' + obj.Zone__c;

        return plan;
    }


    /**
     * Metodo para generar los datos comunes de los planes anuales de retencion y siniestralidad
     * @param obj: objetivo
     * @param user: usuario piloto
     * @author dmunoz
     * @date 23/02/2023
     */
    private static PlanComercial__c calculateAnualPlan(Objective__c obj, User user) {

        PlanComercial__c plan = new PlanComercial__c();        
        plan.OwnerId = UserInfo.getUserId(); // será un home office
        plan.AssignedTo__c = user.Id;
        plan.RecordTypeId = Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('AnualPlan').getRecordTypeId();
        plan.Indicator__c = obj.Indicator__c;
        plan.Segment__c = obj.Segment__c;
        plan.Product__c = obj.Product__c;
        plan.Zone__c = obj.Zone__c;
        plan.StartDate__c = Date.newinstance(Integer.valueOf(obj.Year__c), 1, 1);
        plan.EndDate__c = Date.newinstance(Integer.valueOf(obj.Year__c), 12, 31);
        plan.SendNotifications__c = '01';
        plan.SentNotifications__c = '01;02;03'; // seteo las notificaciones de estos planes para no lanzar ninguna notificación para este tipo de plan anual
        plan.AccumulateType__c = 'YTD';
        plan.Completed__c = false;
        plan.Description__c = plan.Name;

        return plan;

    }

    /******************************************************* Métodos auxiliares *****************************************************************************************/

    /**
     * Obtener los ids de los usuarios del piloto
     * @param validEmailList: lista de emails del piloto
     * @author dmunoz
     * @date 23/02/2023
     */
    private static List<User> getIdsValidUser(List<String> validEmailList) {
        List<User> result = (new UserSelector()).getIdsValidUser(validEmailList);

        if (Test.isRunningTest()) {
            result = (new UserSelector()).getSDMUserId();
        }
        return result;
    }
}