force-app/zurich-base/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objetivos</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Objective__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <label>Indicador</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>Portfolio</fullName>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Producto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autos</fullName>
            </value>
            <value>
                <fullName>Hogar</fullName>
            </value>
            <value>
                <fullName>Inmuebles</fullName>
            </value>
            <value>
                <fullName>Accidentes</fullName>
            </value>
            <value>
                <fullName>Comercios</fullName>
            </value>
            <value>
                <fullName>Patrimoniales</fullName>
            </value>
            <value>
                <fullName>Resp. Civil</fullName>
            </value>
            <value>
                <fullName>Vida riesgo individual</fullName>
            </value>
            <value>
                <fullName>Vida riesgo colectivo</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
            <value>
                <fullName>Resto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segmento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulares</fullName>
            </value>
            <value>
                <fullName>PYMEs</fullName>
            </value>
            <value>
                <fullName>Grandes empresas</fullName>
            </value>
            <value>
                <fullName>Vida riesgo</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Año</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zona</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zonas_Plan_Comercial</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/PlanComercial__c.object-meta.xml
<CustomObject>
    <description>SDM: Utilizado para representar el plan de negocio realizado por los directores.</description>
    <label>Plan Comercial</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <description>SDM: indicador (campo) del KPI con el que se quiere comparar el objetivo</description>
    <label>Indicator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>PoliciesPN</fullName>
                <label>Pólizas PN</label>
            </value>
            <value>
                <fullName>PoliciesInForce</fullName>
                <label>Pólizas en vigor</label>
            </value>
            <value>
                <fullName>Portfolio</fullName>
                <label>Cartera</label>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
            <value>
                <fullName>Ratio_Claim</fullName>
                <label>% Sin Total</label>
            </value>
            <value>
                <fullName>Ratio_PNIncrease</fullName>
                <label>% Crec PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesPNIncreas</fullName>
                <label>% Crec Pólizas PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesInForceIncrease</fullName>
                <label>% Crec Pólizas vigor vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PortIncrease</fullName>
                <label>% crecimiento cartera</label>
            </value>
            <value>
                <fullName>Totaldiscount</fullName>
                <label>% Dto. Total</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>SDM: productos del que se quiere obtener la información de los KPIs</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autos</fullName>
                <label>Cars</label>
            </value>
            <value>
                <fullName>Hogar</fullName>
                <label>Home</label>
            </value>
            <value>
                <fullName>Inmuebles</fullName>
                <label>Estate</label>
            </value>
            <value>
                <fullName>Accidentes</fullName>
                <label>Accidents</label>
            </value>
            <value>
                <fullName>Comercios</fullName>
                <label>Commerce</label>
            </value>
            <value>
                <fullName>Patrimoniales</fullName>
                <label>Patrimonial</label>
            </value>
            <value>
                <fullName>Resp. Civil</fullName>
                <label>Civil liability</label>
            </value>
            <value>
                <fullName>Vida riesgo individual</fullName>
                <label>Individual risk life</label>
            </value>
            <value>
                <fullName>Vida riesgo colectivo</fullName>
                <label>Collective risk life</label>
            </value>
            <value>
                <fullName>Todos</fullName>
                <label>All</label>
            </value>
            <value>
                <fullName>Resto</fullName>
            </value>
            <value>
                <fullName>Communitdades</fullName>
                <label>Communities</label>
            </value>
            <value>
                <fullName>Resto Particulares</fullName>
                <isActive>false</isActive>
                <label>Rest Individuals</label>
            </value>
            <value>
                <fullName>Resto PYMEs</fullName>
                <isActive>false</isActive>
                <label>Rest of SMEs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>SDM: segmento del que se quiere obtener la información de los KPIs</description>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Individuals</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>SMEs</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Large companies</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Life risk</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>All products</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zonas_Plan_Comercial</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/Zonas_Plan_Comercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>11 BARCELONA</fullName>
    </customValue>
    <customValue>
        <fullName>12 CATALUNYA ANDORRA</fullName>
    </customValue>
    <customValue>
        <fullName>13 BARCELONA GRANDES BROKERS</fullName>
    </customValue>
    <customValue>
        <fullName>21 LEVANTE NORTE</fullName>
    </customValue>
    <customValue>
        <fullName>22 BALEARES</fullName>
    </customValue>
    <customValue>
        <fullName>23 CENTRO ARAGÓN</fullName>
    </customValue>
    <customValue>
        <fullName>24 LEVANTE SUR</fullName>
    </customValue>
    <customValue>
        <fullName>31 MADRID</fullName>
    </customValue>
    <customValue>
        <fullName>41 SUR ORIENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>42 CANARIAS</fullName>
    </customValue>
    <customValue>
        <fullName>43 SUR OCCIDENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>51 NORTE ORIENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>52 NORTE OCCIDENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>61 CENTRALIZADOS</fullName>
    </customValue>
    <customValue>
        <fullName>Todos</fullName>
    </customValue>
    <customValue>
        <fullName>21 LEVANTE</fullName>
        <isActive>false</isActive>
        <label>21 LEVANTE</label>
    </customValue>
    <description>Valores de zona a usar como eje para planes comerciales</description>
    <masterLabel>Zonas Plan Comercial</masterLabel>
</GlobalValueSet>

force-app/zurich-sdm-app/main/default/classes/PlanesComercialesAnualesUtilTest.cls
@isTest
public with sharing class PlanesComercialesAnualesUtilTest {


    /**
     * generar registros retencion anuales desde mapa de mapas de objetivo
     *
     * @author nts (dmunoz)
     * @date 28/02/2023
     */
    @isTest
    static void testGenerateAnualPlansFromObjectivesMap_OK() {
        Map<String, Map<String, Objective__c>> objectivesMap = new Map<String, Map<String, Objective__c>>();
        Map<String, Objective__c> objectivesRetentionMap = new Map<String, Objective__c>();
        Map<String, Objective__c> objectivesAccidentMap = new Map<String, Objective__c>();

        Objective__c obj = TestDataFactory.generateObjective(2022, 'Ratio_Retention', 'Particulares', 'Autos', '11 BARCELONA', 80.0, 20.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
        Objective__c obj2 = TestDataFactory.generateObjective(2022, 'Ratio_Claim', 'Particulares', 'Autos', '11 BARCELONA', 80.0, 20.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
        
        objectivesRetentionMap.put(getExternalId(obj), obj);
        objectivesAccidentMap.put(getExternalId(obj2), obj2);

        objectivesMap.put('RetentionObjectives', objectivesRetentionMap);
        objectivesMap.put('AccidentObjectives', objectivesAccidentMap);

        List<PlanComercial__c> resultAnualPlan = PlanesComercialesAnualesUtil.generateAnualPlansFromObjectives(objectivesMap, new List<String>());

        System.assertEquals(true, resultAnualPlan.size() != 0, 'Debe haber registros generados');
    }

    /**
     * generar registros retencion anuales desde mapa de objetivo
     *
     * @author nts (dmunoz)
     * @date 28/02/2023
     */
    @isTest
    static void testGenerateAnualPlansFromObjectives_OK() {
        Map<String, Objective__c> objectivesRetentionMap = new Map<String, Objective__c>();

        Objective__c obj = TestDataFactory.generateObjective(2022, 'Ratio_Retention', 'Particulares', 'Autos', '11 BARCELONA', 80.0, 20.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
        
        objectivesRetentionMap.put(getExternalId(obj), obj);

        List<PlanComercial__c> resultAnualPlan = PlanesComercialesAnualesUtil.generateAnualPlansFromUpdateObjectives(objectivesRetentionMap, new List<String>());

        System.assertEquals(true, resultAnualPlan.size() != 0, 'Debe haber registros generados');
    }


    private static String getExternalId(Objective__c obj) {
        String result = obj.Year__c + '-' + obj.Indicator__c + '-' + obj.Segment__c + '-' + obj.Product__c + '-' + obj.Zone__c;
        return result;
    }

}