force-app/zurich-base/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objetivos</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Objective__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <label>Indicador</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>Portfolio</fullName>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/PlanComercial__c.object-meta.xml
<CustomObject>
    <description>SDM: Utilizado para representar el plan de negocio realizado por los directores.</description>
    <label>Plan Comercial</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <description>SDM: indicador (campo) del KPI con el que se quiere comparar el objetivo</description>
    <label>Indicator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>PoliciesPN</fullName>
                <label>Pólizas PN</label>
            </value>
            <value>
                <fullName>PoliciesInForce</fullName>
                <label>Pólizas en vigor</label>
            </value>
            <value>
                <fullName>Portfolio</fullName>
                <label>Cartera</label>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
            <value>
                <fullName>Ratio_Claim</fullName>
                <label>% Sin Total</label>
            </value>
            <value>
                <fullName>Ratio_PNIncrease</fullName>
                <label>% Crec PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesPNIncreas</fullName>
                <label>% Crec Pólizas PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesInForceIncrease</fullName>
                <label>% Crec Pólizas vigor vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PortIncrease</fullName>
                <label>% crecimiento cartera</label>
            </value>
            <value>
                <fullName>Totaldiscount</fullName>
                <label>% Dto. Total</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Intermediary__c.field-meta.xml
<CustomField>
    <fullName>Intermediary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>SDM: mediador sobre el que se quiere realizar la búsqueda de KPIs para el cálculo de las cifras realas para su comparación con el objetivo</description>
    <label>Intermediary</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La cuenta debe ser un agente</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador, Intermediary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planes Comerciales</relationshipLabel>
    <relationshipName>PlanComercial</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/ParentPlan__c.field-meta.xml
<CustomField>
    <fullName>ParentPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDM: hace referencia a un plan anual padre</description>
    <label>Parent Plan</label>
    <referenceTo>PlanComercial__c</referenceTo>
    <relationshipLabel>Planes Comerciales</relationshipLabel>
    <relationshipName>ParentPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/recordTypes/AnualPlan.recordType-meta.xml
<RecordType>
    <fullName>AnualPlan</fullName>
    <active>true</active>
    <description>sdm: plan comercial anual generado a partir del DT</description>
    <label>Anual Plan</label>
</RecordType>

force-app/zurich-base/main/default/objects/PlanComercial__c/recordTypes/MensualPlan.recordType-meta.xml
<RecordType>
    <fullName>MensualPlan</fullName>
    <active>true</active>
    <description>SDM: plan comercial autogenerado a partir de un plan anual</description>
    <label>Mensual Plan</label>
</RecordType>

force-app/zurich-sdm-app/main/default/classes/SDMDeletePlansAsyncBatchTest.cls
@isTest
public with sharing class SDMDeletePlansAsyncBatchTest {

    public static final Integer ACTUAL_YEAR = Date.today().year() + 1;
    
    @TestSetup
    static void makeData(){
        List<Objective__c> objList = new List<Objective__c>();
        Objective__c obj = TestDataFactory.generateObjective(ACTUAL_YEAR, 'PN', 'Particulares', 'Autos', '11 BARCELONA', 80.0, 20.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
        Objective__c objRetention = TestDataFactory.generateObjective(ACTUAL_YEAR, 'Ratio_Retention', 'Particulares', 'Autos', '11 BARCELONA', 80.0, 20.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0);

        objList.add(obj);
        objList.add(objRetention);
        insert objList;

        TestDataFactorySDM.anualPlanSetupData(ACTUAL_YEAR, AccountsSelector.SDM_DT_EMAIL_FIELD);
    }


    /**
     * eliminar planes mensuales pn
     *
     * @author nts (dmunoz)
     * @date 28/02/2023
     */
    @isTest
    static void testDeletePlanPN_OK() {
        List<PlanComercial__c> planesIniciales = new List<PlanComercial__c>([SELECT Id
                                                                            FROM PlanComercial__c 
                                                                            WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('AnualPlan').getRecordTypeId()
                                                                            AND ParentPlan__c != NULL 
                                                                            AND Indicator__c = 'PN'
                                                                            AND Intermediary__c = NULL]);

        List<PlanComercial__c> planesToDelete = new List<PlanComercial__c>([SELECT Id
                                                        FROM PlanComercial__c 
                                                        WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('AnualPlan').getRecordTypeId()
                                                        AND ParentPlan__c != NULL 
                                                        AND Indicator__c = 'PN'
                                                        AND Intermediary__c = NULL
                                                        LIMIT 1]);

        if (!planesToDelete.isEmpty()) {

            Test.startTest();
            delete planesToDelete;
            Test.stopTest();

            List<PlanComercial__c> planesAfterDelete = new List<PlanComercial__c>([SELECT Id
                                                                            FROM PlanComercial__c 
                                                                            WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('AnualPlan').getRecordTypeId()
                                                                            AND ParentPlan__c != NULL 
                                                                            AND Indicator__c = 'PN'
                                                                            AND Intermediary__c = NULL]);

            System.assertEquals(true, planesIniciales.size() != planesAfterDelete.size());
        }
    }


    /**
     * eliminar objetivo retencion
     *
     * @author nts (dmunoz)
     * @date 28/02/2023
     */
    @isTest
    static void testDeleteObjetivoRetencion_OK() {
        List<Objective__c> objToDelete = new List<Objective__c>([SELECT Id FROM Objective__c WHERE Indicator__c = 'Ratio_Retention' LIMIT 1]);
        List<PlanComercial__c> planesIniciales = new List<PlanComercial__c>([SELECT Id
                                                                            FROM PlanComercial__c 
                                                                            WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('AnualPlan').getRecordTypeId()
                                                                            AND ParentPlan__c != NULL 
                                                                            AND Indicator__c = 'Ratio_Retention'
                                                                            AND Intermediary__c = NULL]);
        

        if (!objToDelete.isEmpty()) {

            Test.startTest();
            delete objToDelete;
            Test.stopTest();

            List<PlanComercial__c> planesAfterDelete = new List<PlanComercial__c>([SELECT Id
                                                                            FROM PlanComercial__c 
                                                                            WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('AnualPlan').getRecordTypeId()
                                                                            AND ParentPlan__c != NULL 
                                                                            AND Intermediary__c = NULL]);

            System.assertEquals(true, planesIniciales.size() != planesAfterDelete.size());
        }
    }


    /**
     * eliminar recursivo planes anuales
     *
     * @author nts (dmunoz)
     * @date 28/02/2023
     */
    @isTest
    static void testDMLRecursivoAnual_OK() {
        Map<String, List<PlanComercial__c>> deleteRecursivoMap = new Map<String, List<PlanComercial__c>>();
        List<PlanComercial__c> planesAnualesIniciales = new List<PlanComercial__c>([SELECT Id
                                                                            FROM PlanComercial__c 
                                                                            WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('AnualPlan').getRecordTypeId()                                                                            
                                                                            AND Indicator__c = 'Ratio_Retention'
                                                                            ]);        

        if (!planesAnualesIniciales.isEmpty()) {

            deleteRecursivoMap.put('Anual', planesAnualesIniciales);

            Test.startTest();
            Database.executeBatch(new SDMDeletePlansAsyncBatch(deleteRecursivoMap), 200);
            Test.stopTest();

            List<PlanComercial__c> planesAfterDelete = new List<PlanComercial__c>([SELECT Id
                                                                            FROM PlanComercial__c 
                                                                            WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('AnualPlan').getRecordTypeId()
                                                                            AND Indicator__c = 'Ratio_Retention']);

            System.assertEquals(true, planesAnualesIniciales.size() != planesAfterDelete.size());
        }
    }


    /**
     * eliminar recursivo planes mensuales
     *
     * @author nts (dmunoz)
     * @date 28/02/2023
     */
    @isTest
    static void testDMLRecursivoMensual_OK() {
        Map<String, List<PlanComercial__c>> deleteRecursivoMap = new Map<String, List<PlanComercial__c>>();
        List<PlanComercial__c> planesAnualesIniciales = new List<PlanComercial__c>([SELECT Id
                                                                            FROM PlanComercial__c 
                                                                            WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('MensualPlan').getRecordTypeId()                                                                            
                                                                            AND Indicator__c = 'Ratio_Retention'
                                                                            ]);        

        if (!planesAnualesIniciales.isEmpty()) {

            deleteRecursivoMap.put('Mensual', planesAnualesIniciales);

            Test.startTest();
            Database.executeBatch(new SDMDeletePlansAsyncBatch(deleteRecursivoMap), 200);
            Test.stopTest();

            List<PlanComercial__c> planesAfterDelete = new List<PlanComercial__c>([SELECT Id
                                                                            FROM PlanComercial__c 
                                                                            WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('MensualPlan').getRecordTypeId()
                                                                            AND Indicator__c = 'Ratio_Retention']);

            System.assertEquals(true, planesAnualesIniciales.size() != planesAfterDelete.size());
        }
    }


    /**
     * continue recursive test
     *
     * @author nts (dmunoz)
     * @date 28/02/2023
     */
    @isTest
    static void testContinueRecursive_OK() {
        Map<String, List<PlanComercial__c>> deleteRecursivoMap = new Map<String, List<PlanComercial__c>>();
        List<PlanComercial__c> planesAnualesIniciales = new List<PlanComercial__c>([SELECT Id
                                                                            FROM PlanComercial__c 
                                                                            WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('MensualPlan').getRecordTypeId()                                                                            
                                                                            AND Indicator__c = 'Ratio_Retention'
                                                                            ]);        

        if (!planesAnualesIniciales.isEmpty()) {

            deleteRecursivoMap.put('Mensual', planesAnualesIniciales);

            Test.startTest();
            SDMDeletePlansAsyncBatch batch = new SDMDeletePlansAsyncBatch(deleteRecursivoMap);
            Boolean result = batch.continueRecursive();
            Test.stopTest();
            
            System.assertEquals(true, result);
        }
    }

}