force-app/zurich-base/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objetivos</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Objective__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <label>Indicador</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>Portfolio</fullName>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Producto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autos</fullName>
            </value>
            <value>
                <fullName>Hogar</fullName>
            </value>
            <value>
                <fullName>Inmuebles</fullName>
            </value>
            <value>
                <fullName>Accidentes</fullName>
            </value>
            <value>
                <fullName>Comercios</fullName>
            </value>
            <value>
                <fullName>Patrimoniales</fullName>
            </value>
            <value>
                <fullName>Resp. Civil</fullName>
            </value>
            <value>
                <fullName>Vida riesgo individual</fullName>
            </value>
            <value>
                <fullName>Vida riesgo colectivo</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
            <value>
                <fullName>Resto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segmento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulares</fullName>
            </value>
            <value>
                <fullName>PYMEs</fullName>
            </value>
            <value>
                <fullName>Grandes empresas</fullName>
            </value>
            <value>
                <fullName>Vida riesgo</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Año</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zona</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zonas_Plan_Comercial</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/PlanComercial__c.object-meta.xml
<CustomObject>
    <description>SDM: Utilizado para representar el plan de negocio realizado por los directores.</description>
    <label>Plan Comercial</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/AccumulateType__c.field-meta.xml
<CustomField>
    <fullName>AccumulateType__c</fullName>
    <description>SDM: tipo de acumulado con el que se quiere comparar dentro del objeto KPI</description>
    <label>Accumulate type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
                <label>Current month</label>
            </value>
            <value>
                <fullName>YTD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Actual_KPI__c.field-meta.xml
<CustomField>
    <fullName>Actual_KPI__c</fullName>
    <description>SDM: el resultado de KPI calculado de forma automática para el plan de acción a través de todos los criterios establecidos en el mismo</description>
    <label>Actual KPI</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>SDM: fecha en la que finaliza el plan de acción (solo aplicable a tipo acumulado YTD)</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <description>SDM: indicador (campo) del KPI con el que se quiere comparar el objetivo</description>
    <label>Indicator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>PoliciesPN</fullName>
                <label>Pólizas PN</label>
            </value>
            <value>
                <fullName>PoliciesInForce</fullName>
                <label>Pólizas en vigor</label>
            </value>
            <value>
                <fullName>Portfolio</fullName>
                <label>Cartera</label>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
            <value>
                <fullName>Ratio_Claim</fullName>
                <label>% Sin Total</label>
            </value>
            <value>
                <fullName>Ratio_PNIncrease</fullName>
                <label>% Crec PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesPNIncreas</fullName>
                <label>% Crec Pólizas PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesInForceIncrease</fullName>
                <label>% Crec Pólizas vigor vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PortIncrease</fullName>
                <label>% crecimiento cartera</label>
            </value>
            <value>
                <fullName>Totaldiscount</fullName>
                <label>% Dto. Total</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/ParentPlan__c.field-meta.xml
<CustomField>
    <fullName>ParentPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDM: hace referencia a un plan anual padre</description>
    <label>Parent Plan</label>
    <referenceTo>PlanComercial__c</referenceTo>
    <relationshipLabel>Planes Comerciales</relationshipLabel>
    <relationshipName>ParentPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>SDM: productos del que se quiere obtener la información de los KPIs</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autos</fullName>
                <label>Cars</label>
            </value>
            <value>
                <fullName>Hogar</fullName>
                <label>Home</label>
            </value>
            <value>
                <fullName>Inmuebles</fullName>
                <label>Estate</label>
            </value>
            <value>
                <fullName>Accidentes</fullName>
                <label>Accidents</label>
            </value>
            <value>
                <fullName>Comercios</fullName>
                <label>Commerce</label>
            </value>
            <value>
                <fullName>Patrimoniales</fullName>
                <label>Patrimonial</label>
            </value>
            <value>
                <fullName>Resp. Civil</fullName>
                <label>Civil liability</label>
            </value>
            <value>
                <fullName>Vida riesgo individual</fullName>
                <label>Individual risk life</label>
            </value>
            <value>
                <fullName>Vida riesgo colectivo</fullName>
                <label>Collective risk life</label>
            </value>
            <value>
                <fullName>Todos</fullName>
                <label>All</label>
            </value>
            <value>
                <fullName>Resto</fullName>
            </value>
            <value>
                <fullName>Communitdades</fullName>
                <label>Communities</label>
            </value>
            <value>
                <fullName>Resto Particulares</fullName>
                <isActive>false</isActive>
                <label>Rest Individuals</label>
            </value>
            <value>
                <fullName>Resto PYMEs</fullName>
                <isActive>false</isActive>
                <label>Rest of SMEs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>SDM: segmento del que se quiere obtener la información de los KPIs</description>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Individuals</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>SMEs</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Large companies</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Life risk</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>All products</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/SendNotifications__c.field-meta.xml
<CustomField>
    <fullName>SendNotifications__c</fullName>
    <description>SDM: se permite definir al usuario cúando quiere que se le mande notificación. Vacío para no mandar notificación</description>
    <label>Send notifications</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Indicator__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Above threshold</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Below threshold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>SDM: fecha en la que comienza el plan de acción (solo aplicable a tipo acumulado YTD)</description>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/TargetKPICurrency__c.field-meta.xml
<CustomField>
    <fullName>TargetKPICurrency__c</fullName>
    <description>SDM: el objetivo  económico que se define en el plan para poder comparar con datos reales a futuro</description>
    <label>Target KPI €</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/TargetKPINumber__c.field-meta.xml
<CustomField>
    <fullName>TargetKPINumber__c</fullName>
    <description>SDM: el objetivo de cuantía que se define en el plan para poder comparar con datos reales a futuro</description>
    <label>Target KPI Nº</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/TargetKPIPercent__c.field-meta.xml
<CustomField>
    <fullName>TargetKPIPercent__c</fullName>
    <description>SDM: el objetivo de porcentaje que se define en el plan para poder comparar con datos reales a futuro</description>
    <label>Target KPI %</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zonas_Plan_Comercial</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/recordTypes/AnualPlan.recordType-meta.xml
<RecordType>
    <fullName>AnualPlan</fullName>
    <active>true</active>
    <description>sdm: plan comercial anual generado a partir del DT</description>
    <label>Anual Plan</label>
</RecordType>

force-app/zurich-base/main/default/objects/PlanComercial__c/recordTypes/MensualPlan.recordType-meta.xml
<RecordType>
    <fullName>MensualPlan</fullName>
    <active>true</active>
    <description>SDM: plan comercial autogenerado a partir de un plan anual</description>
    <label>Mensual Plan</label>
</RecordType>

force-app/zurich-base/main/default/globalValueSets/Zonas_Plan_Comercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>11 BARCELONA</fullName>
    </customValue>
    <customValue>
        <fullName>12 CATALUNYA ANDORRA</fullName>
    </customValue>
    <customValue>
        <fullName>13 BARCELONA GRANDES BROKERS</fullName>
    </customValue>
    <customValue>
        <fullName>21 LEVANTE NORTE</fullName>
    </customValue>
    <customValue>
        <fullName>22 BALEARES</fullName>
    </customValue>
    <customValue>
        <fullName>23 CENTRO ARAGÓN</fullName>
    </customValue>
    <customValue>
        <fullName>24 LEVANTE SUR</fullName>
    </customValue>
    <customValue>
        <fullName>31 MADRID</fullName>
    </customValue>
    <customValue>
        <fullName>41 SUR ORIENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>42 CANARIAS</fullName>
    </customValue>
    <customValue>
        <fullName>43 SUR OCCIDENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>51 NORTE ORIENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>52 NORTE OCCIDENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>61 CENTRALIZADOS</fullName>
    </customValue>
    <customValue>
        <fullName>Todos</fullName>
    </customValue>
    <customValue>
        <fullName>21 LEVANTE</fullName>
        <isActive>false</isActive>
        <label>21 LEVANTE</label>
    </customValue>
    <description>Valores de zona a usar como eje para planes comerciales</description>
    <masterLabel>Zonas Plan Comercial</masterLabel>
</GlobalValueSet>

force-app/zurich-sdm-app/main/default/classes/PlanesComercialesMensualesUtilTest.cls
@isTest
public with sharing class PlanesComercialesMensualesUtilTest {

    public static final Integer ACTUAL_YEAR = Date.today().year() + 1;

    // aqui se ejecuta la mayor parte de la clase a la que hacemos test, los metodos a continuación terminan de probarla
    @TestSetup
    static void makeData(){
        List<Objective__c> objList = new List<Objective__c>();
        Objective__c obj = TestDataFactory.generateObjective(ACTUAL_YEAR, 'PN', 'Particulares', 'Autos', '11 BARCELONA', 80.0, 20.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
        Objective__c objRetention = TestDataFactory.generateObjective(ACTUAL_YEAR, 'Ratio_Retention', 'Particulares', 'Autos', '11 BARCELONA', 80.0, 20.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0);

        objList.add(obj);
        objList.add(objRetention);
        insert objList;

        TestDataFactorySDM.anualPlanSetupData(ACTUAL_YEAR, AccountsSelector.SDM_DT_EMAIL_FIELD);
    }

    

    /**
     * Buscar planes mensuales de retencion
     *
     * @author nts (dmunoz)
     * @date 28/02/2023
     */
    @isTest
    static void testGetPlanesComercialesAnualesMensualesByObjetivosMensual_OK() {

        Map<String, Objective__c> objetivosInput = new Map<String, Objective__c>();

        List<Objective__c> objList = new List<Objective__c>([SELECT Id, Year__c, Indicator__c, Segment__c, Product__c, Zone__c, ExternalId__c FROM Objective__c WHERE Indicator__c = 'Ratio_Retention']);
        
        if (!objList.isEmpty()) {
            Objective__c obj = objList.get(0);

            objetivosInput.put(obj.ExternalId__c, obj);
            List<PlanComercial__c> retentionPlans = PlanesComercialesMensualesUtil.getPlanesComercialesAnualesMensualesByObjetivos(objetivosInput, 'Mensual');

            System.assertEquals(true, retentionPlans.size() != 0);

        }
    }


    /**
     * actualizar kpi de plan comercial para lanzar los metodos de plan mensual util
     *
     * @author nts (dmunoz)
     * @date 28/02/2023
     */
    @isTest
    static void updateKPIPlanComercialPNTest_OK() {
        List<PlanComercial__c> planesToUpdate = new List<PlanComercial__c>([SELECT ID, Name, SendNotifications__c, AccumulateType__c, Startdate__c, EndDate__c, 
                                                                Indicator__c, Segment__c, Product__c, TargetKPIPercent__c, TargetKPINumber__c, TargetKPICurrency__c, OwnerId, Actual_KPI__c, Zone__c, 
                                                                ParentPlan__r.OwnerId, Intermediary__c
                                                        FROM PlanComercial__c 
                                                        WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('AnualPlan').getRecordTypeId()
                                                        AND ParentPlan__c != NULL 
                                                        AND Indicator__c = 'PN'
                                                        AND Intermediary__c = NULL
                                                        LIMIT 1]);

        if (!planesToUpdate.isEmpty()) {
            PlanComercial__c plan = planesToUpdate.get(0);

            Date endDate = Date.newInstance(ACTUAL_YEAR, 1, 31);

            // obtener el kpi del plan mensual antes de actualizar
            List<PlanComercial__c> planMensualListBefore = new List<PlanComercial__c>([SELECT Id, TargetKPINumber__c FROM PlanComercial__c
                                                                                WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('MensualPlan').getRecordTypeId()
                                                                                AND ParentPlan__c = :plan.Id
                                                                                AND Indicator__c = 'PN'
                                                                                AND EndDate__c =: endDate
                                                                                LIMIT 1]);


            // update target kpi
            plan.TargetKPINumber__c = 200;
            
            Test.startTest();
            update plan;
            Test.stopTest();

            // vuelvo a consultar el mismo plan  mensual que arriba para comparar
            if (!planMensualListBefore.isEmpty()) {
                PlanComercial__c planBeforeUpdate = planMensualListBefore.get(0);
                
                PlanComercial__c planAfterUpdate = [SELECT Id, TargetKPINumber__c FROM PlanComercial__c WHERE Id =:planBeforeUpdate.Id];

                System.assertEquals(true, planBeforeUpdate.TargetKPINumber__c != planAfterUpdate.TargetKPINumber__c);
            }
        }   
    }


    /**
     * actualizar pesos objetivo pn
     *
     * @author nts (dmunoz)
     * @date 28/02/2023
     */
    @isTest
    static void updatePesosObjetivoPNTest_OK() {

        // obtener objetivo 
        List<Objective__c> objList = new List<Objective__c>([SELECT Id, January__c FROM Objective__c WHERE Indicator__c = 'PN' LIMIT 1]);

        if (!objList.isEmpty()) {
            Date endDate = Date.newInstance(ACTUAL_YEAR, 1, 31);

            List<PlanComercial__c> planMensualListBefore = new List<PlanComercial__c>([SELECT Id, TargetKPINumber__c FROM PlanComercial__c
                                                                                WHERE RecordTypeId = :Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get('MensualPlan').getRecordTypeId()                                                                                
                                                                                AND Indicator__c = 'PN'
                                                                                AND EndDate__c =: endDate
                                                                                LIMIT 1]);

            Objective__c obj = objList.get(0);
            obj.January__c = 70.0;
            obj.February__c = 0.0;
            obj.December__c = 30.0;

            Test.startTest();
            update obj;
            Test.stopTest();

            if (!planMensualListBefore.isEmpty()) {
                PlanComercial__c planBeforeUpdate = planMensualListBefore.get(0);
                PlanComercial__c planAfterUpdate = [SELECT Id, TargetKPINumber__c FROM PlanComercial__c WHERE Id =:planBeforeUpdate.Id];
    
                System.assertEquals(true, planBeforeUpdate.TargetKPINumber__c != planAfterUpdate.TargetKPINumber__c);
            }

        }
    }
}