force-app/zurich-base/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objetivos</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Objective__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/April__c.field-meta.xml
<CustomField>
    <fullName>April__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Abril</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/August__c.field-meta.xml
<CustomField>
    <fullName>August__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agosto</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/DaysLeft__c.field-meta.xml
<CustomField>
    <fullName>DaysLeft__c</fullName>
    <description>Remaining days to notify that the monthly plan ends.</description>
    <label>Days left</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/December__c.field-meta.xml
<CustomField>
    <fullName>December__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Diciembre</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/February__c.field-meta.xml
<CustomField>
    <fullName>February__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Febrero</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <label>Indicador</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>Portfolio</fullName>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/January__c.field-meta.xml
<CustomField>
    <fullName>January__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Enero</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/July__c.field-meta.xml
<CustomField>
    <fullName>July__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Julio</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/June__c.field-meta.xml
<CustomField>
    <fullName>June__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Junio</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/March__c.field-meta.xml
<CustomField>
    <fullName>March__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Marzo</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Mayo</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/November__c.field-meta.xml
<CustomField>
    <fullName>November__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Noviembre</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/October__c.field-meta.xml
<CustomField>
    <fullName>October__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Octubre</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Producto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autos</fullName>
            </value>
            <value>
                <fullName>Hogar</fullName>
            </value>
            <value>
                <fullName>Inmuebles</fullName>
            </value>
            <value>
                <fullName>Accidentes</fullName>
            </value>
            <value>
                <fullName>Comercios</fullName>
            </value>
            <value>
                <fullName>Patrimoniales</fullName>
            </value>
            <value>
                <fullName>Resp. Civil</fullName>
            </value>
            <value>
                <fullName>Vida riesgo individual</fullName>
            </value>
            <value>
                <fullName>Vida riesgo colectivo</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
            <value>
                <fullName>Resto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segmento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulares</fullName>
            </value>
            <value>
                <fullName>PYMEs</fullName>
            </value>
            <value>
                <fullName>Grandes empresas</fullName>
            </value>
            <value>
                <fullName>Vida riesgo</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/September__c.field-meta.xml
<CustomField>
    <fullName>September__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Septiembre</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Año</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zona</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zonas_Plan_Comercial</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Objective__c/recordTypes/FrequencyNotifications.recordType-meta.xml
<RecordType>
    <fullName>FrequencyNotifications</fullName>
    <active>true</active>
    <description>Record type in which the information regarding the remaining days to notify the end of the monthly plan is stored.</description>
    <label>Frequency of notifications</label>
</RecordType>

force-app/zurich-base/main/default/objects/Objective__c/recordTypes/Objectives.recordType-meta.xml
<RecordType>
    <fullName>Objectives</fullName>
    <active>true</active>
    <description>Record type for monthly plan objectives.</description>
    <label>Objectives</label>
</RecordType>

force-app/zurich-base/main/default/globalValueSets/Zonas_Plan_Comercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>11 BARCELONA</fullName>
    </customValue>
    <customValue>
        <fullName>12 CATALUNYA ANDORRA</fullName>
    </customValue>
    <customValue>
        <fullName>13 BARCELONA GRANDES BROKERS</fullName>
    </customValue>
    <customValue>
        <fullName>21 LEVANTE NORTE</fullName>
    </customValue>
    <customValue>
        <fullName>22 BALEARES</fullName>
    </customValue>
    <customValue>
        <fullName>23 CENTRO ARAGÓN</fullName>
    </customValue>
    <customValue>
        <fullName>24 LEVANTE SUR</fullName>
    </customValue>
    <customValue>
        <fullName>31 MADRID</fullName>
    </customValue>
    <customValue>
        <fullName>41 SUR ORIENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>42 CANARIAS</fullName>
    </customValue>
    <customValue>
        <fullName>43 SUR OCCIDENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>51 NORTE ORIENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>52 NORTE OCCIDENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>61 CENTRALIZADOS</fullName>
    </customValue>
    <customValue>
        <fullName>Todos</fullName>
    </customValue>
    <customValue>
        <fullName>21 LEVANTE</fullName>
        <isActive>false</isActive>
        <label>21 LEVANTE</label>
    </customValue>
    <description>Valores de zona a usar como eje para planes comerciales</description>
    <masterLabel>Zonas Plan Comercial</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/ObjectivesSelector.cls
/**
 * Clase Apex que encapsula las consultas a BBDD a realizar sobre el objeto Objective__c
 */
public with sharing class ObjectivesSelector {

    //#region Record Types

    public static final String RT_NAME_OBJECTIVES = 'Objectives';
    public static final String RT_NAME_FREQUENCY_NOTIFICATIONS = 'FrequencyNotifications';

    public static Id rtObjectives
    {
        get
        {
            return Schema.SObjectType.Objective__c.getRecordTypeInfosByDeveloperName().get(RT_NAME_OBJECTIVES)?.getRecordTypeId();
        }
    }

    public static Id rtFrequencyNotifications
    {
        get
        {
            return Schema.SObjectType.Objective__c.getRecordTypeInfosByDeveloperName().get(RT_NAME_FREQUENCY_NOTIFICATIONS)?.getRecordTypeId();
        }
    }

    //#endregion

    private static String getFieldListString() {
        return ' Id, Year__c, Indicator__c, Segment__c, Product__c, Zone__c, January__c, February__c, March__c, April__c, May__c, June__c, July__c, August__c, September__c, October__c, November__c, December__c, Active__c, ExternalId__c ';
    }
    
    private static String getSObjectName() {
        return ' Objective__c ';
    }

    private static String getOrderBy(){
        return ' Indicator__c, Segment__c, Product__c, Zone__c ASC ';
    }

    public ObjectivesSelector() {}

    /**
     * Obtiene un listado de Objetivos dado un año ordenados de forma ascendente por Indicador y Segmento
     * @param year: String con el año a consultar
     * @return Listado de objetivos
     * @author dmunoz
     * @date 06/07/2022
     * @change amiranda 04/01/2023 Se añade el filtra de tipo de registro 'Objecitves' en la query
     */
    public static List<Objective__c> selectObjectivesByYear(String year) {
        //Devolver lista vacía
        if (year == null || String.isEmpty(year)) {
            return new List<Objective__c>();
        }

        String query = String.format(
            'SELECT {0} FROM {1} WHERE Year__c =: year AND RecordTypeId = :rtObjectives ORDER BY {2}',
            new List<String> {getFieldListString(), getSObjectName(), getOrderBy()}
            );
        System.debug('query ' + query + 'year ' + year);

        return (List<Objective__c>) Database.query(query);
    }

    /**
    * @description Método que recupera frecuencia de notificaciones. Es un registro 
    * único para el tipo de registro FrequencyNotifications del objeto Objective__c, 
    * por lo tanto la lista solo tendrá un elemento.
    * @author amiranda
    * @date 29-12-2022 
    * @return List<Objective__c> Lista con el único registro disponible para la frecuencia de notificaciones
    **/
    public static List<Objective__c> selectFrequencyNotification()
    {
        List<Objective__c> frequencyNotifications = [SELECT DaysLeft__c 
                                                    FROM Objective__c 
                                                    WHERE RecordTypeId = :rtFrequencyNotifications];

        return frequencyNotifications;
    }

    /**
     * Obtiene un listado de Objetivos activos según indicadores en externalId
     * @param year: String con el año a consultar
     * @return Listado de objetivos
     * @author dmunoz
     * @date 06/07/2022
     * @change amiranda 04/01/2023 Se añade el filtra de tipo de registro 'Objecitves' en la query
     * 
     */
    public static List<Objective__c> selectObjectivesByExternalId(Set<String> externalIdList) {
        //Devolver lista vacía
        if (externalIdList == null || externalIdList.isEmpty()) {
            return new List<Objective__c>();
        }

        String query = String.format(
            'SELECT {0} FROM {1} WHERE ExternalId__c in :externalIdList AND Active__c = true AND RecordTypeId = :rtObjectives',
            new List<String> {getFieldListString(), getSObjectName()}
            );
        System.debug('query ' + query);

        return (List<Objective__c>) Database.query(query);
    }
}