force-app/zurich-base/main/default/objects/IBADocument__c/IBADocument__c.object-meta.xml
<CustomObject>
    <label>Documento IBA</label>
    <nameField>
        <label>Nombre de Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos IBA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/IBADocument__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Póliza</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos_IBA</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/IBADocument__c/fields/PolicyNum__c.field-meta.xml
<CustomField>
    <fullName>PolicyNum__c</fullName>
    <label>Número de póliza</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/PolicyNum__c.field-meta.xml
<CustomField>
    <fullName>PolicyNum__c</fullName>
    <externalId>true</externalId>
    <label>Número de la póliza</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/classes/DocumentUtil.cls
/**
 **
 * @author nbizkarra
 * @date 23/04/2020
 */

public with sharing class DocumentUtil {
  /**
   ** Method that relates document with existing policy
   * @author nbizkarra
   * @date 23/04/2020
   */

  /* Descartado en fase de implementación

    public static void insertDocument(IBADocument__c document,Map<String, Order> mapPolicies, List <IBADocument__c> documentsToInsert) {

        Order policySF=mapPolicies.get(document.PolicyNum__c);

        if(policySF!=null){
            
           // document.Policy__c=policySF.id;
            documentsToInsert.add(document);

        }else{
            System.debug('Error insertando document: poliza no existe');
            throw new IntegrationException(Label.ErrorIBADocument+' '+ document.Name+'. '+Label.PolicyNotExisting+' '+document.PolicyNum__c);

        }
       
    }*/
}