force-app/zurich-base/main/default/objects/DeleteRecordsEvent__e/DeleteRecordsEvent__e.object-meta.xml
<CustomObject>
    <description>Evento lanzado para avisar de un borrado en masa de un objeto concreto y con unas condiciones concretas. está pensado para lanzarlo periódicamente desde un flow</description>
    <label>Delete Records Event</label>
    <pluralLabel>Delete Records Events</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/DeleteRecordsEvent__e/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <description>son las condiciones que se pondrán en la query en el WHERE y antes del limit . Si estuviera vacío no se aplica “where” y se elimina todos los registros del objeto indicado</description>
    <label>Criteria</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/DeleteRecordsEvent__e/fields/LaunchedCount__c.field-meta.xml
<CustomField>
    <fullName>LaunchedCount__c</fullName>
    <defaultValue>1</defaultValue>
    <description>número de veces que se ha lanzado el evento para evitar bucles</description>
    <label>Launched Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/DeleteRecordsEvent__e/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>Objeto del cual se quieren borrar sus registros, ej: &apos;Survey__c&apos;</description>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>OCS - Encuestas al finalizar la llamada en GenesysCloud (WS)</description>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Survey__c/fields/CanBeRemoved__c.field-meta.xml
<CustomField>
    <fullName>CanBeRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>OCS - Marcado a true cuando un usuario determine que se ha realizado la export a Medalia.
Por defecto, false.</description>
    <label>Can Be Removed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Survey__c/fields/InteractionId__c.field-meta.xml
<CustomField>
    <fullName>InteractionId__c</fullName>
    <description>Coincide con el valor de Task.CallObject</description>
    <externalId>true</externalId>
    <label>Interaction Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Survey__c/fields/NumberOfQuestions__c.field-meta.xml
<CustomField>
    <fullName>NumberOfQuestions__c</fullName>
    <defaultValue>1</defaultValue>
    <description>OCS - Número de preguntas que contiene la encuesta y que se utiliza para el procesado de la información antes de enviar a Medalia. Número de preguntas de tipo “ivr” que contiene la encuesta. Necesario para procesamiento de datos en Salesforce. Ejemplo, si tenemos 6 preguntas en total y una de ellas es de tipo “asr” entonces en este parámetro se indicará 5.</description>
    <label>Number Of Questions</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/classes/DeleteRecordsEventUtilTest.cls
@isTest
private class DeleteRecordsEventUtilTest {

    //IMPORTANTE: Se ha probado y validado con 18k de registros pero el test tarda 2min en ejecutar
    //así que se ha reducido el volumen para que tarde menos, pero se puede cambiar aquí para probar
    private static Integer numRecordsInsert = 9; //9000
    private static Integer numRecordsTotal = 18; //18000

    @TestSetup
    static void makeData()
    {
        List<Survey__c> surveys = new List<Survey__c>();
        for(Integer i = 0 ; i < numRecordsInsert; i++)
        {
            Survey__c survey = new Survey__c(InteractionId__c='uniqueId'+i, NumberOfQuestions__c=1, CanBeRemoved__c=true);
            surveys.add(survey);
        }
        insert surveys;
    }

    @isTest
    static void test_handleEvents_ok()
    {
        List<DeleteRecordsEvent__e> events = new List<DeleteRecordsEvent__e>();
        for(Integer j=0; j<2; j++)
        {
            DeleteRecordsEvent__e event = new DeleteRecordsEvent__e(ObjectName__c = 'Survey__c', Criteria__c = 'CanBeRemoved__c = true', LaunchedCount__c = 1);
            events.add(event);
        }

        Test.startTest(); //Como se han limpiado los límites se puede volver a insertar (límite de 10.000)
            List<Survey__c> surveys = new List<Survey__c>();
            for(Integer i = 0 ; i < numRecordsInsert; i++)
            {
                Survey__c survey = new Survey__c(InteractionId__c='2uniqueId'+i, NumberOfQuestions__c=1, CanBeRemoved__c=true);
                surveys.add(survey);
            }
            insert surveys;

            List<Survey__c> insertedSurveys = new List<Survey__c>();
            insertedSurveys = [SELECT Id FROM Survey__c];
            System.assertEquals(numRecordsTotal, insertedSurveys.size(), 'Deberían existir 18000 surveys');

            //Test
            EventBus.publish(events);
            Test.getEventBus().deliver(); //Importante para que se terminen de ejecutar los eventos encolados
        Test.stopTest();

        List<Survey__c> deletedSurveys = new List<Survey__c>();
        deletedSurveys = [SELECT Id FROM Survey__c];
        System.assertEquals(0, deletedSurveys.size(), 'Se deberían haber borrado todas las surveys');
    }

    @isTest
    static void test_handleEvents_ko()
    {
        List<DeleteRecordsEvent__e> events = new List<DeleteRecordsEvent__e>();
        for(Integer j=0; j<2; j++)
        {
            DeleteRecordsEvent__e event = new DeleteRecordsEvent__e(ObjectName__c = 'Survey__c', Criteria__c = 'CanBeRemoved__c = false', LaunchedCount__c = 1);
            events.add(event);
        }

        Test.startTest(); //Como se han limpiado los límites se puede volver a insertar (límite DML de 10.000)
            List<Survey__c> surveys = new List<Survey__c>();
            for(Integer i = 0 ; i < numRecordsInsert; i++)
            {
                Survey__c survey = new Survey__c(InteractionId__c='2uniqueId'+i, NumberOfQuestions__c=1, CanBeRemoved__c=true);
                surveys.add(survey);
            }
            insert surveys;

            List<Survey__c> insertedSurveys = new List<Survey__c>();
            insertedSurveys = [SELECT Id FROM Survey__c];
            System.assertEquals(numRecordsTotal, insertedSurveys.size(), 'Deberían existir 18000 surveys');

            //Test
            EventBus.publish(events);
            Test.getEventBus().deliver(); //Importante para que se terminen de ejecutar los eventos encolados
        Test.stopTest();

        List<Survey__c> deletedSurveys = new List<Survey__c>();
        deletedSurveys = [SELECT Id FROM Survey__c];
        System.assertEquals(numRecordsTotal, deletedSurveys.size(), 'No se deberían haber borrado surveys porque no cumplen la condición de la query');
    }

}