force-app/zurich-base/main/default/objects/Account/recordTypes/BusinessCustomer.recordType-meta.xml
<RecordType>
    <fullName>BusinessCustomer</fullName>
    <active>true</active>
    <description>Tipo de registro para las cuentas empresariales</description>
    <label>Business Customer</label>
</RecordType>

force-app/zurich-base/main/default/objects/Asset/fields/PolicyId__c.field-meta.xml
<CustomField>
    <fullName>PolicyId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS): Relación con la póliza</description>
    <label>Policy Number</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Insured Objects</relationshipLabel>
    <relationshipName>PolicyNumbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scope</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>(OCS). Identifica el ámbito a utilizar para la colaboración del registro</description>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZE</fullName>
                <label>Zurich Empresas</label>
            </value>
            <value>
                <fullName>ZEO</fullName>
                <label>Zurich Empresas Orange</label>
            </value>
            <value>
                <fullName>Z</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>ZEB</fullName>
                <label>Zurich Empresas Brokers</label>
            </value>
            <value>
                <fullName>ZDA</fullName>
                <label>Zurich ZDA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/Scope.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z</fullName>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>ZE</fullName>
        <label>Zurich Empresas</label>
    </customValue>
    <customValue>
        <fullName>ZEO</fullName>
        <label>Zurich Empresas Orange</label>
    </customValue>
    <customValue>
        <fullName>ZEB</fullName>
        <label>Zurich Empresas Brokers</label>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
        <label>Zurich Ventas</label>
    </customValue>
    <customValue>
        <fullName>ZDA</fullName>
        <label>Zurich ZDA</label>
    </customValue>
    <masterLabel>Scope</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/AssetUtilTest.cls
@isTest
private class AssetUtilTest
{
    @TestSetup
    static void makeData()
    {
        List<Account> accounts = TestDataFactory.generateAccounts(Label.GeneralInsurance, 'BusinessCustomer', 10);
        insert accounts;

        List<Policy__c> policies = TestDataFactory.generatePoliciesForEachAccount(accounts, 1);
        for(Policy__c p: policies) {
            p.Scope__c = 'ZE';
        }
        insert policies;
    }

    /**
     * Test que comprueba la generación del ámbito correspondiente para cada siniestro (Asset)
     *
     * @author nts (agonzalezisasi)
     * @date 18/02/2021
     */
    @isTest
    static void test_generateScope()
    {
        // Recuperamos las polizas
        List<Policy__c> policies = [SELECT Id, Scope__c FROM Policy__c WHERE Scope__c != null];
        System.assertEquals(10, policies.size(), 'Deberia haber 10 polizas con scope');

        // Preparamos los siniestros (Asset) sin indicar el scope
        List<Asset> assets = new List<Asset>();
        for( Integer i=0,j=policies.size();i<j;i++ ) {
            assets.add(new Asset(
                Name= String.valueOf(i + 1).leftPad(9, '0'),
                PolicyId__c= policies[i].Id,
                Scope__c= null
            ));
        }
        
        Test.startTest();
        insert assets;
        Test.stopTest();

        List<Asset> assetsUpdated = [SELECT Scope__c FROM Asset WHERE Scope__c != null];
        System.assertEquals(10, assetsUpdated.size(), 'No se han generado todas los Assets con el Ambito correctamente');

        //Para cobertura beforeDelete/afterDelete
        delete assets;
    }
}