force-app/zurich-base/main/default/objects/Account/recordTypes/Intermediary.recordType-meta.xml
<RecordType>
    <fullName>Intermediary</fullName>
    <active>true</active>
    <label>Intermediary</label>
</RecordType>

force-app/zurich-base/main/default/objects/Account/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>Comprende aquellos posibles clientes todavía no existentes en el sistema transaccional</description>
    <label>Lead</label>
</RecordType>

force-app/zurich-base/main/default/objects/Campaign/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código de Campaña</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Cross_Selling__c/Cross_Selling__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Venta Cruzada</label>
</CustomObject>

force-app/zurich-base/main/default/objects/Cross_Selling__c/fields/ContactCenterUser__c.field-meta.xml
<CustomField>
    <fullName>ContactCenterUser__c</fullName>
    <label>Usuario CC</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cross_Selling__c/fields/DefaultUser__c.field-meta.xml
<CustomField>
    <fullName>DefaultUser__c</fullName>
    <description>Alias del usuario genérico al que asignar Ofertas de Venta Cruzada y de Leads en caso de error en la asignación.
ej: ntsadmin</description>
    <label>Usuario Por Defecto</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/InfoQuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>InfoQuoteNumber__c</fullName>
    <description>(ZE/OCS) identificador de la oferta en INFO.</description>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-ventas-app/main/default/classes/Batch_FinishCrossSellingCampaignTest.cls
@IsTest
public with sharing class Batch_FinishCrossSellingCampaignTest {
    
    @TestSetup
    static void makeData(){
        // Crear custom setting que indica el usuario genérico
        Cross_Selling__c ventaCruzada = new Cross_Selling__c();
        ventaCruzada.ContactCenterUser__c = 'generico';
        ventaCruzada.DefaultUser__c = 'adminkli';

        insert ventaCruzada;

        List<Account> accounts = TestDataFactory.generateAccounts('001', 'Customer', 1);
        insert accounts;

        List<Campaign> campaigns = TestDataFactory.generateCampaigns('001', 1);
        
        for (Campaign c: campaigns) {
            c.Type = 'Cross Selling';
            c.IsActive = true;
            c.StartDate = Date.today() - 1;
            c.EndDate = Date.today();
            c.ExternalId__c = 'TestCampaign';
        }

        insert campaigns;

        // Insertar un usuario Agente Ventas

        // Crear cuentas de intermediarios
        List<Account> intermediaries = TestDataFactory.generateAccounts(Label.GeneralInsurance,'Intermediary', 1);

        insert intermediaries;

        // Crear contactos de intermediarios
        List<Contact> intermediaryContacts = TestDataFactory.generateContactsFromAccounts(intermediaries, ContactsSelector.RT_NAME_CONTACT, 1);

        insert intermediaryContacts;

        // Crear los usuarios
        List<String> adminProfiles = new List<String> {'Administrador del sistema', 'System Administrator'};
        List<Boolean> activeStatus = new List<Boolean> {true};
        User adminUser = ( new UsersSelector() ).findByProfileName(adminProfiles, activeStatus, 1)[0];

        // Create portal account owner

        // Partners
        String portalProfile = [SELECT Id FROM Profile WHERE Name = 'Agente Ventas' LIMIT 1].Id;
        List<User> listUser = TestDataFactory.generateUsersByProfile(portalProfile, 1);

        listUser[0].FirstName='Agente';
        listUser[0].LastName='Mediador 1';
        listUser[0].Alias='test1Med';
        listUser[0].ContactId = intermediaryContacts[0].Id;

        System.runAs (adminUser) {
            insert listUser;
        }

        // Insertar oportunidades
        List<Opportunity> offerList = new List<Opportunity>();

        List<Opportunity> legitLeadOfferList = TestDataFactory.generateOpportunitiesForEachAccount(accounts, 'Ventas', 'Legit Lead', Date.today(), 1);
        Integer i = 0;
        for (Opportunity o: legitLeadOfferList) {
            o.InfoQuoteNumber__c = '';              
            o.CampaignId = campaigns.get(0).Id;
            o.ownerId = listUser.get(0).Id;
        }

        i = 50;
        List<Opportunity> appSubmittedOferList = TestDataFactory.generateOpportunitiesForEachAccount(accounts, 'Ventas', 'App Submitted', Date.today(), 1);
        for (Opportunity o: appSubmittedOferList) {
            o.InfoQuoteNumber__c = o.InfoQuoteNumber__c + i;            
            o.CampaignId = campaigns.get(0).Id;
            o.ownerId = listUser.get(0).Id;
            i++;
        }

        i = 100;
        List<Opportunity> quotedOfferList = TestDataFactory.generateOpportunitiesForEachAccount(accounts, 'Ventas', 'Quoted', Date.today(), 1);
        for (Opportunity o: quotedOfferList) {
            o.InfoQuoteNumber__c = o.InfoQuoteNumber__c + i;            
            o.CampaignId = campaigns.get(0).Id;
            o.ownerId = listUser.get(0).Id;
            i++;
        }

        offerList.addAll(legitLeadOfferList);
        offerList.addAll(appSubmittedOferList);
        offerList.addAll(quotedOfferList);

        insert offerList;

        // insertar tarea
        List<Task> taskList = TestDataFactory.generateInteractionTasksWithWhatId(appSubmittedOferList.get(0).Id, 1);
        insert taskList;
    }

    @isTest
    static void testBatchOk() {

        List<Opportunity> offersBeforeList = new List<Opportunity>([SELECT Id FROM Opportunity WHERE StageName != 'Closed Lost']);

        Test.startTest();

        Batch_FinishCrossSellingCampaign batch = new Batch_FinishCrossSellingCampaign();
        Database.executeBatch(batch, 200);

        Test.stopTest();

        List<Opportunity> offersAfterList = new List<Opportunity>([SELECT Id FROM Opportunity WHERE Id IN :offersBeforeList AND StageName = 'Closed Lost']);
        System.assertEquals(offersBeforeList.size(), offersAfterList.size(), 'Las ofertas deberian haberse cambiado de etapa a Cerrada Perdida');
    }


    @isTest
    static void testScheduleByQuery() {
         // prueba batch
         Test.startTest();
         String jobName = 'testScheduleByQuery';
         String cron = '';
 
         String jobId = Batch_FinishCrossSellingCampaign.createStandardSchedule(jobName, cron);
 
         Test.stopTest();
 
         List<CronTrigger> cronList = new List<CronTrigger>([SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]);
 
         System.assertEquals(1, cronList.size(), 'Debe haber un job programado');

    }
}