force-app/zurich-base/main/default/objects/Account/recordTypes/Intermediary.recordType-meta.xml
<RecordType>
    <fullName>Intermediary</fullName>
    <active>true</active>
    <label>Intermediary</label>
</RecordType>

force-app/zurich-base/main/default/objects/Case/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Dependiente de Type N3</description>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TypeN3__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bono</fullName>
            </value>
            <value>
                <fullName>Mi Zurich</fullName>
            </value>
            <value>
                <fullName>Oferta</fullName>
            </value>
            <value>
                <fullName>Póliza Viaje</fullName>
            </value>
            <value>
                <fullName>Recibo</fullName>
            </value>
            <value>
                <fullName>Póliza</fullName>
            </value>
            <value>
                <fullName>Productos</fullName>
            </value>
            <value>
                <fullName>Estado gestión</fullName>
            </value>
            <value>
                <fullName>Garantías/capitales asegurados</fullName>
            </value>
            <value>
                <fullName>Precio renovación póliza</fullName>
            </value>
            <value>
                <fullName>Riesgo asegurado</fullName>
            </value>
            <value>
                <fullName>Recibo -Estado</fullName>
            </value>
            <value>
                <fullName>Recibo – Importe</fullName>
            </value>
            <value>
                <fullName>Recibo - Fecha</fullName>
            </value>
            <value>
                <fullName>Peritación</fullName>
            </value>
            <value>
                <fullName>Siniestros</fullName>
            </value>
            <value>
                <fullName>Soporte navegación</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>Carta verde</fullName>
            </value>
            <value>
                <fullName>Certificados</fullName>
            </value>
            <value>
                <fullName>Comisiones</fullName>
            </value>
            <value>
                <fullName>Documentación mediadores</fullName>
            </value>
            <value>
                <fullName>Documento seguro</fullName>
            </value>
            <value>
                <fullName>Duplicado de Cartera</fullName>
            </value>
            <value>
                <fullName>Factura mediador</fullName>
            </value>
            <value>
                <fullName>Informe de Comisiones</fullName>
            </value>
            <value>
                <fullName>Modelo 347 / DEC</fullName>
            </value>
            <value>
                <fullName>N57 / Asesoría Jurídica</fullName>
            </value>
            <value>
                <fullName>Normativa</fullName>
            </value>
            <value>
                <fullName>Parte DDA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Export_CSV_Field__mdt/Export_CSV_Field__mdt.object-meta.xml
<CustomObject>
    <label>Export CSV Field</label>
    <pluralLabel>Export CSV Field</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/Export_CSV_Field__mdt/fields/FieldToExport__c.field-meta.xml
<CustomField>
    <fullName>FieldToExport__c</fullName>
    <label>FieldToExport</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/Export_CSV_Field__mdt/fields/Labels__c.field-meta.xml
<CustomField>
    <fullName>Labels__c</fullName>
    <label>Labels</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/zurich-base/main/default/classes/DynamicSelectorTest.cls
@IsTest(SeeAllData=true)    
private with sharing class DynamicSelectorTest {
    

    @IsTest(SeeAllData=true)    
    private static void test_getQueryStringMetadataInfoToExport_matchedRecord()
    {
        List<Export_CSV_Field__mdt> listMatchedRecords= new List<Export_CSV_Field__mdt>();
        Export_CSV_Field__mdt metadataFieldObject = new Export_CSV_Field__mdt();
        String sobjectName='Case';

        metadataFieldObject= [SELECT Id,FieldToExport__c,Labels__c FROM Export_CSV_Field__mdt WHERE Object__c=:sobjectName];

        // Test
        Test.startTest();
        listMatchedRecords = new DynamicSelector(metadataFieldObject.getsobjectType()).getQueryStringMetadataInfoToExport(sobjectName);
        Test.stopTest();

        System.assertEquals(listMatchedRecords[0].FieldToExport__c,metadataFieldObject.FieldToExport__c);
        System.assertEquals(listMatchedRecords[0].Labels__c,metadataFieldObject.Labels__c);
    }


    @IsTest(SeeAllData=true)    
    private static void test_GetRecordsExportsButton_matchedRecord()
    {
        List<SObject> objectsExport= new List<SObject>();

        List<Account> accounts = TestDataFactory.generateAccounts(Label.GeneralInsurance, 'Intermediary', 1);
        insert accounts;

        List<Case> cases = TestDataFactory.generateCasesForEachAccount(accounts, 2);
        insert cases;

        List<String> listIdsRecordsExports= new List<String>();

        for(Case record: cases)
        {
            listIdsRecordsExports.add(record.Id);
        }

        String fieldsQuery='Id,CaseNumber';
        String objetExportName='Case';

        // Test
        Test.startTest();
        objectsExport= new DynamicSelector(cases[0].getsobjectType()).getListSobjectToExport(fieldsQuery,objetExportName,listIdsRecordsExports);
        Test.stopTest();

        System.assertEquals(objectsExport.size(),2);

    }

    
}