force-app/zurich-base/main/default/objects/Account/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>Comprende aquellos posibles clientes todavía no existentes en el sistema transaccional</description>
    <label>Lead</label>
</RecordType>

force-app/zurich-base/main/default/objects/Case/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scope</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Entity in which to register relevant data of policies contracted by the Customer with competitors of Zurich.</description>
    <label>Competitor</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Competitor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nombre del cliente del que se está registrando la competencia</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor</relationshipLabel>
    <relationshipName>Competitors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cross_Selling__c/Cross_Selling__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Venta Cruzada</label>
</CustomObject>

force-app/zurich-base/main/default/objects/Cross_Selling__c/fields/ContactCenterUser__c.field-meta.xml
<CustomField>
    <fullName>ContactCenterUser__c</fullName>
    <label>Usuario CC</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cross_Selling__c/fields/DefaultUser__c.field-meta.xml
<CustomField>
    <fullName>DefaultUser__c</fullName>
    <description>Alias del usuario genérico al que asignar Ofertas de Venta Cruzada y de Leads en caso de error en la asignación.
ej: ntsadmin</description>
    <label>Usuario Por Defecto</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>(OCS) Identifica el código de negocio en INFO.</description>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>(ZE/OCS) Identifica el ámbito a utilizar para la colaboración del registro.</description>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZE</fullName>
                <label>Zurich Empresas</label>
            </value>
            <value>
                <fullName>ZEO</fullName>
                <label>Zurich Empresas Orange</label>
            </value>
            <value>
                <fullName>Z</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>ZEB</fullName>
                <label>Zurich Empresas Brokers</label>
            </value>
            <value>
                <fullName>Ventas</fullName>
                <label>Zurich Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/Scope.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z</fullName>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>ZE</fullName>
        <label>Zurich Empresas</label>
    </customValue>
    <customValue>
        <fullName>ZEO</fullName>
        <label>Zurich Empresas Orange</label>
    </customValue>
    <customValue>
        <fullName>ZEB</fullName>
        <label>Zurich Empresas Brokers</label>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
        <label>Zurich Ventas</label>
    </customValue>
    <customValue>
        <fullName>ZDA</fullName>
        <label>Zurich ZDA</label>
    </customValue>
    <masterLabel>Scope</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Batch_DeleteOldLeadsTest.cls
/**
 * @description       :
 * @author            : rserrano
 * @group             :
 * @last modified on  : 25/04/2024
 * @last modified by  : rserrano
 **/
@IsTest
public with sharing class Batch_DeleteOldLeadsTest
{

    private static final String OFFER_SCOPE_VENTAS = GlobalConfigUtil.getGlobalConfigurationValue('Opportunity_Scope_Ventas');
    private static final String OFFER_STATUS_LEGIT_LEAD = GlobalConfigUtil.getGlobalConfigurationValue('Opportunity_Stage_Name_Legit_Lead');

    @TestSetup
    static void makeData()
    {

        /*****************************  CUSTOM SETTINGS  ****************************/
        Cross_Selling__c ventaCruzada = new Cross_Selling__c();
        ventaCruzada.ContactCenterUser__c = 'generico';
        ventaCruzada.DefaultUser__c = 'adminkli';

        insert ventaCruzada;

        // Insertar objetos para el test

        List<Account> accounts = TestDataFactory.generateAccounts(Label.GeneralInsurance, 'Lead', 2);
        insert accounts;

        List<Competitor__c> competitors = TestDataFactory.generateCompetitors(accounts, 2);
        insert competitors;
    }

    // compruebo que en el caso de leads con ofertas legit lead solo de ventas/zrm elimina todos los datos, lead, oferta y competencias
    @isTest
    private static void testBatchUnicaOfertaVentas()
    {
        List<Account> leadsList = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Lead'];
        // Inserto oferta Ventas/ZRM
        List<Opportunity> opportunitiesToInsert = TestDataFactory.generateOpportunities(leadsList, OFFER_SCOPE_VENTAS, OFFER_STATUS_LEGIT_LEAD, Date.today() + 30, 2);
        insert opportunitiesToInsert;

        // Envejezco las ofertas mas allá de 90 días
        for(Opportunity offer : opportunitiesToInsert)
        {
            Test.setCreatedDate( offer.Id, Datetime.now().addDays(-91) );
        }


        Test.startTest();

        Batch_DeleteOldLeads batch = new Batch_DeleteOldLeads();
        Database.executeBatch(batch, 200);

        Test.stopTest();

        //Recuperar registros después de la ejecución
        List<Account> updatedLeadList = [SELECT Id FROM Account WHERE Recordtype.DeveloperName = 'Lead'];
        List<Opportunity> updatedOpportunityList = [SELECT Id FROM Opportunity];
        List<Competitor__c> updatedCompetitorList = [SELECT Id FROM Competitor__c];

        Assert.isTrue(updatedLeadList.size() == 0, 'Se deberían haber borrado todos los leads');
        Assert.isTrue(updatedOpportunityList.size() == 0, 'Se deberían haber borrado todas las ofertas');
        Assert.isTrue(updatedCompetitorList.size() == 0, 'Se deberían haber borrado todas las competencias');
    }


    // compruebo que un lead le cargo ofertas de ZE y Ventas para que no elimine el lead ni sus competencias
    @isTest
    private static void testBatchLeadConOfertasVentaYZE()
    {
        List<Account> leadsList = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Lead' LIMIT 1];
        // Inserto oferta Ventas/ZRM
        List<Opportunity> opportunitiesToInsert = TestDataFactory.generateOpportunities(leadsList, OFFER_SCOPE_VENTAS, OFFER_STATUS_LEGIT_LEAD, Date.today() + 30, 1);
        insert opportunitiesToInsert;

        // Inserto oferta ZE
        List<Opportunity> opportunitiesZEToInsert = TestDataFactory.generateOpportunities(leadsList, 'ze', OFFER_STATUS_LEGIT_LEAD, Date.today() + 30, 1);
        // le asigno un codigo de negocio
        for (Opportunity opp: opportunitiesZEToInsert)
        {
            OPP.Scope__c = 'ZE';
            opp.BusinessCode__c = '123456';
        }
        insert opportunitiesZEToInsert;

        // Envejezco las ofertas mas allá de 90 días
        for(Opportunity offer : opportunitiesToInsert)
        {
            Test.setCreatedDate( offer.Id, Datetime.now().addDays(-91) );
        }

        Test.startTest();

        Batch_DeleteOldLeads batch = new Batch_DeleteOldLeads();
        Database.executeBatch(batch, 200);

        Test.stopTest();

        //Recuperar registros después de la ejecución
        List<Account> updatedLeadList = [SELECT Id FROM Account WHERE Id = : leadsList.get(0).Id];
        List<Opportunity> updatedOpportunityList = [SELECT Id FROM Opportunity WHERE AccountId = : leadsList.get(0).Id];
        List<Competitor__c> updatedCompetitorList = [SELECT Id FROM Competitor__c WHERE Account__c = : leadsList.get(0).Id];

        Assert.isTrue(updatedLeadList.size() > 0, 'NO Se deberían haber borrado todos los leads');
        Assert.isTrue(updatedOpportunityList.size() > 0, 'NO Se deberían haber borrado todas las ofertas');
        Assert.isTrue(updatedCompetitorList.size() > 0, 'NO Se deberían haber borrado todas las competencias');
    }

    // compruebo que un lead le cargo ofertas de Ventas (2 una con -90 dias y otra con -50) para que no elimine el lead, ni la otra oferta ni sus competencias
    @isTest
    private static void testBatchLeadConOfertasVentaSinCaducar()
    {
        List<Account> leadsList = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Lead' LIMIT 1];
        // Inserto oferta Ventas/ZRM
        List<Opportunity> opportunitiesToInsert = TestDataFactory.generateOpportunities(leadsList, OFFER_SCOPE_VENTAS, OFFER_STATUS_LEGIT_LEAD, Date.today() + 30, 2);
        insert opportunitiesToInsert;

        // Envejezco solo una oferta mas allá de 90 días
        Test.setCreatedDate( opportunitiesToInsert.get(0).Id, Datetime.now().addDays(-91) );

        Test.startTest();

        Batch_DeleteOldLeads batch = new Batch_DeleteOldLeads();
        Database.executeBatch(batch, 200);

        Test.stopTest();

        //Recuperar registros después de la ejecución
        List<Account> updatedLeadList = [SELECT Id FROM Account WHERE Id = : leadsList.get(0).Id];
        List<Opportunity> updatedOpportunityList = [SELECT Id FROM Opportunity WHERE AccountId = : leadsList.get(0).Id];
        List<Competitor__c> updatedCompetitorList = [SELECT Id FROM Competitor__c WHERE Account__c = : leadsList.get(0).Id];

        Assert.isTrue(updatedLeadList.size() > 0, 'NO Se deberían haber borrado todos los leads');
        Assert.isTrue(updatedOpportunityList.size() == 1, 'Debe quedar una oferta de ZRM');
        Assert.isTrue(updatedCompetitorList.size() > 0, 'NO Se deberían haber borrado todas las competencias');
    }


    // compruebo que un lead le cargo ofertas de Ventas (2 una con -90 dias y otra con -50)  y de ZE con fecha caducada para que no elimine el lead, ni las 2 ofertas una de ventas y otra de ZE, ni sus competencias
    @isTest
    private static void testBatchLeadConOfertasVentaYZESinCaducar()
    {
        List<Account> leadsList = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Lead' LIMIT 1];
        // Inserto oferta Ventas/ZRM
        List<Opportunity> opportunitiesToInsert = TestDataFactory.generateOpportunities(leadsList, OFFER_SCOPE_VENTAS, OFFER_STATUS_LEGIT_LEAD, Date.today() + 30, 2);
        insert opportunitiesToInsert;

        // Envejezco solo una oferta mas allá de 90 días
        Test.setCreatedDate( opportunitiesToInsert.get(0).Id, Datetime.now().addDays(-91) );

        // Inserto oferta ZE
        List<Opportunity> opportunitiesZEToInsert = TestDataFactory.generateOpportunities(leadsList, 'ze', OFFER_STATUS_LEGIT_LEAD, Date.today() + 30, 1);
        // le asigno un codigo de negocio
        for (Opportunity opp: opportunitiesZEToInsert)
        {
            OPP.Scope__c = 'ZE';
            opp.BusinessCode__c = '123456';
        }
        insert opportunitiesZEToInsert;

        Test.setCreatedDate( opportunitiesZEToInsert.get(0).Id, Datetime.now().addDays(-151) );

        Test.startTest();

        Batch_DeleteOldLeads batch = new Batch_DeleteOldLeads();
        Database.executeBatch(batch, 200);

        Test.stopTest();

        //Recuperar registros después de la ejecución
        List<Account> updatedLeadList = [SELECT Id FROM Account WHERE Id = : leadsList.get(0).Id];
        List<Opportunity> updatedOpportunityList = [SELECT Id FROM Opportunity WHERE AccountId = : leadsList.get(0).Id];
        List<Competitor__c> updatedCompetitorList = [SELECT Id FROM Competitor__c WHERE Account__c = : leadsList.get(0).Id];

        Assert.isTrue(updatedLeadList.size() > 0, 'NO Se deberían haber borrado todos los leads');
        Assert.isTrue(updatedOpportunityList.size() == 2, 'Debe quedar una oferta de ZRM y otra de ZE');
        Assert.isTrue(updatedCompetitorList.size() > 0, 'NO Se deberían haber borrado todas las competencias');
    }


    // compruebo que en el caso de leads con ofertas legit lead solo de ventas/zrm elimina todos los datos, lead, oferta y competencias
    @isTest
    private static void testBatchLeadConCaso()
    {
        List<Account> leadsList = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Lead'];
        // Inserto oferta Ventas/ZRM
        List<Opportunity> opportunitiesToInsert = TestDataFactory.generateOpportunities(leadsList, OFFER_SCOPE_VENTAS, OFFER_STATUS_LEGIT_LEAD, Date.today() + 30, 2);
        insert opportunitiesToInsert;

        // Envejezco las ofertas mas allá de 90 días
        for(Opportunity offer : opportunitiesToInsert)
        {
            Test.setCreatedDate( offer.Id, Datetime.now().addDays(-91) );
        }

        // Inserto un caso al lead
        List<Case> cases = TestDataFactory.generateCasesForEachAccount(leadsList, 1);
        insert cases;


        Test.startTest();

        Batch_DeleteOldLeads batch = new Batch_DeleteOldLeads();
        Database.executeBatch(batch, 200);

        Test.stopTest();

        //Recuperar registros después de la ejecución
        List<Account> updatedLeadList = [SELECT Id FROM Account WHERE Recordtype.DeveloperName = 'Lead'];
        List<Opportunity> updatedOpportunityList = [SELECT Id FROM Opportunity];
        List<Competitor__c> updatedCompetitorList = [SELECT Id FROM Competitor__c];

        Assert.isTrue(updatedLeadList.size() > 0, 'No se deberían haber borrado todos los leads');
        Assert.isTrue(updatedOpportunityList.size() == 0, 'Se deberían haber borrado todas las ofertas');
        Assert.isTrue(updatedCompetitorList.size() > 0, 'No se deberían haber borrado todas las competencias');
    }

    @isTest
    private static void testSchedulerOK()
    {
        Test.startTest();

        Batch_DeleteOldLeads batch = new Batch_DeleteOldLeads();
        String sch = '0 0 23 ? * * *';
        String jobID = System.schedule('BATCH DELETE OLD LEADS Test', sch, batch);

        Test.stopTest();

        List<CronTrigger> cronList = new List<CronTrigger>([SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = : jobID]);

        Assert.areEqual(1, cronList.size(), 'Debe haber un job programado');
    }
}