force-app/zurich-base/main/default/objects/Account/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>Comprende aquellos posibles clientes todavía no existentes en el sistema transaccional</description>
    <label>Lead</label>
</RecordType>

force-app/zurich-base/main/default/objects/CampaignMember/fields/OfferAssignedType__c.field-meta.xml
<CustomField>
    <fullName>OfferAssignedType__c</fullName>
    <description>Tipo de mediador asignado a la oferta.</description>
    <label>Offer Assigned Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Mediador</label>
            </value>
            <value>
                <fullName>CC</fullName>
                <label>Contact Center</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Cross_Selling__c/Cross_Selling__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Venta Cruzada</label>
</CustomObject>

force-app/zurich-base/main/default/objects/Cross_Selling__c/fields/ContactCenterUser__c.field-meta.xml
<CustomField>
    <fullName>ContactCenterUser__c</fullName>
    <label>Usuario CC</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cross_Selling__c/fields/DefaultUser__c.field-meta.xml
<CustomField>
    <fullName>DefaultUser__c</fullName>
    <description>Alias del usuario genérico al que asignar Ofertas de Venta Cruzada y de Leads en caso de error en la asignación.
ej: ntsadmin</description>
    <label>Usuario Por Defecto</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/InfoQuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>InfoQuoteNumber__c</fullName>
    <description>(ZE/OCS) identificador de la oferta en INFO.</description>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/Sales_Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Sales_Loss_Reason__c</fullName>
    <description>Campo Motivo de pérdida para su uso en la app Ventas, sustituye al ya existente para el resto de apps</description>
    <label>Sales Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SalesProcess__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interested later on</fullName>
                <label>Interesado más adelante</label>
            </value>
            <value>
                <fullName>CC - Interested, managed by my agent</fullName>
            </value>
            <value>
                <fullName>Better competition conditions</fullName>
                <label>Mejores condiciones competencia</label>
            </value>
            <value>
                <fullName>Lack/limitation of coverage</fullName>
                <label>Falta/limitación de coberturas</label>
            </value>
            <value>
                <fullName>Insurance required by the bank</fullName>
                <label>Seguro obligado con el banco</label>
            </value>
            <value>
                <fullName>Already take a policy</fullName>
                <label>Ya ha contratado póliza</label>
            </value>
            <value>
                <fullName>Bad experience</fullName>
                <label>Mala experiencia</label>
            </value>
            <value>
                <fullName>Need higher discount</fullName>
                <label>Necesita descuento mayor</label>
            </value>
            <value>
                <fullName>Incidence unresolved with policy</fullName>
                <label>Incidencia actual no resuelta con alguna póliza en vigor</label>
            </value>
            <value>
                <fullName>No insurable risk</fullName>
                <label>No Dispone de Riesgo Asegurable</label>
            </value>
            <value>
                <fullName>Agenda Not Contacted</fullName>
                <label>Agenda No Contactada</label>
            </value>
            <value>
                <fullName>Out of Recruitment Policy</fullName>
                <label>Fuera Política Contratación</label>
            </value>
            <value>
                <fullName>Not Zurich customer</fullName>
                <label>No es cliente Zurich</label>
            </value>
            <value>
                <fullName>No Recording Accepted</fullName>
                <label>No Acepta Grabación</label>
            </value>
            <value>
                <fullName>Unreachable After Hours</fullName>
                <label>Ilocalizable Fuera de Horario</label>
            </value>
            <value>
                <fullName>Maximum Attempts</fullName>
                <label>Máximo Intentos</label>
            </value>
            <value>
                <fullName>Robinson List</fullName>
                <label>Lista Robinson</label>
            </value>
            <value>
                <fullName>No cooperation</fullName>
                <label>No colabora</label>
            </value>
            <value>
                <fullName>CC - Interested contact agent</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Canceled Policy</fullName>
                <label>Póliza Anulada</label>
            </value>
            <value>
                <fullName>Not interested Policy - Revocation Consents</fullName>
                <label>No quiere Póliza - Revocación Consentimientos</label>
            </value>
            <value>
                <fullName>HOME- Never had it and does not want it</fullName>
                <label>HOGAR- No ha tenido nunca y no lo quiere</label>
            </value>
            <value>
                <fullName>Insufficient/incorrect data</fullName>
                <label>Datos insuficientes/erróneos</label>
            </value>
            <value>
                <fullName>Automatic - Not managed by the Agent</fullName>
            </value>
            <value>
                <fullName>Automatic - Campaign completed</fullName>
            </value>
            <value>
                <fullName>Automatic - Agent removes from the campaign</fullName>
            </value>
            <value>
                <fullName>Do not want Policy - Expired</fullName>
                <label>No quiere Póliza - Supera Antigüedad</label>
            </value>
            <value>
                <fullName>Integral customer</fullName>
            </value>
            <value>
                <fullName>Impossible to contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/ZRM__c.field-meta.xml
<CustomField>
    <fullName>ZRM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ZRM: usamos este campo para identificar las ofertas que un usuario de ZRM puede editar, se usa junto con la VR IntermediaryCannotEdit</description>
    <label>ZRM</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/classes/CampaignMemberUtilTest.cls
/**
 * Clases de test para CampaignMemberUtilTest
 **
 * @author rlopez
 * @date 21/12/2020
 */
@isTest(SeeAllData=false)
private with sharing class CampaignMemberUtilTest
{
    @TestSetup
    public static void createScenario()
    {
        List<Account> accounts = TestDataFactory.generateAccounts('001', 'Customer', 10);
        insert accounts;

        Cross_Selling__c ventaCruzada = new Cross_Selling__c();
        ventaCruzada.ContactCenterUser__c = 'generico';
        ventaCruzada.DefaultUser__c = 'adminkli';
        insert ventaCruzada;

        List<Campaign> campaigns = TestDataFactory.generateCampaigns('001', 10);
        campaigns[0].Type = 'Cross Selling';
        campaigns[0].StartDate = Date.today();
        campaigns[0].EndDate = Date.today() + 7;
        insert campaigns;

        List<CampaignMemberStatus> newStatuses = new List<CampaignMemberStatus>();
        for(Campaign campaign: campaigns)
        {
            newStatuses.add(
                new CampaignMemberStatus(
                    CampaignID=campaign.Id,
                    Label='New',
                    IsDefault=false,
                    HasResponded=false,
                    SortOrder=5
                    )
                );
            newStatuses.add(
                new CampaignMemberStatus(
                    CampaignID=campaign.Id,
                    Label='Delete',
                    IsDefault=false,
                    HasResponded=false,
                    SortOrder=6
                    )
                );
        }

        insert newStatuses;

        // hotfix: obtener cuentas de tipo personales con el campo PersonContactId relleno
        accounts = new List<Account>([SELECT Id, PersonContactId FROM Account WHERE PersonContactId != null]);

        List<CampaignMember> campaignMembers = TestDataFactory.generateCampaignMembersForEachCampaign(accounts, campaigns, 'New');
        campaignMembers[0].OfferAssignedType__c = 'CC';
        insert campaignMembers;

        Profile readOnlyProfile = [SELECT Id FROM Profile WHERE Name = 'Read Only'];
        List<User> users = TestDataFactory.generateUsersByProfile(readOnlyProfile.Id, 1);
        insert users;
    }

    /**
     * Método que comprueba que se eliminan todos los miembros de campaña con Status = Delete
     * al llamar a CampaignMemberUtil.deleteMembers
     *
     * @author rlopez
     * @date 21/12/2020
     */
    @isTest
    static void test_deleteMembers_bulk_ok()
    {
        //Recuperamos CampaignMembers para marcarlos con Status = Delete
        List<CampaignMember> campaignMembersToUpdate = [SELECT Id, Status, CampaignId FROM CampaignMember];
        System.assertEquals(false, campaignMembersToUpdate.isEmpty(), 'List should NOT be empty');

        for(CampaignMember member: campaignMembersToUpdate)
        {
            member.Status = 'Delete';
        }

        update campaignMembersToUpdate;

        Test.startTest();
        CampaignMemberUtil.deleteMembers();
        Test.stopTest();

        //Comprobamos que se han eliminado todos los miembros de campaña
        List<CampaignMember> deletedMembers = new CampaignMembersSelector().selectByStatus('Delete');
        System.assertEquals(true, deletedMembers.isEmpty(), 'There should not be any CampaignMember with status "Delete"');

        //Comprobamos que hemos borrado todos los miembros de campaña
        List<CampaignMember> currentCampaignMembers = [SELECT Id, Status FROM CampaignMember];
        System.assertEquals(true, currentCampaignMembers.isEmpty(), 'List should be empty');
    }

    /**
     * Método que comprueba que se eliminan todos los miembros de campaña con Status = Delete
     * al llamar a CampaignMemberUtil.deleteMembers
     *
     * @author rlopez
     * @date 21/12/2020
     */
    @isTest
    static void test_deleteMembers_ok()
    {
        //Recuperamos CampaignMembers para marcarlos con Status = Delete
        List<CampaignMember> campaignMembersToUpdate = [SELECT Id, Status, CampaignId FROM CampaignMember];
        System.assertEquals(false, campaignMembersToUpdate.isEmpty(), 'List should NOT be empty');

        campaignMembersToUpdate.get(0).Status = 'Delete';

        update campaignMembersToUpdate;

        Test.startTest();
        CampaignMemberUtil.deleteMembers();
        Test.stopTest();

        //Comprobamos que se han eliminado todos los miembros de campaña
        List<CampaignMember> deletedMembers = new CampaignMembersSelector().selectByStatus('Delete');
        System.assertEquals(true, deletedMembers.isEmpty(), 'There should not be any CampaignMember with status "Delete"');

        //Comprobamos que SOLO hemos borrado un miembro de campaña
        List<CampaignMember> currentCampaignMembers = [SELECT Id, Status FROM CampaignMember];
        System.assertEquals(false, currentCampaignMembers.isEmpty(), 'List should NOT be empty');
    }
    

    /**
     * Método de test que comprueba que al eliminar un miembro de campaña de una campaña, las ofertas relacionadas pasan a estado Cerrado Perdida
     * 
     * @author: arcortazar
     * @date: 13/11/2023
     */
    @IsTest
    static void test_closeRelatedOffer_ok()
    {
        // Recuperamos las ofertas correspondientes a los miembros de campaña que vamos a eliminar
        Set<String> idCampanyas = new Set<String>();
        Set<String> idMiembros = new Set<String>();

        //Recuperamos CampaignMembers para marcarlos con Status = Delete
        List<CampaignMember> campaignMembersToDelete = [SELECT Id, Status, CampaignId, Contact.AccountId, LeadOrContactOwnerId FROM CampaignMember WHERE Campaign.Type = 'Cross Selling'];
        System.assertEquals(false, campaignMembersToDelete.isEmpty(), 'List should NOT be empty');

        for(CampaignMember cm : campaignMembersToDelete)
        {
            idCampanyas.add(cm.CampaignId);
            idMiembros.add(cm.Contact.AccountId);
        }

        List<Account> accounts = new List<Account>([SELECT Id FROM Account WHERE id in :idMiembros]);

        List<Opportunity> legitLeadOfferList = TestDataFactory.generateOpportunitiesForEachAccount(accounts, 'Ventas', 'Legit Lead', Date.today(), 1);
        List<String> campaignIdList = new List<String>(idCampanyas);
        
        for (Opportunity o: legitLeadOfferList) {
            o.InfoQuoteNumber__c = '';              
            o.CampaignId = campaignIdList.get(0);
            o.ZRM__c = true;
        }

        insert legitLeadOfferList;

        
        
        OpportunitiesSelector selector = new OpportunitiesSelector();
        List<Opportunity> oportunidades = selector.findByCampaignAndCampaignMember(idCampanyas, idMiembros);
        System.assertEquals(false, oportunidades.isEmpty(), 'Ha de haber ofertas para cerrar');

        Test.startTest();
        delete campaignMembersToDelete;
        Test.stopTest();

        // Comprobamos que el miembro se ha borrado
        List<CampaignMember> existMember = [SELECT Id, Status, CampaignId, Contact.AccountId FROM CampaignMember WHERE Id =:campaignMembersToDelete[0].id];
        System.assertEquals(true, existMember.isEmpty(), 'El miembro se tiene que haber borrado');

        oportunidades = selector.findByCampaignAndCampaignMember(idCampanyas, idMiembros);
        System.assertEquals(true, oportunidades.isEmpty(), 'No deben quedar ofertas abiertas para estos miembros de campaña');

        oportunidades = [SELECT id, StageName, Sales_Loss_Reason__c FROM Opportunity WHERE CampaignID IN :idCampanyas AND AccountId IN :idMiembros AND Campaign.Type = 'Cross Selling'];
        for(Opportunity o : oportunidades)
        {
            System.assertEquals('Closed Lost', o.StageName, 'Deberia ser Cerrado Perdido');
            System.assertEquals('Agent removes from the campaign', o.Sales_Loss_Reason__c, 'Deberia ser Cerrado Perdido');
        }
    }
}