force-app/zurich-base/main/default/objects/Account/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Primer nivel de restricción de acceso</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/BusinessCustomer.recordType-meta.xml
<RecordType>
    <fullName>BusinessCustomer</fullName>
    <active>true</active>
    <description>Tipo de registro para las cuentas empresariales</description>
    <label>Business Customer</label>
</RecordType>

force-app/zurich-base/main/default/objects/Campaign/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad legal</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/CampaignMember/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Primer nivel de restricción de acceso</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/ClaimId__c.field-meta.xml
<CustomField>
    <fullName>ClaimId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OCS</description>
    <label>Claim Name</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/CreatedOffer__c.field-meta.xml
<CustomField>
    <fullName>CreatedOffer__c</fullName>
    <label>Created Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad Legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Policy to which is related to</description>
    <label>Póliza</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/PolicyNum__c.field-meta.xml
<CustomField>
    <fullName>PolicyNum__c</fullName>
    <externalId>true</externalId>
    <label>Número de póliza</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>OCS</description>
    <label>Siniestro</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Siniestros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Claim__c/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <description>(OCS). Puntero a la póliza vinculada</description>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/fields/PolicyHolder__c.field-meta.xml
<CustomField>
    <fullName>PolicyHolder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Puntero al tomador de la póliza vinculada</description>
    <label>Policy holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a borrar debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to</description>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/EmailMessage/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/EmailMessage/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Primer nivel de restricción de acceso.</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Primer nivel de restricción de acceso</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &apos;Life&apos;, &apos;Life Insurance&apos;, 
			IF($Profile.Name = &apos;ZE User&apos; || $Profile.Name = &apos;Ventas User&apos;,
			    &apos;001&apos;,
			        &apos;&apos;))</defaultValue>
    <description>(ZE/OCS) Identifica la entidad legal a la que pertenece la oferta.</description>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Insurance</fullName>
            </value>
            <value>
                <fullName>General Insurance</fullName>
            </value>
            <value>
                <fullName>000</fullName>
                <label>Todos</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>Zurich</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>CAN SSGG</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>CAS SSGG</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>CAS Vida</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Zurich Vida</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>DZ Pensiones</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>EPSV Zurich</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>BSSG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>Multientidad</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Primer nivel de restricción de acceso</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>(OCS). Identifica la entidad legal a la que está asociada la póliza en INFO</description>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Insurance</fullName>
            </value>
            <value>
                <fullName>General Insurance</fullName>
            </value>
            <value>
                <fullName>000</fullName>
                <label>Todos</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>Zurich</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>CAN SSGG</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>CAS SSGG</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>CAS Vida</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Zurich Vida</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>DZ Pensiones</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>EPSV Zurich</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>BSSG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>Multientidad</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/PolicyHolder__c.field-meta.xml
<CustomField>
    <fullName>PolicyHolder__c</fullName>
    <description>(OCS). Identifica el tomador de la póliza</description>
    <label>Policy Holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Policy Holder)</relationshipLabel>
    <relationshipName>PoliciesHolder</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/GDPRPropagateBlockedFieldBatchTest.cls
/**
 * @description       :
 * @author            : jgallaga
 * @group             :
 * @last modified on  : 18/10/2023
 * @last modified by  : jgallaga
**/
@istest
public with sharing class GDPRPropagateBlockedFieldBatchTest
{

    private static final String ACCOUNT_CUSTOMER = 'Customer';
    private static final String ACCOUNT_BCUSTOMER = 'BusinessCustomer';
    private static final String LEGAL_ENTITY = '001';
    private static final Id CustomerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().
                                                get(ACCOUNT_CUSTOMER).getRecordTypeId();
    private static final Id BCustomerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().
                                                get(ACCOUNT_BCUSTOMER).getRecordTypeId();


    @TestSetup
    private static void makeData()
    {
        List<Account> accs = TestDataFactory.generateAccounts(LEGAL_ENTITY, ACCOUNT_CUSTOMER, 1);

        for(Integer i = 0; accs.size() < i; i++){
            accs[i].FirstName = 'Test Account';
            accs[i].LastName = '-001';
            accs[i].RecordTypeId = CustomerRecordTypeId;
        }
        insert accs;

        List<Opportunity> opp = TestDataFactory.generateOpportunitiesForEachAccount(accs, 'ZE', 'Closed Won', System.today().addDays(10), 1);
        insert opp;

        List<Policy__c> poliza1 = TestDataFactory.generatePoliciesForEachAccount(accs, 1);
        insert poliza1;

        List<Policy__c> poliza2 = TestDataFactory.generatePoliciesForEachOpportunity(opp, 1);
        insert poliza2;

        Claim__c cl = new Claim__c(Name='000049', PolicyHolder__c=accs[0].Id);
        insert cl;

        List<Case> cases = TestDataFactory.generateCasesForEachAccount(accs, 3);
        cases[0].PolicyNum__c = poliza1[0].Name;
        cases[1].CreatedOffer__c = opp[0].Name;
        cases[2].ClaimId__c = cl.Id;
        insert cases;

        Task tk = new Task(WhatId=cases[0].Id, Status='3');
        insert tk;

        EmailMessage em = new EmailMessage(RelatedToId=cases[0].Id, ParentId=cases[0].Id, ActivityId=tk.Id);
        insert em;

        List<Account> accs2 = TestDataFactory.generateAccounts(LEGAL_ENTITY, ACCOUNT_BCUSTOMER, 1);
        for(Integer i = 0; accs2.size() < i; i++){
            accs2[i].FirstName = 'Test Account';
            accs2[i].LastName = '-001';
            accs2[i].RecordTypeId = BCustomerRecordTypeId;
        }
        insert accs2;

        Contact cont = new Contact(LastName='Contact Test', AccountId=accs2[0].Id);
        insert cont;

        Campaign camp = new Campaign(Name='Campaña test', LegalEntity__c='001');
        insert camp;

        CampaignMember cm = new CampaignMember(ContactId=cont.Id, CampaignId=camp.Id);
        insert cm;
    }

    /*************************************************
     * PROPAGATE BLOCKED
     ************************************************/

    @isTest
    private static void test_blockFieldPropagation_ContactBlocked()
    {
        List<Account> allTestAccounts = [SELECT Id FROM Account];

        for(Account currentTestAccount : allTestACcounts)
        {
            currentTestAccount.blocked__c = true;
        }

        update allTestAccounts;

        Test.startTest();
        Database.executeBatch(new GDPRPropagateBlockedFieldBatch(false));
        Test.stopTest();

        for(Account testAccount : [SELECT Blocked__c FROM Account])
        {
            Assert.isTrue(testAccount.Blocked__c,'No se ha asignado el campo blocked a true en las cuentas');
        }

        for(Contact testContact : [SELECT Blocked__c FROM Contact])
        {
            Assert.isTrue(testContact.Blocked__c,'No se ha asignado el campo blocked a true en los contactos');
        }
    }

    @isTest
    private static void test_blockFieldPropagation_CampaignMemberBlocked()
    {
        List<Account> allTestAccounts = [SELECT Id FROM Account];

        for(Account currentTestAccount : allTestACcounts)
        {
            currentTestAccount.blocked__c = true;
        }

        update allTestAccounts;

        List<Contact> allTestContacts = [SELECT Id FROM Contact];

        for(Contact currentTestContact : allTestContacts)
        {
            currentTestContact.Blocked__c = true;
        }

        update allTestContacts;

        Test.startTest();
        Database.executeBatch(new GDPRPropagateBlockedFieldBatch('2', false));
        Test.stopTest();

        for(CampaignMember testCampaignMember : [SELECT Blocked__c FROM CampaignMember])
        {
            Assert.isTrue(testCampaignMember.Blocked__c, 'No se ha asignado el campo blocked a true en los miembros de campaña');
        }
    }

    @isTest
    private static void test_blockFieldPropagation_OpportunityBlocked()
    {
        List<Account> allTestAccounts = [SELECT Id FROM Account];

        for(Account currentTestAccount : allTestACcounts)
        {
            currentTestAccount.blocked__c = true;
        }

        update allTestAccounts;

        Test.startTest();
        Database.executeBatch(new GDPRPropagateBlockedFieldBatch('3', false));
        Test.stopTest();

        for(Opportunity testOpportunity : [SELECT Blocked__c FROM Opportunity])
        {
            Assert.isTrue(testOpportunity.Blocked__c, 'No se ha asignado el campo blocked a true en las ofertas');
        }
    }

    /**
     *
     */
    @isTest
    private static void test_blockFieldPropagation_CaseAndEmailMessageBlocked()
    {
        List<Account> allTestAccounts = [SELECT Id FROM Account];

        for(Account currentTestAccount : allTestACcounts)
        {
            currentTestAccount.blocked__c = true;
        }

        update allTestAccounts;

        Test.startTest();
        Database.executeBatch(new GDPRPropagateBlockedFieldBatch('4', false));
        Test.stopTest();

        for(Case testCase : [SELECT Blocked__c FROM Case])
        {
            Assert.isTrue(testCase.Blocked__c, 'No se ha asignado el campo blocked a true en los casos');
        }

        for(EmailMessage testEmailmessage : [SELECT Blocked__c FROM EmailMessage])
        {
            Assert.isTrue(testEmailmessage.Blocked__c, 'No se ha asignado el campo blocked a true en los Email Message');
        }
    }

    /*************************************************
     * PROPAGATE ANONYMOUS
     ************************************************/

     @isTest
     private static void test_anonymousFieldPropagation_Contact()
     {
         List<Account> allTestAccounts = [SELECT Id FROM Account];

         for(Account currentTestAccount : allTestACcounts)
         {
             currentTestAccount.Anonymized__c = true;
         }

         update allTestAccounts;

         Test.startTest();
         Database.executeBatch(new GDPRPropagateBlockedFieldBatch(true));
         Test.stopTest();

         for(Account testAccount : [SELECT Anonymized__c FROM Account])
         {
             Assert.isTrue(testAccount.Anonymized__c,'No se ha asignado el campo anonymized a true en las cuentas');
         }

         for(Contact testContact : [SELECT Anonymized__c FROM Contact])
         {
             Assert.isTrue(testContact.Anonymized__c,'No se ha asignado el campo anonymized a true en los contactos');
         }
     }

     @isTest
     private static void test_anonymousFieldPropagation_CampaignMember()
     {
         List<Account> allTestAccounts = [SELECT Id FROM Account];

         for(Account currentTestAccount : allTestACcounts)
         {
             currentTestAccount.Anonymized__c = true;
         }

         update allTestAccounts;

         List<Contact> allTestContacts = [SELECT Id FROM Contact];

         for(Contact currentTestContact : allTestContacts)
         {
             currentTestContact.Anonymized__c = true;
         }

         update allTestContacts;

         Test.startTest();
         Database.executeBatch(new GDPRPropagateBlockedFieldBatch('3', true));
         Test.stopTest();

         for(CampaignMember testCampaignMember : [SELECT Anonymized__c FROM CampaignMember])
         {
             Assert.isTrue(testCampaignMember.Anonymized__c, 'No se ha asignado el campo anonymized a true en los miembros de campaña');
         }
     }

     @isTest
     private static void test_anonymousFieldPropagation_Opportunity()
     {
         List<Account> allTestAccounts = [SELECT Id FROM Account];

         for(Account currentTestAccount : allTestACcounts)
         {
             currentTestAccount.Anonymized__c = true;
         }

         update allTestAccounts;

         Test.startTest();
         Database.executeBatch(new GDPRPropagateBlockedFieldBatch('4', true));
         Test.stopTest();

         for(Opportunity testOpportunity : [SELECT Anonymized__c FROM Opportunity])
         {
             Assert.isTrue(testOpportunity.Anonymized__c, 'No se ha asignado el campo anonymized a true en las ofertas');
         }
     }

     /**
      *
      */
     @isTest
     private static void test_anonymousFieldPropagation_CaseAndEmailMessage()
     {
         List<Account> allTestAccounts = [SELECT Id FROM Account];

         for(Account currentTestAccount : allTestACcounts)
         {
             currentTestAccount.Anonymized__c = true;
         }

         update allTestAccounts;

         Test.startTest();
         Database.executeBatch(new GDPRPropagateBlockedFieldBatch('5', true));
         Test.stopTest();

         List<Case> testCases = [SELECT Anonymized__c FROM Case];

         for(Case testCase : testCases)
         {
             Assert.isTrue(testCase.Anonymized__c, 'No se ha asignado el campo anonymized a true en los casos');
         }

         for(EmailMessage testEmailmessage : [SELECT Anonymized__c FROM EmailMessage where parentId IN :testCases])
         {
             Assert.isTrue(testEmailmessage.Anonymized__c, 'No se ha asignado el campo anonymized a true en los Email Message');
         }

         for(EmailMessage allMail : [SELECT HTmlBody FROM EmailMessage])
         {
            System.debug(allMail.HTMLBody);
         }
     }
}