force-app/zurich-base/main/default/objects/Account/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Primer nivel de restricción de acceso</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/INFOBusinessCode__c.field-meta.xml
<CustomField>
    <fullName>INFOBusinessCode__c</fullName>
    <externalId>true</externalId>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/IntermediaryGroup__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referencia al registro de Cuenta Agrupación</description>
    <label>Intermediary Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Solo se puede seleccionar una cuenta de tipo Agrupación Mediador</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Intermediary Group</relationshipLabel> 
    <relationshipName>IntermediaryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/IsAccountZDA__c.field-meta.xml
<CustomField>
    <fullName>IsAccountZDA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Utilizado para saber si una cuenta tiene pólizas u ofertas de ZDA</description>
    <label>IsAccountZDA</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Primer nivel de restricción de acceso</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>(OCS). Identifica el código de negocio en INFO</description>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/InfoPolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>InfoPolicyNumber__c</fullName>
    <description>(OCS). Identificador único de la póliza.</description>
    <externalId>true</externalId>
    <label>INFO Policy Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica el nombre del intermediario ya sea partner o mediador</description>
    <label>Intermediary</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/LastAccountId__c.field-meta.xml
<CustomField>
    <fullName>LastAccountId__c</fullName>
    <description>[ZRM] campo que acompaña a LastDateIntermediaryOrAccountChange__c indicando el valor anterior de IntermediaryId__c o AccountId cuando se han actualizado. Para account solo se escribe si el cambio es de cliente a cliente</description>
    <label>Last Account</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/LastDateIntermediaryOrAccountChange__c.field-meta.xml
<CustomField>
    <fullName>LastDateIntermediaryOrAccountChange__c</fullName>
    <description>[ZRM] Guardamos la fecha de la ultima modificación que ha sufrido el campo IntermediaryId__c o el campo AccountId para que el proceso batch recalcule la visibilidad de los ATM de la comunidad</description>
    <label>Last Date Intermediary Or Account Change</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/OpportunityName__c.field-meta.xml
<CustomField>
    <fullName>OpportunityName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica la oferta a la que se encuentra asociada la póliza</description>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Partner)</relationshipLabel>
    <relationshipName>PoliciesPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/PolicyHolder__c.field-meta.xml
<CustomField>
    <fullName>PolicyHolder__c</fullName>
    <description>(OCS). Identifica el tomador de la póliza</description>
    <label>Policy Holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Policy Holder)</relationshipLabel>
    <relationshipName>PoliciesHolder</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/PolicyStatus__c.field-meta.xml
<CustomField>
    <fullName>PolicyStatus__c</fullName>
    <description>(OCS). Indica si la póliza está Cancelada, rehabilitada, saneada…</description>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/PotentialMatch__c.field-meta.xml
<CustomField>
    <fullName>PotentialMatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Potential Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>(OCS). Identifica el ámbito a utilizar para la colaboración del registro</description>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZE</fullName>
                <label>Zurich Empresas</label>
            </value>
            <value>
                <fullName>ZEO</fullName>
                <label>Zurich Empresas Orange</label>
            </value>
            <value>
                <fullName>Z</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>ZEB</fullName>
                <label>Zurich Empresas Brokers</label>
            </value>
            <value>
                <fullName>ZDA</fullName>
                <label>Zurich ZDA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/ScopeId__c.field-meta.xml
<CustomField>
    <fullName>ScopeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica el ámbito al que se encuentra asociada la póliza</description>
    <label>Scope Name</label>
    <referenceTo>Scope__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/VisibilityRetry__c.field-meta.xml
<CustomField>
    <fullName>VisibilityRetry__c</fullName>
    <description>[ZRM] en caso de error al procesar los cambios de mediador o cliente por el batch, se indica este número de reintentos para tener rastreabilidad de estos problemas y definir un número máximo de intentos para dicho registro y no se acumulen indefinidamente errores</description>
    <label>Visibility Retry</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/ZRMMovementType__c.field-meta.xml
<CustomField>
    <fullName>ZRMMovementType__c</fullName>
    <description>[ZRM] campo que acompaña a LastDateIntermediaryOrAccountChange__c. Indica el tipo de movimiento que ha sufrido el registro para que el proceso batch identifque el cambio y haga los cálculos apropiados de ATM</description>
    <label>MovementType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IntermediaryChange</fullName>
            </value>
            <value>
                <fullName>AccountChange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a borrar debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Scope_Setting__mdt/Scope_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Información sobre los scopes de Zurich Empresas para crear los registros en función del campo BusinessCode recibido en el formulario web</description>
    <label>Scope Setting</label>
    <pluralLabel>Scope Settings</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope_Setting__mdt/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/classes/PolicyUtil.cls
public class PolicyUtil
{
    private static final string CLASS_NAME = 'PolicyUtil';
    private static final string AGENTEVENTA_PROFILE = 'Agente Ventas';
    private static final string AGENTEVENTAAGR_PROFILE = 'Agente Ventas - AGR';
    public static Map<String, String> mapBusinessCodes; // Mapa que va a contener la relación entre los Business codes y los scopes de las Polizas
    private static final string ZRM_SCOPE = 'Ventas'; //Scope de las polizas de ZRM
    private static final string ZDA_SCOPE = 'ZDA'; 

    public static List<Account> accountsToMarkClientZDA = new List<Account>();

    /**
     * Método que rellena el mapa que contiene la relación entre Business Code y Scopes
     *
     * @author Iván García
     * @date 08/04/2024
     */
    public static void fillMapBusinessCode ()
    {
        mapBusinessCodes = new Map<String, String>();
        List<Scope_Setting__mdt> scopeSettingsMapping = Scope_Setting__mdt.getAll().values();

        for(Scope_Setting__mdt scope : scopeSettingsMapping)
        {
            mapBusinessCodes.put(scope.BusinessCode__c, scope.Scope__c);
        }
    }

    /**
     * @description Método que marca la poliza para ser revisada por un
     * proceso asíncrono en busca de coincidencias, siempre y cuando pertenezca a ZRM.
     *
     * @author igarcia
     * @date 09-04-2024
     * @param List<Policy> Lista de polizas que van a ser insertadas
     **/
    public static void identifyPotentialMatches(List<Policy__c> newList)
    {
        for (Policy__c policy : newList)
        {

            //Se comprueba que el registro pertenece al aplicativo ZRM y no tenga ninguna oferta enlazada
            if ( String.isBlank(policy.OpportunityName__c) &&
                 ( mapBusinessCodes?.get(policy.BusinessCode__c) == (ZRM_SCOPE) || String.isBlank(policy.BusinessCode__c) ) )
            {
                policy.PotentialMatch__c = true;
            }
        }
    }

    /**
     * Método que controla la generación del scope correspondiente
     * Actualmente solo se generá scope para pólizas que provengan de INFO
     *
     * @author adelgado
     * @date 08/01/2021
     *
     * @change 10/05/2021 - nts (agonzalezisasi) - OCS-1798 - Se incluye el calculo de la cuenta Partner de la poliza
     *         como evento.
     */
    public static void generateScope(List<Policy__c> newList)
    {
        List<Policy__c> polToGenerateScope = new List<Policy__c>();
        List<Policy__c> polToGeneratePartner = new List<Policy__c>();

        for(Policy__c policy : newList)
        {
            if( String.isNotBlank(policy.InfoPolicyNumber__c) && policy.ScopeId__c == null && policy.PolicyHolder__c != null)
            {
                polToGenerateScope.add(policy);
            }

            if( String.isNotBlank(policy.BusinessCode__c) && policy.Partner__c == null )
            {
                polToGeneratePartner.add(policy);
            }
        }

        if( !polToGenerateScope.isEmpty() )
        {
            GenerateScopeUtil.generateScopeEvents('PolicyHolder__c', 'BusinessCode__c', polToGenerateScope);
        }

        if( !polToGeneratePartner.isEmpty() )
        {
            GenerateScopeUtil.generatePartnerEvents(
                Policy__c.BusinessCode__c.getDescribe().getName(),
                Policy__c.Partner__c.getDescribe().getName(),
                Account.getSObjectType().getDescribe().getName(),
                Account.INFOBusinessCode__c.getDescribe().getName(),
                polToGeneratePartner
                );
        }
    }

    /**
     * Informa los siguientes campos para pólizas en las que se haya cambiado el mediador o cliente
     *
     * @author fpalomo
     * @date 08/04/2024
     */
    public static void handlePolicyHolderOrIntermediaryChange(List<Policy__c> newList, Map<Id, Policy__c> oldMap)
    {
        for(Policy__c policyNew : newList)
        {   
            if (String.isNotEmpty(policyNew.IntermediaryId__c) && String.isNotEmpty(policyNew.PolicyHolder__c) &&
                    ( 'A'.equals(policyNew.PolicyStatus__c) || 'V'.equals(policyNew.PolicyStatus__c) )
                    && !policyNew.Blocked__c && !policyNew.Anonymized__c) // solo procesamos cambios sobre polizas no bloqueadas y en vigor o anuladas que tengan mediador y cliente
            {
                Policy__c policyOld = oldMap.get(policyNew.Id);
    
                // AccountId
                if (policyNew.PolicyHolder__c != policyOld.PolicyHolder__c)
                {
                    policyNew.ZRMMovementType__c = Batch_IntermediaryOrAccountChangeUtil.MOVEMENT_TYPE_CAMBIO_CLIENTE;
                    policyNew.LastAccountId__c = policyOld.PolicyHolder__c;
                }
    
                // Mediador
                else if (policyOld.IntermediaryId__c != policyNew.IntermediaryId__c)
                {
                    policyNew.ZRMMovementType__c = Batch_IntermediaryOrAccountChangeUtil.MOVEMENT_TYPE_CAMBIO_MEDIADOR;
                    policyNew.LastAccountId__c = policyOld.IntermediaryId__c; 
                }
    
                // Estos dos campos se rellenan de la misma forma para cualquiera de los dos casos posibles
                if (policyOld.LastAccountId__c != policyNew.LastAccountId__c)
                {
                    policyNew.LastDateIntermediaryOrAccountChange__c = System.today();
                    policyNew.VisibilityRetry__c = 1; // Inicializo el numero de reintentos en 1 ya que el 0 es para identificar ok
                }                
            }
        }
    }
    
    /******************************* Métodos principales Visibilidad ZRM ******************************************************/

    /**
     * Metodo que genera atm cuando llega una nueva poliza en vigor o anulada para los usuarios ZRM
     *
     *
     * @author dmunoz
     * @date 12/02/2024
     */
    public static void zrmVisibilityNewPolicy(List<Policy__c> newList)
    {

        try
        {
            // 1º obtener los mediadores y clientes de las polizas en vigor <IntermdiaryId__c, List<PolicyHolder__c>>
            Map<String, Set<String> > policyHoldersByIntermediaryMap = ZRMPolicyVisibilityUtil.getPolicyHoldersByIntermediaryMap(newList);

            if ( policyHoldersByIntermediaryMap != null && !policyHoldersByIntermediaryMap.isEmpty() )
            {
                // 2º Obtener las agrupaciones de los mediadores para obtener los usuarios agr de esos mediadores <IntermdiaryId__c, IntermediaryGroup__c>
                Map<String, String> intermediaryWithIntermediariesGroupsIdMap = ZRMPolicyVisibilityUtil.getIntermediaryGroupIdMap( policyHoldersByIntermediaryMap.keySet() );

                // 3º Obtener los usuarios de los mediadores <IntermediaryId, List<UserId>
                Map<String, List<String> > intermediariesWithUsers = ZRMPolicyVisibilityUtil.getIntermediariesUsers(policyHoldersByIntermediaryMap.keySet(), intermediaryWithIntermediariesGroupsIdMap);

                // 4º Insertar atm y activar registros de competencia y cuentas relacionadas
                ZRMPolicyVisibilityUtil.newPolicyInsertATMs(policyHoldersByIntermediaryMap, intermediariesWithUsers);
            }
        }
        catch (Exception e)
        {
            ErrorLogUtil.commitError(e, CLASS_NAME);
        }
    }

    /**
    * @description Método que obtiene las cuentas para marcar a true que una cuenta es de ZDA 
    * en caso de que la póliza pertenezca a ZDA.Es decir, que su business code sea de ZDA. 
    *
    * @author aberuete
    * @date 16-05-2024 
    * @param List<Policy__c> newPolicies : Lista de pólizas que van a ser insertadas o actualizas
    **/
    public static void getAccountsZDA(List<Policy__c> newPolicies)
    {
        Set<String> accountsRelatedToPoliciesZDA = new Set<String> ();

        for (Policy__c newPolicy : newPolicies)
        {
            if (newPolicy.PolicyHolder__c != null && newPolicy.BusinessCode__c != null && mapBusinessCodes?.get(newPolicy.BusinessCode__c) == ZDA_SCOPE)
            {
                accountsRelatedToPoliciesZDA.add(newPolicy.PolicyHolder__c); 
            }
        }

        List<Account> accountsToUpdate = new AccountsSelector().selectByIdAndAccountZDA(accountsRelatedToPoliciesZDA, false);
        
        for (Account account : accountsToUpdate)
        {
            account.IsAccountZDA__c = true;
            accountsToMarkClientZDA.add(account);
        }
    }

    /**
    * @description Método que actualiza las cuentas para marcar a true que una cuenta es de ZDA 
    * en caso de que la póliza pertenezca a ZDA.Es decir, que su business code sea de ZDA. 
    *
    * @author aberuete
    * @date 16-05-2024 
    * @param List<Policy__c> newPolicies : Lista de pólizas que van a ser insertadas o actualizas
    * @param Map<Id,Policy__c> oldPolicyMap: Mapa de pólizas que guarda los valores antes de ser actualizada la oportunidad
    **/
    public static void updateAccountsToMarkAccountZDA ()
    {
        List<String> msgErrores = new List<String>();

        if( !accountsToMarkClientZDA.isEmpty() )
        {
            try
            {
                Database.SaveResult [] resultList = Database.update(accountsToMarkClientZDA, false);

                for (Database.SaveResult result: resultList )
                {
                    if( !result.isSuccess() )
                    {
                        for ( Database.Error error :result.getErrors() )
                        {
                            msgErrores.add( error.getStatusCode() + ': ' + error.getMessage() );
                        }
                    }
                }
                if ( !msgErrores.isEmpty() )
                {
                    ErrorLogUtil.commitError( ErrorLogUtil.ERROR_LEVEL_ERROR,'Se ha producido un error actualizando las cuentas relacionadas con las pólizas',PolicyUtil.class.getName(),( String.join(msgErrores,'\n') ) );
                }
            }
            catch (Exception e)
            {
                ErrorLogUtil.commitError( e, PolicyUtil.class.getName() );
            }
        }
    }
}