force-app/zurich-base/main/default/objects/Account/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Primer nivel de restricción de acceso</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generated to identify a customer</description>
    <externalId>true</externalId>
    <inlineHelpText>Code that IBA generated to identify a customer</inlineHelpText>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/INFOCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>INFOCustomerNumber__c</fullName>
    <description>(OCS/ZE). Destinado a almacenar el código de filiación proveniente del transaccional INFO</description>
    <externalId>true</externalId>
    <label>Affiliation Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/IntermediaryGroup__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referencia al registro de Cuenta Agrupación</description>
    <label>Intermediary Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Solo se puede seleccionar una cuenta de tipo Agrupación Mediador</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Intermediary Group</relationshipLabel> 
    <relationshipName>IntermediaryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LastIntermediaryGroup__c.field-meta.xml
<CustomField>
    <fullName>LastIntermediaryGroup__c</fullName>
    <description>ZRM: Guardamos en este campo en caso de baja de un mediador de una agrupación la agrupación a la que pertenecía para hacer un recálculo de visibilidad de la anterior ya que si tuviera usuarios AGR debería de hacerse un recálculo de la visibilidad completa</description>
    <label>Last Intermediary Group</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LastIntermediaryGroupChange__c.field-meta.xml
<CustomField>
    <fullName>LastIntermediaryGroupChange__c</fullName>
    <description>[ZRM] informo este campo cuando se ha modificado la relación entre un mediador y el campo agrupación IntermediaryGroup__c. Se informa a partir de la actualización de agrupaciones por external request de INFO</description>
    <label>Last Intermediary Group Change</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LeadBusinessCode__c.field-meta.xml
<CustomField>
    <fullName>LeadBusinessCode__c</fullName>
    <description>ZE - Campaña Telemarketing, contiene el código del metadato Scope Setting para Zurich Empresas (3200012491)</description>
    <label>Lead Business Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LeadSource__c.field-meta.xml
<CustomField>
    <fullName>LeadSource__c</fullName>
    <description>ZE - Campaña Telemarketing. Sirve para filtrar el registro en el trigger AccountUtil y generar Scope para dichas cuentas. El filtro es &apos;Telemarketing&apos;</description>
    <label>Lead Telemarketing Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Masterpolicy__c.field-meta.xml
<CustomField>
    <fullName>Masterpolicy__c</fullName>
    <description>Partner identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>Masterpolicy</inlineHelpText>
    <label>Código partner</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/NationalId__c.field-meta.xml
<CustomField>
    <fullName>NationalId__c</fullName>
    <description>(OCS/ZE). Identificador nacional del cliente</description>
    <label>National ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>Comprende aquellos posibles clientes todavía no existentes en el sistema transaccional</description>
    <label>Lead</label>
</RecordType>

force-app/zurich-base/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a borrar debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Último nivel de restricción de acceso. Anonimización de los datos sensibles o de identificación.</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generates to identify a customer. As for life and non-life is the same number, for life record type, it will have prefix LIFE-XXX and for non-life GI-XXX</description>
    <externalId>true</externalId>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MasterPolicy__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Specifies if the contact comes from a partner. Linked to the partner acccount.</description>
    <label>Masterpolicy</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MasterPolicyDesc__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyDesc__c</fullName>
    <description>Not visible field in the page layout and used to copy its value to account Name field after parsing it in the parser.</description>
    <label>Masterpolicy description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MasterPolicyNum__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyNum__c</fullName>
    <label>Masterpolicy Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Order/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <label>Customer Num</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/Masterpolicy__c.field-meta.xml
<CustomField>
    <fullName>Masterpolicy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Masterpolicy</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Polizas</relationshipLabel>
    <relationshipName>Polizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/MasterPolicyDescr__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyDescr__c</fullName>
    <label>Masterpolicy description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/MasterPolicyNum__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyNum__c</fullName>
    <label>Masterpolicy Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/PolicyNum__c.field-meta.xml
<CustomField>
    <fullName>PolicyNum__c</fullName>
    <externalId>true</externalId>
    <label>Número de la póliza</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/QuoteEntry__c.field-meta.xml
<CustomField>
    <fullName>QuoteEntry__c</fullName>
    <externalId>true</externalId>
    <label>Quote entry</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/ZRMLeadATM__e/ZRMLeadATM__e.object-meta.xml
<CustomObject>
    <description>Evento que se lanza cuando se inserta un lead desde el botón nuevo de la comunidad ZRM para generar los atm y modificar el owner a un usuario admin</description>
    <label>ZRM Lead ATM</label>
    <pluralLabel>ZRM Leads ATM</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/ZRMLeadATM__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Id del lead a insertar el ATM</description>
    <label>AccountId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ZRMLeadATM__e/fields/ZRMUserId__c.field-meta.xml
<CustomField>
    <fullName>ZRMUserId__c</fullName>
    <description>El id del usuario que ha pulsado el botón nuevo</description>
    <label>ZRM User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/classes/AccountUtil.cls
/**
**
* @author nbizkarra
* @date 01/04/2020
*/
public class AccountUtil
{

    public static final String CUSTOMER_RT_DEVELOPER_NAME = GlobalConfigUtil.getGlobalConfigurationValue('Account_RecordType_Customer');
    public static final String INTERMEDIARY_RT_DEVELOPER_NAME = GlobalConfigUtil.getGlobalConfigurationValue('Account_RecordType_Intermediary');

    /**
     * Método que crea un nuevo partner si no existe y lo asocia al contacto
     * @author nbizkarra
     * @date 23/04/2020
     */
    public static void associatePartner(
        Contact customer,
        Map<String, Account> mapPartners,
        Map<String, Contact> contactsToUpdateWithPartner,
        Map<String, Account> partnersToUpdateList,
        User recordOwner
        )
    {
        Account partnerSF = mapPartners.get(customer.MasterPolicyNum__c);

        if ( String.isBlank(customer.MasterPolicyDesc__c) )
        {
            customer.MasterPolicyDesc__c = Label.LeadLastName;
        }

        if (partnerSF != null)
        {

            customer.MasterPolicy__c = partnerSF.Id;
        }
        else
        {

            Account newPartner = new Account(
                Name = customer.MasterPolicyDesc__c,
                Masterpolicy__c = customer.MasterPolicyNum__c,
                OwnerId = recordOwner.id,
                RecordTypeId = SystemUtil.getAccountRecordTypeIdByName(Label.Partner)
                );
            // nts (agonzalezisasi) - 03/11/2020 - Inlcude IBA Multi-Partner logic
            if( !String.isBlank(customer.Partner__c) )
            {
                newPartner.Partner__c = customer.Partner__c;
            }

            Account partnerRef = new Account(
                Masterpolicy__c = customer.MasterPolicyNum__c
                );

            if ( !partnersToUpdateList.containsKey(newPartner.Masterpolicy__c) )
            {
                partnersToUpdateList.put(newPartner.Masterpolicy__c, newPartner);
            }

            customer.MasterPolicy__r = partnerRef;
        }

        contactsToUpdateWithPartner.put(customer.CustomerNum__c, customer);
    }

    /**
     * Método que crea un nuevo partner si no existe y lo asocia a la póliza o quote
     * @author nbizkarra
     * @date 23/04/2020
     */
    public static void associatePartnerToOrder(
        Order order,
        Map<String, Account> mapPartners,
        Map<String, Order> ordersToUpdateWithPartner,
        Map<String, Account> partnersToUpdateList,
        User recordOwner
        )
    {
        Account partnerSF = mapPartners.get(order.MasterPolicyNum__c);

        if ( String.isBlank(order.MasterPolicyDescr__c) )
        {
            order.MasterPolicyDescr__c = Label.LeadLastName;
        }

        if (partnerSF != null)
        {

            order.MasterPolicy__c = partnerSF.Id;
        }
        else
        {

            Account newPartner = new Account(
                Name = order.MasterPolicyDescr__c,
                Masterpolicy__c = order.MasterPolicyNum__c,
                OwnerId = recordOwner.id,
                RecordTypeId = SystemUtil.getAccountRecordTypeIdByName(Label.Partner)
                );
            Account partnerRef = new Account(
                Masterpolicy__c = order.MasterPolicyNum__c
                );

            if ( !partnersToUpdateList.containsKey(newPartner.Masterpolicy__c) )
            {
                partnersToUpdateList.put(newPartner.Masterpolicy__c, newPartner);
            }

            order.MasterPolicy__r = partnerRef;
        }
        //Si es quote, key=quoteEntry, si es poliza, key=policyNum
        String key;
        if (order.PolicyNum__c != null)
        {
            key = order.PolicyNum__c;
        }
        else
        {
            key = order.QuoteEntry__c;
        }

        ordersToUpdateWithPartner.put(key, order);
    }

    /**
     * Método que controla la generación del scope correspondiente
     * Actualmente solo se generá scope para Accounts que provengan de INFO
     *
     * @author adelgado
     * @date 07/12/2020
     * @edit 30/7/2021 ZE Campaña Telemarketing
     */
    public static void generateScope(List<Account> newList)
    {
        List<Account> accountsToGenerateScope = new List<Account>();
        List<Account> accountsTelemarketingToGenerateScope = new List<Account>();

        for(Account account : newList)
        {
            if( String.isNotBlank(account.INFOCustomerNumber__c) )
            {
                accountsToGenerateScope.add(account);
            }
            else if(String.isNotBlank(account.LeadSource__c) && account.LeadSource__c == 'Telemarketing')
            {//ZE Campaña Telemarketing
                accountsTelemarketingToGenerateScope.add(account);
            }
        }

        if( !accountsToGenerateScope.isEmpty() )
        {
            GenerateScopeUtil.generateScopeEvents('Id', null, accountsToGenerateScope);
        }
        //ZE Campaña Telemarketing
        if( !accountsTelemarketingToGenerateScope.isEmpty() )
        {//BusinessCode: 3200012491
            GenerateScopeUtil.generateScopeEvents('Id', 'LeadBusinessCode__c', accountsTelemarketingToGenerateScope);
        }
    }

    /**
     * Método que devuelve un mapa de cuentas por cif a partir de una lista de cuentas
     * @author jjuaristi@seidor.es
     * @date 20/10/2022
     * @param Lista de cuentas
     * @return Mapa de cuentas por CIF
     */
    public static Map<String, Account> generateMapByCif(List<Account> accounts)
    {
        Map<String, Account> mapAccountsToRelateByCIF = new Map<String,Account>();
        if( accounts != null && !accounts.isEmpty() )
        {
            //Mapa para identificar cada cuenta con su cif

            // Se recorre la lista de cuentas para no tener que recorrerla una vez por cada caso
            for(Account currentAccount : accounts)
            {
                mapAccountsToRelateByCIF.put(currentAccount.NationalId__c, currentAccount);
            }
        }
        return mapAccountsToRelateByCIF;
    }


    /**
     * Método que resuelve la visibilidad para los cambios de mediador de agrupación, alta a una agrupacion o baja de una agrupación
     * @author dmunoz
     * @date 14/2/2024
     */
    public static void zrmVisibility(List<Account> accountsTrigger, Map<Id,Account> oldMap)
    {
        Date todayDate = Date.today();

        for (Account account: accountsTrigger)
        {
            if ( esMediador(account) )
            {
                if ( esAltaAgrupacion(account, oldMap) )
                {
                    account.LastIntermediaryGroupChange__c = todayDate;
                    account.LastIntermediaryGroup__c = '';
                }
                else if ( esBajaAgrupacion(account, oldMap) || esCambioAgrupacion(account, oldMap) )
                {
                    account.LastIntermediaryGroupChange__c = todayDate;
                    account.LastIntermediaryGroup__c = oldMap.get(account.Id).IntermediaryGroup__c;
                }
            }
        }
    }


    /**
     * Se ha de insertar atm para lead si los está insertando un usuario ZRM desde el boton nuevo de la comunidad
     * @author dmunoz
     * @date 06/03/2024
     */

    public static void zrmNewLeadVisibility(List<Account> newList)
    {

        String leadRT = ( new AccountsSelector() ).rtLeadId;

        // Recorremos los leads que no esten ni bloqueados ni anonimizados
        List<Account> leadsToProcessList = new List<Account>();
        for (Account account: newList)
        {
            if (account.RecordTypeId.equals(leadRT) && !account.Blocked__c && !account.Anonymized__c)
            {
                leadsToProcessList.add(account);
            }
        }

        if ( !leadsToProcessList.isEmpty() )
        {
            // 1º informacion del usuario logueado - solo ejecutamos este codigo si es usuario ZRM
            User loggedUser = ( new UsersSelector() ).findUserIntermediaryByUserId( UserInfo.getUserId() );

            if (loggedUser.Profile.Name == ProfilesSelector.PROFILE_AGENTE_VENTAS || loggedUser.Profile.Name == ProfilesSelector.PROFILE_AGENTE_VENTAS_AGR)
            {

                // genero los eventos y los publico
                for (Account lead: leadsToProcessList)
                {
                    Eventbus.publish(
                        new ZRMLeadATM__e(
                            AccountId__c = lead.Id,
                            ZRMUserId__c = loggedUser.Id
                            )
                        );
                }

            }
        }
    }


    /****************** Metodos Visibilidad ****************************************/
    /**
     * Comprobamos si el registro es un mediador, no se procesa otro tipo de registro
     * @author dmunoz
     * @date 14/2/2024
     */
    private static Boolean esMediador(Account account)
    {
        Boolean result = false;

        if ( new AccountsSelector().rtIntermediaryId.equals(account.RecordTypeId) )
        {
            result = true;
        }

        return result;
    }

    /**
     * Comprobamos si el movimiento es de un mediador haciendo un alta a una agrupación (no cambio)
     * @author dmunoz
     * @date 14/2/2024
     */
    private static Boolean esAltaAgrupacion(Account account, Map<Id,Account> oldMap)
    {
        Boolean result = false;
        String oldIntermediaryGroup = oldMap.get(account.Id).IntermediaryGroup__c;

        // si la relacion de agrupación pasa de vacio a un valor, lo añadimos a la lista de alta
        if (oldIntermediaryGroup == null && account.IntermediaryGroup__c != null)
        {
            result = true;
        }

        return result;
    }

    /**
     * Comprobamos si el movimiento es de un mediador haciendo un cambio de agrupación
     * @author dmunoz
     * @date 14/2/2024
     */
    private static Boolean esCambioAgrupacion(Account account, Map<Id,Account> oldMap)
    {
        Boolean result = false;
        String oldIntermediaryGroup = oldMap.get(account.Id).IntermediaryGroup__c;

        // si la relacion de agrupación cambia, lo añadimos a la lista de cambio
        if ( oldIntermediaryGroup != null && account.IntermediaryGroup__c != null && !account.IntermediaryGroup__c.equals(oldIntermediaryGroup) )
        {
            result = true;
        }

        return result;
    }

    /**
     * Comprobamos si el movimiento es de un mediador haciendo una baja a una agrupación (no cambio)
     * @author dmunoz
     * @date 14/2/2024
     */
    private static Boolean esBajaAgrupacion(Account account, Map<Id,Account> oldMap)
    {
        Boolean result = false;
        String oldIntermediaryGroup = oldMap.get(account.Id).IntermediaryGroup__c;

        // si la relacion de agrupación pasa de un valor a vacio, lo añadimos a la lista de baja
        if (oldIntermediaryGroup != null && account.IntermediaryGroup__c == null)
        {
            result = true;
        }

        return result;
    }
}