force-app/zurich-base/main/default/objects/Account/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Primer nivel de restricción de acceso</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/IntermediaryGroup__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referencia al registro de Cuenta Agrupación</description>
    <label>Intermediary Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Solo se puede seleccionar una cuenta de tipo Agrupación Mediador</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Intermediary Group</relationshipLabel> 
    <relationshipName>IntermediaryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/IntermediaryVisibilityAcc__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryVisibilityAcc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intermediary Visibility Acc</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Intermediary Visibility)</relationshipLabel>
    <relationshipName>IntermediaryVisibilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/IntermediaryVisibilityForm__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryVisibilityForm__c</fullName>
    <description>Campo fórmula para recalcular visibilidad en ZRM</description>
    <formula>IF(Blocked__c, 
	IF(ISBLANK(IntermediaryVisibilityAcc__c), 
		&apos;AccountBlocked&apos;, 
		null
	),
	IF(IntermediaryVisibilityAcc__c = Intermediary_Name__c, 
		IF(ISBLANK(IntermediaryVisibilityAcc__c), 
			&apos;WithoutIntermediary&apos;, 
			&apos;CurrentIntermediary&apos;
		),
		IF(IntermediaryVisibilityAcc__c = Intermediary_Name__r.IntermediaryGroup__r.IntermediaryWithUser__c, 
		&apos;MainIntermediary&apos;,
		null
		)
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Intermediary Visibility Form</label>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/IntermediaryWithUser__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryWithUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referencia al registro de Cuenta Mediador asociado a la licencia de usuario compartida (si aplica).</description>
    <label>Intermediary With User</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Main Intermediaries</relationshipLabel>
    <relationshipName>MainIntermediaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/PersonLeadSource__c.field-meta.xml
<CustomField>
    <fullName>PersonLeadSource__c</fullName>
    <defaultValue>&apos;Manual&apos;</defaultValue>
    <label>Person Lead Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/PreferedContactEnd__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactEnd__c</fullName>
    <label>Horario Cont. Preferente Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/PreferedContactStart__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactStart__c</fullName>
    <label>Horario Cont. Preferente Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Campaign/fields/ProductBranch__c.field-meta.xml
<CustomField>
    <fullName>ProductBranch__c</fullName>
    <description>Ramo correspondiente al producto asociado a la campaña.</description>
    <label>Product Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductBranches</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Campaign/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Zurich Empresas</fullName>
            </value>
            <value>
                <fullName>Zurich Empresas Orange</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(OCS/ZE). Destinado a gestionar la visibilidad del cliente debido a la GDPR. Primer nivel de restricción de acceso</description>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/CarRegistration__c.field-meta.xml
<CustomField>
    <fullName>CarRegistration__c</fullName>
    <externalId>true</externalId>
    <label>Car Registration</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/InfoQuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>InfoQuoteNumber__c</fullName>
    <description>(ZE/OCS) identificador de la oferta en INFO.</description>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IntermediaryCode__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryCode__c</fullName>
    <description>(OCS) Identifica al Mediador o Partner asociado a la oferta.</description>
    <label>Intermediary Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS) Identifica el nombre del intermediario ya sea partner o mediador.</description>
    <label>Intermediary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers (Intermediary)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IntermediaryVisibilityAcc__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryVisibilityAcc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Registro de Cuenta Mediador asociado a la Póliza que determina la visibilidad del usuario:

    - Si existe Agrupación y esta tiene definida que se use la Cuenta Mediador-padre: Cuenta Mediador-padre de la Agrupación

    - Sino: Valor del campo IntermediaryId__c</description>
    <label>Intermediary Visibility Acc</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers (Intermediary Visibility)</relationshipLabel>
    <relationshipName>IntermediariesOffersVisibility</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IntermediaryVisibilityForm__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryVisibilityForm__c</fullName>
    <description>Campo fórmula para recalcular visibilidad en ZRM</description>
    <formula>IF(Account.Blocked__c, 
	IF(ISBLANK(IntermediaryVisibilityAcc__c), 
		&apos;AccountBlocked&apos;, 
		null
	), 
	IF(IntermediaryVisibilityAcc__c = IntermediaryId__c,
		IF(ISBLANK(IntermediaryVisibilityAcc__c), 
			&apos;WithoutIntermediary&apos;, 
			&apos;CurrentIntermediary&apos;
		), 
		IF(IntermediaryVisibilityAcc__c = IntermediaryId__r.IntermediaryGroup__r.IntermediaryWithUser__c, 
			&apos;MainIntermediary&apos;, 
			null
		)
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Intermediary Visibility Form</label>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IsTest__c.field-meta.xml
<CustomField>
    <fullName>IsTest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permite identificar las ofertas introducidas en el sistema a causa de una prueba automatizada por un sistema externo.</description>
    <label>Oferta de prueba</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/isUpdatedFromINFO__c.field-meta.xml
<CustomField>
    <fullName>isUpdatedFromINFO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is updated from INFO</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/PersonLeadSource__c.field-meta.xml
<CustomField>
    <fullName>PersonLeadSource__c</fullName>
    <label>Person Lead Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/PreferedContactEnd__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactEnd__c</fullName>
    <label>Horario Cont. Preferente Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/PreferedContactStart__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactStart__c</fullName>
    <label>Horario Cont. Preferente Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/ProductBranch__c.field-meta.xml
<CustomField>
    <fullName>ProductBranch__c</fullName>
    <label>Product Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductBranches</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/SalesProcess__c.field-meta.xml
<CustomField>
    <fullName>SalesProcess__c</fullName>
    <description>Se autoinformará en la creación en función del tipo de cliente:

Cuenta-Lead &gt;&gt; Lead
Cuenta-Cliente &gt;&gt; Venta Cruzada</description>
    <label>Sales Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesProcesses</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>(ZE/OCS) Identifica el ámbito a utilizar para la colaboración del registro.</description>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZE</fullName>
                <label>Zurich Empresas</label>
            </value>
            <value>
                <fullName>ZEO</fullName>
                <label>Zurich Empresas Orange</label>
            </value>
            <value>
                <fullName>Z</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>ZEB</fullName>
                <label>Zurich Empresas Brokers</label>
            </value>
            <value>
                <fullName>Ventas</fullName>
                <label>Zurich Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/ScopeId__c.field-meta.xml
<CustomField>
    <fullName>ScopeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(ZE/OCS) Identifica el ámbito al que se encuentra asociada la oferta.</description>
    <label>Scope Name</label>
    <referenceTo>Scope__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/SessionId__c.field-meta.xml
<CustomField>
    <fullName>SessionId__c</fullName>
    <description>Stores the session id and product code of an offer created in the web fomulary</description>
    <externalId>true</externalId>
    <label>SessionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/SalesProcesses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
        <label>Lead</label>
    </customValue>
    <customValue>
        <fullName>VC</fullName>
        <label>Cross Selling</label>
    </customValue>
    <masterLabel>Sales Processes</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/OpportunitiesSelector.cls
/**
 * @description       :
 * @author            : jgallaga
 * @group             :
 * @last modified on  : 09-25-2023
 * @last modified by  : overes
 **/
public with sharing class OpportunitiesSelector extends RecordsSelector
{
    //#region Contructores
    public OpportunitiesSelector()
    {
        super( Opportunity.getSObjectType() );
    }

    //#endregion

    /**
     * Busca Opportunities a partir del Id de cuenta y de un conjunto de Ids de Scopes
     *
     * @author rlopez
     * @date 30/11/2020
     * @param  accountId    Id de la cuenta para la que queremos buscar ofertas
     * @param  scopesIds    Conjunto de Ids de Scope por los que queremos buscar ofertas
     *
     * @return              Listado de opportunies sobre los que se ha realizado match
     */
    public List<Opportunity> selectByAccountIdAndScopes(Id accountId, Set<Id> scopeIds)
    {
        List<Opportunity> result = new List<Opportunity>();

        if( accountId != null && scopeIds != null )
        {
            this.baseQuery.selectFields(new Set<Schema.SObjectField> {
                Opportunity.Id,
                Opportunity.AccountId,
                Opportunity.ScopeId__c,
                Opportunity.OwnerId
            })
            .addCondition( Query.conditionEq(Opportunity.AccountId, accountId) )
            .addCondition( Query.conditionIn(Opportunity.ScopeId__c, scopeIds) )
            .orderBy(Opportunity.CreatedDate.getDescribe().getName(), 'DESC');

            result = (List<Opportunity>) this.baseQuery.run();
        }

        return result;

    }

    /**
     * Busca Opportunities a partir del Id de cuenta, de un conjunto de Ids de Scopes y
     * de un conjunto de nombres de perfiles para filtrar por los propietarios
     *
     * @author rlopez
     * @date 12/01/2021
     * @param accountId         Id de la cuenta para la que queremos buscar ofertas
     * @param scopesIds         Conjunto de Ids de Scope por los que queremos buscar ofertas
     * @param ownerProfileNames Conjunto de nombres de perfiles para filtrar los propietarios de las ofertas
     *
     * @return                  Listado de opportunies sobre los que se ha realizado match
     *
     * @last modified by  : overes
     */
    public List<Opportunity> selectByAccountIdScopesAndOwnerProfile(Id accountId, Set<Id> scopeIds, Set<String> ownerProfileNames)
    {
        List<Opportunity> result = new List<Opportunity>();

        if(accountId != null && scopeIds != null && ownerProfileNames != null)
        {
            this.baseQuery.selectFields(new Set<Schema.SObjectField> {
                Opportunity.Id,
                Opportunity.AccountId,
                Opportunity.ScopeId__c,
                Opportunity.OwnerId
            })
            .addCondition( Query.conditionEq(Opportunity.AccountId, accountId) )
            .addCondition( Query.conditionIn(Opportunity.ScopeId__c, scopeIds) )
            .addConditionString('Owner.Profile.Name IN (\'' + String.join(new List<String>(ownerProfileNames), '\',\'') + '\')')
            .addCondition( Query.conditionEq(Opportunity.IsTest__c, false) ) // arcortazar - 31/01/2022: Incluímos esta condición para que no devuelva las ofertas de test
            .orderBy(Opportunity.CreatedDate.getDescribe().getName(), 'DESC');

            result = (List<Opportunity>) this.baseQuery.run();
        }

        return result;
    }

    /**
     * Busca Ofertas a partir del Id del cliente, del ambito.
     *
     * @author nts (agonzalezisasi)
     * @date 04/06/2021
     * @param {Id accountId} id del cliente
     * @param {String scope} ambito
     * @return {List<Opportunity} ofertas encontradas
     */
    public List<Opportunity> findByAccountIdAndScope(Id accountId, String scope)
    {
        this.baseQuery.selectFields(new Set<Schema.SObjectField> {
            Opportunity.Id,
            Opportunity.InfoQuoteNumber__c,
            Opportunity.SessionId__c,
            Opportunity.isUpdatedFromINFO__c
        })
        .addCondition( Query.conditionEq(Opportunity.AccountId, accountId) )
        .addCondition( Query.conditionEq(Opportunity.Scope__c, scope) );

        return (List<Opportunity>) this.baseQuery.run();
    }


    /**
     * Busca Ofertas a partir del Id del cliente, del ambito.
     *
     * @author nts (arcortazar)
     * @date 01/02/2022
     * @param {Id id} id de la oportunidad
     * @return {List<Opportunity} ofertas encontradas
     */
    public List<Opportunity> findById(Id id)
    {
        this.baseQuery.selectFields(new Set<Schema.SObjectField> {
            Opportunity.Id,
            Opportunity.AccountId,
            Opportunity.ScopeId__c,
            Opportunity.OwnerId,
            Opportunity.IsTest__c
        })
        .selectFields('Owner.ProfileId')
        .selectFields('Owner.Profile.Name')
        .addCondition( Query.conditionEq(Opportunity.Id, id) );
        return (List<Opportunity>) this.baseQuery.run();
    }

    /**
     * Busca Ofertas a partir del AccountId, ScopeId y que tenga distinto ID
     *
     * @author nts (arcortazar)
     * @date 01/02/2022
     * @param {Id id} id de la oportunidad
     * @param {Id accountId} id de la Account asociada a la oportunidd
     * @param {String scope} id del scope
     * @return {List<Opportunity} ofertas encontradas
     */
    public List<Opportunity> findByAccountIdAndScopeAndNotId(Id id, Id accountId, String scope)
    {
        this.baseQuery.selectFields(new Set<Schema.SObjectField> {
            Opportunity.Id,
            Opportunity.IsTest__c,
            Opportunity.OwnerId
        })
        .selectFields('Owner.ProfileId')
        .selectFields('Owner.Profile.Name')
        .addCondition( Query.conditionNotEq(Opportunity.Id, id) )
        .addCondition( Query.conditionEq(Opportunity.AccountId, accountId) )
        .addCondition( Query.conditionEq(Opportunity.ScopeId__c, scope) );

        return (List<Opportunity>) this.baseQuery.run();

    }

    /**
     * Busca Ofertas a partir del Id del cliente, del ambito.
     *
     * @author nts (arcortazar)
     * @date 30/03/2022
     * @param {Set<String> } lista de InfoQuoteNumber por los que buscar
     * @return {List<Opportunity} ofertas encontradas
     */
    public Set<String> findUpdatedFromInfoByQuoteNumber(Set<String> quoteNumbers)
    {
        Set<String> setInfoQuoteNumbers = new Set<String>();
        if(!quoteNumbers.isEmpty() && quoteNumbers != null)
        {
            this.baseQuery.selectFields(new Set<Schema.SObjectField> {
                Opportunity.Id,
                Opportunity.InfoQuoteNumber__c
            })
            .addConditionString('InfoQuoteNumber__c IN (\'' + String.join(new List<String>(quoteNumbers), '\',\'') + '\')')
            .addCondition( Query.conditionEq(Opportunity.isUpdatedFromINFO__c, true) );

            List<Opportunity> listaRetorno = (List<Opportunity>) this.baseQuery.run();
            for (Opportunity o : listaRetorno)
            {
                setInfoQuoteNumbers.add(o.InfoQuoteNumber__c);
            }
            return setInfoQuoteNumbers;
        }
        else
        {
            return setInfoQuoteNumbers;
        }
    }

    /**
     * Método utilizado por el batch RelateCasesToNewOffersBatch para definir el scope
     * @author lrodriguez6@seidor.es
     * @date 11/11/2022
     * @param String days para filtrar la query
     * @return String query que se va a lanzar en el batch
     */
    public List<Opportunity> findByCreatedOfferAndCreationDate(List<String> createdOffer, String daysToRetrieve)
    {
        if( daysToRetrieve != null && !String.isBlank(daysToRetrieve) && createdOffer != null && !createdOffer.isEmpty() )
        {
            this.baseQuery.selectFields(new Set<Schema.SObjectField> {
                Opportunity.Id,
                Opportunity.InfoQuoteNumber__c
            })
            .addConditionIn(Opportunity.InfoQuoteNumber__c, createdOffer);



            return (List<Opportunity>) this.baseQuery.run();
        }
        else
        {
            return new List<Opportunity>();
        }
    }


    /**
     * Busca Ofertas a partir del Id del cliente, del ambito.
     *
     * @author nts (arcortazar)
     * @date 01/02/2022
     * @param {Id id} id de la oportunidad
     * @return {List<Opportunity} ofertas encontradas
     */
    public List<Opportunity> findByName(Set<String> setNames)
    {
        if( setNames != null && !setNames.isEmpty() )
        {
            this.baseQuery.selectFields(new Set<Schema.SObjectField> {
                Opportunity.Id,
                Opportunity.Name
            })
            .addCondition( Query.conditionIn(Opportunity.Name, setNames) );
            return (List<Opportunity>) this.baseQuery.run();
        }
        else
        {
            return new List<Opportunity>();
        }
    }

    /**
     * @description Método que recupera ofertas en base al Id de la cuenta, el códig
     * de intermediario, el ramo, la fecha de creación y que la oferta no esté cerrada.
     *
     * @author amiranda
     * @date 01-09-2023
     * @param Id accountId Id de la cuenta asociada a la oportunidad
     * @param String intermediaryCode Código de intermedairio asociado a la oportunidad
     * @param String productBranch Ramo de la oportunidad
     * @param Query.DateLiteral daysToRetrieve Días a tener en cuenta
     * @return List<Opportunity> Lista de ofertas encontradas
     **/
    public List<Opportunity> findByAccIdAndIntermediaryCodAndProdBranchAndCreationDateAndNotClosed(
        Id accountId,
        String intermediaryCode,
        String productBranch,
        Query.DateLiteral daysToRetrieve)
    {

        List<Opportunity> retrievedOpportunities = new List<Opportunity>();

        if ( accountId != null  && daysToRetrieve != null )
        {
            Set<Schema.SObjectField> fieldsToRetrieve = new Set<Schema.SObjectField>
            {
                Opportunity.Name,
                Opportunity.StageName,
                Opportunity.AccountId,
                Opportunity.OwnerId,
                Opportunity.IntermediaryId__c,
                Opportunity.IntermediaryCode__c,
                Opportunity.PersonLeadSource__c,
                Opportunity.ProductBranch__c,
                Opportunity.Description,
                Opportunity.PreferedContactStart__c,
                Opportunity.PreferedContactEnd__c
            };

            retrievedOpportunities = this.baseQuery.selectfields(fieldsToRetrieve)
                                     .addConditionEq(Opportunity.AccountId, accountId)
                                     .addConditionEq(Opportunity.IntermediaryCode__c, intermediaryCode)
                                     .addConditionEq(Opportunity.ProductBranch__c, productBranch)
                                     .addConditionEq(Opportunity.CreatedDate, daysToRetrieve)
                                     .addConditionNotEq(Opportunity.StageName, 'Closed Won')
                                     .addConditionNotEq(Opportunity.StageName, 'Closed Lost')
                                     .run();
        }

        return retrievedOpportunities;
    }

    /**
     * Método que recupera las ofertas que InfoQuoteNumber es nulo
     * *
     * @author overes | 09-04-2023
     * @param offerRecord
     * @return  List<Opportunity>
     */
    public List<Opportunity> findOppWhenInfoQuoteNumberIsNull(Opportunity offerRecord)
    {
        return [SELECT Id, SessionId__c, InfoQuoteNumber__c, StageName, Name, CloseDate FROM Opportunity
                WHERE SessionId__c = : offerRecord.SessionId__c
                                     OR (AccountId = : offerRecord.InfoQuoteNumber__c AND CarRegistration__c = : offerRecord.CarRegistration__c AND PersonLeadSource__c = : offerRecord.PersonLeadSource__c)
                                     ORDER BY CreatedDate DESC];
    }

    /**
     * Método que recupera las ofertas que InfoQuoteNumber no es nulo
     * *
     * @author overes | 09-04-2023
     * @param offerRecord
     * @return  List<Opportunity>
     */
    public List<Opportunity> findOppWhenInfoQuoteNumberIsNOTNull(Opportunity offerRecord)
    {
        return [SELECT Id, SessionId__c, InfoQuoteNumber__c, StageName, Name, CloseDate FROM Opportunity
                WHERE SessionId__c = : offerRecord.SessionId__c
                                     OR InfoQuoteNumber__c = : offerRecord.InfoQuoteNumber__c
                                                             OR (AccountId = : offerRecord.AccountId AND CarRegistration__c = : offerRecord.CarRegistration__c AND PersonLeadSource__c = : offerRecord.PersonLeadSource__c)
                                                             ORDER BY CreatedDate DESC];
    }

    /**
     * Método que recupera las ofertas que necesitan recalcular la visibilidad para zrm
     * *
     * @author dmonuz | 18/9/2023
     * @return  List<Opportunity>
     */
    public List<Opportunity> findOffersWithIncorrectVisibility() {

        List<Opportunity> result = new List<Opportunity>([SELECT Id, Account.Blocked__c, Owner.Profile.Name, IntermediaryId__c, 
                                                        IntermediaryId__r.IsPartner, IntermediaryId__r.IntermediaryGroup__c, 
                                                        IntermediaryId__r.IntermediaryGroup__r.IntermediaryWithUser__c, IntermediaryVisibilityAcc__c 
                                                        FROM Opportunity
                                                        WHERE (IntermediaryVisibilityAcc__c != null OR IntermediaryId__r.IntermediaryGroup__c != null)
                                                        AND (IntermediaryVisibilityForm__c = null
                                                        OR (IntermediaryId__r.IsPartner = true AND IntermediaryVisibilityForm__c = 'MainIntermediary')
                                                        OR (IntermediaryId__r.IsPartner = false AND IntermediaryVisibilityForm__c = 'CurrentIntermediary'))]);
        return result;
    }


    /**
     * Método que recupera las ofertas que necesitan recalcular la visibilidad para zrm a partir de una lista de ids
     * *
     * @author dmonuz | 18/9/2023
     * @return  List<Opportunity>
     */
    public List<Opportunity> findOffersWithIncorrectVisibilityByAccountId(Set<String> accountIds) {

        List<Opportunity> result = new List<Opportunity>();

        if (accountIds != null && !accountIds.isEmpty()) {
            result = new List<Opportunity>([SELECT Id, Account.Blocked__c, Owner.Profile.Name, IntermediaryId__c, 
                                                            IntermediaryId__r.IsPartner, IntermediaryId__r.IntermediaryGroup__c, 
                                                            IntermediaryId__r.IntermediaryGroup__r.IntermediaryWithUser__c, IntermediaryVisibilityAcc__c 
                                                            FROM Opportunity
                                                            WHERE AccountId IN :accountIds AND (IntermediaryVisibilityAcc__c != null OR IntermediaryId__r.IntermediaryGroup__c != null)
                                                            AND (IntermediaryVisibilityForm__c = null
                                                            OR (IntermediaryId__r.IsPartner = true AND IntermediaryVisibilityForm__c = 'MainIntermediary')
                                                            OR (IntermediaryId__r.IsPartner = false AND IntermediaryVisibilityForm__c = 'CurrentIntermediary'))]);
        }

        return result;

    }

    /**
     * Devuelve un String con la query para conseguir oportunidades de campaña de Venta Cruzada que no esten cerradas
     * *
     * @author  jgallaga | 07-09-2023
     * @return  String
     */
    public String findCrossSellingOpportunitiesNotClosed()
    {
        this.baseQuery
        .selectFields(new List<Schema.SObjectField> {Opportunity.AccountId, Opportunity.CampaignId, Opportunity.Campaign.Type})
        .addConditionEq(Opportunity.Campaign.Type, 'Cross Selling')
        .addConditionEq(Opportunity.IsClosed, false);

        return 'SELECT Accountid, Campaignid, Campaign.type, SalesProcess__c, Account.RecordType.DeveloperName FROM Opportunity WHERE (Campaign.Type = \'Cross Selling\') AND (IsClosed = false)';
    }
}