force-app/zurich-base/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium (PV-1)</fullName>
            </value>
            <value>
                <fullName>Plus (PV0)</fullName>
            </value>
            <value>
                <fullName>Estándar (PV1)</fullName>
            </value>
            <value>
                <fullName>Básica (PV2)</fullName>
            </value>
            <value>
                <fullName>Esencial (PV3)</fullName>
            </value>
            <value>
                <fullName>Varios</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generated to identify a customer</description>
    <externalId>true</externalId>
    <inlineHelpText>Code that IBA generated to identify a customer</inlineHelpText>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/Cover__c.object-meta.xml
<CustomObject>
    <label>Cobertura</label>
    <nameField>
        <label>Nombre de Cobertura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coberturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Cover__c/fields/CoverId__c.field-meta.xml
<CustomField>
    <fullName>CoverId__c</fullName>
    <externalId>true</externalId>
    <label>Cover ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to, used to set access with sharing rules</description>
    <label>Entidad legal</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/ParentCoverId__c.field-meta.xml
<CustomField>
    <fullName>ParentCoverId__c</fullName>
    <label>ParentCoverId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/PolicyProduct__c.field-meta.xml
<CustomField>
    <fullName>PolicyProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto asegurado</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Coberturas</relationshipLabel>
    <relationshipName>Coberturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/Processing_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Processing_Timestamp__c</fullName>
    <label>Processing Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <label>Nombre de Descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Discount__c/fields/DiscountId__c.field-meta.xml
<CustomField>
    <fullName>DiscountId__c</fullName>
    <externalId>true</externalId>
    <label>Id descuento</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Discount__c/fields/DiscountPct__c.field-meta.xml
<CustomField>
    <fullName>DiscountPct__c</fullName>
    <label>Porcentaje descuento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/Discount__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Póliza</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Descuentos</relationshipLabel>
    <relationshipName>Descuentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/After_Processing_Check__c.field-meta.xml
<CustomField>
    <fullName>After_Processing_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Processing Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <label>Customer Num</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/PolicyNum__c.field-meta.xml
<CustomField>
    <fullName>PolicyNum__c</fullName>
    <externalId>true</externalId>
    <label>Número de la póliza</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/Processing_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Processing_Timestamp__c</fullName>
    <label>Processing Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/recordTypes/PolicyGI.recordType-meta.xml
<RecordType>
    <fullName>PolicyGI</fullName>
    <active>true</active>
    <label>Póliza GI</label>
</RecordType>

force-app/zurich-base/main/default/objects/OrderItem/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies if the product is active in the policy</description>
    <inlineHelpText>Specifies if the product is active in the policy</inlineHelpText>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nintendo</fullName>
            </value>
            <value>
                <fullName>Micro</fullName>
            </value>
            <value>
                <fullName>Raycool</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>Moma Bikes</fullName>
            </value>
            <value>
                <fullName>Urban Fox</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
            <value>
                <fullName>E-Twow</fullName>
            </value>
            <value>
                <fullName>LG</fullName>
            </value>
            <value>
                <fullName>Nilox</fullName>
            </value>
            <value>
                <fullName>Huawei</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Segway</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>MSI</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoría</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Laptop</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Game Console</fullName>
            </value>
            <value>
                <fullName>Smartphone</fullName>
            </value>
            <value>
                <fullName>GoPro</fullName>
            </value>
            <value>
                <fullName>ELECTRIC BIKE</fullName>
            </value>
            <value>
                <fullName>Electric Scooter</fullName>
            </value>
            <value>
                <fullName>Smartwatch</fullName>
            </value>
            <value>
                <fullName>Insured Person</fullName>
            </value>
            <value>
                <fullName>Airpods</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/ItemAge__c.field-meta.xml
<CustomField>
    <fullName>ItemAge__c</fullName>
    <description>Product age in months</description>
    <inlineHelpText>Product age in months</inlineHelpText>
    <label>Antigüedad</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/ItemId__c.field-meta.xml
<CustomField>
    <fullName>ItemId__c</fullName>
    <description>Unique identifier or an insured product</description>
    <externalId>true</externalId>
    <label>Item Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/itemModel__c.field-meta.xml
<CustomField>
    <fullName>itemModel__c</fullName>
    <label>Modelo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>(OCS). Identifica la entidad legal a la que está asociada la póliza en INFO</description>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Insurance</fullName>
            </value>
            <value>
                <fullName>General Insurance</fullName>
            </value>
            <value>
                <fullName>000</fullName>
                <label>Todos</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>Zurich</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>CAN SSGG</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>CAS SSGG</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>CAS Vida</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Zurich Vida</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>DZ Pensiones</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>EPSV Zurich</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>BSSG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>Multientidad</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica el producto para el que se realiza la póliza. En la web se (OCS) Identifica como Tipo de Registro</description>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PricebookEntry/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <externalId>true</externalId>
    <label>ProductID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <description>Field to be used as external ID of the product</description>
    <externalId>true</externalId>
    <label>ProductID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Test_Batch_PostProcessing.cls
/**
 * Clases de test para Batch_PostProcessing
 **
 * @author nbizkarra
 * @date 18/06/2020
 */

@isTest
private with sharing class Test_Batch_PostProcessing
{
    private static final String PRODUCT_NAME = 'Samsung Galaxy';
    /**
     * Create test data: an order with a new timestamp and orderItem, discount and cover with old timestamp
     **
     * @author nbizkarra
     * @date 18/06/2020
     */
    @TestSetup
    private static void test_CreateData()
    {
        // Instantiate the Pricebook2 record first, setting the Id
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
            );
        update standardPricebook;

        Product2 newProduct = new Product2(
            ProductID__c = PRODUCT_NAME,
            Name = PRODUCT_NAME,
            Family = 'Smartphone',
            Brand__c = 'Samsung',
            IsActive = true
            );
        insert newProduct;
        PricebookEntry pricebookEntry = new PricebookEntry(
            UnitPrice = 0,
            ProductID__c = PRODUCT_NAME,
            Pricebook2Id = Test.getStandardPricebookId(),
            IsActive = true
            );
        pricebookEntry.Product2Id = newProduct.id;
        insert pricebookEntry;

        Account newMaster = new Account(Name = 'test', CustomerNum__c = '3123');
        Account masterRef = new Account(CustomerNum__c = '3123');
        insert newMaster;

        Datetime newTimestamp = Datetime.newInstance(2020, 12, 1, 12, 30, 2);

        Order quote = new Order(
            EffectiveDate = Date.valueOf('1990-01-02'),
            CustomerNum__c = '3123',
            Status = 'Sync',
            PolicyNum__c = '12345',
            LegalEntity__c = Label.GeneralInsurance,
            RecordTypeId = SystemUtil.getOrderRecordTypeIdByName(Label.PolicyGI),
            After_Processing_Check__c = true,
            Processing_Timestamp__c = newTimestamp
            );

        quote.Account = MasterRef;
        quote.Pricebook2Id = Test.getStandardPricebookId();
        insert quote;

        Datetime oldTimestamp = Datetime.newInstance(2008, 12, 1, 12, 30, 2);

        OrderItem item = new OrderItem(
            itemId__c = '7777',
            ItemAge__c = 2,
            Category__c = 'Smartphone',
            Brand__c = 'Samsung',
            itemModel__c = 'Samsung Galaxy',
            Processing_Timestamp__c = oldTimestamp
            );
        item.OrderId = quote.id;
        item.Active__c = true;
        item.UnitPrice = 0;
        item.Quantity = 1;
        item.PricebookEntryId = pricebookEntry.id;
        insert item;

        Discount__c disc = new Discount__c(
            Name = 'Primavera 2020',
            DiscountPct__c = 50,
            DiscountId__c = '1111',
            Processing_Timestamp__c = oldTimestamp
            );
        disc.Policy__c = quote.id;
        insert disc;

        Cover__c cover = new Cover__c(
            CoverId__c = '1',
            ParentCoverId__c = null,
            Name = 'Robo',
            LegalEntity__c = Label.GeneralInsurance,
            Processing_Timestamp__c = oldTimestamp
            );

        cover.PolicyProduct__c = item.id;
        insert cover;
    }

    /**
     * This batch will delete the orderitem, discount and cover because they have an older timestamp than the order
     **
     * @author nbizkarra
     * @date 18/06/2020
     */
    @isTest
    private static void test_DeleteOutdatedData()
    {
        Order policy = [
            SELECT After_Processing_Check__c
            FROM Order
            WHERE PolicyNum__c = '12345'
        ];
        Integer numOrderItem = [SELECT COUNT() FROM OrderItem];
        Integer numDiscount = [SELECT COUNT() FROM Discount__c];
        Integer numCover = [SELECT COUNT() FROM Cover__c];

        System.assertEquals(true, policy.After_Processing_Check__c);
        System.assertEquals(1, numOrderItem);
        System.assertEquals(1, numDiscount);
        System.assertEquals(1, numCover);

        Test.startTest();
        Batch_PostProcessing b = new Batch_PostProcessing('select'); // for coverage
        b = new Batch_PostProcessing();
        database.executeBatch(b, 200);
        Test.stopTest();

        policy = [
            SELECT After_Processing_Check__c
            FROM Order
            WHERE PolicyNum__c = '12345'
        ];
        numOrderItem = [SELECT COUNT() FROM OrderItem];
        numDiscount = [SELECT COUNT() FROM Discount__c];
        numCover = [SELECT COUNT() FROM Cover__c];

        System.assertEquals(false, policy.After_Processing_Check__c);
        System.assertEquals(0, numOrderItem);
        System.assertEquals(0, numDiscount);
        System.assertEquals(0, numCover);
    }

    /**
     * For testing Schedule
     */
    @isTest
    private static void testBatch_schedule()
    {
        Batch_PostProcessing m = new Batch_PostProcessing();
        String sch = '20 30 8 10 2 ?';

        Test.startTest();
        system.schedule('Post Processing batch', sch, m);
        Test.stopTest();
    }

    /**
     * Test que comprueba si se obtienen correctamente los order items a borrar
     **
     * @author aberuete
     * @date 21/04/2023
     */
    @isTest
    private static void testGetItemsToDelete()
    {
        Batch_PostProcessing batch = new Batch_PostProcessing();

        List<OrderItem> itemsToDelete = new List<OrderItem>();
        Order quote = [Select id,(Select id from OrderItems) from Order limit 1];
        System.assertNotEquals(0, quote.OrderItems.size(), 'Debería tener alguna order item relacionada');

        Test.startTest();
        itemsToDelete = batch.getItemsToDelete (quote, itemsToDelete);
        Test.stopTest();

        System.assertEquals(1, itemsToDelete.size(), 'Debería devolver un orderitem para borrar');
    }

    /**
     * Test que comprueba si se obtienen correctamente los descuentos a borrar
     **
     * @author aberuete
     * @date 21/04/2023
     */
    @isTest
    private static void testGetDiscountsToDelete()
    {
        Batch_PostProcessing batch = new Batch_PostProcessing();

        List<Discount__c> discountsToDelete = new List<Discount__c>();
        Order quote = [Select id,(Select id from Descuentos__r) from Order limit 1];
        System.assertNotEquals(0, quote.Descuentos__r.size(), 'Debería tener algun descuento relacionado');

        Test.startTest();
        discountsToDelete = batch.getDiscountsToDelete (quote, discountsToDelete);
        Test.stopTest();

        System.assertEquals(1, discountsToDelete.size(), 'Debería devolver un descuento para borrar');
    }
}