force-app/zurich-base/main/default/objects/Account/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generated to identify a customer</description>
    <externalId>true</externalId>
    <inlineHelpText>Code that IBA generated to identify a customer</inlineHelpText>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Masterpolicy__c.field-meta.xml
<CustomField>
    <fullName>Masterpolicy__c</fullName>
    <description>Partner identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>Masterpolicy</inlineHelpText>
    <label>Código partner</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
            </value>
            <value>
                <fullName>002</fullName>
            </value>
            <value>
                <fullName>003</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>Comprende aquellos posibles clientes todavía no existentes en el sistema transaccional</description>
    <label>Lead</label>
</RecordType>

force-app/zurich-base/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/fields/Abandoned_Lead__c.field-meta.xml
<CustomField>
    <fullName>Abandoned_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used in order to identify the abandoned cart in step 1</description>
    <label>Abandoned Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/CNO__c.field-meta.xml
<CustomField>
    <fullName>CNO__c</fullName>
    <description>A life lead or customer CNO</description>
    <label>CNO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/CreditCard__c.field-meta.xml
<CustomField>
    <fullName>CreditCard__c</fullName>
    <description>Last four digits from credit card</description>
    <label>4 últimos dígitos tarjeta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generates to identify a customer. As for life and non-life is the same number, for life record type, it will have prefix LIFE-XXX and for non-life GI-XXX</description>
    <externalId>true</externalId>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <description>A customer or lead DNI</description>
    <label>DNI</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/EmailHash__c.field-meta.xml
<CustomField>
    <fullName>EmailHash__c</fullName>
    <label>Email tarificador hash</label>
    <type>TextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mujer</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>No aplica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/IsSubscriber__c.field-meta.xml
<CustomField>
    <fullName>IsSubscriber__c</fullName>
    <defaultValue>false</defaultValue>
    <description>KLINC: Indica si un contacto se ha dado de alta como suscriptor en la newsletter. Se rellena en el procesamiento tras darse de alta mediante el formulario Web-to-Lead.</description>
    <label>Subscriber</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>Life lead or customer job</description>
    <label>Profesión</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
            <value>
                <fullName>Agricultor, ganadero de reses no bravas</fullName>
            </value>
            <value>
                <fullName>Escoger...</fullName>
            </value>
            <value>
                <fullName>Director de cine y espectáculos</fullName>
            </value>
            <value>
                <fullName>Pastelero, panadero y cocinero</fullName>
            </value>
            <value>
                <fullName>Boxeador Professional</fullName>
            </value>
            <value>
                <fullName>Antidisturbios: Policía Municipal, Autonómica y Guardia Civil</fullName>
            </value>
            <value>
                <fullName>Administrativo: Policía Municipal, Autonómica y Guardia Civil</fullName>
            </value>
            <value>
                <fullName>Guarda Jurado armado, vigilante seguridad armado</fullName>
            </value>
            <value>
                <fullName>Estudiante</fullName>
            </value>
            <value>
                <fullName>Óptico y/u optometrista y otorrinolaringólogo</fullName>
            </value>
            <value>
                <fullName>Piloto</fullName>
            </value>
            <value>
                <fullName>Ingeniería (técnico, naval, industrial, montes y caminos, agrónomo y aeronáutico)</fullName>
            </value>
            <value>
                <fullName>Controlador aéreo</fullName>
            </value>
            <value>
                <fullName>Mediador de seguros</fullName>
            </value>
            <value>
                <fullName>Joyero, relojero y reparador de electrodomésticos</fullName>
            </value>
            <value>
                <fullName>Periodista, presentador e intérprete</fullName>
            </value>
            <value>
                <fullName>Artista, decorador, restaurador</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/JobPosition__c.field-meta.xml
<CustomField>
    <fullName>JobPosition__c</fullName>
    <description>A life lead or customer job position</description>
    <label>Posición de trabajo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to</description>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MasterPolicy__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Specifies if the contact comes from a partner. Linked to the partner acccount.</description>
    <label>Masterpolicy</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MasterPolicyDesc__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyDesc__c</fullName>
    <description>Not visible field in the page layout and used to copy its value to account Name field after parsing it in the parser.</description>
    <label>Masterpolicy description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MasterPolicyNum__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyNum__c</fullName>
    <label>Masterpolicy Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MonthExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>MonthExpiryDate__c</fullName>
    <description>Month expiry date from credit card</description>
    <label>Mes expiración tarjeta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
            <value>
                <fullName>Español</fullName>
            </value>
            <value>
                <fullName>España</fullName>
            </value>
            <value>
                <fullName>Francia</fullName>
            </value>
            <value>
                <fullName>Afganistan</fullName>
            </value>
            <value>
                <fullName>Alemania</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Danés</fullName>
            </value>
            <value>
                <fullName>Noruego</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Finlandés</fullName>
            </value>
            <value>
                <fullName>Irlanda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/SourceCountry__c.field-meta.xml
<CustomField>
    <fullName>SourceCountry__c</fullName>
    <label>Source Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/YearExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>YearExpiryDate__c</fullName>
    <description>Year expiry date from credit card</description>
    <label>Año expiración tarjeta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/recordTypes/CustomerGI.recordType-meta.xml
<RecordType>
    <fullName>CustomerGI</fullName>
    <active>true</active>
    <label>Cliente no vida</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/recordTypes/CustomerLife.recordType-meta.xml
<RecordType>
    <fullName>CustomerLife</fullName>
    <active>true</active>
    <label>Cliente vida</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/recordTypes/LeadGI.recordType-meta.xml
<RecordType>
    <fullName>LeadGI</fullName>
    <active>true</active>
    <label>Lead no vida</label>
</RecordType>

force-app/zurich-base/main/default/objects/Lead/fields/CheckGI__c.field-meta.xml
<CustomField>
    <fullName>CheckGI__c</fullName>
    <defaultValue>false</defaultValue>
    <description>KLINC: Check de aceptación de envíos comerciales de GI para el formulario Web-to-Lead</description>
    <label>Check acceptance GI</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Lead/fields/CheckLife__c.field-meta.xml
<CustomField>
    <fullName>CheckLife__c</fullName>
    <defaultValue>false</defaultValue>
    <description>KLINC: Check de aceptación de envíos comerciales de GI para el formulario Web-to-Lead</description>
    <label>Check acceptance Life</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Test_LeadUtil.cls
/**
 * Clases de test para LeadUtil
 **
 * @author nbizkarra
 * @date 17/11/2020
 **/
@isTest
private with sharing class Test_LeadUtil
{
    static final String EMAIL_CONTACTOS_TEST = 'testexisting@test.com';
    static final String CUSTOMER_NUM_TEST = 'Life-3123';

    @testSetup
    private static void makeData()
    {
        Account newMaster = new Account(Name = 'test', CustomerNum__c = '3123');
        insert newMaster;

        Contact customerGI = new Contact(
            Email = EMAIL_CONTACTOS_TEST,
            LastName = 'Test',
            CustomerNum__c = 'GI-3123',
            LegalEntity__c = Label.GeneralInsurance,
            Status__c = 'Activo',
            RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.CustomerGI),
            SourceCountry__c = 'Spain',
            AccountId = newMaster.Id
            );

        insert customerGI;

        Contact customerLife = new Contact(
            Email = EMAIL_CONTACTOS_TEST,
            LastName = 'Test',
            CustomerNum__c = CUSTOMER_NUM_TEST,
            LegalEntity__c = Label.LifeInsurance,
            Status__c = 'Activo',
            RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.CustomerLife),
            SourceCountry__c = 'Spain',
            AccountId = newMaster.Id
            );

        insert customerLife;

        Contact lead = new Contact(
            Email = 'edutest@test.com',
            Birthdate = Date.valueOf('1990-01-01'),
            FirstName = 'Edu',
            LastName = 'Test',
            CustomerNum__c = 'GI-3125',
            LegalEntity__c = Label.GeneralInsurance,
            RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.LeadGI),
            IsSubscriber__c = true,
            HasOptedOutOfEmail = false
            );
        insert lead;

        Contact lead2 = new Contact(
            Email = 'edu2test@test.com',
            Birthdate = Date.valueOf('1990-01-01'),
            FirstName = 'Edu2',
            LastName = 'Test2',
            CustomerNum__c = 'GI-1112',
            LegalEntity__c = Label.GeneralInsurance,
            RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.LeadGI),
            IsSubscriber__c = true,
            HasOptedOutOfEmail = true 
            );
        insert lead2;
    }


    /**
     * @description This method creates a new subscriber whose email doesn't exist in SF
     * @author nbizkarra
     * @date 17/11/2020
     **/
    @isTest
    private static void test_NewSubscriber()
    {

        List<Lead> subscribers = new List<Lead>();

        Lead subscriber = new Lead (
            Email = 'test@test.com',
            LastName = 'Test',
            CheckGI__c = true,
            CheckLife__c = true,
            Country = 'Spain',
            LeadSource = 'Klinc'
            );

        subscribers.add(subscriber);

        Test.startTest();

        LeadUtil.NewSubscribers(subscribers);
        //Check that 2 contacts (life and GI) are created in SF
        System.assertEquals( 2, LeadUtil.contactsToCreate.size() );

        Test.stopTest();
    }

    /**
     * @description This method creates a new subscriber and updates existing contact
     * @author nbizkarra
     * @date 17/11/2020
     **/
    @isTest
    private static void test_ExistingSubscriber()
    {

        List<Lead> subscribers = new List<Lead>();

        Lead subscriber = new Lead (
            Email = EMAIL_CONTACTOS_TEST,
            LastName = 'Test',
            CheckGI__c = true,
            CheckLife__c = true,
            Country = 'Spain',
            LeadSource = 'Klinc'
            );

        subscribers.add(subscriber);

        Test.startTest();

        LeadUtil.NewSubscribers(subscribers);
        //Check that 2 contacts (life and GI) are updated in SF
        List<Contact> c=LeadUtil.mapContacts.values().get(0);
        System.assertEquals(EMAIL_CONTACTOS_TEST, c.get(0).Email);
        System.assertEquals( 2, LeadUtil.contactsToUpdate.size() );

        Test.stopTest();
    }

    /**
     * @description This method creates a new subscriber and relates to the existing account
     * @author nbizkarra
     * @date 17/11/2020
     **/
    @isTest
    private static void test_ExistingMaster1()
    {

        List<Lead> subscribers = new List<Lead>();

        Lead subscriber = new Lead (
            Email = EMAIL_CONTACTOS_TEST,
            LastName = 'Test',
            CheckGI__c = true,
            CheckLife__c = true,
            Country = 'France',
            LeadSource = 'Klinc'
            );

        subscribers.add(subscriber);

        Test.startTest();

        LeadUtil.NewSubscribers(subscribers);
        //Check that 2 contacts (life and GI) are created in SF
        System.assertEquals( 2, LeadUtil.contactsToCreate.size() );

        Test.stopTest();
    }

    /**
     * @description This method creates a new subscriber and relates to one of the 2 existing account
     * @author nbizkarra
     * @date 17/11/2020
     **/
    @isTest
    private static void test_ExistingMaster2()
    {
        Account newMaster = new Account(Name = 'test', CustomerNum__c = '1111');
        insert newMaster;

        Contact customerGI = new Contact(
            Email = EMAIL_CONTACTOS_TEST,
            LastName = 'Test',
            CustomerNum__c = 'GI-1111',
            LegalEntity__c = Label.GeneralInsurance,
            Status__c = 'Lead',
            RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.LeadGI),
            SourceCountry__c = 'Spain',
            AccountId = newMaster.Id
            );

        insert customerGI;

        List<Lead> subscribers = new List<Lead>();

        Lead subscriber = new Lead (
            Email = EMAIL_CONTACTOS_TEST,
            LastName = 'Test',
            CheckGI__c = true,
            CheckLife__c = true,
            Country = 'France',
            LeadSource = 'Klinc'
            );

        subscribers.add(subscriber);

        Test.startTest();

        LeadUtil.NewSubscribers(subscribers);
        //Check that 2 contacts (life and GI) are created in SF
        System.assertEquals( 2, LeadUtil.contactsToCreate.size() );

        //Check that the created contacts are related to the master whose contact is a customer
        SET<String> customerNum = new SET<String>();
        customerNum.add(CUSTOMER_NUM_TEST);
        Map<String, Contact> mapContact = SystemUtil.contactsSelector(customerNum);
        Contact contact = mapContact.get(CUSTOMER_NUM_TEST);

        System.assertEquals(contact.AccountId, LeadUtil.contactsToCreate.get(0).AccountId);
        System.assertEquals(contact.AccountId, LeadUtil.contactsToCreate.get(1).AccountId);

        Test.stopTest();
    }

     /**
     * @description Comprueba si se elimina correctamente un contacto que es suscriptor y se ha desuscrito
     * @author aberuete
     * @date 03/04/2023
     **/
    @isTest
    private static void test_deleteContact()
    {
        List<Contact> leadsToDeleteBefore = [Select id,IsSubscriber__c,HasOptedOutOfEmail from Contact where recordtype.developerName =: Label.LeadGI and IsSubscriber__c = true and HasOptedOutOfEmail = true ];
        
        Test.startTest(); 
        LeadUtil.deleteOrUpdateContacs(leadsToDeleteBefore);
        Test.stopTest(); 

        List<Contact> leadsToDeleteAfter = [Select id,IsSubscriber__c,HasOptedOutOfEmail from Contact where recordtype.developerName =: Label.LeadGI and IsSubscriber__c = true and HasOptedOutOfEmail = true ];

        System.assertEquals (1,leadsToDeleteBefore.size(),'El número de contactos debe ser 1');
        System.assertEquals (0,leadsToDeleteAfter.size(),'El contacto se debe haber borrado');
    }

    /**
     * @description Comprueba si se actualizan los valores a nulo si  un contacto que es suscriptor y  no se ha desuscrito
     * @author aberuete
     * @date 03/04/2023
     **/
    @isTest
    private static void test_updateContact()
    {
        List<Contact> leadsToUpdateBefore = [Select id,IsSubscriber__c,HasOptedOutOfEmail,Balance__c,Birthdate,CNO__c,CreditCard__c,CustomerID__c,CustomerNum__c,DNI__c,EmailHash__c,Gender__c,Job__c,JobPosition__c,
        MailingCity,MailingCountry,MailingPostalCode,MailingState,MailingStreet,MasterPolicy__c,MasterPolicyDesc__c,MasterPolicyNum__c,MobilePhone,MonthExpiryDate__c,Nationality__c,YearExpiryDate__c,Abandoned_Lead__c
         from Contact where recordtype.developerName =: Label.LeadGI and IsSubscriber__c = true and HasOptedOutOfEmail = false ];
        
        Test.startTest(); 
        LeadUtil.deleteOrUpdateContacs(leadsToUpdateBefore);
        Test.stopTest(); 

        List<Contact> leadsToUpdateAfter = [Select id,IsSubscriber__c,HasOptedOutOfEmail,Balance__c,Birthdate,CNO__c,CreditCard__c,CustomerID__c,CustomerNum__c,DNI__c,EmailHash__c,Gender__c,Job__c,JobPosition__c,
        MailingCity,MailingCountry,MailingPostalCode,MailingState,MailingStreet,MasterPolicy__c,MasterPolicyDesc__c,MasterPolicyNum__c,MobilePhone,MonthExpiryDate__c,Nationality__c,YearExpiryDate__c,Abandoned_Lead__c
         from Contact where recordtype.developerName =: Label.LeadGI and IsSubscriber__c = true and HasOptedOutOfEmail = false ];

        System.assertEquals (null,leadsToUpdateAfter[0].Birthdate,'El valor del campo cumpleaños debe ser nulo');
    }

}