force-app/zurich-base/main/default/objects/Account/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generated to identify a customer</description>
    <externalId>true</externalId>
    <inlineHelpText>Code that IBA generated to identify a customer</inlineHelpText>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generates to identify a customer. As for life and non-life is the same number, for life record type, it will have prefix LIFE-XXX and for non-life GI-XXX</description>
    <externalId>true</externalId>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <description>A customer or lead DNI</description>
    <label>DNI</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to</description>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/recordTypes/CustomerGI.recordType-meta.xml
<RecordType>
    <fullName>CustomerGI</fullName>
    <active>true</active>
    <label>Cliente no vida</label>
</RecordType>

force-app/zurich-base/main/default/objects/Opportunity/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>(OCS) Identifica el código de negocio en INFO.</description>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &apos;Life&apos;, &apos;Life Insurance&apos;, 
			IF($Profile.Name = &apos;ZE User&apos; || $Profile.Name = &apos;Ventas User&apos;,
			    &apos;001&apos;,
			        &apos;&apos;))</defaultValue>
    <description>(ZE/OCS) Identifica la entidad legal a la que pertenece la oferta.</description>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Insurance</fullName>
            </value>
            <value>
                <fullName>General Insurance</fullName>
            </value>
            <value>
                <fullName>000</fullName>
                <label>Todos</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>Zurich</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>CAN SSGG</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>CAS SSGG</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>CAS Vida</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Zurich Vida</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>DZ Pensiones</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>EPSV Zurich</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>BSSG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>Multientidad</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(ZE/OCS) Identifica el producto para el que se realiza la oferta. En la web se identifica como Tipo de Registro.</description>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/GroupDescription__c.field-meta.xml
<CustomField>
    <fullName>GroupDescription__c</fullName>
    <description>INFO Source: KTPM08T - DSAGRPCN</description>
    <label>Group Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/INFO_Product_Number__c.field-meta.xml
<CustomField>
    <fullName>INFO_Product_Number__c</fullName>
    <description>(OCS). En Productos que provengan de INFO, el campo estará conformado por la concatenación del Commercial ID y el Technical ID</description>
    <externalId>true</externalId>
    <label>INFO Product Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <description>Field to be used as external ID of the product</description>
    <externalId>true</externalId>
    <label>ProductID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/User/fields/IsZESupervisor__c.field-meta.xml
<CustomField>
    <fullName>IsZESupervisor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if user is a supervisor in Zurich Empresas (ZE)</description>
    <label>Is ZE supervisor</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Test_ClosedWinOfferByUser.cls
/* Clase de test que comprueba la creación de una nueva task asociada a una oferta y la 
asignación del owner a la oferta
@author: arcortazar
@date: 04/03/2022
*/

@isTest
public with sharing class Test_ClosedWinOfferByUser {

    // Corremos el test como SysAdmin, tiene que funcionar bien.

    @isTest
    static void test_runAsSysAdmin() {
        Account acc = new Account(Name = 'New Account 1');
        insert acc;

        Product2 p = new Product2
        (
            Name = 'Product test 1',
            GroupDescription__c = 'Group 1'
        );
        insert p;

        Contact customer = new Contact(
            Email = 'edu@test.com',
            MobilePhone = '675887723',
            DNI__c = '05289654W',
            Birthdate = Date.valueOf('1990-01-01'),
            FirstName = 'Edu',
            LastName = 'Sanchez',
            CustomerNum__c = 'GI-3123',
            LegalEntity__c = Label.GeneralInsurance,
            RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.CustomerGI),
            AccountId = acc.Id
            );
        insert customer;

        Opportunity opp = new Opportunity(
            AccountId = acc.Id,
            Name = 'New Opportunity',
            CloseDate = Date.today().addDays(3),
            TotalOpportunityQuantity = 10,
            BusinessCode__c = '1234',
            ProductId__c = p.Id, 
            StageName = 'Closed Won');
        insert opp;

        // Creamos la task asociada a la oferta cerrada -> Tiene que funcionar
        
        Task interactionTask = new Task(
            Subject = 'Llamada ' + Datetime.now().format(),
            Status = 'Nueva',
            Priority = 'Normal',
            CallObject = 'ABCD12345',
            WhoId = customer.Id,
            TaskSubtype = 'Call',
            Type = 'Call', 
            OwnerId = UserInfo.getUserId(),
            WhatId = opp.Id
        );
    
        Test.startTest();
        insert interactionTask;
        Test.stopTest();

        // Comprobamos que se haya modificado la oferta
        List<Opportunity> oportunidades  = [SELECT Id, Name, OwnerId FROM Opportunity WHERE StageName like 'Closed Won']; 
        System.assertEquals(1, oportunidades.size(), 'Ha de haber una oferta insertada');
        System.assertEquals(UserInfo.getUserId(), oportunidades.get(0).OwnerId, 'EL owner de la oferta ha de ser el usuario que corre el test');

        // Comprobamos que se haya insertado la task
        List<Task> tareas = [SELECT Id, OwnerId FROM Task WHERE WhatId = :oportunidades.get(0).id];
        System.assertEquals(1, tareas.size(), 'Ha de haber una tarea insertada para la oferta de la que disponemos');
    }

    // Corremos el test como User que es ZE Supervisor, tiene que funcionar bien.
    @isTest
    static void test_runAsZEUser_SupervisorTrue() {

        // Agustín Zapata tiene a True el flag "isZESupervisor__c"
        User u = [SELECT Id, IsZESupervisor__c FROM User WHERE Name='Agustin Angel Zapata Mendez'];
        System.runAs(u) {
            // The following code runs as user 'u'
            System.debug('Current User: ' + UserInfo.getUserName());
            System.debug('Is ZE Supervisor: ' + u.IsZESupervisor__c);

            Account acc = new Account(Name = 'New Account 1');
            insert acc;

            Contact customer = new Contact(
            Email = 'edu@test.com',
            MobilePhone = '675887723',
            DNI__c = '05289654W',
            Birthdate = Date.valueOf('1990-01-01'),
            FirstName = 'Edu',
            LastName = 'Sanchez',
            CustomerNum__c = 'GI-3123',
            LegalEntity__c = Label.GeneralInsurance,
            RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.CustomerGI),
            AccountId = acc.Id
            );
        
            insert customer;

            Product2 p = new Product2
            (
                Name = 'Product test 1',
                GroupDescription__c = 'Group 1',
                INFO_Product_Number__c = '00800-00001'
            );
            insert p;

            Opportunity opp = new Opportunity(
                AccountId = acc.Id,
                Name = 'New Opportunity',
                CloseDate = Date.today().addDays(3),
                TotalOpportunityQuantity = 10,
                BusinessCode__c = '1234',
                ProductId__c = p.Id, 
                StageName = 'Closed Won');
            insert opp;

            // Creamos la task asociada a la oferta cerrada -> Tiene que funcionar
            
            Task interactionTask = new Task(
                Subject = 'Llamada ' + Datetime.now().format(),
                Status = 'Nueva',
                Priority = 'Normal',
                CallObject = 'ABCD12345',
                WhoId = customer.Id,
                TaskSubtype = 'Call',
                Type = 'Call', 
                OwnerId = u.Id,
                WhatId = opp.Id
            );
        
            Test.startTest();
            insert interactionTask;
            Test.stopTest();
        }

        // Comprobamos que se haya modificado la oferta
        List<Opportunity> oportunidades  = [SELECT Id, Name, OwnerId FROM Opportunity WHERE StageName like 'Closed Won']; 
        System.assertEquals(1, oportunidades.size(), 'Ha de haber una oferta insertada');
        System.assertEquals(u.id, oportunidades.get(0).OwnerId, 'EL owner de la oferta ha de ser el usuario que corre el test');

        // Comprobamos que se haya insertado la task
        List<Task> tareas = [SELECT Id, OwnerId FROM Task WHERE WhatId = :oportunidades.get(0).id];
        System.assertEquals(1, tareas.size(), 'Ha de haber una tarea insertada para la oferta de la que disponemos');

    }

    // Corremos el test como User que no es ZE Supervisor, pero como no cambiamos de OwnerId a la oferta, tiene que funcionar bien.
    @isTest
    static void test_runAsZEUser_SupervisorFalse_OK() {

        // Julio Fabeiro Garcia tiene a True el flag "isZESupervisor__c"
        User u = [SELECT Id, IsZESupervisor__c FROM User WHERE Name='Julio Fabeiro Garcia'];

        System.runAs(u) {

            // The following code runs as user 'u'
            System.debug('Current User: ' + UserInfo.getUserName());
            System.debug('Is ZE Supervisor: ' + u.IsZESupervisor__c);

            Account acc = new Account(Name = 'New Account 1');
            insert acc;

            Contact customer = new Contact(
            Email = 'edu@test.com',
            MobilePhone = '675887723',
            DNI__c = '05289654W',
            Birthdate = Date.valueOf('1990-01-01'),
            FirstName = 'Edu',
            LastName = 'Sanchez',
            CustomerNum__c = 'GI-3123',
            LegalEntity__c = Label.GeneralInsurance,
            RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.CustomerGI),
            AccountId = acc.Id
            );
        
            insert customer;

            Product2 p = new Product2
            (
                Name = 'Product test 1',
                GroupDescription__c = 'Group 1',
                INFO_Product_Number__c = '00800-00001'
            );
            insert p;

            User u2 = [SELECT Id FROM User WHERE Name='Agustin Angel Zapata Mendez'];

            Opportunity opp = new Opportunity(
                AccountId = acc.Id,
                Name = 'New Opportunity',
                CloseDate = Date.today().addDays(3),
                TotalOpportunityQuantity = 10,
                BusinessCode__c = '1234',
                ProductId__c = p.Id, 
                StageName = 'Closed Won',
                OwnerId = u.Id);
            insert opp;

            // Creamos la task asociada a la oferta cerrada -> Tiene que funcionar
            
            Task interactionTask = new Task(
                Subject = 'Llamada ' + Datetime.now().format(),
                Status = 'Nueva',
                Priority = 'Normal',
                CallObject = 'ABCD12345',
                WhoId = customer.Id,
                TaskSubtype = 'Call',
                Type = 'Call', 
                OwnerId = u.Id,
                WhatId = opp.Id
            );
        
            Test.startTest();
            insert interactionTask;
            Test.stopTest();
        }

        // Comprobamos que se haya modificado la oferta
        List<Opportunity> oportunidades  = [SELECT Id, Name, OwnerId FROM Opportunity WHERE StageName like 'Closed Won']; 
        System.assertEquals(1, oportunidades.size(), 'Ha de haber una oferta insertada');
        System.assertEquals(u.id, oportunidades.get(0).OwnerId, 'El owner de la oferta ha de ser el usuario que corre el test');

        // Comprobamos que se haya insertado la task
        List<Task> tareas = [SELECT Id, OwnerId FROM Task WHERE WhatId = :oportunidades.get(0).id];
        System.assertEquals(1, tareas.size(), 'La oferta se ha debido de insertar bien');
    }


    // Corremos el test como User que no es ZE Supervisor, pero como cambiamos de OwnerId a la oferta, tiene que fallar.

    @isTest
    static void test_runAsZEUser_SupervisorFalse_NOK() {

        // Julio Fabeiro Garcia tiene a True el flag "isZESupervisor__c"
        User u = [SELECT Id, IsZESupervisor__c FROM User WHERE Name='Julio Fabeiro Garcia'];

        System.runAs(u) {

            // The following code runs as user 'u'
            System.debug('Current User: ' + UserInfo.getUserName());
            System.debug('Is ZE Supervisor: ' + u.IsZESupervisor__c);

            Account acc = new Account(Name = 'New Account 1');
            insert acc;

            Contact customer = new Contact(
            Email = 'edu@test.com',
            MobilePhone = '675887723',
            DNI__c = '05289654W',
            Birthdate = Date.valueOf('1990-01-01'),
            FirstName = 'Edu',
            LastName = 'Sanchez',
            CustomerNum__c = 'GI-3123',
            LegalEntity__c = Label.GeneralInsurance,
            RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.CustomerGI),
            AccountId = acc.Id
            );
        
            insert customer;

            Product2 p = new Product2
            (
                Name = 'Product test 1',
                GroupDescription__c = 'Group 1',
                INFO_Product_Number__c = '00800-00001'
            );
            insert p;

            User u2 = [SELECT Id FROM User WHERE Name='Agustin Angel Zapata Mendez'];

            Opportunity opp = new Opportunity(
                AccountId = acc.Id,
                Name = 'New Opportunity',
                CloseDate = Date.today().addDays(3),
                TotalOpportunityQuantity = 10,
                BusinessCode__c = '1234',
                ProductId__c = p.Id, 
                StageName = 'Closed Won',
                OwnerId = u2.Id);
            insert opp;

            // Creamos la task asociada a la oferta cerrada -> Tiene que funcionar
            
            Task interactionTask = new Task(
                Subject = 'Llamada ' + Datetime.now().format(),
                Status = 'Nueva',
                Priority = 'Normal',
                CallObject = 'ABCD12345',
                WhoId = customer.Id,
                TaskSubtype = 'Call',
                Type = 'Call', 
                OwnerId = u.Id,
                WhatId = opp.Id
            );
        
            Test.startTest();
            try
            {
                insert interactionTask;
            }
            catch(DmlException e) {
                System.debug('The following exception has occurred: ' + e.getMessage());
                System.assert( e.getMessage().contains('INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY'), e.getMessage());
            }

            Test.stopTest();
        }

        // Comprobamos que se haya modificado la oferta
        List<Opportunity> oportunidades  = [SELECT Id, Name, OwnerId FROM Opportunity WHERE StageName like 'Closed Won']; 
        System.assertEquals(1, oportunidades.size(), 'Ha de haber una oferta insertada');
        System.assertNotEquals(u.id, oportunidades.get(0).OwnerId, 'El owner de la oferta ha de ser el usuario que corre el test');

        // Comprobamos que se haya insertado la task
        List<Task> tareas = [SELECT Id, OwnerId FROM Task WHERE WhatId = :oportunidades.get(0).id];
        System.assertEquals(0, tareas.size(), 'No se ha debido de insertar la oferta');
    }
}