force-app/zurich-base/main/default/objects/Account/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generated to identify a customer</description>
    <externalId>true</externalId>
    <inlineHelpText>Code that IBA generated to identify a customer</inlineHelpText>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Masterpolicy__c.field-meta.xml
<CustomField>
    <fullName>Masterpolicy__c</fullName>
    <description>Partner identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>Masterpolicy</inlineHelpText>
    <label>Código partner</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/Master.recordType-meta.xml
<RecordType>
    <fullName>Master</fullName>
    <active>true</active>
    <label>Master</label>
</RecordType>

force-app/zurich-base/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/zurich-base/main/default/objects/Case/fields/ClaimNumber__c.field-meta.xml
<CustomField>
    <fullName>ClaimNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número de siniestro</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/DateReg__c.field-meta.xml
<CustomField>
    <fullName>DateReg__c</fullName>
    <description>Claim creation date</description>
    <label>Fecha creación de siniestro</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/InsuredObjectId__c.field-meta.xml
<CustomField>
    <fullName>InsuredObjectId__c</fullName>
    <description>Hidden field to save the value received from IBA</description>
    <label>InsuredObjectId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad Legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/PolicyNum__c.field-meta.xml
<CustomField>
    <fullName>PolicyNum__c</fullName>
    <externalId>true</externalId>
    <label>Número de póliza</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Siniestro</businessProcess>
    <label>Siniestro</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generates to identify a customer. As for life and non-life is the same number, for life record type, it will have prefix LIFE-XXX and for non-life GI-XXX</description>
    <externalId>true</externalId>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <description>A customer or lead DNI</description>
    <label>DNI</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/IsSubscriber__c.field-meta.xml
<CustomField>
    <fullName>IsSubscriber__c</fullName>
    <defaultValue>false</defaultValue>
    <description>KLINC: Indica si un contacto se ha dado de alta como suscriptor en la newsletter. Se rellena en el procesamiento tras darse de alta mediante el formulario Web-to-Lead.</description>
    <label>Subscriber</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to</description>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MasterPolicy__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Specifies if the contact comes from a partner. Linked to the partner acccount.</description>
    <label>Masterpolicy</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/MasterPolicyNum__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyNum__c</fullName>
    <label>Masterpolicy Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/recordTypes/CustomerLife.recordType-meta.xml
<RecordType>
    <fullName>CustomerLife</fullName>
    <active>true</active>
    <label>Cliente vida</label>
</RecordType>

force-app/zurich-base/main/default/objects/Cover__c/Cover__c.object-meta.xml
<CustomObject>
    <label>Cobertura</label>
    <nameField>
        <label>Nombre de Cobertura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coberturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Cover__c/fields/CoverId__c.field-meta.xml
<CustomField>
    <fullName>CoverId__c</fullName>
    <externalId>true</externalId>
    <label>Cover ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descripción</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to, used to set access with sharing rules</description>
    <label>Entidad legal</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/ParentCoverId__c.field-meta.xml
<CustomField>
    <fullName>ParentCoverId__c</fullName>
    <label>ParentCoverId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cover__c/fields/SumInsured__c.field-meta.xml
<CustomField>
    <fullName>SumInsured__c</fullName>
    <label>Capital asegurado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/zurich-base/main/default/objects/ErrorManagementSetting__mdt/ErrorManagementSetting__mdt.object-meta.xml
<CustomObject>
    <label>ErrorManagementSetting</label>
    <pluralLabel>ErrorManagementSetting</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/Order/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes y Pólizas</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <label>Customer Num</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/Masterpolicy__c.field-meta.xml
<CustomField>
    <fullName>Masterpolicy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Masterpolicy</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Polizas</relationshipLabel>
    <relationshipName>Polizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/MasterPolicyDescr__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyDescr__c</fullName>
    <label>Masterpolicy description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/MasterPolicyNum__c.field-meta.xml
<CustomField>
    <fullName>MasterPolicyNum__c</fullName>
    <label>Masterpolicy Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/PolicyContractSerial__c.field-meta.xml
<CustomField>
    <fullName>PolicyContractSerial__c</fullName>
    <label>Versión de póliza</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/PolicyContractStartDate__c.field-meta.xml
<CustomField>
    <fullName>PolicyContractStartDate__c</fullName>
    <label>Fecha inicio versión póliza</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/PolicyNum__c.field-meta.xml
<CustomField>
    <fullName>PolicyNum__c</fullName>
    <externalId>true</externalId>
    <label>Número de la póliza</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/QuoteEntry__c.field-meta.xml
<CustomField>
    <fullName>QuoteEntry__c</fullName>
    <externalId>true</externalId>
    <label>Quote entry</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/SumInsured__c.field-meta.xml
<CustomField>
    <fullName>SumInsured__c</fullName>
    <description>Klinc. Suma asegurada para Xiaomi Multidevice</description>
    <label>Sum Insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/recordTypes/QuoteGI.recordType-meta.xml
<RecordType>
    <fullName>QuoteGI</fullName>
    <active>true</active>
    <label>Quote GI</label>
</RecordType>

force-app/zurich-base/main/default/objects/OrderItem/fields/ItemAge__c.field-meta.xml
<CustomField>
    <fullName>ItemAge__c</fullName>
    <description>Product age in months</description>
    <inlineHelpText>Product age in months</inlineHelpText>
    <label>Antigüedad</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/OrderItem/fields/ItemId__c.field-meta.xml
<CustomField>
    <fullName>ItemId__c</fullName>
    <description>Unique identifier or an insured product</description>
    <externalId>true</externalId>
    <label>Item Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/PricebookEntry/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <externalId>true</externalId>
    <label>ProductID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <description>Field to be used as external ID of the product</description>
    <externalId>true</externalId>
    <label>ProductID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Test_SystemUtil.cls
/**
 * Clases de test para SystemUtil
 **
 * @author nts
 * @date 24/02/2020
 */
@isTest(SeeAllData=false)
public class Test_SystemUtil
{
    @testSetup
    static void makeData()
    {
        // Instantiate the Pricebook2 record first, setting the Id
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
            );

        //Execute an update DML on the Pricebook2 record, to make IsStandard to true
        update standardPricebook;

        // Create the Product
        Product2 testProduct = new Product2(
            Name = 'Test Product',
            IsActive = true,
            ProductID__c = 'Test Product'
            );
        insert testProduct;

        // Create the PricebookEntry
        PricebookEntry testPbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = testProduct.Id,
            UnitPrice = 100,
            IsActive = true
            );

        insert testPbe;

        Account master = new Account(CustomerNum__c = '4747', Name = 'Test');
        insert (master);

        Account masterRef = new Account(CustomerNum__c = '4747');

        Contact customer = new Contact(
            DNI__c = '44348579Ñ',
            Email = 'andrea11@test.com',
            Birthdate = Date.valueOf('1990-01-01'),
            FirstName = 'test',
            LastName = 'Gomez',
            CustomerNum__c = '454545',
            LegalEntity__c = Label.GeneralInsurance
            );
        customer.Account = masterRef;
        insert (customer);

        Contact contactRef = new Contact(CustomerNum__c = '454545');

        Order quote = new Order(
            EffectiveDate = Date.valueOf('1994-01-01'),
            CustomerNum__c = '4747',
            LegalEntity__c = Label.LifeInsurance,
            QuoteEntry__c = '333333',
            Status = 'Sync'
            );

        String legalEntityName;
        if ( quote.LegalEntity__c.equals(Label.GeneralInsurance) )
        {
            legalEntityName = 'GI';
        }
        else
        {
            legalEntityName = 'Life';
        }
        quote.RecordTypeId = SystemUtil.getOrderRecordTypeIdByName(
            'Quote' + legalEntityName
            );
        quote.Pricebook2Id = standardPricebook.Id;
        quote.Account = masterRef;
        quote.ContactId__r = contactRef;
        insert (quote);


        Order quoteRef = new Order(QuoteEntry__c = '333333');

        OrderItem oi = new OrderItem(
            ItemAge__c = 2,
            itemId__c = '111111',
            UnitPrice = 0,
            Quantity = 1
            );
        oi.Order = quoteRef;
        oi.PricebookEntryId = testPbe.Id;

        insert (oi);

    }

    @IsTest
    static void test_getSettings()
    {
        Test.startTest();
        ErrorManagementSetting__mdt setupErrors = SystemUtil.getErrorLogSettingsMetadata();
        System.assert (
            setupErrors != null,
            'Test_SystemUtil: No se ha recuperado correctamente ErrorManagementSetting__mdt para ErrorLogUtil'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_maskEmail()
    {
        String emailToMask = 'test@example.com';
        String code = '00001';
        Test.startTest();
        String maskedEmail = SystemUtil.maskEmail(emailToMask, code);
        System.assertEquals(
            'test@00001-mng.dev',
            maskedEmail,
            'No se ha enmascarado correctamente el email'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_isValidDate()
    {
        Test.startTest();
        String validDate = '2012-01-12';
        System.assert (
            SystemUtil.isValidDate(validDate),
            'No ha detectado correctamente una fecha válida'
            );
        String invalidDate = '23-13-1999';
        System.assert (
            !SystemUtil.isValidDate(invalidDate),
            'No ha detectado correctamente una fecha invalida'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getExternalRequest()
    {
        Test.startTest();
        System.assert (
            String.isNotBlank( Systemutil.getExternalRequests() ),
            'No se ha podido recuperar la query de external request'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getProcessedExternalRequests()
    {
        Test.startTest();
        System.assert (
            String.isNotBlank( Systemutil.getProcessedExternalRequests() ),
            'No se ha podido recuperar la query de processed external request'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getOldExternalRequests()
    {
        Test.startTest();
        System.assert (
            String.isNotBlank( Systemutil.getOldExternalRequests() ),
            'No se ha podido recuperar la query de old external request'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getErrorLogs()
    {
        Test.startTest();
        System.assert (
            String.isNotBlank( Systemutil.getErrorLogs() ),
            'No se ha podido recuperar la query de error logs'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getQuotesToDelete()
    {
        Test.startTest();
        System.assert (
            String.isNotBlank( Systemutil.getQuotesToDelete() ),
            'No se ha podido recuperar la query de quotes para borrar'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getLeadsToDelete()
    {
        Test.startTest();
        System.assert (
            String.isNotBlank( Systemutil.getLeadsToDelete() ),
            'No se ha podido recuperar la query de leads para borrar'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getMastersToDelete()
    {
        Test.startTest();
        System.assert (
            String.isNotBlank( Systemutil.getMastersToDelete() ),
            'No se ha podido recuperar la query de masters para borrar'
            );
        Test.stopTest();
    }
    @IsTest
    static void test_getContactRecordTypeIdByName()
    {
        Test.startTest();
        String id = SystemUtil.getContactRecordTypeIdByName(Label.CustomerLife);

        System.assert (
            String.isNotBlank(id),
            'No se ha podido recuperar el record type id de contacto'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getAccountRecordTypeIdByName()
    {
        Test.startTest();
        String id = SystemUtil.getAccountRecordTypeIdByName(Label.Master);

        System.assert (
            String.isNotBlank(id),
            'No se ha podido recuperar el record type id de cuenta'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getOrderRecordTypeIdByName()
    {
        Test.startTest();
        String id = SystemUtil.getOrderRecordTypeIdByName(Label.QuoteGI);

        System.assert (
            String.isNotBlank(id),
            'No se ha podido recuperar el record type id de order'
            );
        Test.stopTest();
    }

    static void test_getClaimRecordTypeIdByName()
    {
        Test.startTest();
        String id = SystemUtil.getClaimRecordType();

        System.assert (
            String.isNotBlank(id),
            'No se ha podido recuperar el record type id de claim'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_PartnerSelector()
    {
        Account partner = new Account(
            Name = 'test',
            Masterpolicy__c = '121',
            RecordTypeId = SystemUtil.getAccountRecordTypeIdByName(Label.Partner)
            );
        insert (partner);
        Map<String, Account> mapa = new Map<String, Account>();

        SET<String> keys = new Set<String>();
        keys.add(partner.Masterpolicy__c);

        Test.startTest();
        mapa = SystemUtil.PartnerSelector(keys);
        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar los partners'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_ContactsSelector()
    {
        Map<String, Contact> mapa = new Map<String, Contact>();
        SET<String> keys = new Set<String>();
        keys.add('454545');

        Test.startTest();
        mapa = SystemUtil.ContactsSelector(keys);

        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar los contactos'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_ContactsSelectorEmail()
    {
        Map<String, List<Contact> > mapa = new Map<String, List<Contact> >();
        SET<String> keys = new Set<String>();
        keys.add('andrea11@test.com');

        Test.startTest();
        mapa = SystemUtil.contactsSelectorEmail(keys);

        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar los contactos'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_contactsSelectorSubscribers()
    {
        Contact subscriber = new Contact (
            Email = 'testexisting@test.com',
            LastName = 'Test',
            IsSubscriber__c  = true
            );

        insert subscriber;

        Map<String, List<Contact> > mapa = new Map<String, List<Contact> >();
        SET<String> keys = new Set<String>();
        keys.add('testexisting@test.com');

        SET<String> mobiles = new Set<String>();

        Test.startTest();
        SystemUtil.contactsSelectorMatchCode(keys, mobiles, null, null, null, mapa);
        // mapa = SystemUtil.contactsSelectorSubscribers(keys);

        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar los contactos'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getQuoteSameProduct()
    {

        Map<String, List<Order> > mapa = new Map<String, List<Order> >();
        SET<String> customerNum = new Set<String>();
        customerNum.add('454545');
        SET<String> products = new Set<String>();
        products.add('Test Product');

        Test.startTest();
        mapa = SystemUtil.getQuoteSameProduct( customerNum,  products);

        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar las quotes'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getSubscribers()
    {
        Test.startTest();
        System.assert (
            String.isNotBlank( Systemutil.getSubscribers() ),
            'No se ha podido recuperar la query de error logs'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_ContactsSelectorEmailBirthDate()
    {
        Map<String, Contact> mapa1 = new Map<String, Contact>();
        Map<String, Contact> mapa2 = new Map<String, Contact>();
        Map<String, Contact> mapa3 = new Map<String, Contact>();

        SET<String> keys = new Set<String>();
        keys.add('andrea11@test.com');

        SET<String> mobiles = new Set<String>();

        Test.startTest();
        SystemUtil.contactsSelectorMatchCode(keys, mobiles, mapa1, mapa2, mapa3, null);

        System.assert (
            !mapa1.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar los contactos con email y fecha de nacimiento'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_PolicySelector()
    {
        Account master = new Account(CustomerNum__c = '454545', Name = 'Test');
        insert (master);
        Account masterRef = new Account(CustomerNum__c = '454545');
        Order policy = new Order(
            EffectiveDate = Date.valueOf('1990-01-02'),
            CustomerNum__c = '454545',
            PolicyNum__c = '1010',
            PolicyContractSerial__c = '1010-5',
            PolicyContractStartDate__c = Date.valueOf('1990-02-02'),
            LegalEntity__c = Label.GeneralInsurance,
            QuoteEntry__c = '',
            MasterPolicyNum__c = '22',
            MasterPolicyDescr__c = 'Rastreator2',
            Status = 'Sync'
            );
        policy.Account = masterRef;
        String legalEntityName;
        if ( policy.LegalEntity__c.equals(Label.GeneralInsurance) )
        {
            legalEntityName = 'GI';
        }
        else
        {
            legalEntityName = 'Life';
        }
        policy.RecordTypeId = SystemUtil.getOrderRecordTypeIdByName(
            'Policy' + legalEntityName
            );
        insert (policy);
        Map<String, Order> mapa = new Map<String, Order>();

        SET<String> keys = new Set<String>();
        keys.add(policy.PolicyNum__c);

        Test.startTest();
        mapa = SystemUtil.PolicySelector(keys);
        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar las polizas'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_QuoteSelector()
    {
        Map<String, Order> mapa = new Map<String, Order>();
        SET<String> keys = new Set<String>();
        keys.add('333333');

        Test.startTest();
        mapa = SystemUtil.QuoteSelector(keys);
        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar los quotes'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_OrderItemSelector()
    {
        Order quoteRef = new Order(QuoteEntry__c = '333333');
        PricebookEntry testPbe = [
            SELECT Id, Pricebook2.IsStandard
            FROM PricebookEntry
        ];

        OrderItem oi = new OrderItem(
            ItemAge__c = 2,
            itemId__c = '646464',
            UnitPrice = 0,
            Quantity = 1
            );
        oi.Order = quoteRef;
        oi.PricebookEntryId = testPbe.Id;

        insert (oi);
        Map<String, OrderItem> mapa = new Map<String, OrderItem>();

        SET<String> keys = new Set<String>();
        keys.add(oi.itemId__c);
        Test.startTest();
        mapa = SystemUtil.OrderItemSelector(keys);
        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar los order items'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_ProductsSelector()
    {
        Map<String, PricebookEntry> mapa = new Map<String, PricebookEntry>();
        SET<String> keys = new Set<String>();
        keys.add('Test Product');

        Test.startTest();
        mapa = SystemUtil.ProductsSelector(keys);
        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar los productos'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_getStandardPricebook()
    {
        Pricebook2 pb = new Pricebook2();

        Test.startTest();
        pb = SystemUtil.getStandardPricebook();
        System.assert (
            pb != null,
            'Test_SystemUtil: No se han podido recuperar el standard pricebook'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_CoversSelector()
    {
        Map<String, Cover__c> mapa = new Map<String, Cover__c>();
        Cover__c cover = new Cover__c(
            CoverId__c = '1',
            ParentCoverId__c = null,
            Name = 'Robo',
            Description__c = 'Cobertura por robo',
            SumInsured__c = 1000,
            LegalEntity__c = Label.LifeInsurance
            );
        insert cover;

        SET<String> keys = new Set<String>();
        keys.add(cover.CoverId__c);

        Test.startTest();
        mapa = SystemUtil.CoversSelector(keys);
        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar los covers'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_ClaimsSelector()
    {
        Case claim = new Case(
            ClaimNumber__c = '797',
            PolicyNum__c = '8989',
            CustomerNum__c = '3123',
            LegalEntity__c = Label.GeneralInsurance,
            DateReg__c = Date.valueOf('2020-01-02'),
            InsuredObjectId__c = '123456789',
            RecordTypeId = SystemUtil.getClaimRecordType()
            );
        insert claim;
        Map<String, Case> mapa = new Map<String, Case>();

        SET<String> keys = new Set<String>();
        keys.add(claim.ClaimNumber__c);

        Test.startTest();
        mapa = SystemUtil.ClaimsSelector(keys);
        System.assert (
            !mapa.isEmpty(),
            'Test_SystemUtil: No se han podido recuperar los siniestros'
            );
        Test.stopTest();
    }

    @IsTest
    static void test_createJSON()
    {
        String json;
        ID identifier = 'a085E00000ARPh3QAH';

        Test.startTest();
        json = SystemUtil.createJSON(
            identifier,
            'errorCode',
            'errorDescription',
            Datetime.now(),
            'Origin',
            'Country',
            'Entity',
            Datetime.now(),
            'Json'
            );
        System.assert (
            !String.isBlank(json),
            'Test_SystemUtil: No se han podido crear el json'
            );
        Test.stopTest();
    }
}