force-app/zurich-base/main/default/objects/Account/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generated to identify a customer</description>
    <externalId>true</externalId>
    <inlineHelpText>Code that IBA generated to identify a customer</inlineHelpText>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <description>Code that IBA generates to identify a customer. As for life and non-life is the same number, for life record type, it will have prefix LIFE-XXX and for non-life GI-XXX</description>
    <externalId>true</externalId>
    <label>Customer Num</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <description>A customer or lead DNI</description>
    <label>DNI</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to</description>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/recordTypes/CustomerGI.recordType-meta.xml
<RecordType>
    <fullName>CustomerGI</fullName>
    <active>true</active>
    <label>Cliente no vida</label>
</RecordType>

force-app/zurich-base/main/default/objects/Order/fields/CustomerNum__c.field-meta.xml
<CustomField>
    <fullName>CustomerNum__c</fullName>
    <label>Customer Num</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Order/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Order/recordTypes/PolicyGI.recordType-meta.xml
<RecordType>
    <fullName>PolicyGI</fullName>
    <active>true</active>
    <label>Póliza GI</label>
</RecordType>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/OrdersSelectorTest.cls
@isTest
private without sharing class OrdersSelectorTest {

    @TestSetup
    public static void createScenario()
    {
        Account newMaster = new Account(Name = 'test', CustomerNum__c = '3123');
        insert newMaster;

        Contact customer = new Contact(
            Email = 'edu@test.com',
            MobilePhone = '675887723',
            DNI__c = '05289654W',
            Birthdate = Date.valueOf('1990-01-01'),
            FirstName = 'Edu',
            LastName = 'Sanchez',
            CustomerNum__c = 'GI-3123',
            LegalEntity__c = Label.GeneralInsurance,
            RecordTypeId = SystemUtil.getContactRecordTypeIdByName(Label.CustomerGI),
            AccountId = newMaster.Id
            );
        insert customer;

        //Generar 10 orders para que las querys devuelvan un listado
        List<Order> orders = TestDataFactory.generateOrdersKlinc(newMaster.Id, customer.Id, customer.CustomerNum__c, Label.PolicyGI, 10);
        insert orders;
    }

    @IsTest
    static void test_selectByDNI_ok()
    {
        // Comprobaciones iniciales
        List<Order> orders = [SELECT Id FROM Order];
        System.assertEquals(false, orders.isEmpty(), 'Orders list should NOT be empty');

        Test.startTest();
        List<Order> matchedRecords = new OrdersSelector().selectByDNI('05289654W'); //El DNI es el del TestSetup
        Test.stopTest();

        //El tamaño de la lista depende de lo generado en el TestSetup
        System.assertEquals(10, matchedRecords.size(), 'List should NOT be empty');
    }

    @IsTest
    static void test_selectByDNI_ko()
    {
        // Comprobaciones iniciales
        List<Order> orders = [SELECT Id FROM Order];
        System.assertEquals(false, orders.isEmpty(), 'Orders list should NOT be empty');

        Test.startTest();
        OrdersSelector ordersSelector = new OrdersSelector();
        ordersSelector.setFields(new List<Schema.SobjectField>{Order.Id});
        List<Order> matchedRecords = ordersSelector.selectByDNI('noExisteEsteDNI'); //El DNI NO es el del TestSetup
        Test.stopTest();

        //El tamaño de la lista depende de lo generado en el TestSetup
        System.assertEquals(0, matchedRecords.size(), 'List should be empty');
    }

    @IsTest
    static void test_selectByEmail_ok()
    {
        // Comprobaciones iniciales
        List<Order> orders = [SELECT Id FROM Order];
        System.assertEquals(false, orders.isEmpty(), 'Orders list should NOT be empty');

        Test.startTest();
        List<Order> matchedRecords = new OrdersSelector().selectByEmail('edu@test.com'); //El Email es el del TestSetup
        Test.stopTest();

        //El tamaño de la lista depende de lo generado en el TestSetup
        System.assertEquals(10, matchedRecords.size(), 'List should NOT be empty');
    }

    @IsTest
    static void test_selectByEmail_ko()
    {
        // Comprobaciones iniciales
        List<Order> orders = [SELECT Id FROM Order];
        System.assertEquals(false, orders.isEmpty(), 'Orders list should NOT be empty');

        Test.startTest();
        OrdersSelector ordersSelector = new OrdersSelector();
        ordersSelector.setFields(new List<Schema.SobjectField>{Order.Id});
        List<Order> matchedRecords = ordersSelector.selectByEmail('no@existe.com'); //El Email NO es el del TestSetup
        Test.stopTest();

        //El tamaño de la lista depende de lo generado en el TestSetup
        System.assertEquals(0, matchedRecords.size(), 'List should be empty');
    }

    @IsTest
    static void test_selectByMobilePhone_ok()
    {
        // Comprobaciones iniciales
        List<Order> orders = [SELECT Id FROM Order];
        System.assertEquals(false, orders.isEmpty(), 'Orders list should NOT be empty');

        Test.startTest();
        List<Order> matchedRecords = new OrdersSelector().selectByMobilePhone('675887723'); //El MobilePhone es el del TestSetup
        Test.stopTest();

        //El tamaño de la lista depende de lo generado en el TestSetup
        System.assertEquals(10, matchedRecords.size(), 'List should NOT be empty');
    }

    @IsTest
    static void test_selectByMobilePhone_ko()
    {
        // Comprobaciones iniciales
        List<Order> orders = [SELECT Id FROM Order];
        System.assertEquals(false, orders.isEmpty(), 'Orders list should NOT be empty');

        Test.startTest();
        OrdersSelector ordersSelector = new OrdersSelector();
        ordersSelector.setFields(new List<Schema.SobjectField>{Order.Id});
        List<Order> matchedRecords = ordersSelector.selectByMobilePhone('666778899'); //El MobilePhone NO es el del TestSetup
        Test.stopTest();

        //El tamaño de la lista depende de lo generado en el TestSetup
        System.assertEquals(0, matchedRecords.size(), 'List should be empty');
    }


}