force-app/zurich-base/main/default/objects/Account/fields/INFOIntermediaryCode__c.field-meta.xml
<CustomField>
    <fullName>INFOIntermediaryCode__c</fullName>
    <description>(OCS). Identificador único de intermediario</description>
    <externalId>true</externalId>
    <label>Intermediary Code</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>Comprende aquellos posibles clientes todavía no existentes en el sistema transaccional</description>
    <label>Lead</label>
</RecordType>

force-app/zurich-base/main/default/objects/Case/fields/ClaimId__c.field-meta.xml
<CustomField>
    <fullName>ClaimId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OCS</description>
    <label>Claim Name</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/HegeoClaimId__c.field-meta.xml
<CustomField>
    <fullName>HegeoClaimId__c</fullName>
    <label>Hegeo Claim Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/HegeoIntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>HegeoIntermediaryId__c</fullName>
    <label>Robot Intermediary Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/HegeoOfferId__c.field-meta.xml
<CustomField>
    <fullName>HegeoOfferId__c</fullName>
    <label>Hegeo Offer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/HegeoPolicyId__c.field-meta.xml
<CustomField>
    <fullName>HegeoPolicyId__c</fullName>
    <label>Hegeo Policy Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/HegeoPrePolicyId__c.field-meta.xml
<CustomField>
    <fullName>HegeoPrePolicyId__c</fullName>
    <label>Hegeo PrePolicy Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/OfferId__c.field-meta.xml
<CustomField>
    <fullName>OfferId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OCS</description>
    <label>Offer Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Policy to which is related to</description>
    <label>Póliza</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/fields/PolicyId__c.field-meta.xml
<CustomField>
    <fullName>PolicyId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OCS</description>
    <label>Policy Name</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Case/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <businessProcess>Siniestro</businessProcess>
    <label>Siniestro</label>
</RecordType>

force-app/zurich-base/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>OCS</description>
    <label>Siniestro</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Siniestros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Claim__c/fields/INFOClaimNumber__c.field-meta.xml
<CustomField>
    <fullName>INFOClaimNumber__c</fullName>
    <description>OCS</description>
    <externalId>true</externalId>
    <label>INFO Claim Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <description>(OCS). Puntero a la póliza vinculada</description>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Opportunity/fields/InfoQuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>InfoQuoteNumber__c</fullName>
    <description>(ZE/OCS) identificador de la oferta en INFO.</description>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/InfoPolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>InfoPolicyNumber__c</fullName>
    <description>(OCS). Identificador único de la póliza.</description>
    <externalId>true</externalId>
    <label>INFO Policy Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/InfoQuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>InfoQuoteNumber__c</fullName>
    <label>Quote Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/classes/NoteInfoLookupBatchTest.cls
/**
 * Test the methods in the class noteInfoLookupBatch
 * 
 * @author nts (agonzalezisasi)
 * @date 28/04/2021
 */
@isTest
private class NoteInfoLookupBatchTest
{

	/**
	 * Offer
	 *      Opportunity -> InfoQuoteNumber__c
	 *      HegeoPrePolicyId__c, HegeoOfferId__c => OfferId__c
	 * Account
	 * 		Account -> INFOIntermediaryCode__c
	 * 		HegeoIntermediaryId__c => AccountId
	 * Policy
	 * 		Policy__c -> InfoPolicyNumber__c
	 * 		HegeoPolicyId__c => PolicyId__c
	 * Claim
	 * 		Claim__c -> INFOClaimNumber__c
	 * 		HegeoClaimId__c => ClaimId__c
	 */
	@testSetup 
	static void makedata()
	{
		// PreOffer + Account
		Case notePreOffer = new Case(Subject= 'note preoffer', Origin=NoteInfoLookupBatch.NOTE_CASE_ORIGIN);
		notePreOffer.HegeoPrePolicyId__c = String.valueOf(1).leftPad(9, '0');
		notePreOffer.HegeoIntermediaryId__c = String.valueOf(1).leftPad(9, '0');
		insert notePreOffer;

		// Offer + Account + Policy + Claim
		Case noteOffer = new Case(Subject= 'note offer', Origin=NoteInfoLookupBatch.NOTE_CASE_ORIGIN);
		noteOffer.HegeoOfferId__c = String.valueOf(2).leftPad(9, '0');
		noteOffer.HegeoIntermediaryId__c = String.valueOf(2).leftPad(9, '0');
		noteOffer.HegeoPolicyId__c = String.valueOf(2).leftPad(9, '0');
		noteOffer.HegeoClaimId__c = String.valueOf(2).leftPad(9, '0');
		insert noteOffer;
	}

	/**
	 * Creates the parents sobject to be found by the batch for the Note (case)
	 * 
	 * @param {Integer i} numeric secuence to create differnt test cases
	 * @param {Boolean bCreatePolicy} if insert a policy (true) or not (false)
	 * @param {Boolean bCreateClaim} if insert a claim (true) or not (false)
	 * @param {Boolean bCreateOffer} if insert an Offer-Opportunity (true) or not (false)
	 */
	private static void generateNoteRelatedData(Integer i, Boolean bCreatePolicy, Boolean bCreateClaim, Boolean bCreateOffer) {
		Account a = new Account(
			LastName= 'acc test note ' + i,
			INFOIntermediaryCode__c= String.valueOf(i).leftPad(9, '0')
		);
		insert a;
	
		if( bCreatePolicy ) {
			Policy__c p = new Policy__c(
				Name= String.valueOf(i).leftPad(9, '0'),
				InfoPolicyNumber__c = String.valueOf(i).leftPad(9, '0')
			);
			insert p;
		}
	
		if( bCreateClaim ) {
			Claim__c c = new Claim__c(
				Name= String.valueOf(i).leftPad(9, '0'),
				InfoClaimNumber__c = String.valueOf(i).leftPad(9, '0')
			);
			insert c;
		}
	
		if( bCreateOffer ) {
			Date d = Date.today().addDays(10);
			Opportunity o = new Opportunity(
				Name= String.valueOf(i).leftPad(9, '0'),
				CloseDate= d,
				StageName= 'Legit Lead',
				InfoQuoteNumber__c= String.valueOf(i).leftPad(9, '0')
			);
			insert o;
		}
	}

	/**
	 * Test of the batch execution
	 */
	@isTest 
	static void execute() {
		generateNoteRelatedData(1, false, false, true);
		generateNoteRelatedData(2, true, true, true);
		
		
		

		Test.startTest();
		NoteInfoLookupBatch m = new NoteInfoLookupBatch();
		Id batchId = Database.executeBatch(m);
		Test.stopTest();

		Case notePreOffer = [SELECT Id, OfferId__c, AccountId FROM Case WHERE Subject = 'note preoffer'];
		System.assertNotEquals(null, notePreOffer.OfferId__c, 'For PreOffer, the OfferId should not be null');
		System.assertNotEquals(null, notePreOffer.AccountId, 'For PreOffer, the AccountId should not be null');
		Case noteOffer = [SELECT Id, OfferId__c, AccountId, PolicyId__c, ClaimId__c FROM Case WHERE Subject = 'note offer'];
		System.assertNotEquals(null, noteOffer.OfferId__c, 'For Offer, the OfferId should not be null');
		System.assertNotEquals(null, noteOffer.AccountId, 'For Offer, the AccountId should not be null');
		System.assertNotEquals(null, noteOffer.PolicyId__c, 'For Offer, the PolicyId should not be null');
		System.assertNotEquals(null, noteOffer.ClaimId__c, 'For Offer, the ClaimId should not be null');
	}

	@isTest
	static void execute_ko()
	{
		generateNoteRelatedData(1, false, false, true);
		
		Test.startTest();
		NoteInfoLookupBatch m = new NoteInfoLookupBatch('Select'); // for coverage
		m = new NoteInfoLookupBatch();
		m.listHegeoExternal[0].parentSObjectName = 'invalid';
		Id batchId = Database.executeBatch(m);
		Test.stopTest();

		List<Error_Log__c> errors = [SELECT Id, Message__c FROM Error_Log__c];
		System.assertEquals(true, errors.size() > 0, 'There should be errors');
	}

	/**
	 * Test of the batch scheduling
	 */
	@isTest 
	static void schedule() {
		NoteInfoLookupBatch m = new NoteInfoLookupBatch();
		String sch = '20 30 8 10 2 ?';

		Test.startTest();
		String jobID = system.schedule('Test Note Info Lookup batch', sch, m);
		Test.stopTest();
		
	}
}