force-app/zurich-base/main/default/objects/Account/fields/INFOIntermediaryCode__c.field-meta.xml
<CustomField>
    <fullName>INFOIntermediaryCode__c</fullName>
    <description>(OCS). Identificador único de intermediario</description>
    <externalId>true</externalId>
    <label>Intermediary Code</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/TerritorialDirection__c.field-meta.xml
<CustomField>
    <fullName>TerritorialDirection__c</fullName>
    <label>Territorial Direction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/Intermediary.recordType-meta.xml
<RecordType>
    <fullName>Intermediary</fullName>
    <active>true</active>
    <label>Intermediary</label>
</RecordType>

force-app/zurich-base/main/default/objects/CustomerWarning__c/CustomerWarning__c.object-meta.xml
<CustomObject>
    <label>Customer Warning</label>
    <nameField>
        <label>Customer Warning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Warnings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/CustomerWarning__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>TODAY() &lt;  EndDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/CustomerWarning__c/fields/WarningNumber__c.field-meta.xml
<CustomField>
    <fullName>WarningNumber__c</fullName>
    <displayFormat>A-{YY}-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Warning Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/zurich-base/main/default/objects/RelatedAccount__c/RelatedAccount__c.object-meta.xml
<CustomObject>
    <label>Related Account</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Related Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/RelatedAccount__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/RelatedAccount__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <label>Warning</label>
    <referenceTo>CustomerWarning__c</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>RelatedAccounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Special_Condition__c/Special_Condition__c.object-meta.xml
<CustomObject>
    <label>Condición especial</label>
    <nameField>
        <label>Condition Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condiciones especiales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Special_Condition__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>(OCS) Detalle de la condición especial</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Special_Condition__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>(OCS) Fecha en la que vence la condición especial</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Special_Condition__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>(OCS) Fecha en la que entra en vigor la condición especial</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Special_Condition__c/fields/TerritorialDirection__c.field-meta.xml
<CustomField>
    <fullName>TerritorialDirection__c</fullName>
    <label>Territorial Direction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Special_Condition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/classes/WarningAndAgreementViewerControllerTest.cls
@IsTest
public with sharing class WarningAndAgreementViewerControllerTest {

    @TestSetup
    static void makeData()
    {
        List<Account> accounts = TestDataFactory.generateAccounts('001', 'Intermediary', 1);
        for(Account record : accounts){
            record.INFOIntermediaryCode__c = '1122334455';
            record.TerritorialDirection__c =  'DT Madrid';
        }
        insert accounts;

        List<CustomerWarning__c> warnings = new List<CustomerWarning__c>();
        CustomerWarning__c warning = new CustomerWarning__c();
        warning.StartDate__c = System.today();
        warning.Description__c = 'Descripción';
        warnings.add(warning);
        insert(warnings);

        RelatedAccount__c relation = new RelatedAccount__c();
        relation.Warning__c = warning.Id;
        relation.Identifier__c = '1122334455';
        insert(relation); 
        
        List<Special_Condition__c> agreements = new List<Special_Condition__c>();
        Special_Condition__c agreement = new Special_Condition__c();
        agreement.TerritorialDirection__c =  'DT Madrid';
        agreement.Type__c = 'Agreement';
        agreements.add(agreement);
        insert(agreements);
    }

    @IsTest
    static void test_getFields_OK()
    {
        List<WarningAndAgreementViewerController.Field> fields = WarningAndAgreementViewerController.getFields('CustomerWarning__c');

        Map<String, Schema.SObjectType> globalDescribeMap = Schema.getGlobalDescribe(); 
        Schema.SObjectType sObjectTypeObj = globalDescribeMap.get('CustomerWarning__c');
        Schema.DescribeSObjectResult describeSObjectResultObj = sObjectTypeObj.getDescribe();
        Schema.FieldSet fieldSetObj = describeSObjectResultObj.FieldSets.getMap().get('RelatedListFields');
        List<Schema.FieldSetMember> fieldList=  fieldSetObj.getFields(); 

        System.assertEquals(fields.size(), fieldList.size());
    }

    // List<CustomerWarning__c> getWarnings(Account record, String salesforceObject, String recordType)
    @IsTest
    static void test_getWarnings_OK()
    {
        Account account = [SELECT Id, INFOIntermediaryCode__c FROM Account LIMIT 1];
        List<CustomerWarning__c> warnings = WarningAndAgreementViewerController.getWarnings(account, 'CustomerWarning__c', 'Intermediary');

        System.assertEquals(1, warnings.size());
    }

    @IsTest
    static void test_getAgreements_OK()
    {
        Account account = [SELECT Id, INFOIntermediaryCode__c, TerritorialDirection__c FROM Account LIMIT 1];
        List<Special_Condition__c> agreements = WarningAndAgreementViewerController.getAgreements(account, 'Special_Condition__c');

        System.assertEquals(1, agreements.size());
    }

    @IsTest
    static void test_cancelWarnings_OK()
    {
        List<CustomerWarning__c> warnings = [SELECT Id, IsActive__c, EndDate__c FROM CustomerWarning__c];
        WarningAndAgreementViewerController.cancelWarnings(warnings);

        List<CustomerWarning__c> updatedWarnings = [SELECT Id, IsActive__c FROM CustomerWarning__c];
        for(CustomerWarning__c warning : updatedWarnings)
        {
            System.assertEquals(false, warning.IsActive__c);
        }
    }

    @IsTest
    static void test_cancelAgreements_OK()
    {
        List<Special_Condition__c> agreements = [SELECT Id, IsActive__c FROM Special_Condition__c];
        WarningAndAgreementViewerController.cancelAgreements(agreements);

        List<Special_Condition__c> updatedAgreements = [SELECT Id, IsActive__c FROM Special_Condition__c];
        for(Special_Condition__c agreement : updatedAgreements)
        {
            System.assertEquals(false, agreement.IsActive__c);
        }
    }

    @IsTest
    static void test_createRelatedAccount_OK()
    {
        Account account = [SELECT Id, INFOIntermediaryCode__c, TerritorialDirection__c FROM Account LIMIT 1];
        CustomerWarning__c warning = [SELECT Id, IsActive__c, EndDate__c, WarningNumber__c FROM CustomerWarning__c LIMIT 1];

        WarningAndAgreementViewerController.createRelatedAccount(account, warning.WarningNumber__c, 'Intermediary');
        List<RelatedAccount__c> relations = [SELECT Id FROM RelatedAccount__c];
        System.assertEquals(2, relations.size());
    }
}