force-app/zurich-base/main/default/objects/Account/fields/INFOIntermediaryCode__c.field-meta.xml
<CustomField>
    <fullName>INFOIntermediaryCode__c</fullName>
    <description>(OCS). Identificador único de intermediario</description>
    <externalId>true</externalId>
    <label>Intermediary Code</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Intermediary_Name__c.field-meta.xml
<CustomField>
    <fullName>Intermediary_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS/ZE). Relación a la cuenta de intermediario asociada al contacto (Partner o Mediador). Al existir este dato únicamente a nivel de póliza, el CRM lo informa en base al valor de Intermediario de la póliza más reciente</description>
    <label>Intermediary Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Intermediary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/NationalId__c.field-meta.xml
<CustomField>
    <fullName>NationalId__c</fullName>
    <description>(OCS/ZE). Identificador nacional del cliente</description>
    <label>National ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/NationalIdType__c.field-meta.xml
<CustomField>
    <fullName>NationalIdType__c</fullName>
    <description>(OCS/ZE). Tipo de documento de identidad</description>
    <label>National ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>TZ</fullName>
            </value>
            <value>
                <fullName>UA</fullName>
            </value>
            <value>
                <fullName>UG</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>UY</fullName>
            </value>
            <value>
                <fullName>UZ</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>VC</fullName>
            </value>
            <value>
                <fullName>VE</fullName>
            </value>
            <value>
                <fullName>VG</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
            <value>
                <fullName>VU</fullName>
            </value>
            <value>
                <fullName>WF</fullName>
            </value>
            <value>
                <fullName>WS</fullName>
            </value>
            <value>
                <fullName>YE</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
            <value>
                <fullName>ZA</fullName>
            </value>
            <value>
                <fullName>ZM</fullName>
            </value>
            <value>
                <fullName>ZW</fullName>
            </value>
            <value>
                <fullName>T</fullName>
                <isActive>false</isActive>
                <label>T</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/BusinessCustomer.recordType-meta.xml
<RecordType>
    <fullName>BusinessCustomer</fullName>
    <active>true</active>
    <description>Tipo de registro para las cuentas empresariales</description>
    <label>Business Customer</label>
</RecordType>

force-app/zurich-base/main/default/objects/Account/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>Comprende aquellos posibles clientes todavía no existentes en el sistema transaccional</description>
    <label>Lead</label>
</RecordType>

force-app/zurich-base/main/default/objects/ContactPointPhone/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>(ZE/OCS) Identifica el ámbito a utilizar para la colaboración del registro.</description>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ContactPointPhone/fields/ScopeId__c.field-meta.xml
<CustomField>
    <fullName>ScopeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OCS</description>
    <label>Scope Name</label>
    <referenceTo>Scope__c</referenceTo>
    <relationshipLabel>Contact Point Phones</relationshipLabel>
    <relationshipName>ContactPointPhones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>(ZE/OCS) Identifica la cuenta a la que está asociado el ámbito</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scope</relationshipLabel>
    <relationshipName>Scope</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/classes/AccountSelectorWithoutSharing.cls
/**
 *
 * @description       : Clase Apex con el without sharing en la cual creamos 3 métodos, que serán referenciados en la clase AccountLeadUtil
 * @author            : overes
 **/
public without sharing class AccountSelectorWithoutSharing
{
    public AccountSelectorWithoutSharing()
    {}

    //#region RECORD TYPES
    public static final String RT_NAME_CUSTOMER = 'Customer';
    public static final String RT_NAME_BUSINESSCUSTOMER = 'BusinessCustomer';
    public static final String RT_NAME_LEAD= 'Lead';

    // Recupera el Id del RecordType de clientes personales
    public ID rtCustomerId
    {
        get
        {
            return Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(RT_NAME_CUSTOMER)?.getRecordTypeId();
        }
    }
    // Recupera el Id del RecordType de clientes Lead
    public ID rtLeadId
    {
        get
        {
            return Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(RT_NAME_LEAD)?.getRecordTypeId();
        }
    }
    // Recupera el Id del RecordType de clientes
    public ID rtBusinessCustomerId
    {
        get
        {
            return Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(RT_NAME_BUSINESSCUSTOMER)?.getRecordTypeId();
        }
    }

    /**
     * Busca cuentas a partir de un listado de DNIs y record type Customer o Business Customer
     * @author overes
     * @date 16/08/2023
     * @param  documents Listado de DNIs
     * @return           Listado de cuentas
     * **
     * @modification    Se añade que se ordene por fecha de creación
     * @author          jgallaga
     * @date            21/09/2023
     */
    public List<Account> findByNationalIdAndRcTypeCustAndBC(List<String> documents)
    {
        List<Account> result = new List<Account>();

        if ( documents != null && !documents.isEmpty() )
        {
            result = new List<Account>(
                [
                    SELECT Id, FirstName, LastName, Intermediary_Name__c, Intermediary_Name__r.INFOIntermediaryCode__c,
                    NationalIdType__c, RecordType.DeveloperName, NationalId__c
                    FROM Account
                    WHERE NationalId__c IN: documents
                    AND     (
                        RecordTypeId = : rtCustomerId
                                       OR
                                       RecordTypeId = : rtBusinessCustomerId
                        )
                    ORDER BY LastModifiedDate DESC
                ]);
        }
        return result;
    }

    /**
     * Busca cuentas a partir de un listado de DNIs y lecord type Lead
     * @author overes
     * @date 16/08/2023
     * @param  documents   Listado de DNIs
     * @return             Listado de cuentas sobre los que se ha realizado match
     *
     * @change amiranda 31/08/2023 Se elimina el campo 'Name' de la query. Es un
     * campo de solo lectura que se conforma por la concatenación de los campos
     * 'FirstName' y 'LastName' (entre otros) que son los que se consultarán
     * en la query. Por lo tanto, al intentar actualizar la lista de cuentas que
     *  nos devuelve este método, Salesforce lanza una excepción.
     * *
     * @modification    Se añade que el resultado este ordenado por fecha de creación, mas reciente primero
     * @author          jgallaga
     * @date            21/09/2023
     */
    public List<Account> findByNationalIdAndRcTypeLead(List<String> documents)
    {
        List<Account> result = new List<Account>();

        if ( documents != null && !documents.isEmpty() )
        {
            result = new List<Account>(
                [
                    SELECT Id, FirstName, LastName, NationalIdType__c, Intermediary_Name__c, Intermediary_Name__r.INFOIntermediaryCode__c, RecordType.DeveloperName, NationalId__c
                    FROM account
                    WHERE NationalId__c IN: documents
                    AND RecordTypeId = : rtLeadId
                                       ORDER BY LastModifiedDate DESC
                ]);
        }
        return result;
    }

    /**
     * Busca un registro account a partir de un id, si no encuentra resultado devuelve null
     *
     * @author dmunoz
     * @date 28/09/2023
     * @return Account cuenta a la que comprobar si es duplicado, en caso que no encuentre resultado devuelve null (no hay duplicado)
     */
    public Account findAccountById(String accountId)
    {
        Account result = null;
        if ( String.isNotEmpty(accountId) )
        {
            List<Account> accountQueryList = new List<Account>([SELECT Id, FirstName, LastName, Intermediary_Name__c, Intermediary_Name__r.INFOIntermediaryCode__c,
                                                                NationalIdType__c, RecordType.DeveloperName, NationalId__c
                                                                FROM Account
                                                                WHERE Id = : accountId]);

            if ( !accountQueryList.isEmpty() )
            {
                result = accountQueryList.get(0);
            }

        }
        return result;
    }

    /**
     * Se ha intentado evitar crear una Query más sólo para el nombre y se construía el mensaje de los registros devueltos
     * con el firstName + lastName pero en caso de las cuentas con RecordType Business Customer no tiene esos campos
     * @author overes
     * @date 28-09-2023
     * @param  accountId id a buscar
     * @return           Listado de cuentas
     */
    public List<Account> findAccountNameById(ID accountId)
    {
        List<Account> result = new List<Account>();
        if ( accountId != null)
        {
            result = new List<Account>([SELECT Id, Name FROM account WHERE Id = : accountId]);
        }
        return result;
    }

    public List<ContactpointPhone> selectByAccountScopeLead(string phone)
    {
        return [SELECT Scope__c,ScopeId__c, ScopeId__r.AccountId__c, ScopeId__r.AccountId__r.Createddate FROM ContactPointPhone WHERE TelephoneNumber = :phone AND ScopeId__r.AccountId__r.RecordType.DeveloperName = 'Lead'];
    }
}