force-app/zurich-base/main/default/objects/Account/fields/INFOIntermediaryCode__c.field-meta.xml
<CustomField>
    <fullName>INFOIntermediaryCode__c</fullName>
    <description>(OCS). Identificador único de intermediario</description>
    <externalId>true</externalId>
    <label>Intermediary Code</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/PreferedContactEnd__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactEnd__c</fullName>
    <label>Horario Cont. Preferente Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/PreferedContactStart__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactStart__c</fullName>
    <label>Horario Cont. Preferente Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>Comprende aquellos posibles clientes todavía no existentes en el sistema transaccional</description>
    <label>Lead</label>
</RecordType>

force-app/zurich-base/main/default/objects/Lead_Offers__c/Lead_Offers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Ofertas de Lead</label>
</CustomObject>

force-app/zurich-base/main/default/objects/Lead_Offers__c/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>Código de Negocio para las Ofertas del Contact Center.</description>
    <label>Código de Negocio</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Lead_Offers__c/fields/BusinessHour__c.field-meta.xml
<CustomField>
    <fullName>BusinessHour__c</fullName>
    <description>Nombre del registro de Business Hour al que asociar un registro de ContactRequest para el Contact Center.</description>
    <label>Horario de Oficina</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Lead_Offers__c/fields/VoiceQueue__c.field-meta.xml
<CustomField>
    <fullName>VoiceQueue__c</fullName>
    <description>Nombre de la cola de CTI a la que asociar un registro de ContactRequest para el Contact Center.</description>
    <label>Cola CTI</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>(OCS) Identifica el código de negocio en INFO.</description>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/InfoQuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>InfoQuoteNumber__c</fullName>
    <description>(ZE/OCS) identificador de la oferta en INFO.</description>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IntermediaryCode__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryCode__c</fullName>
    <description>(OCS) Identifica al Mediador o Partner asociado a la oferta.</description>
    <label>Intermediary Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS) Identifica el nombre del intermediario ya sea partner o mediador.</description>
    <label>Intermediary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers (Intermediary)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/PreferedContactEnd__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactEnd__c</fullName>
    <label>Horario Cont. Preferente Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/PreferedContactStart__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactStart__c</fullName>
    <label>Horario Cont. Preferente Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/SessionId__c.field-meta.xml
<CustomField>
    <fullName>SessionId__c</fullName>
    <description>Stores the session id and product code of an offer created in the web fomulary</description>
    <externalId>true</externalId>
    <label>SessionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>(OCS). Identifica el código de negocio en INFO</description>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/InfoQuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>InfoQuoteNumber__c</fullName>
    <label>Quote Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/Intermediary_Code__c.field-meta.xml
<CustomField>
    <fullName>Intermediary_Code__c</fullName>
    <description>(OCS). Identifica al Mediador o Partner asociado a la oferta</description>
    <label>Intermediary Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica el nombre del intermediario ya sea partner o mediador</description>
    <label>Intermediary</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/OpportunityName__c.field-meta.xml
<CustomField>
    <fullName>OpportunityName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica la oferta a la que se encuentra asociada la póliza</description>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-ventas-app/main/default/classes/AccountLeadOpportunityQueueJob.cls
/**
 * @description       : Clase-queueable ejecutada desde el WS de Quote&Buy que inserta/actualiza/asigna un registro de Oferta de Lead e inserta un registro de Póliza (si aplica)
 * @author            : nts - overes
 * @last modified on  : 09-25-2023
 **/

public with sharing class AccountLeadOpportunityQueueJob implements Queueable
{

    /**
     * Registro de Cuenta
     **/
    private Account accountRecord;
    /**
     * Registro de Oferta a insertar/actualizar/asignar
     **/
    private Opportunity offerRecord;
    /**
     * Registro de Póliza a insertar
     **/
    private Policy__c policyRecord;
    /**
     * Código Postal
     **/
    private String postalCode;
    /**
     * Teléfono
     **/
    private String phone;

    private static final String CONTACT_CENTER = 'CONTACT_CENTER';

    /**
     * Constructor de la clase que inicializa los parámentros recibidos
     * *
     * @author overes | 08-31-2023
     * @param accountRecord
     * @param offerRecord
     * @param policyRecord
     * @param postalCode
     * @param phone
     **/
    public AccountLeadOpportunityQueueJob(Account accountRecord, Opportunity offerRecord, Policy__c policyRecord, String postalCode, String phone)
    {
        this.accountRecord = accountRecord;
        this.offerRecord = offerRecord;
        this.policyRecord = policyRecord;
        this.postalCode = postalCode;
        this.phone = phone;
    }

    /**
     * Método que se autoejecuta cuando se invoca la clase
     * *
     * @author overes | 08-31-2023
     * @param context
     **/
    public void execute(QueueableContext context)
    {
        processOpportunityAndPolicy(this.accountRecord, this.offerRecord, this.policyRecord, this.postalCode, this.phone);
    }

    /**
     * Método
     * *
     * @author overes | 08-31-2023
     * @param accountRecord
     * @param offerRecord
     * @param policyRecord
     * @param postalCode
     **/
    public static void processOpportunityAndPolicy(Account accountRecord, Opportunity offerRecord, Policy__c policyRecord, String postalCode, String phone)
    {
        Opportunity offerToInsertUpdate = offerRecord;
        List<Opportunity> listOffer = new List<Opportunity>();
        OpportunitiesSelector oppSelector = new OpportunitiesSelector();
        if ( String.isBlank(offerRecord.InfoQuoteNumber__c) )
        {
            listOffer = oppSelector.findOppWhenInfoQuoteNumberIsNull(offerRecord);
        }
        else
        {
            listOffer = oppSelector.findOppWhenInfoQuoteNumberIsNOTNull(offerRecord);
        }

        manageOfferRecord(offerRecord, offerToInsertUpdate, listOffer);

        if (offerToInsertUpdate != null && offerToInsertUpdate.Id == null)
        {
            insert offerToInsertUpdate;
        }
        else if (offerToInsertUpdate != null && offerToInsertUpdate.Id != null)
        {
            update offerToInsertUpdate;
        }

        managePolicyRecord(policyRecord, offerToInsertUpdate);

        offerToInsertUpdate = manageOfferToInsertUpdate (offerToInsertUpdate, accountRecord, postalCode, phone);

        insert fillPolicyRecord(policyRecord, offerToInsertUpdate);
    }

    public static Policy__c fillPolicyRecord(Policy__c policyRecord, Opportunity offerToInsertUpdate)
    {
        Policy__c pol = policyRecord;
        pol.OpportunityName__c= offerToInsertUpdate.Id;
        pol.InfoQuoteNumber__c = offerToInsertUpdate.InfoQuoteNumber__c;
        pol.IntermediaryId__c = [SELECT Id FROM Account WHERE INFOIntermediaryCode__c = : offerToInsertUpdate.IntermediaryCode__c].get(0).Id;
        pol.Intermediary_Code__c = offerToInsertUpdate.IntermediaryCode__c;

        return pol;
    }

    public static Opportunity manageOfferToInsertUpdate (Opportunity offerToInsertUpdate, Account accountRecord, String postalCode, String phone)
    {
        Opportunity offerToUpdate = offerToInsertUpdate;
        if (offerToInsertUpdate != null && offerToInsertUpdate.Id == null && offerToInsertUpdate.StageName != 'Cerrada-Ganada')   //Ejecutar Proceso de Asignación si la Oferta se debe insertar y no es el escenario de integración 3.
        {
            Map<String, Account> assign = AccountLeadUtil.leadAssignment(accountRecord, offerToInsertUpdate.IntermediaryCode__c, offerToInsertUpdate.IntermediaryCode__c, null, postalCode);
            if ( assign.containsKey(CONTACT_CENTER) )
            {
                Lead_Offers__c leadOffersCS = Lead_Offers__c.getInstance();
                manageCallMeBack(accountRecord, offerToInsertUpdate, leadOffersCS, phone);

                if (offerToInsertUpdate.InfoQuoteNumber__c == null)
                {
                    offerToUpdate = null;
                }
                else
                {
                    offerToUpdate.BusinessCode__c = leadOffersCS.BusinessCode__c;
                }
            }
            else
            {
                offerToUpdate.OwnerId = new List<String>( assign.keySet() ).get(0);
                if (assign.get(offerToInsertUpdate.OwnerId) != null)
                {
                    offerToUpdate.IntermediaryId__c = assign.get(offerToInsertUpdate.OwnerId).Id;
                    offerToUpdate.IntermediaryCode__c = assign.get(offerToInsertUpdate.OwnerId).INFOIntermediaryCode__c;
                }
            }
        }
        return offerToUpdate;
    }

    public static void manageCallMeBack(Account accountRecord, Opportunity offerToInsertUpdate, Lead_Offers__c leadOffersCS, String phone)
    {
        CallMeBackUtil.CallMeBack callMeBack = new CallMeBackUtil.CallMeBack();
        callMeBack.name = accountRecord.Name;
        callMeBack.phone = phone;
        callMeBack.bestTimeFrom = accountRecord.PreferedContactStart__c;
        callMeBack.bestTimeUntil = accountRecord.PreferedContactEnd__c;
        callMeBack.businessCode = leadOffersCS.BusinessCode__c;

        CallMeBackUtil.insertCallMeBack(callMeBack, leadOffersCS.VoiceQueue__c, leadOffersCS.BusinessHour__c);
    }

    /**
     * Método que gestiona la creación de una póliza
     * *
     * @author overes | 08-31-2023
     * @param policyRecord
     * @param offerToInsertUpdate
     */
    private static void managePolicyRecord(Policy__c policyRecord, Opportunity offerToInsertUpdate)
    {
        if (policyRecord != null && offerToInsertUpdate != null)
        {
            Policy__c policyToInsert = policyRecord;
            AccountsSelector accSelector = new AccountsSelector();
            List<Account> listAcc = accSelector.findByINFOIntermediaryCode(new List<String> {(String) offerToInsertUpdate.IntermediaryCode__c});
            policyToInsert.OpportunityName__c = offerToInsertUpdate.Id;
            policyToInsert.InfoQuoteNumber__c = offerToInsertUpdate.InfoQuoteNumber__c;
            if (listAcc.size() > 0)
            {
                policyToInsert.IntermediaryId__c = listAcc.get(0).Id;
            }
            policyToInsert.Intermediary_Code__c = offerToInsertUpdate.IntermediaryCode__c;
            insert policyToInsert;
        }
    }

    /**
     * Método que gestiona la creación o la actualización de Policy__c
     * *
     * @author overes | 08-31-2023
     * @param offerRecordParam
     * @param offerToInsertUpdateParam
     */
    private static void manageOfferRecord(Opportunity offerRecord, Opportunity offerToInsertUpdate,List<Opportunity> listOffer)
    {
        for (Opportunity offerQuery : listOffer)
        {
            if ( ( offerRecord.InfoQuoteNumber__c != null && offerQuery.InfoQuoteNumber__c == offerRecord.InfoQuoteNumber__c && (offerQuery.StageName == 'Cerrada-Ganada' || offerQuery.StageName == 'Cerrada-Perdida') )  || (offerRecord.InfoQuoteNumber__c == null && offerQuery.SessionId__c == offerRecord.SessionId__c) )
            {
                offerToInsertUpdate = null;
                break;
            }
            else if (offerRecord.InfoQuoteNumber__c != null && offerQuery.InfoQuoteNumber__c == offerRecord.InfoQuoteNumber__c)
            {
                offerToInsertUpdate.Id = offerQuery.Id;
            }
            else if (offerToInsertUpdate.Id == null && offerQuery.InfoQuoteNumber__c == null)
            {
                offerToInsertUpdate.Id = offerQuery.Id;
            }
        }
    }
}