force-app/zurich-base/main/default/objects/Account/fields/INFOCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>INFOCustomerNumber__c</fullName>
    <description>(OCS/ZE). Destinado a almacenar el código de filiación proveniente del transaccional INFO</description>
    <externalId>true</externalId>
    <label>Affiliation Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/INFOIntermediaryCode__c.field-meta.xml
<CustomField>
    <fullName>INFOIntermediaryCode__c</fullName>
    <description>(OCS). Identificador único de intermediario</description>
    <externalId>true</externalId>
    <label>Intermediary Code</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Intermediary_Name__c.field-meta.xml
<CustomField>
    <fullName>Intermediary_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS/ZE). Relación a la cuenta de intermediario asociada al contacto (Partner o Mediador). Al existir este dato únicamente a nivel de póliza, el CRM lo informa en base al valor de Intermediario de la póliza más reciente</description>
    <label>Intermediary Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Intermediary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/IntermediaryGroup__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referencia al registro de Cuenta Agrupación</description>
    <label>Intermediary Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Solo se puede seleccionar una cuenta de tipo Agrupación Mediador</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Intermediary Group</relationshipLabel> 
    <relationshipName>IntermediaryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Campaign/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>Código de Negocio</description>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Campaign/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código de Campaña</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Campaign/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Entidad legal</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Campaign/fields/ProductBranch__c.field-meta.xml
<CustomField>
    <fullName>ProductBranch__c</fullName>
    <description>Ramo correspondiente al producto asociado a la campaña.</description>
    <label>Product Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductBranches</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Campaign/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Zurich Empresas</fullName>
            </value>
            <value>
                <fullName>Zurich Empresas Orange</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/CampaignMember/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/CampaignMember/fields/OfferAssignedCode__c.field-meta.xml
<CustomField>
    <fullName>OfferAssignedCode__c</fullName>
    <description>Código del mediador asignado a la oferta.</description>
    <label>Mediator Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/CampaignMember/fields/OfferAssignedType__c.field-meta.xml
<CustomField>
    <fullName>OfferAssignedType__c</fullName>
    <description>Tipo de mediador asignado a la oferta.</description>
    <label>Offer Assigned Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Mediador</label>
            </value>
            <value>
                <fullName>CC</fullName>
                <label>Contact Center</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/IntermediaryCode__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryCode__c</fullName>
    <label>Código de intermediario</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>Indicates the legal entity which belongs to</description>
    <label>Entidad legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Opportunity/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>(OCS) Identifica el código de negocio en INFO.</description>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IntermediaryCode__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryCode__c</fullName>
    <description>(OCS) Identifica al Mediador o Partner asociado a la oferta.</description>
    <label>Intermediary Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS) Identifica el nombre del intermediario ya sea partner o mediador.</description>
    <label>Intermediary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers (Intermediary)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &apos;Life&apos;, &apos;Life Insurance&apos;, 
			IF($Profile.Name = &apos;ZE User&apos; || $Profile.Name = &apos;Ventas User&apos;,
			    &apos;001&apos;,
			        &apos;&apos;))</defaultValue>
    <description>(ZE/OCS) Identifica la entidad legal a la que pertenece la oferta.</description>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Insurance</fullName>
            </value>
            <value>
                <fullName>General Insurance</fullName>
            </value>
            <value>
                <fullName>000</fullName>
                <label>Todos</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>Zurich</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>CAN SSGG</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>CAS SSGG</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>CAS Vida</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Zurich Vida</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>DZ Pensiones</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>EPSV Zurich</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>BSSG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>Multientidad</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/ProductBranch__c.field-meta.xml
<CustomField>
    <fullName>ProductBranch__c</fullName>
    <label>Product Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductBranches</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/ZRM__c.field-meta.xml
<CustomField>
    <fullName>ZRM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ZRM: usamos este campo para identificar las ofertas que un usuario de ZRM puede editar, se usa junto con la VR IntermediaryCannotEdit</description>
    <label>ZRM</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>(OCS). Identifica el código de negocio en INFO</description>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica el nombre del intermediario ya sea partner o mediador</description>
    <label>Intermediary</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>(OCS). Identifica la entidad legal a la que está asociada la póliza en INFO</description>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Insurance</fullName>
            </value>
            <value>
                <fullName>General Insurance</fullName>
            </value>
            <value>
                <fullName>000</fullName>
                <label>Todos</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>Zurich</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>CAN SSGG</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>CAS SSGG</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>CAS Vida</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Zurich Vida</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>DZ Pensiones</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>EPSV Zurich</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>BSSG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>Multientidad</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/PolicyHolder__c.field-meta.xml
<CustomField>
    <fullName>PolicyHolder__c</fullName>
    <description>(OCS). Identifica el tomador de la póliza</description>
    <label>Policy Holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Policy Holder)</relationshipLabel>
    <relationshipName>PoliciesHolder</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/ProductBranch__c.field-meta.xml
<CustomField>
    <fullName>ProductBranch__c</fullName>
    <formula>ProductId__r.GroupDescription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product branch</label>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Batch_CampaignMemberToOpportunity.cls
/**
 * Procesa los miembros de campaña tras su inserción, para generar Ofertas de forma automática.
 * En función de su tipología se asignarán a un Agente Mediador o al usuario genérico del Contact Center.
 *
 * @author nts (jfherrero)
 * @date 24/07/2023
 **/

public with sharing class Batch_CampaignMemberToOpportunity implements Database.Batchable<sObject>
{
    // #region Atributos

    
    private static final String CLASS_NAME = 'Batch_CampaignMemberToOpportunity';
    private static final Map<String, String> configValues = GlobalConfigUtil.getGlobalConfigurationValues();
    private static final String PRODUCT_BRANCH_VIDA_CODE = configValues.get('Product_Branch_Vida_Code');
    private static final Id OFFER_RECORD_TYPE_VIDA = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(configValues.get('Opportunity_RecordTypeDevName_Life')).getRecordTypeId();
    private static final Id OFFER_RECORD_TYPE_NO_VIDA = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(configValues.get('Opportunity_RecordTypeDevName_NoLife')).getRecordTypeId();
    private static final String LEGAL_ENTITY_LIFE_INSURANCE = configValues.get('Legal_Entity_Life_Insurance');

    private Set<Id> campMemberIdSet = new Set<Id>();
    private List<Opportunity> oppsToInsert = new List <Opportunity>();
    private static UsersSelector usersSelector = new UsersSelector();

    private static Boolean isAGRUser;

    // #endregion Atributos

    // #region Métodos propios del batch

    /**
     * Constructor.
     * @author jfherrero
     * @date 27/07/2023
     * @param campMemberIdSet Set con los Id de los miembros de campaña
     **/
    public Batch_CampaignMemberToOpportunity (Set<Id> campMemberIdSet)
    {
        this.campMemberIdSet = campMemberIdSet;
    }

    public List<CampaignMember> start(Database.BatchableContext bc)
    {
        List<String> crossSellingCampaigns = new List<String> {'Cross Selling', 'Venta Cruzada'};

        CampaignMembersSelector campaignMembersSelector = new CampaignMembersSelector(new Set<String> {
            'Id', 'CampaignMember.CampaignId', 'CampaignMember.OfferAssignedCode__c', 'CampaignMember.OfferAssignedType__c',
            'CampaignMember.Contact.AccountId', 'CampaignMember.Contact.Account.INFOCustomerNumber__c',
            'CampaignMember.Contact.Account.Intermediary_Name__c', 'CampaignMember.Contact.Account.Intermediary_Name__r.INFOIntermediaryCode__c',
            'CampaignMember.Campaign.StartDate', 'CampaignMember.Campaign.EndDate', 'CampaignMember.Campaign.ExternalId__c',
            'CampaignMember.Campaign.ProductBranch__c', 'CampaignMember.Campaign.BusinessCode__c'
        });

        return ( campaignMembersSelector.selectByCampaignTypeAndId(crossSellingCampaigns, campMemberIdSet) );
    }

    public void execute(Database.BatchableContext bc, List<CampaignMember> campaignMembers)
    {
        try
        {
            oppsToInsert.clear();

            // 0. Obtengo el usuario logueado
            // Obtengo el usuario logueado
            User loggedUser = ( new UsersSelector() ).findUserIntermediaryByUserId( UserInfo.getUserId() );
            isAGRUser = ProfilesSelector.PROFILE_AGENTE_VENTAS_AGR.equals(loggedUser.Profile.Name) && String.isNotBlank(loggedUser.Contact.Account.IntermediaryGroup__c);

            Set<Id> accountList = new Set<Id>();
            Set<String> intermediaryList = new Set<String>();

            // 1º Recupero datos de cliente y codigos de mediador de los miembros de campaña obtenidos
            for (CampaignMember cm: campaignMembers) {
                accountList.add(cm.Contact.AccountId);
                intermediaryList.add(cm.OfferAssignedCode__c);
            }

            // 2º Revisar los pares cliente - mediador tienen una oferta u poliza a los cuales se puede generar oferta
            Map<String, List<CampaignMember>> processedCampaignMembersMap = checkVisibility(campaignMembers, accountList, intermediaryList, loggedUser);

            // 3º Para los miembros de campaña permitidos se generan las ofertas
            insertNewOffers(processedCampaignMembersMap.get('ValidCampaignMembers'), loggedUser);

            // 4º Actualizar miembros de campaña a Mediador Sin Visibilidad
            updateInvalidCampaignMembers(processedCampaignMembersMap.get('InvalidCampaignMembers'));

        }
        catch (Exception e)
        {
            ErrorLogUtil.commitError(e, CLASS_NAME);
        }

    }

    public void finish(Database.BatchableContext bc)
    {
        //No se requiere de acciones
    }

    // #regionend

    // #region Check Visibilidad

    /**
     * Recorremos los datos de entrada para determinar que el par cliente- mediador tiene una oferta o una poliza en el sistema
     *
     * @author dmunoz
     * @date 13/11/2024
     *
     * @return Map<String, List<CampaignMember>>
     */
    private Map<String, List<CampaignMember>> checkVisibility(List<CampaignMember> campaignMembers, Set<Id> accountList, Set<String> intermediaryCodesList, User loggedUser) {
        Map<String, List<CampaignMember>> result = new Map<String, List<CampaignMember>>();

        List<CampaignMember> validCampaignMembers = new List<CampaignMember>();
        List<CampaignMember> invalidCampaignMembers = new List<CampaignMember>();
        

        // Obtengo un conjunto de valores AccountId-CodigoMediador de ofertas y polizas o el par AccountId-AgrupacionId
        Set<String> campaignMembersPoliciesSet = getPolicyHolderIntermediaryPolicies(accountList, intermediaryCodesList, loggedUser);
        Set<String> campaignMembersOpportunitiesSet = getAccountIdIntermediaryOpportunities(accountList, intermediaryCodesList, loggedUser);
        
        // recorro los miembros de campaña y los clasifico en validos o no
        String parAux;
        for (CampaignMember cm : campaignMembers) {
            parAux = cm.Contact.AccountId + '-' + cm.OfferAssignedCode__c;
            if (campaignMembersPoliciesSet.contains(parAux) || campaignMembersOpportunitiesSet.contains(parAux)) {
                validCampaignMembers.add(cm);
            } else {
                invalidCampaignMembers.add(cm);
            }
        }

        result.put('ValidCampaignMembers', validCampaignMembers);
        result.put('InvalidCampaignMembers', invalidCampaignMembers);

        
        return result;
    }


    /**
     * Obtenemos todas las polizas de los clientes y los mediadores y lo devolvemos como conjunto de string AccountId-CodigoMediador
     *
     * @author dmunoz
     * @date 13/11/2024
     *
     * @return Set<String> par accountId-CodigoMediador
     */
    private Set<String> getPolicyHolderIntermediaryPolicies(Set<Id> accountList, Set<String> intermediaryCodesList, User loggedUser) {

        Set<String> result = new Set<String>();

        List<Policy__c> policyQuery = new List<Policy__c>();
        

        // Obtenemos las pólizas si el usuario es agente de ventas AGR
        if (isAGRUser)
        {
            policyQuery = ( new PoliciesSelector() ).policiesHoldersFromIntermediaryGroup(new Set<String> {accountList}, new Set<String> { loggedUser.Contact.Account.IntermediaryGroup__c });

            for (Policy__c policy: policyQuery) {
                result.add(policy.PolicyHolder__c + '-' + policy.IntermediaryId__r.IntermediaryGroup__c);
            }
        }
        else
        {
            policyQuery = ( new PoliciesSelector() ).findPoliciesByAccountId(accountList, intermediaryCodesList);

            for (Policy__c policy: policyQuery) {
                result.add(policy.PolicyHolder__c + '-' + policy.IntermediaryId__r.INFOIntermediaryCode__c);
            }
        }

        return result;
    }


    /**
     * Obtenemos todas las ofertas de los clientes y los mediadores y lo devolvemos como conjunto de string AccountId-CodigoMediador / AccountId-AgrupacionId
     *
     * @author dmunoz
     * @date 13/11/2024
     *
     * @return Set<String> par accountId-CodigoMediador
     */
    private Set<String> getAccountIdIntermediaryOpportunities(Set<Id> accountList, Set<String> intermediaryCodesList, User loggedUser) {

        Set<String> result = new Set<String>();

        List<Opportunity> opportunityQuery = new List<Opportunity>();        

        // Obtenemos las ofertas si el usuario es agente de ventas AGR
        if (isAGRUser)
        {
            opportunityQuery = ( new OpportunitiesSelector() ).findOpportunitiesByAccountIdAndIntermediaryGroup(accountList, new Set<String> { loggedUser.Contact.Account.IntermediaryGroup__c });

            for (Opportunity opportunity: opportunityQuery) {
                result.add(opportunity.AccountId + '-' + opportunity.IntermediaryId__r.IntermediaryGroup__c);
            }
        }
        else // Resto de perfiles
        {
            opportunityQuery = ( new OpportunitiesSelector() ).findOpportunitiesByAccountIdAndIntermediary(accountList, intermediaryCodesList);

            for (Opportunity opportunity: opportunityQuery) {
                result.add(opportunity.AccountId + '-' + opportunity.IntermediaryId__r.INFOIntermediaryCode__c);
            }
        }

        return result;
    }

    //#region Insertar Ofertas


    /* Método para generar las oportunidades a partir de los miembros de campaña y los mapas generados.
     * @author jfherrero
     * @date 03/08/2023
     * @param campaignMembers Lista con los registros a tratar.
     * @param accountByIntermCode Mapa de cuentas por código de intermediario.
     * @param userIdByAccountId Mapa de usuarios por cuenta.
     **/
    private void insertNewOffers(List<CampaignMember> campaignMembers, User loggedUser)
    {

        for (CampaignMember cm :campaignMembers)
        {
            Opportunity opp = new Opportunity();

            opp.Name = ('OF' + cm.Campaign.ExternalId__c + cm.Contact.Account.INFOCustomerNumber__c).left(120);
            opp.StageName = GlobalConfigUtil.getGlobalConfigurationValueId('Opportunity_Stage_Name_Legit_Lead');
            opp.CloseDate = cm.Campaign.EndDate;
            opp.AccountId = cm.Contact.AccountId;
            opp.ProductBranch__c = cm.Campaign.ProductBranch__c;
            opp.CampaignId = cm.CampaignId;
            opp.IntermediaryCode__c = cm.OfferAssignedCode__c;
            opp.OwnerId = obtainDefaultUser();

            // Asociar el mediador en funcion del usuario logueado
            if (isAGRUser) {
                opp.IntermediaryId__c = loggedUser.Contact.AccountId;
            } else {
                opp.IntermediaryId__r = new Account(INFOIntermediaryCode__c = cm.OfferAssignedCode__c);
            }

            // M se corresponde con miembros de campaña para Agentes Mediador
            if (cm.OfferAssignedType__c == 'M')
            {
                opp.ZRM__c = true;
            }

            // CC se corresponde con miembros de campaña para el Contact Center, que se asignarán a un usuario genérico
            else if  (cm.OfferAssignedType__c == 'CC')
            {
                opp.LegalEntity__c = '001';
                opp.BusinessCode__c = cm.Campaign.BusinessCode__c;
                opp.Scope__c = GlobalConfigUtil.getGlobalConfigurationValueId('Opportunity_Scope_Ventas');
                opp.ZRM__c = false;
            }

            if(PRODUCT_BRANCH_VIDA_CODE.equals(opp.ProductBranch__c))
            {
                opp.RecordTypeId = OFFER_RECORD_TYPE_VIDA;
                opp.LegalEntity__c = LEGAL_ENTITY_LIFE_INSURANCE;
            }
            else
            {
                opp.RecordTypeId = OFFER_RECORD_TYPE_NO_VIDA;    
            }

            oppsToInsert.add(opp);
        }

        if (!oppsToInsert.isEmpty()) {
            insert oppsToInsert;
        }

    }

    // #region Mediador Sin Visibilidad

    /**
     * Actualiza el estado de los miembros de campaña que recibe como parámetro y que no se encuentran en el filtro
     *
     * @author fpalomo
     * @date 04/04/2024
     *
     * @return List<Opportunities>
     */
    private void updateInvalidCampaignMembers(List<CampaignMember> campaignMembers)
    {

        if (!campaignMembers.isEmpty()) {

            for (CampaignMember cm : campaignMembers)
            {                
                cm.Status = GlobalConfigUtil.getGlobalConfigurationValueId('CampaignMemberStatusMediadorSinVisibilid');             
            }

            update campaignMembers;
        }
    }

    //#region Flow invocation
    /**
     * Clase para el acceso a los registros y poder lanzar el batch desde un flow.
     * @author jfherrero
     * @date 27/07/2023
     **/
    public class FlowInputs
    {
        @InvocableVariable public List<Id> campMemberIds;
    }

    /**
     * Método invocable para poder lanzar el batch desde un Action en un flow.
     * @author jfherrero
     * @date 27/07/2023
     * @param campaignMembers Lista con los registros a tratar.
     **/
    @InvocableMethod(label='Create Offers from Campaign Members'
                            description='Genera ofertas para mediadores o agente genérico CC a partir de miembros de campaña'
                                         category='Campaign Member')
    public static void createOffers(List<String> campaignMembers)
    {
        if( System.isBatch() )
        {
            return;
        }

        Set<Id> campMemberIdSetReceived = new Set<Id>();

        for (String cmId : campaignMembers)
        {
            campMemberIdSetReceived.add(cmId);
        }

        List<String> crossSellingCampaigns = new List<String> {'Cross Selling', 'Venta Cruzada'};

        CampaignMembersSelector campaignMembersSelector = new CampaignMembersSelector(new Set<String> {
            'Id', 'CampaignMember.CampaignId', 'CampaignMember.OfferAssignedCode__c', 'CampaignMember.OfferAssignedType__c',
            'CampaignMember.Contact.AccountId', 'CampaignMember.Contact.Account.INFOCustomerNumber__c',
            'CampaignMember.Contact.Account.Intermediary_Name__c', 'CampaignMember.Contact.Account.Intermediary_Name__r.INFOIntermediaryCode__c',
            'CampaignMember.Campaign.StartDate', 'CampaignMember.Campaign.EndDate', 'CampaignMember.Campaign.ExternalId__c',
            'CampaignMember.Campaign.ProductBranch__c', 'CampaignMember.Campaign.BusinessCode__c'
        });

        Map<Id, CampaignMember> cms = new Map<Id, CampaignMember>( campaignMembersSelector.selectByCampaignTypeAndId(crossSellingCampaigns, campMemberIdSetReceived) );
        Set<Id> campMemberIdSetFlow = cms.keyset();

        Database.executeBatch( new Batch_CampaignMemberToOpportunity(campMemberIdSetFlow), 100 );
    }

    // #region Otros metodos Auxiliares
    /**
     * @description Método para recuperar los Ids de los usuarios configurados para ser los
     *              Ids por defecto para el usuario por defecto CC y el usuario por defecto
     *              en caso de error.
     * @author      jgallaga
     * @date        18/08/2023
     */
    private String obtainDefaultUser()
    {

        String defaultUserId;
        String aliasDeaultUser = Cross_Selling__c.getinstance().DefaultUser__c;

        UsersSelector userQuery = new UsersSelector();

        List<User> defaultUsers = userQuery.findUsersByAlias(new List<String> {aliasDeaultUser});

        defaultUserId = defaultUsers.get(0).Id;

        return defaultUserId;
    }



    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * Devuelve la lista de CampaignMembers que recibe como parámetro, filtrada para eliminar todos aquellos para los que el mediador no tenga visibilidad
     *
     * @author fpalomo
     * @date 04/04/2024
     *
     * @return List<Opportunities>
     */
    /*private List<CampaignMember> getFilteredCampaignMembers(Map<Id, CampaignMember> campaignMembersAccountMap, Set<String> intermediaryCodes)
    {
        List<CampaignMember> filteredCampaignMembers = new List<CampaignMember>();
        List<Policy__c> campaignMembersPolicies = new List<Policy__c>();
        User loggedUser = ( new UsersSelector() ).findUserIntermediaryByUserId( UserInfo.getUserId() );

        // Obtenemos las pólizas
        if ( ProfilesSelector.PROFILE_AGENTE_VENTAS_AGR.equals(loggedUser.Profile.Name) && String.isNotBlank(loggedUser.Contact.Account.IntermediaryGroup__c) )
        {
            campaignMembersPolicies = ( new PoliciesSelector() ).selectByIntermediaryGroupId(new Set<String> { loggedUser.Contact.Account.IntermediaryGroup__c });
        }
        else
        {
            campaignMembersPolicies = ( new PoliciesSelector() ).findPoliciesByAccountId(campaignMembersAccountMap.keySet(), intermediaryCodes);
        }

        // Lista con las IDs de cuenta para las que se van a generar ofertas
        Set<String> toOfferAccountIDs = new Set<String>();

        // Añadimos los clientes de las pólizas a la lista de cuentas
        for(Policy__c policy : campaignMembersPolicies)
        {
            toOfferAccountIDs.add(policy.PolicyHolder__c);
        }

        Set<String> campaignIDsToExcludeMembers = new Set<String>();
        for ( CampaignMember cm : campaignMembersAccountMap.values() )
        {
            campaignIDsToExcludeMembers.add(cm.CampaignId);
        }

        // Recuperamos las ofertas, excluyendo las que pertenezcan a clientes que ya estén en la lista
        List<Opportunity> campaignMembersOffers = ( new OpportunitiesSelector() ).getIntermediaryOtherOffersByCampaignMembers(campaignIDsToExcludeMembers, toOfferAccountIDs, loggedUser.Contact.AccountId);

        // Añadimos los clientes de las ofertas recuperadas a la lista de cuentas a las que se le van a generar ofertas
        for(Opportunity offer : campaignMembersOffers)
        {
            toOfferAccountIDs.add(offer.AccountId);
        }

        // Añadimos a la lista los miembros de campaña que cumplan el filtro
        for ( CampaignMember campaignMember : campaignMembersAccountMap.values() )
        {
            if ( toOfferAccountIDs.contains(campaignMember.Contact.AccountId) )
            {
                filteredCampaignMembers.add(campaignMember);
            }
        }

        return filteredCampaignMembers;
    }*/

    

}