force-app/zurich-base/main/default/objects/Account/fields/IntermediaryStatus__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryStatus__c</fullName>
    <label>Intermediary Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/MainEmail__c.field-meta.xml
<CustomField>
    <fullName>MainEmail__c</fullName>
    <label>Main Email</label>
    <type>Email</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/NationalId__c.field-meta.xml
<CustomField>
    <fullName>NationalId__c</fullName>
    <description>(OCS/ZE). Identificador nacional del cliente</description>
    <label>National ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
            </value>
            <value>
                <fullName>002</fullName>
            </value>
            <value>
                <fullName>003</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/TerritorialDirection__c.field-meta.xml
<CustomField>
    <fullName>TerritorialDirection__c</fullName>
    <label>Territorial Direction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/TerritoryManagerEmail__c.field-meta.xml
<CustomField>
    <fullName>TerritoryManagerEmail__c</fullName>
    <description>SDM: Director Territorial Email</description>
    <label>Territory Manager Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-sdm-app/main/default/objects/SDMAccountContactRelation__mdt/SDMAccountContactRelation__mdt.object-meta.xml
<CustomObject>
    <description>SDM: Configuracion para la relacion de roles de Account Contact Realtion y campos de mediador (account)</description>
    <label>SDMAccountContactRelation</label>
    <pluralLabel>SDMAccountContactRelations</pluralLabel>
</CustomObject>

force-app/zurich-sdm-app/main/default/objects/SDMAccountContactRelation__mdt/fields/IntermediaryField__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryField__c</fullName>
    <description>SDM: the name of the field in the account sobject (intermediary)</description>
    <label>Intermediary Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-sdm-app/main/default/objects/SDMAccountContactRelation__mdt/fields/NameText__c.field-meta.xml
<CustomField>
    <fullName>NameText__c</fullName>
    <description>SDM: the first part for the name of the contact if created</description>
    <label>Texto de nombre</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-sdm-app/main/default/objects/SDMAccountContactRelation__mdt/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>SDM: nombre del rol en los Account Contact Relation</description>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main</fullName>
                <default>true</default>
                <label>Principal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
                <label>Siniestros</label>
            </value>
            <value>
                <fullName>Administration</fullName>
                <label>Administracion</label>
            </value>
            <value>
                <fullName>Subscription</fullName>
                <label>Contratacion</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-sdm-app/main/default/objects/SDMAccountTeamRole__mdt/SDMAccountTeamRole__mdt.object-meta.xml
<CustomObject>
    <description>SDM: Configuracion para la relacion de roles de Account Team Member y campos de mediador (account)</description>
    <label>SDMAccountTeamRole</label>
    <pluralLabel>SDMAccountTeamRoles</pluralLabel>
</CustomObject>

force-app/zurich-sdm-app/main/default/objects/SDMAccountTeamRole__mdt/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>SDM: nombre del rol en los Account Team Member</description>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TerritoryManager</fullName>
                <default>true</default>
                <label>Director Territorial</label>
            </value>
            <value>
                <fullName>Manager</fullName>
                <label>Director Zona</label>
            </value>
            <value>
                <fullName>BusinessManager</fullName>
                <label>Responsable de Negocio</label>
            </value>
            <value>
                <fullName>LifeManager</fullName>
                <label>Director Vida</label>
            </value>
            <value>
                <fullName>EnterpriseManager</fullName>
                <label>Director Empresas</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
                <label>Formador</label>
            </value>
            <value>
                <fullName>LifeConsultant</fullName>
                <label>Consultor Vida</label>
            </value>
            <value>
                <fullName>PYMEConsultant</fullName>
                <label>Consultor Empresas</label>
            </value>
            <value>
                <fullName>PYMEManager</fullName>
                <isActive>true</isActive>
                <label>PYMEManager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-sdm-app/main/default/objects/SDMAccountTeamRole__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>SDM: if the role is used or not</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-sdm-app/main/default/classes/TestDataFactorySDM.cls
/**
 * Clase para generar los escenarios de pruebas de los test para el proyecto SDM
 **
 * @author nts
 * @date 05/07/2021
 */
@isTest
public class TestDataFactorySDM
{
    public static final String ACCOUNT_LEGAL_ENTITY = '001';
    public static final String AGRUPATION_CIF = '1111';

    public static final String TERRITORY_ROL = 'TerritoryManager';
    public static final String TERRITORY_EMAIL = 'territorymanager{0}@invalid.com';
    public static final String TERRITORY_FIELD = 'TerritoryManagerEmail__c';
    public static final String BUSINESS_ROL = 'BusinessManager';

    public static final String MAINEMAIL_ROL = 'Principal';
    public static final String MAINEMAIL_FIELD = 'MainEmail__c';
    public static final String MAINEMAIL_TEXT = 'Cto Pcipal';
    public static final String MAINEMAIL_EMAIL = 'cto.principal{0}@invalid.com';
    public static final String CONTACT_FIELD = 'Email';

    public static final String RN_FIELD = 'TerritorialDirection__c';
    public static final String RN_NAME = 'ZONA ZURICH CENTRALIZADOS';
    
    /**
     * Metodo que crea datos de configuracion de prueba para los Account Team Members (ATM)
     *
     * @author nts (agonzalezisasi)
     * @date 02/07/2021
     */
    public static List<SDMAccountTeamRole__mdt> getSDMSettingsATM(string role, string field)
    {
        List<SDMAccountTeamRole__mdt> settings = new List<SDMAccountTeamRole__mdt>();
        settings.add(new SDMAccountTeamRole__mdt(
            Label= 'testATM',
            DeveloperName= 'testATM',
            Role__c= role,
            IntermediaryField__c= field,
            Status__c= 'Active'
        ));
        return settings;
    }

    /**
     * Metodo que crea datos de configuracion de prueba para los Account Contact Relation (ACR)
     *
     * @author nts (agonzalezisasi)
     * @date 02/07/2021
     */
    public static List<SDMAccountContactRelation__mdt> getSDMSettingsACR(string role, string field, string text)
    {
        List<SDMAccountContactRelation__mdt> settings = new List<SDMAccountContactRelation__mdt>();

        settings.add(
            new SDMAccountContactRelation__mdt(
                Label= 'testATM',
                DeveloperName= 'testATM',
                Role__c= role,
                IntermediaryField__c= field,
                NameText__c= text
            )
        );

        return settings;
    }

    public static void IntermediarySetupData()
    {
        // Creacion de las Agrupaciones de Mediadores
        List<Account> agrupations = TestDataFactory.generateAccounts(
            ACCOUNT_LEGAL_ENTITY, AccountsSelector.RT_NAME_AGRUPATION, 1
        );
        agrupations[0].NationalId__c = AGRUPATION_CIF;
        insert agrupations;

        // Creacion de los Mediadores
        List<Account> intermediaries = TestDataFactory.generateAccounts(ACCOUNT_LEGAL_ENTITY, AccountsSelector.RT_NAME_INTERMEDIARY, 10);
        for( Integer i=0; i<intermediaries.size(); i++ ) {
            // Para la agrupacion de mediadores
            intermediaries[i].NationalId__c = AGRUPATION_CIF;
            // Para el equipo de cuentas
            intermediaries[i].put(TERRITORY_FIELD, String.format(TERRITORY_EMAIL, new List<String>{String.valueOf(i)}));
            intermediaries[i].IntermediaryStatus__c = 'Active';
            // Para la relacion de contactos
            intermediaries[i].put(MAINEMAIL_FIELD, String.format(MAINEMAIL_EMAIL, new List<String>{String.valueOf(i)}));
        }
        insert intermediaries;

        // Creacion de los usuarios para el equipo de cuentas
        List<Profile> profiles = [SELECT Id FROM Profile WHERE Name = 'SDM RN'];
        System.assertEquals(1, profiles.size(), 'El perfil SDM RN deberia existir');
        List<User> users = TestDataFactory.generateUsersByProfile(profiles[0].Id, 10);
        for( Integer i=0; i<users.size(); i++ ) {
            users[i].Email = String.format(TERRITORY_EMAIL, new List<String>{String.valueOf(i)});
        }
        insert users;

        // 4 Contactos para los 4 primeros Mediadores, creara ACRs sin Rol
        List<Account> intermediariesToCreateContact = new List<Account>();
        intermediariesToCreateContact.add(intermediaries[0]);
        intermediariesToCreateContact.add(intermediaries[1]);
        intermediariesToCreateContact.add(intermediaries[2]);
        intermediariesToCreateContact.add(intermediaries[3]);

        // Creacion de los contactos para el proceso de relacion de contactos
        List<Contact> contacts = TestDataFactory.generateContactsFromAccounts(intermediariesToCreateContact, ContactsSelector.RT_NAME_CONTACT, 1);
        for( Integer i=0; i<4; i++ ) {
            contacts[i].Email = String.format(MAINEMAIL_EMAIL, new List<String>{String.valueOf(i)});
        }
        insert contacts;

        // Asignamos el rol a las ACRs creadas al insertar los contactos
        List<AccountContactRelation> acrs = [SELECT Id, Roles FROM AccountContactRelation WHERE ContactId IN :contacts];
        System.assertEquals(4, acrs.size(), 'Deberian existir 4 ACRs');
        for(AccountContactRelation acr: acrs) {
            acr.Roles = 'Other rol';
        }
        update acrs;
    }
}