force-app/zurich-base/main/default/objects/Account/fields/IntermediaryGroup__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referencia al registro de Cuenta Agrupación</description>
    <label>Intermediary Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Solo se puede seleccionar una cuenta de tipo Agrupación Mediador</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Intermediary Group</relationshipLabel> 
    <relationshipName>IntermediaryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>Comprende aquellos posibles clientes todavía no existentes en el sistema transaccional</description>
    <label>Lead</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Cross_Selling__c/Cross_Selling__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Venta Cruzada</label>
</CustomObject>

force-app/zurich-base/main/default/objects/Cross_Selling__c/fields/DefaultUser__c.field-meta.xml
<CustomField>
    <fullName>DefaultUser__c</fullName>
    <description>Alias del usuario genérico al que asignar Ofertas de Venta Cruzada y de Leads en caso de error en la asignación.
ej: ntsadmin</description>
    <label>Usuario Por Defecto</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ZRMLeadATM__e/ZRMLeadATM__e.object-meta.xml
<CustomObject>
    <description>Evento que se lanza cuando se inserta un lead desde el botón nuevo de la comunidad ZRM para generar los atm y modificar el owner a un usuario admin</description>
    <label>ZRM Lead ATM</label>
    <pluralLabel>ZRM Leads ATM</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/ZRMLeadATM__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Id del lead a insertar el ATM</description>
    <label>AccountId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/ZRMLeadATM__e/fields/ZRMUserId__c.field-meta.xml
<CustomField>
    <fullName>ZRMUserId__c</fullName>
    <description>El id del usuario que ha pulsado el botón nuevo</description>
    <label>ZRM User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/zurich-ventas-app/main/default/classes/GenerateZRMLeadATMUtil.cls
/**
 * Clase utilidad del trigger para el evento ZRMLeadATM__e
 *
 * @author dmunoz
 * @date 07/03/2024 
 */
public with sharing class GenerateZRMLeadATMUtil {
    
    public static void handleEventAfterInsert(List<ZRMLeadATM__e> eventListTrigger) {

        try
        {
            
            List<String> leadsIds = new List<String>();
            List<String> eventUsersIdList = new List<String>();
    
            for (ZRMLeadATM__e event: eventListTrigger) {
                eventUsersIdList.add(event.ZRMUserId__c);
                leadsIds.add(event.AccountId__c);
            }
    
            // Update owner
            updateZRMLeadsOwner(leadsIds);
    
            // Generate ATMs
            generateZRMLeadsATM(leadsIds, eventUsersIdList);

        }
        catch (Exception e)
        {            
            ErrorLogUtil.commitError(e, 'GenerateZRMLeadATMTrigger', 'handleEventAfterInsert');            
        }


    }


    private static void updateZRMLeadsOwner(List<String> leadsIdsToUpdateOwner) {

        List<Account> leadsToUpdate = new List<Account>();
        String defaultUser = obtainDefaultUser();
        Account acc;

        for (String accountId: leadsIdsToUpdateOwner) {
            acc = new Account();
            acc.Id = accountId;
            acc.OwnerId = defaultUser;
            leadsToUpdate.add(acc);

        }

        update leadsToUpdate;
        
    }


    private static void generateZRMLeadsATM(List<String> leadsIds, List<String> eventUsersIdList) {

        List<AccountTeamMember> atmToInsert = new List<AccountTeamMember>();

        // Obtengo el mediador y agrupacion del usuario del evento. Solo me quedo con el primero ya que generamos un evento por cada lead no se inserta en modo bulk
        UsersSelector userSelector = new UsersSelector();
        User userEvent = userSelector.findUserIntermediaryByUserId(eventUsersIdList.get(0));

        // Obtengo todos los usuarios a los que generaremos atm a través del mediador y de la agrupacion del mediador        
        Set<String> intermediariesSet = new Set<String>{userEvent.Contact.AccountId};
        Map<String, String> mediadoresIdsYAgrupacionesIdMap = new Map<String, String>();
        mediadoresIdsYAgrupacionesIdMap.put(userEvent.Contact.AccountId, userEvent.Contact.Account.IntermediaryGroup__c);

        // <IntermediaryId, List<UserId>
        Map<String, List<String>> intermediariesWithUsers = ZRMAccountVisibilityUtil.getIntermediariesUsers(intermediariesSet, mediadoresIdsYAgrupacionesIdMap);

        // Generamos los atms a insertar (el bucle solo se ejecutará una vez)
        for (String leadId: leadsIds) {
            atmToInsert.addAll(AccountTeamMemberUtil.createATMZRMRecordList(leadId, intermediariesWithUsers.get(userEvent.Contact.AccountId)));
        }

        if (!atmToInsert.isEmpty()) {
            insert atmToInsert;
        }
    }

    /**
     * @description Método para recuperar los Ids de los usuarios configurados para ser los
     *              Ids por defecto para el usuario por defecto CC y el usuario por defecto
     *              en caso de error.
     * @author      jgallaga
     * @date        18/08/2023
     */
    private static String obtainDefaultUser()
    {

        String defaultUserId;
        String aliasDeaultUser = Cross_Selling__c.getinstance().DefaultUser__c;

        UsersSelector userQuery = new UsersSelector();

        List<User> defaultUsers = userQuery.findUsersByAlias(new List<String> {aliasDeaultUser});

        defaultUserId = defaultUsers.get(0).Id;

        return defaultUserId;
    }

}