force-app/zurich-base/main/default/objects/Account/fields/IntermediaryGroup__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referencia al registro de Cuenta Agrupación</description>
    <label>Intermediary Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Solo se puede seleccionar una cuenta de tipo Agrupación Mediador</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Intermediary Group</relationshipLabel> 
    <relationshipName>IntermediaryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/AgrupacionMediador.recordType-meta.xml
<RecordType>
    <fullName>AgrupacionMediador</fullName>
    <active>true</active>
    <description>SDM: Agrupación de mediador a nivel CIF</description>
    <label>Agrupación Mediador</label>
</RecordType>

force-app/zurich-base/main/default/objects/Account/recordTypes/Intermediary.recordType-meta.xml
<RecordType>
    <fullName>Intermediary</fullName>
    <active>true</active>
    <label>Intermediary</label>
</RecordType>

force-app/zurich-base/main/default/objects/AccountRelationship__c/AccountRelationship__c.object-meta.xml
<CustomObject>
    <label>Cuenta Relacionada</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuentas Relacionadas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/AccountRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Lead</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BusinessCustomer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Relationships</relationshipLabel>
    <relationshipName>Accounts_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/AccountRelationship__c/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifica el intermediario</description>
    <label>Intermediary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas Relacionadas (Intermediary)</relationshipLabel>
    <relationshipName>Cuentas_Relacionadas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/AccountRelationship__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Relationships (Related Account)</relationshipLabel>
    <relationshipName>Accounts_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/AccountRelationship__c/fields/RelationshipType__c.field-meta.xml
<CustomField>
    <fullName>RelationshipType__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1er grado familiar</fullName>
            </value>
            <value>
                <fullName>2º grado familiar</fullName>
            </value>
            <value>
                <fullName>Relación laboral</fullName>
            </value>
            <value>
                <fullName>Relación amistad</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Cross_Selling__c/Cross_Selling__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Venta Cruzada</label>
</CustomObject>

force-app/zurich-base/main/default/objects/Cross_Selling__c/fields/ContactCenterUser__c.field-meta.xml
<CustomField>
    <fullName>ContactCenterUser__c</fullName>
    <label>Usuario CC</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Cross_Selling__c/fields/DefaultUser__c.field-meta.xml
<CustomField>
    <fullName>DefaultUser__c</fullName>
    <description>Alias del usuario genérico al que asignar Ofertas de Venta Cruzada y de Leads en caso de error en la asignación.
ej: ntsadmin</description>
    <label>Usuario Por Defecto</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/RelatedAccount__c/RelatedAccount__c.object-meta.xml
<CustomObject>
    <label>Related Account</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Related Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/classes/AccountRelationshipUtilTest.cls
@isTest
public with sharing class AccountRelationshipUtilTest
{
    @TestSetup
    static void makeData()
    {
        /* ----------------------------- CUSTOM SETTINGS ---------------------------- */
        Cross_Selling__c ventaCruzada = new Cross_Selling__c();
        ventaCruzada.ContactCenterUser__c = 'generico';
        ventaCruzada.DefaultUser__c = 'adminkli';
        insert ventaCruzada;

        /* -------------------------------- ACCOUNTS -------------------------------- */
        // Cliente
        List<Account> customerAccounts = TestDataFactory.generateAccounts('001', 'Customer', 2);
        insert customerAccounts;

        //Agrupaciones
        List<Account> agrupaciones = TestDataFactory.generateAccounts(Label.GeneralInsurance, 'AgrupacionMediador', 1);
        insert agrupaciones;

        // Mediador
        List<Account> intermediarios = TestDataFactory.generateAccounts(Label.GeneralInsurance, 'Intermediary', 1);
        for(Integer i = 0; i < intermediarios.size(); i++)
        {
            intermediarios[i].IntermediaryGroup__c = agrupaciones[i].Id;
        }
        insert intermediarios;

        /* -------------------------------- CONTACTS -------------------------------- */
        // Mediador
        List<Contact> intermediaryContacts = TestDataFactory.generateContactsFromAccounts(intermediarios, ContactsSelector.RT_NAME_CONTACT, 1);
        insert intermediaryContacts;

        /* ---------------------------------- USERS --------------------------------- */
        UserRole portalRole = [SELECT Id FROM UserRole WHERE PortalType = 'None' LIMIT 1];
        Id portalProfile = [SELECT Id FROM Profile WHERE Name = 'Agente Ventas' LIMIT 1].Id;
        List<User> users = TestDataFactory.generateUsersByProfile(portalProfile, 1);
        for(Integer i = 0; i < users.size(); i++)
        {
            users[i].UserRole = portalRole;
            users[i].ContactId = intermediaryContacts[i].Id;
        }

        insert users;
    }

    @isTest
    static void testOnBeforeInsertChangeOwner()
    {
        /* -------------------------------- TEST DATA ------------------------------- */
        List<Account> customerAccounts = [SELECT Id, OwnerId FROM Account WHERE Name LIKE 'testlastname%'];
        User defaultOwner = AccountRelationshipUtil.getDefaultOwnerUser();

        AccountRelationship__c ar = new AccountRelationship__c();
        ar.Account__c = customerAccounts[0].Id;
        ar.RelatedAccount__c = customerAccounts[1].Id;
        ar.RelationshipType__c = 'Otros';

        /* ---------------------------------- TEST ---------------------------------- */
        Test.startTest();
        AccountRelationshipUtil.onBeforeInsertChangeOwner(new List<AccountRelationship__c> {ar});
        Test.stopTest();

        /* --------------------------------- ASSERTS -------------------------------- */
        Assert.areEqual(defaultOwner.Id, ar.OwnerId, 'Owner should be the default owner user.');
    }

    @isTest
    static void testUpdateIntermediaryId()
    {
        /* -------------------------------- TEST DATA ------------------------------- */
        List<Account> customerAccounts = [SELECT Id, OwnerId FROM Account WHERE Name LIKE 'testlastname%'];
        User agenteVentas = [SELECT Id, Account.IntermediaryGroup__c FROM User WHERE Profile.Name = 'Agente Ventas' LIMIT 1];

        AccountRelationship__c ar = new AccountRelationship__c();
        ar.Account__c = customerAccounts[0].Id;
        ar.RelatedAccount__c = customerAccounts[1].Id;
        ar.RelationshipType__c = 'Otros';

        /* ---------------------------------- TEST ---------------------------------- */
        Test.startTest();
        System.runAs(agenteVentas)
        {
            AccountRelationshipUtil.updateIntermediaryId(new List<AccountRelationship__c> {ar}, null);
        }
        Test.stopTest();

        /* --------------------------------- ASSERTS -------------------------------- */
        Assert.areEqual(agenteVentas.Account.IntermediaryGroup__c, ar.IntermediaryId__c, 'IntermediaryId should be the same as the Agente Ventas Account.IntermediaryGroup__c');
    }
}