force-app/zurich-base/main/default/objects/Account/fields/IntermediaryGroup__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referencia al registro de Cuenta Agrupación</description>
    <label>Intermediary Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Solo se puede seleccionar una cuenta de tipo Agrupación Mediador</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Intermediary Group</relationshipLabel> 
    <relationshipName>IntermediaryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/IntermediaryVisibilityAcc__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryVisibilityAcc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intermediary Visibility Acc</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Intermediary Visibility)</relationshipLabel>
    <relationshipName>IntermediaryVisibilityAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/IntermediaryWithUser__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryWithUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referencia al registro de Cuenta Mediador asociado a la licencia de usuario compartida (si aplica).</description>
    <label>Intermediary With User</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Main Intermediaries</relationshipLabel>
    <relationshipName>MainIntermediaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS) Identifica el nombre del intermediario ya sea partner o mediador.</description>
    <label>Intermediary</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers (Intermediary)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/IntermediaryVisibilityAcc__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryVisibilityAcc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Registro de Cuenta Mediador asociado a la Póliza que determina la visibilidad del usuario:

    - Si existe Agrupación y esta tiene definida que se use la Cuenta Mediador-padre: Cuenta Mediador-padre de la Agrupación

    - Sino: Valor del campo IntermediaryId__c</description>
    <label>Intermediary Visibility Acc</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers (Intermediary Visibility)</relationshipLabel>
    <relationshipName>IntermediariesOffersVisibility</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-ventas-app/main/default/classes/Batch_IntermediaryVisibilityRecalcOpp.cls
global with sharing class Batch_IntermediaryVisibilityRecalcOpp implements Database.Batchable<sObject>{
    
    private static final String CLASS_NAME = 'Batch_IntermediaryVisibilityRecalcOpp';
    

    /*********** Métodos Batch **************************************************************************/
    /**
     * Metodo start del batch, devuelve la lista de elementos a los que se recalculará la visibilidad
     * @param bc: batch context
     * @return List los campaign member a clonar
     * @author dmunoz
     * @date 18/09/2023
     */
    global List<Opportunity> start(Database.BatchableContext bc) { 
        return (new OpportunitiesSelector()).findOffersWithIncorrectVisibility();        
    }


    /**
     * Metodo execute del batch, 
     * @param bc: batch context
     * @param scope lista de Offers procedentes del método start
     * @return void
     * @author dmunoz
     * @date 18/09/2023
     */
    global void execute(Database.BatchableContext bc, List<Opportunity> scope) {
        try {
            List<Opportunity> updatedOffersVisibilityList = updateOffersVisibility(scope);

            update updatedOffersVisibilityList;
        } catch (Exception e) {
            ErrorLogUtil.commitError(e, CLASS_NAME);
        }
    }

    /**
     * Metodo finish del batch, 
     * @param bc: batch context
     * @return void
     * @author dmunoz
     * @date 18/09/2023
     */
    global void finish(Database.BatchableContext bc) {
        // nothing
    }
    
    


    /*********** Métodos Auxiliares **************************************************************************/
    
    /**
     * Actualiza el campo de visibilidad de las ofertas recuperadas con la consulta de bd con el valor correcto, 
     * @param bc: batch context
     * @return void
     * @author dmunoz
     * @date 18/09/2023
     */
    private List<Opportunity> updateOffersVisibility(List<Opportunity> scope) {

        for (Opportunity op: scope) {
            if (op.IntermediaryId__c != null && !op.IntermediaryId__r.IsPartner && op.IntermediaryId__r.IntermediaryGroup__c != null && op.IntermediaryId__r.IntermediaryGroup__r.IntermediaryWithUser__c != null) {
                op.IntermediaryVisibilityAcc__c = op.IntermediaryId__r.IntermediaryGroup__r.IntermediaryWithUser__c;
            } else {
                op.IntermediaryVisibilityAcc__c = op.IntermediaryId__c; 
            }
        }
        return scope;
    }
}