force-app/zurich-base/main/default/objects/Account/fields/IntermediaryGroup__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referencia al registro de Cuenta Agrupación</description>
    <label>Intermediary Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Solo se puede seleccionar una cuenta de tipo Agrupación Mediador</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Intermediary Group</relationshipLabel> 
    <relationshipName>IntermediaryGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/AgrupacionMediador.recordType-meta.xml
<RecordType>
    <fullName>AgrupacionMediador</fullName>
    <active>true</active>
    <description>SDM: Agrupación de mediador a nivel CIF</description>
    <label>Agrupación Mediador</label>
</RecordType>

force-app/zurich-base/main/default/objects/Account/recordTypes/Intermediary.recordType-meta.xml
<RecordType>
    <fullName>Intermediary</fullName>
    <active>true</active>
    <label>Intermediary</label>
</RecordType>

force-app/zurich-base/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Record type for business contacts</description>
    <label>Contact</label>
</RecordType>

force-app/zurich-base/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/IntermediaryId__c.field-meta.xml
<CustomField>
    <fullName>IntermediaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica el nombre del intermediario ya sea partner o mediador</description>
    <label>Intermediary</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/VisibilityRetry__c.field-meta.xml
<CustomField>
    <fullName>VisibilityRetry__c</fullName>
    <description>[ZRM] en caso de error al procesar los cambios de mediador o cliente por el batch, se indica este número de reintentos para tener rastreabilidad de estos problemas y definir un número máximo de intentos para dicho registro y no se acumulen indefinidamente errores</description>
    <label>Visibility Retry</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-ventas-app/main/default/classes/Batch_IntermediaryOrAccountChangeDMLTest.cls
/**
 * @description       : Clase de test que comprueba el correcto funcionamiento
 * de la clase 'Batch_IntermediaryOrAccountChangeDML'.
 * @author            : amiranda
 * @date              : 11-04-2024
 * @last modified on  : 11-04-2024
 * @last modified by  : amiranda
 * Modifications Log
 * Ver   Date         Author     Modification
 * 1.0   11-04-2024   amiranda   Initial Version
 **/
@IsTest
private with sharing class Batch_IntermediaryOrAccountChangeDMLTest
{

    /**
    * @description Método para inicializar los datos de prueba
    * @author amiranda
    * @date 11-04-2024 
    **/
    @TestSetup
    private static void makeData()
    {
        /** Insertar usuarios ZRM ***************************************************************/
        // Crear cuentas de agrupacion
        List<Account> agrupaciones = TestDataFactory.generateAccounts(Label.GeneralInsurance,'AgrupacionMediador', 1);
        insert agrupaciones;
        // Crear cuentas de mediadores
        List<Account> intermediaryAccounts = TestDataFactory.generateAccounts(Label.GeneralInsurance,'Intermediary', 2);
        intermediaryAccounts.get(0).IntermediaryGroup__c = agrupaciones.get(0).Id;
        intermediaryAccounts.get(0).Name = 'MediadorTest';
        intermediaryAccounts.get(1).Name = 'MediadorTest2';
        insert intermediaryAccounts;

        // Crear contactos de mediadores
        List<Contact> contacts = TestDataFactory.generateContactsFromAccounts(intermediaryAccounts, ContactsSelector.RT_NAME_CONTACT, 2);
        insert contacts;

        // Crear los usurios para recuperar
        List<User> userList = new List<User>();
        List<User> userAGRList = new List<User>();

        List<String> adminProfiles = new List<String> {'Administrador del sistema', 'System Administrator'};
        List<Boolean> activeStatus = new List<Boolean> {true};
        User adminUser = ( new UsersSelector() ).findByProfileName(adminProfiles, activeStatus, 1)[0];

        System.runAs (adminUser)
        {
            // Usuario Nominal
            String portalProfile = [SELECT Id FROM Profile WHERE Name = 'Agente Ventas' LIMIT 1].Id;

            userList = TestDataFactory.generateUsersByProfile(portalProfile, 1);
            userList[0].ContactId = contacts[0].Id;
            insert userList;

            // Usuario AGR
            String portalAGRProfile = [SELECT Id FROM Profile WHERE Name = 'Agente Ventas - AGR' LIMIT 1].Id;

            userAGRList = TestDataFactory.generateUsersByProfile(portalAGRProfile, 1);
            userAGRList[0].ContactId = contacts[1].Id;

            insert userAGRList;
        }

        List<Account> customers = TestDataFactory.generateAccounts(Label.GeneralInsurance, 'Customer', 2);
        insert customers;

        List<Policy__c> policies = TestDataFactory.generatePoliciesForEachAccount(customers, 1);
        for (Policy__c policy : policies)
        {
            policy.IntermediaryId__c = intermediaryAccounts.get(0).Id;
        }
        insert policies;
    }

    /**
    * @description Método de test que comprueba que se insertan y eliminan
    * AccountTeamMember desde el batch 'Batch_IntermediaryOrAccountChangeDML'
    * @author amiranda
    * @date 11-04-2024 
    **/
    @IsTest
    private static void test_executeBatch_insertAndDelete()
    {
        List<Policy__c> policies = [SELECT VisibilityRetry__c FROM Policy__c LIMIT 1];
        List<AccountTeamMember> atms = [SELECT UserId, AccountId, TeamMemberRole FROM AccountTeamMember];

        List<AccountTeamMember> atmsToInsert = new List<AccountTeamMember>();
        for (AccountTeamMember atm : atms)
        {
            atmsToInsert.add( atm.clone(false, true, false, false) );
        }

        Test.startTest();
        Database.executeBatch( new Batch_IntermediaryOrAccountChangeDMLs(policies,
                                                                         atms,
                                                                         atmsToInsert,
                                                                         10000) );
        Test.stopTest();

        List<AccountTeamMember> atmsInserted = [SELECT Id FROM AccountTeamMember];
        Assert.areEqual(atms.size(), atmsInserted.size(), 'El número total de AccountTeamMembers debería ser el mismo.');
    }

    /**
    * @description Método de test que comprueba que se capturan los errores
    * correctamente en la ejecución del batch 'Batch_IntermediaryOrAccountChangeDML'
    * @author amiranda
    * @date 11-04-2024 
    **/
    @IsTest
    private static void test_executeBatch_ko()
    {
        List<Policy__c> policies = [SELECT VisibilityRetry__c FROM Policy__c LIMIT 1];
        List<AccountTeamMember> atms = [SELECT Id FROM AccountTeamMember];

        List<AccountTeamMember> atmsToInsert = new List<AccountTeamMember>();
        for (AccountTeamMember atm : atms)
        {
            atmsToInsert.add( atm.clone(false, false, false, false) );
        }

        Test.startTest();
        Database.executeBatch( new Batch_IntermediaryOrAccountChangeDMLs(policies,
                                                                         atms,
                                                                         atmsToInsert,
                                                                         10000) );
        Test.stopTest();

        List<Error_Log__c> errors = [SELECT Id FROM Error_Log__c];
        Assert.isTrue(!errors.isEmpty(), 'La lista de errores no debería estar vacía.');
    }

    /**
    * @description Método de test que comprueba que se eliminan los AccountTeamMember
    * desde el batch 'Batch_IntermediaryOrAccountChangeDML'
    * @author amiranda
    * @date 11-04-2024 
    **/
    @IsTest
    private static void test_executeBatch_delete()
    {
        List<Policy__c> policies = [SELECT VisibilityRetry__c FROM Policy__c LIMIT 1];
        List<AccountTeamMember> atmsToDelete = [SELECT Id FROM AccountTeamMember];

        Test.startTest();
        Database.executeBatch( new Batch_IntermediaryOrAccountChangeDMLs(policies,
                                                                         atmsToDelete,
                                                                         new List<AccountTeamMember>(),
                                                                         10000) );
        Test.stopTest();

        List<AccountTeamMember> atms = [SELECT LastModifiedDate FROM AccountTeamMember];
        Assert.isTrue(atms.isEmpty(), 'La lista de AccountTeamMembers debería estar vacía');
    }

    /**
    * @description Método de test que comprueba que se insertan los AccountTeamMember
    * desde el batch 'Batch_IntermediaryOrAccountChangeDML'
    * @author amiranda
    * @date 11-04-2024 
    **/
    @IsTest
    private static void test_executeBatch_insert()
    {
        List<Policy__c> policies = [SELECT VisibilityRetry__c FROM Policy__c LIMIT 1];
        List<AccountTeamMember> atms = [SELECT LastModifiedDate, UserId, AccountId, TeamMemberRole FROM AccountTeamMember];

        List<AccountTeamMember> atmsToInsert = new List<AccountTeamMember>();
        for (AccountTeamMember atm : atms)
        {
            atmsToInsert.add( atm.clone(false, true, false, false) );
        }

        Test.startTest();
        Database.executeBatch( new Batch_IntermediaryOrAccountChangeDMLs(policies,
                                                                         new List<AccountTeamMember>(),
                                                                         atmsToInsert,
                                                                         10000) );
        Test.stopTest();

        List<AccountTeamMember> atmInserted = new List<AccountTeamMember>([SELECT LastModifiedDate FROM AccountTeamMember]);
        Assert.areEqual(atmInserted.size(),
                        atms.size(),
                        'Debe haber el mismo número de atms'); 
    }
}