force-app/zurich-base/main/default/objects/Account/fields/Intermediary_Name__c.field-meta.xml
<CustomField>
    <fullName>Intermediary_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS/ZE). Relación a la cuenta de intermediario asociada al contacto (Partner o Mediador). Al existir este dato únicamente a nivel de póliza, el CRM lo informa en base al valor de Intermediario de la póliza más reciente</description>
    <label>Intermediary Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Intermediary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/KPI__c/KPI__c.object-meta.xml
<CustomObject>
    <description>SDM: KPIs de mediadores</description>
    <label>KPI</label>
    <nameField>
        <label>KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/KPI__c/fields/Intermediary__c.field-meta.xml
<CustomField>
    <fullName>Intermediary__c</fullName>
    <label>Intermediario</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KPIs</relationshipLabel>
    <relationshipName>KPIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/PlanComercial__c.object-meta.xml
<CustomObject>
    <description>SDM: Utilizado para representar el plan de negocio realizado por los directores.</description>
    <label>Plan Comercial</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/AccumulateType__c.field-meta.xml
<CustomField>
    <fullName>AccumulateType__c</fullName>
    <description>SDM: tipo de acumulado con el que se quiere comparar dentro del objeto KPI</description>
    <label>Accumulate type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
                <label>Current month</label>
            </value>
            <value>
                <fullName>YTD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Actual_KPI__c.field-meta.xml
<CustomField>
    <fullName>Actual_KPI__c</fullName>
    <description>SDM: el resultado de KPI calculado de forma automática para el plan de acción a través de todos los criterios establecidos en el mismo</description>
    <label>Actual KPI</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDM: usuario, de tipo RN o consultor, al que irá asociado el registro. Se utiliza de cara a que un Director pueda generar planes para los usuarios de los que es responsable.</description>
    <label>Assigned to</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Solo se puede asignar planes comerciales a usuarios de SDM</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>SDM RN</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>SDM Director</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PlanComercial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <description>SDM: indicador (campo) del KPI con el que se quiere comparar el objetivo</description>
    <label>Indicator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>PoliciesPN</fullName>
                <label>Pólizas PN</label>
            </value>
            <value>
                <fullName>PoliciesInForce</fullName>
                <label>Pólizas en vigor</label>
            </value>
            <value>
                <fullName>Portfolio</fullName>
                <label>Cartera</label>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
            <value>
                <fullName>Ratio_Claim</fullName>
                <label>% Sin Total</label>
            </value>
            <value>
                <fullName>Ratio_PNIncrease</fullName>
                <label>% Crec PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesPNIncreas</fullName>
                <label>% Crec Pólizas PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesInForceIncrease</fullName>
                <label>% Crec Pólizas vigor vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PortIncrease</fullName>
                <label>% crecimiento cartera</label>
            </value>
            <value>
                <fullName>Totaldiscount</fullName>
                <label>% Dto. Total</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Intermediary__c.field-meta.xml
<CustomField>
    <fullName>Intermediary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>SDM: mediador sobre el que se quiere realizar la búsqueda de KPIs para el cálculo de las cifras realas para su comparación con el objetivo</description>
    <label>Intermediary</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La cuenta debe ser un agente</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador, Intermediary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planes Comerciales</relationshipLabel>
    <relationshipName>PlanComercial</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/ParentPlan__c.field-meta.xml
<CustomField>
    <fullName>ParentPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDM: hace referencia a un plan anual padre</description>
    <label>Parent Plan</label>
    <referenceTo>PlanComercial__c</referenceTo>
    <relationshipLabel>Planes Comerciales</relationshipLabel>
    <relationshipName>ParentPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>SDM: productos del que se quiere obtener la información de los KPIs</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autos</fullName>
                <label>Cars</label>
            </value>
            <value>
                <fullName>Hogar</fullName>
                <label>Home</label>
            </value>
            <value>
                <fullName>Inmuebles</fullName>
                <label>Estate</label>
            </value>
            <value>
                <fullName>Accidentes</fullName>
                <label>Accidents</label>
            </value>
            <value>
                <fullName>Comercios</fullName>
                <label>Commerce</label>
            </value>
            <value>
                <fullName>Patrimoniales</fullName>
                <label>Patrimonial</label>
            </value>
            <value>
                <fullName>Resp. Civil</fullName>
                <label>Civil liability</label>
            </value>
            <value>
                <fullName>Vida riesgo individual</fullName>
                <label>Individual risk life</label>
            </value>
            <value>
                <fullName>Vida riesgo colectivo</fullName>
                <label>Collective risk life</label>
            </value>
            <value>
                <fullName>Todos</fullName>
                <label>All</label>
            </value>
            <value>
                <fullName>Resto</fullName>
            </value>
            <value>
                <fullName>Communitdades</fullName>
                <label>Communities</label>
            </value>
            <value>
                <fullName>Resto Particulares</fullName>
                <isActive>false</isActive>
                <label>Rest Individuals</label>
            </value>
            <value>
                <fullName>Resto PYMEs</fullName>
                <isActive>false</isActive>
                <label>Rest of SMEs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>SDM: segmento del que se quiere obtener la información de los KPIs</description>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Individuals</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>SMEs</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Large companies</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Life risk</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>All products</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/SendNotifications__c.field-meta.xml
<CustomField>
    <fullName>SendNotifications__c</fullName>
    <description>SDM: se permite definir al usuario cúando quiere que se le mande notificación. Vacío para no mandar notificación</description>
    <label>Send notifications</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Indicator__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Above threshold</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Below threshold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>SDM: fecha en la que comienza el plan de acción (solo aplicable a tipo acumulado YTD)</description>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/TargetKPICurrency__c.field-meta.xml
<CustomField>
    <fullName>TargetKPICurrency__c</fullName>
    <description>SDM: el objetivo  económico que se define en el plan para poder comparar con datos reales a futuro</description>
    <label>Target KPI €</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/TargetKPINumber__c.field-meta.xml
<CustomField>
    <fullName>TargetKPINumber__c</fullName>
    <description>SDM: el objetivo de cuantía que se define en el plan para poder comparar con datos reales a futuro</description>
    <label>Target KPI Nº</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/TargetKPIPercent__c.field-meta.xml
<CustomField>
    <fullName>TargetKPIPercent__c</fullName>
    <description>SDM: el objetivo de porcentaje que se define en el plan para poder comparar con datos reales a futuro</description>
    <label>Target KPI %</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/recordTypes/AnualPlan.recordType-meta.xml
<RecordType>
    <fullName>AnualPlan</fullName>
    <active>true</active>
    <description>sdm: plan comercial anual generado a partir del DT</description>
    <label>Anual Plan</label>
</RecordType>

force-app/zurich-sdm-app/main/default/classes/PlanComercialSelector.cls
/**
 * Clase selector del objeto PlanComercial__c
 *
 * Proyecto: SDM (Sales Digital Management)
 *
 * @author nts (agonzalezisasi)
 * @date 01/10/2021
 */
public with sharing class PlanComercialSelector extends RecordsSelector {

    public static final String RT_NAME_PLAN_ANUAL = 'AnualPlan'; // Recordtype PlanComercial__c=>PlanAnual

    public static final String SEGMENT_ALL = 'Todos'; // Valor picklist PlanComercial__c.Segment__c
    public static final String PRODUCT_ALL = 'Todos'; // Valor picklist PlanComercial__c.Product__c
    public static final String ACCUMULATE_TYPE_YRD = 'YTD'; // Valor picklist PlanComercial__c.AccumulateType__c
    public static final String INDICATOR_PN = 'PN';  // Valor picklist PlanComercial__c.Indicator__c
    public static final String SEND_NOTIFICATION_ABOVE_THRESHOLD = '01';  // Valor picklist PlanComercial__c.SendNotifications__c

    // Id del tipo de registro de PlanAnual
    public ID rtPlanAnualId {
        get {
            return Schema.SObjectType.PlanComercial__c.getRecordTypeInfosByDeveloperName().get(RT_NAME_PLAN_ANUAL)?.getRecordTypeId();
        }
    }

    // Tipos de indicadores
    public enum eIndicator {
        type_number,
        type_currency,
        type_percent
    }

    // Mapa de equivalencias entre los tipos de Indicador y el campo target del objeto KPI__c
    public static Map<eIndicator, String> mapIndicatorTypeField = new Map<eIndicator, String> {
        eIndicator.type_number => 'TargetKPINumber__c',
        eIndicator.type_currency => 'TargetKPICurrency__c',
        eIndicator.type_percent => 'TargetKPIPercent__c'
    };
    
    // Equivalencias entre la picklist PlanComercial__c.Indicator__c y el tipo de valor para el plan.
    // num = numerico / currency = moneda / percent = porcentaje
    public static Map<String, eIndicator> mapIndicatorType = new Map<String, eIndicator> {
        'PN' => eIndicator.type_number,
        'PoliciesPN' => eIndicator.type_number,
        'PoliciesInForce' => eIndicator.type_number,
        'Portfolio' => eIndicator.type_currency,
        'Ratio_PNIncrease' => eIndicator.type_percent,
        'Ratio_PoliciesPNIncreas' => eIndicator.type_percent,
        'Ratio_PoliciesInForceIncrease' => eIndicator.type_percent,
        'Ratio_PortIncrease' => eIndicator.type_percent,
        'Ratio_Claim' => eIndicator.type_percent,
        'Ratio_Retention' => eIndicator.type_percent,
        'Totaldiscount' => eIndicator.type_percent
    };

    /**
     * Constructor
     */
    public PlanComercialSelector() 
    {
        super(PlanComercial__c.getSObjectType());
    }

    /**
     * Calcula el tipo de indicador segun el indicador de plan indicado
     * 
     * @author nts (agonzalezisasi)
     * @date 20/09/2021
     * 
     * @param {String indicator} indicador del plan
     * @return {eIndicator} tipo de indicador
     */
    public static eIndicator getIndicatorType(String indicator) 
    {
        eIndicator result = eIndicator.type_number;
        if( mapIndicatorType.containsKey(indicator) ) result = mapIndicatorType.get(indicator);

        return result;
    }

    /**
     * Devuelve el nombre del campo TargetKPI... del objeto PlanComercial__c segun
     * el tipo de indicador
     * 
     * @author nts (agonzalezisasi)
     * @date 04/10/2021
     * 
     * @param {eIndicator indicator} tipo de indicador
     * @return {String} nombre del campo
     */
    public static String getTargetKPIFieldByType(eIndicator indicator)
    {
        return mapIndicatorTypeField.get(indicator);
    }

    /**
     * Convierte el mapa de tipos de indicador en un mapa de strings
     * 
     * @author nts (agonzalezisasi)
     * 
     * @return {Map<String, String>} mapa convertido
     */
    public static Map<String, String> getMapIndicatorType()
    {
        Map<String, String> result = new Map<String, String>();
        for(String key: mapIndicatorType.keySet()) {
            result.put(key, String.valueOf(mapIndicatorType.get(key)));
        }
        return result;
    }

    /**
     * Recupera los planes comerciales anuales asignados a un usuario para un año.
     * Incluye tambien los datos de los planes comerciales anuales "hijos"
     * 
     * @author nts (agonzalezisasi)
     * @date 01/10/2021
     * 
     * @param {Id assignedUserId} id de usuario
     * @param {Integer actualYear} año
     * @return {List<PlanComercial__c>} lista de planes
     */
    public List<PlanComercial__c> findAnualPlansByAssignedUserAndYear(Id assignedUserId, Integer actualYear)
    {
        List<PlanComercial__c> parentPlans = [
            SELECT id, Name, Product__c, Segment__c, Indicator__c,
                   TargetKPICurrency__c, TargetKPINumber__c, TargetKPIPercent__c, Actual_KPI__c,
                   (SELECT Id, 
                           AssignedTo__c, AssignedTo__r.Name, Intermediary__c, Intermediary__r.Name,
                           TargetKPICurrency__c, TargetKPINumber__c, TargetKPIPercent__c, Actual_KPI__c 
                   FROM ParentPlans__r)
            FROM PlanComercial__c
            WHERE RecordTypeId = :rtPlanAnualId
            AND Intermediary__c = null
            AND AssignedTo__c = :assignedUserId
            AND CALENDAR_YEAR(StartDate__c) = :actualYear
            Order By CreatedDate
        ];

        return parentPlans;
    }

    /**
     * Recupera los planes comerciales anuales "hijos" de los planes comerciales anuales dados
     * 
     * @author nts (agonzalezisasi)
     * @date 04/10/2021
     * 
     * @param {List<PlanComercial__c} plnes
     * @return {List<PlanComercial__c>} lista de planes descendientes
     */
    public List<PlanComercial__c> findAnualPlanDescendants(List<PlanComercial__c> plans)
    {
        List<PlanComercial__c> childPlans = null;

        if( plans != null && !plans.isEmpty() ) {
            childPlans = [
                SELECT Id, Name, Product__c, Segment__c, Indicator__c, 
                ParentPlan__r.Name, ParentPlan__r.Product__c, ParentPlan__r.Segment__c, ParentPlan__r.Indicator__c, 
                TargetKPICurrency__c, TargetKPINumber__c, TargetKPIPercent__c
                FROM PlanComercial__c
                WHERE RecordTypeId = :rtPlanAnualId
                AND ParentPlan__r.ParentPlan__c IN :plans
            ];
        }

        return childPlans;
    }
}