force-app/zurich-base/main/default/objects/Account/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/INFOInsuredObjectCode__c.field-meta.xml
<CustomField>
    <fullName>INFOInsuredObjectCode__c</fullName>
    <description>(OCS): Concatenación de los campos de Número de póliza y Secuencial</description>
    <externalId>true</externalId>
    <label>INFO Insured Object Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <description>(OCS): Contiene el número de matrícula del vehículo/embarcación asegurado</description>
    <label>Registration number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scope</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/recordTypes/Motor.recordType-meta.xml
<RecordType>
    <fullName>Motor</fullName>
    <active>true</active>
    <description>Zurich OCS Motor Record Type</description>
    <label>Motor</label>
</RecordType>

force-app/zurich-base/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>OCS</description>
    <label>Siniestro</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Siniestros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Claim__c/fields/INFOClaimNumber__c.field-meta.xml
<CustomField>
    <fullName>INFOClaimNumber__c</fullName>
    <description>OCS</description>
    <externalId>true</externalId>
    <label>INFO Claim Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/fields/InsuredObject__c.field-meta.xml
<CustomField>
    <fullName>InsuredObject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Puntero al riesgo asegurado de la póliza</description>
    <label>Insured object</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <description>(OCS). Puntero a la póliza vinculada</description>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Claim__c/fields/PolicyHolder__c.field-meta.xml
<CustomField>
    <fullName>PolicyHolder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Puntero al tomador de la póliza vinculada</description>
    <label>Policy holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &apos;Life&apos;, &apos;Life Insurance&apos;, 
			IF($Profile.Name = &apos;ZE User&apos; || $Profile.Name = &apos;Ventas User&apos;,
			    &apos;001&apos;,
			        &apos;&apos;))</defaultValue>
    <description>(ZE/OCS) Identifica la entidad legal a la que pertenece la oferta.</description>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Insurance</fullName>
            </value>
            <value>
                <fullName>General Insurance</fullName>
            </value>
            <value>
                <fullName>000</fullName>
                <label>Todos</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>Zurich</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>CAN SSGG</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>CAS SSGG</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>CAS Vida</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Zurich Vida</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>DZ Pensiones</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>EPSV Zurich</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>BSSG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>Multientidad</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>(ZE/OCS) Identifica el ámbito a utilizar para la colaboración del registro.</description>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZE</fullName>
                <label>Zurich Empresas</label>
            </value>
            <value>
                <fullName>ZEO</fullName>
                <label>Zurich Empresas Orange</label>
            </value>
            <value>
                <fullName>Z</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>ZEB</fullName>
                <label>Zurich Empresas Brokers</label>
            </value>
            <value>
                <fullName>Ventas</fullName>
                <label>Zurich Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <description>(OCS). Identifica la entidad legal a la que está asociada la póliza en INFO</description>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Insurance</fullName>
            </value>
            <value>
                <fullName>General Insurance</fullName>
            </value>
            <value>
                <fullName>000</fullName>
                <label>Todos</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>Zurich</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>CAN SSGG</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>CAS SSGG</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>CAS Vida</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Zurich Vida</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>DZ Pensiones</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>EPSV Zurich</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>BSSG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>Multientidad</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/PolicyHolder__c.field-meta.xml
<CustomField>
    <fullName>PolicyHolder__c</fullName>
    <description>(OCS). Identifica el tomador de la póliza</description>
    <label>Policy Holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Policy Holder)</relationshipLabel>
    <relationshipName>PoliciesHolder</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>(OCS). Identifica el ámbito a utilizar para la colaboración del registro</description>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZE</fullName>
                <label>Zurich Empresas</label>
            </value>
            <value>
                <fullName>ZEO</fullName>
                <label>Zurich Empresas Orange</label>
            </value>
            <value>
                <fullName>Z</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>ZEB</fullName>
                <label>Zurich Empresas Brokers</label>
            </value>
            <value>
                <fullName>ZDA</fullName>
                <label>Zurich ZDA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/globalValueSets/Scope.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z</fullName>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>ZE</fullName>
        <label>Zurich Empresas</label>
    </customValue>
    <customValue>
        <fullName>ZEO</fullName>
        <label>Zurich Empresas Orange</label>
    </customValue>
    <customValue>
        <fullName>ZEB</fullName>
        <label>Zurich Empresas Brokers</label>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
        <label>Zurich Ventas</label>
    </customValue>
    <customValue>
        <fullName>ZDA</fullName>
        <label>Zurich ZDA</label>
    </customValue>
    <masterLabel>Scope</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/ClaimsSelectorTest.cls
@isTest
public with sharing class ClaimsSelectorTest
{
    @TestSetup
    public static void createScenario()
    {
        List<Account> accounts = TestDataFactory.generateAccounts(Label.GeneralInsurance, 'Customer', 2);
        insert accounts;

        List<Scope__c> scopes = TestDataFactory.generateScopesForEachAccount(accounts, 'ZE', 1);
        insert scopes;

        List<Opportunity> opportunities = TestDataFactory.generateOpportunitiesForEachScope(scopes, 'Qualification', System.today(), 1);
        insert opportunities;

        List<Policy__c> policies = TestDataFactory.generatePoliciesForEachOpportunity(opportunities, 1);
        insert policies;

        List<Asset> insuredObjects = TestDataFactory.generateInsuredObjectsForEachPolicy('Motor', policies, 1);
        insert insuredObjects;

        List<Claim__c> claims = TestDataFactory.generateClaimsForEachPolicyInsuredObject(policies, insuredObjects, 1);
        insert claims;
    }

    @IsTest
    static void test_selectByHolder()
    {
        // Comprobaciones iniciales
        List<Policy__c> policies = [SELECT Id, PolicyHolder__c FROM Policy__c];
        System.assertEquals(false, policies.isEmpty(), '[0] Policies list should NOT be empty');
        List<Asset> insuredObjects = [SELECT Id, Name, RegistrationNumber__c, AccountId, INFOInsuredObjectCode__c, RecordTypeId FROM Asset];
        System.assertEquals(false, insuredObjects.isEmpty(), '[1] Insured Objets list should NOT be empty');
        List<Claim__c> claims = [SELECT Id, Name, PolicyHolder__c, InsuredObject__c, INFOClaimNumber__c FROM Claim__c];
        System.assertEquals(false, claims.isEmpty(), '[2] Claims list should NOT be empty');

        Test.startTest();
        List<Claim__c> matchedRecords = new ClaimsSelector().selectByHolder(policies.get(0).PolicyHolder__c);
        Test.stopTest();

        System.assertEquals(false, matchedRecords.isEmpty(), '[3] List should NOT be empty');
    }

    @IsTest
    static void test_selectByPlate()
    {
        // Comprobaciones iniciales
        List<Policy__c> policies = [SELECT Id, PolicyHolder__c FROM Policy__c];
        System.assertEquals(false, policies.isEmpty(), '[0] Policies list should NOT be empty');
        List<Asset> insuredObjects = [SELECT Id, Name, RegistrationNumber__c, AccountId, INFOInsuredObjectCode__c, RecordTypeId FROM Asset];
        System.assertEquals(false, insuredObjects.isEmpty(), '[1] Insured Objets list should NOT be empty');
        List<Claim__c> claims = [SELECT Id, Name, PolicyHolder__c, InsuredObject__c, INFOClaimNumber__c FROM Claim__c];
        System.assertEquals(false, claims.isEmpty(), '[2] Claims list should NOT be empty');

        Test.startTest();
        List<Claim__c> matchedRecords = new ClaimsSelector().selectByPlate(insuredObjects.get(0).RegistrationNumber__c);
        Test.stopTest();

        System.assertEquals(false, matchedRecords.isEmpty(), '[3] List should NOT be empty');
    }

    @IsTest
    static void test_selectByNumber()
    {
        // Comprobaciones iniciales
        List<Policy__c> policies = [SELECT Id, PolicyHolder__c FROM Policy__c];
        System.assertEquals(false, policies.isEmpty(), '[0] Policies list should NOT be empty');
        List<Asset> insuredObjects = [SELECT Id, Name, RegistrationNumber__c, AccountId, INFOInsuredObjectCode__c, RecordTypeId FROM Asset];
        System.assertEquals(false, insuredObjects.isEmpty(), '[1] Insured Objets list should NOT be empty');
        List<Claim__c> claims = [SELECT Id, Name, PolicyHolder__c, InsuredObject__c, INFOClaimNumber__c FROM Claim__c];
        System.assertEquals(false, claims.isEmpty(), '[2] Claims list should NOT be empty');

        Test.startTest();
        List<Claim__c> matchedRecords = new ClaimsSelector().selectByNumber(claims.get(0).INFOClaimNumber__c);
        Test.stopTest();

        System.assertEquals(false, matchedRecords.isEmpty(), '[3] List should NOT be empty');
    }

    @IsTest
    static void test_selectByNumber_setScope()
    {
        // Comprobaciones iniciales
        List<Policy__c> policies = [SELECT Id, PolicyHolder__c FROM Policy__c];
        System.assertEquals(false, policies.isEmpty(), '[0] Policies list should NOT be empty');
        List<Asset> insuredObjects = [SELECT Id, Name, RegistrationNumber__c, AccountId, INFOInsuredObjectCode__c, RecordTypeId FROM Asset];
        System.assertEquals(false, insuredObjects.isEmpty(), '[1] Insured Objets list should NOT be empty');
        List<Claim__c> claims = [SELECT Id, Name, PolicyHolder__c, InsuredObject__c, INFOClaimNumber__c FROM Claim__c];
        System.assertEquals(false, claims.isEmpty(), '[2] Claims list should NOT be empty');

        for(Claim__c claim : claims)
        {
            claim.Scope__c = RecordsSelector.Scope.Z.name();
        }

        update claims;

        Test.startTest();
        ClaimsSelector claimsSelector = new ClaimsSelector();
        claimsSelector.setScope(RecordsSelector.Scope.Z);
        List<Claim__c> matchedRecords = claimsSelector.selectByNumber(claims.get(0).INFOClaimNumber__c);
        Test.stopTest();

        System.assertEquals(false, matchedRecords.isEmpty(), '[3] List should NOT be empty');
    }

    @IsTest
    static void test_selectByNumber_setLegalEntity()
    {
        // Comprobaciones iniciales
        List<Policy__c> policies = [SELECT Id, PolicyHolder__c FROM Policy__c];
        System.assertEquals(false, policies.isEmpty(), '[0] Policies list should NOT be empty');
        List<Asset> insuredObjects = [SELECT Id, Name, RegistrationNumber__c, AccountId, INFOInsuredObjectCode__c, RecordTypeId FROM Asset];
        System.assertEquals(false, insuredObjects.isEmpty(), '[1] Insured Objets list should NOT be empty');
        List<Claim__c> claims = [SELECT Id, Name, PolicyHolder__c, InsuredObject__c, INFOClaimNumber__c FROM Claim__c];
        System.assertEquals(false, claims.isEmpty(), '[2] Claims list should NOT be empty');

        for(Claim__c claim : claims)
        {
            claim.LegalEntity__c = '001';
        }

        update claims;

        Test.startTest();
        ClaimsSelector claimsSelector = new ClaimsSelector();
        claimsSelector.setLegalEntity(RecordsSelector.LegalEntity.GI);
        List<Claim__c> matchedRecords = claimsSelector.selectByNumber(claims.get(0).INFOClaimNumber__c);
        Test.stopTest();

        System.assertEquals(false, matchedRecords.isEmpty(), '[3] List should NOT be empty');
    }
}