force-app/zurich-base/main/default/objects/Account/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalEntity</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/CommercialStructureCode__c.field-meta.xml
<CustomField>
    <fullName>CommercialStructureCode__c</fullName>
    <description>(OCS). Código de estructura comercial asociado a la oferta</description>
    <label>Commercial Structure Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &apos;Life&apos;, &apos;Life Insurance&apos;, 
			IF($Profile.Name = &apos;ZE User&apos; || $Profile.Name = &apos;Ventas User&apos;,
			    &apos;001&apos;,
			        &apos;&apos;))</defaultValue>
    <description>(ZE/OCS) Identifica la entidad legal a la que pertenece la oferta.</description>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Insurance</fullName>
            </value>
            <value>
                <fullName>General Insurance</fullName>
            </value>
            <value>
                <fullName>000</fullName>
                <label>Todos</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>Zurich</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>CAN SSGG</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>CAS SSGG</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>CAS Vida</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Zurich Vida</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>DZ Pensiones</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>EPSV Zurich</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>BSSG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>Multientidad</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/LegalEntity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Life Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>General Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>999</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
        <isActive>false</isActive>
        <label>Motor</label>
    </customValue>
    <description>Indicates the legal entity which belongs to</description>
    <masterLabel>Entidad legal</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/Batch_GDPRDeleteMassiveOffersTest.cls
/**
 * @description       :
 * @author            : jgallaga
 * @group             :
 * @last modified on  : 26/10/2023
 * @last modified by  : jgallaga
**/
@isTest
public class Batch_GDPRDeleteMassiveOffersTest
{
    @TestSetup
    static void makeData()
    {

        // QUEDA CREAR OFERTAS PARA LOS TIPOS DE DEFAULT
        Integer numFAccounts = 0;
        Integer numJAccounts = 0;

        Map<String,Integer> numTypeAccounts = getHowManyAccountOfEachType(Batch_GDPRDeleteMassiveOffers.INTERNAL_ESTRUCTURE.keySet());

        System.debug('Primer grupo ' + numTypeAccounts);

        numFAccounts = numFAccounts + numTypeAccounts.get('F');
        numJAccounts = numJAccounts + numTypeAccounts.get('J');

        numTypeAccounts = getHowManyAccountOfEachType(Batch_GDPRDeleteMassiveOffers.DEFAULT_ESTRUCTURE.keySet());

        System.debug('Segundo grupo ' + numTypeAccounts);

        numFAccounts = numFAccounts + numTypeAccounts.get('F');
        numJAccounts = numJAccounts + numTypeAccounts.get('J');

        List<Account> accountsForTest = TestDataFactory.generateAccounts('001', 'Business Customer', numFAccounts + numJAccounts);

        List<Account> fAccounts = new List<Account>();
        List<Account> jAccounts = new List<Account>();

        Integer jCounter = 0;

        for(Account nextAccount : accountsForTest)
        {
            if(jCounter < numJAccounts)
            {
                nextAccount.Type = 'J';
                jAccounts.add(nextAccount);
                jCounter++;
            }
            else
            {
                nextAccount.Type = 'F';
                fAccounts.add(nextAccount);
            }
        }

        System.debug('J Account ' + jAccounts);
        System.debug('F ACcount ' + fAccounts);

        insert accountsForTest;

        createTestOffersToDelete(Batch_GDPRDeleteMassiveOffers.INTERNAL_ESTRUCTURE, jAccounts, fAccounts);
        createTestOffersToDelete(Batch_GDPRDeleteMassiveOffers.DEFAULT_ESTRUCTURE, jAccounts, fAccounts);
    }

    private static void createTestOffersToDelete(Map<String,Integer> mapaEstructuras, List<Account> jAccounts, List<Account> fAccounts)
    {
        List<Opportunity> offersForTestToDelete = new List<Opportunity>();

        Boolean isNotDefaultEstructure = false;

        for(String nextEntry : mapaEstructuras.keySet())
        {
            isNotDefaultEstructure = nextEntry.length() > 4;

            Account relatedAccount;
            String accountType = nextEntry.right(1); // Cogemos la letra del tipo de cuenta

            if(accountType == 'J')
            {
                relatedAccount = jAccounts.remove(0); // Cogemos el primer elemento de la lista de cuentas de tipo J y se elimina de la lista de paso
            }
            else
            {
                relatedAccount = fAccounts.remove(0); // Cogemos el primer elemento de la lista de cuentas de tipo F y se elimina de la lista de paso
            }

            // Procedemos a crear la oferta
            Opportunity newOpp = TestDataFactory.generateOpportunitiesForEachAccount(new List<Account>{relatedAccount}, 'General', 'Open', Date.today().addDays(30), 1)[0];

            newOpp.LegalEntity__c = nextEntry.substring(0,3); // -> Desde el indice siendo un array que empieza en 0. Hasta donde quieres -1.
            if(isNotDefaultEstructure)
            {
                newOpp.CommercialStructureCode__c = nextEntry.substring(3,7);  // -> Desde el indice siendo un array que empieza en 0. Hasta donde quieres -1.
            }
            else
            {
                newOpp.CommercialStructureCode__c = '0000';
            }

            offersForTestToDelete.add(newOpp);
        }

        insert offersForTestToDelete;

        for(Opportunity testOpportunity : [SELECT Account.Type, CommercialStructureCode__c, LegalEntity__c FROM Opportunity])
        {
            String keyValue;

            if(isNotDefaultEstructure)
            {
                keyValue = testOpportunity.LegalEntity__c + testOpportunity.CommercialStructureCode__c + testOpportunity.Account.Type;
            }
            else
            {
                keyValue = testOpportunity.LegalEntity__c + testOpportunity.Account.Type;
            }

            Integer days = mapaEstructuras.get(keyValue);
            Date fakeCreatedDate = Date.today().addDays(-days);

            Test.setCreatedDate(testOpportunity.Id, fakeCreatedDate);
        }
    }

    private static Map<String,Integer> getHowManyAccountOfEachType(Set<String> mapKeySet)
    {
        Map<String,Integer> mapCounter = new Map<String,Integer>{ 'F' => 0, 'J' => 0};

        for(String nextValue : mapKeySet)
        {
            String accountType = nextValue.right(1);
            mapCounter.put(accountType, mapCounter.get(accountType) + 1);
        }

        return mapCounter;
    }

    @isTest
    private static void test()
    {
        Test.startTest();
        for(Opportunity testOpportunity : [SELECT Account.Type, CommercialStructureCode__c, LegalEntity__c, createddate FROM Opportunity])
        {
            System.debug('Opp ' + testOpportunity.Account.Type + ' - Estructura ' + testOpportunity.CommercialStructureCode__c  + ' - Entidad ' + testOpportunity.LegalEntity__c + ' - ' +  testOpportunity.createddate);
        }
        Database.executeBatch(new Batch_GDPRDeleteMassiveOffers());
        Test.stopTest();

        List<Opportunity> deletedOffers = [SELECT Id FROM Opportunity];

        System.debug(deletedOffers.size());

        Assert.isTrue(deletedOffers.isEmpty(), 'No se han borrado las ofertas esperadas');
    }
}