force-app/zurich-base/main/default/objects/Account/fields/NationalId__c.field-meta.xml
<CustomField>
    <fullName>NationalId__c</fullName>
    <description>(OCS/ZE). Identificador nacional del cliente</description>
    <label>National ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/zurich-base/main/default/objects/Asset/fields/BrandName__c.field-meta.xml
<CustomField>
    <fullName>BrandName__c</fullName>
    <description>(OCS): Contiene la marca del vehículo/dispositivo asegurado</description>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>(OCS): Contiene el modelo del vehículo/dispositivo asegurado</description>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/PolicyId__c.field-meta.xml
<CustomField>
    <fullName>PolicyId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS): Relación con la póliza</description>
    <label>Policy Number</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Insured Objects</relationshipLabel>
    <relationshipName>PolicyNumbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <description>(OCS): Contiene el número de matrícula del vehículo/embarcación asegurado</description>
    <label>Registration number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scope</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Asset/recordTypes/Motor.recordType-meta.xml
<RecordType>
    <fullName>Motor</fullName>
    <active>true</active>
    <description>Zurich OCS Motor Record Type</description>
    <label>Motor</label>
</RecordType>

force-app/zurich-base/main/default/objects/ContactPointPhone/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>(ZE/OCS) Identifica el ámbito a utilizar para la colaboración del registro.</description>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/ContactPointPhone/fields/ScopeId__c.field-meta.xml
<CustomField>
    <fullName>ScopeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OCS</description>
    <label>Scope Name</label>
    <referenceTo>Scope__c</referenceTo>
    <relationshipLabel>Contact Point Phones</relationshipLabel>
    <relationshipName>ContactPointPhones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>Destinado a almacenar la información de las pólizas provenientes de INFO</description>
    <label>Póliza</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pólizas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Policy__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>(OCS). Identifica la fecha de vencimiento de la póliza</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/InfoPolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>InfoPolicyNumber__c</fullName>
    <description>(OCS). Identificador único de la póliza.</description>
    <externalId>true</externalId>
    <label>INFO Policy Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/MovementStartDate__c.field-meta.xml
<CustomField>
    <fullName>MovementStartDate__c</fullName>
    <description>(OCS). Identifica la fecha de efecto de un movimiento</description>
    <label>Movement Start Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Partner)</relationshipLabel>
    <relationshipName>PoliciesPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/PolicyHolder__c.field-meta.xml
<CustomField>
    <fullName>PolicyHolder__c</fullName>
    <description>(OCS). Identifica el tomador de la póliza</description>
    <label>Policy Holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Policy Holder)</relationshipLabel>
    <relationshipName>PoliciesHolder</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/PolicyVersion__c.field-meta.xml
<CustomField>
    <fullName>PolicyVersion__c</fullName>
    <description>(OCS). Campo oculto usado en la integración para parsear el valor y copiarlo al campo Nombre del objeto Versión de Póliza</description>
    <label>Policy Version</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica el producto para el que se realiza la póliza. En la web se (OCS) Identifica como Tipo de Registro</description>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>(OCS). Identifica el ámbito a utilizar para la colaboración del registro</description>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZE</fullName>
                <label>Zurich Empresas</label>
            </value>
            <value>
                <fullName>ZEO</fullName>
                <label>Zurich Empresas Orange</label>
            </value>
            <value>
                <fullName>Z</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>ZEB</fullName>
                <label>Zurich Empresas Brokers</label>
            </value>
            <value>
                <fullName>ZDA</fullName>
                <label>Zurich ZDA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/Policy__c/fields/ScopeId__c.field-meta.xml
<CustomField>
    <fullName>ScopeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(OCS). Identifica el ámbito al que se encuentra asociada la póliza</description>
    <label>Scope Name</label>
    <referenceTo>Scope__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PolicyVersion__c/PolicyVersion__c.object-meta.xml
<CustomObject>
    <description>This entity represents all the changes that a policy can suffer such as activation and deactivation of a On Demand non-life policy, change of a product, policy activation and so on.</description>
    <label>Versión de póliza</label>
    <nameField>
        <label>Versión de póliza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versiones de póliza</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PolicyVersion__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Indicates when finishes that version of policy</description>
    <label>Fecha fin</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/PolicyVersion__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/GroupDescription__c.field-meta.xml
<CustomField>
    <fullName>GroupDescription__c</fullName>
    <description>INFO Source: KTPM08T - DSAGRPCN</description>
    <label>Group Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Product2/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <description>Field to be used as external ID of the product</description>
    <externalId>true</externalId>
    <label>ProductID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/zurich-base/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>(ZE/OCS) Entidad utilizada para definir el ámbito al que aplican algunos de los campos de la cuenta. A su vez, se identifica la vía de contacto (email, telefono y dirección) principal para cada ámbito y se recupera para Marketing Cloud el email y teléfono principal.</description>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/Scope__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/Scope.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Z</fullName>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>ZE</fullName>
        <label>Zurich Empresas</label>
    </customValue>
    <customValue>
        <fullName>ZEO</fullName>
        <label>Zurich Empresas Orange</label>
    </customValue>
    <customValue>
        <fullName>ZEB</fullName>
        <label>Zurich Empresas Brokers</label>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
        <label>Zurich Ventas</label>
    </customValue>
    <customValue>
        <fullName>ZDA</fullName>
        <label>Zurich ZDA</label>
    </customValue>
    <masterLabel>Scope</masterLabel>
</GlobalValueSet>

force-app/zurich-base/main/default/classes/ClientInteracionServiceTest.cls
@isTest(SeeAllData=false)
public with sharing class ClientInteracionServiceTest
{
    private static String GRUPO_MOTOR = 'Motor';

    @TestSetup
    public static void createScenario()
    {
        List<Account> accounts = TestDataFactory.generateAccounts('001', 'Customer', 2);
        insert accounts;

        List<ContactPointPhone> contactPointPhones = TestDataFactory.generateContactPointPhonesFromAccounts(accounts, 1);
        insert contactPointPhones;

        List<Account> partners = TestDataFactory.generateAccounts('001', 'Partner', 1);
        insert partners;

        List<Account> tempList = new List<Account>();
        tempList.add( accounts.get(0) );

        List<Policy__c> policies = TestDataFactory.generatePoliciesForEachAccount(tempList, 10);
        insert policies;

        List<Asset> assets = TestDataFactory.generateInsuredObjectsForEachPolicy('Motor', policies, 1);
        insert assets;

        List<Product2> productos = TestDataFactory.generateProducts(1);
        productos[0].GroupDescription__c = GRUPO_MOTOR;
        insert productos;
    }

    /**
     * Método de test que confirma que existe tanto el DNI que nos mandan, como el número de póliza, son correctas
     */
    @isTest
    static void processData_foundClient()
    {
        List<Policy__c> policies = [SELECT Id, InfoPolicyNumber__c, PolicyHolder__c, PolicyHolder__r.NationalId__c FROM Policy__c LIMIT 1];
        List<Account> accounts = [SELECT Id, NationalId__c FROM Account WHERE NationalId__c = : policies[0].PolicyHolder__r.NationalId__c LIMIT 1];

        policies[0].MovementStartDate__c = date.today();
        policies[0].EndDate__c = date.today().addDays(10);
        policies[0].PolicyVersion__c = '2';

        upsert policies[0];

        ClientIdentificationService.Client testClient = new ClientIdentificationService.Client();
        testClient.fullName = 'Nombre Apellido';
        testClient.nationalID = accounts[0].NationalId__c;
        testClient.policyNumber = policies[0].InfoPolicyNumber__c;

        // Test
        ClientIdentificationService.ClientIdentificationException expectedError;
        ClientIdentificationService.SearchResult resultado;

        Test.startTest();
        try
        {
            String salida = ClientIdentificationService.processData(testClient, 'findByPolicyNumber');
            resultado= (ClientIdentificationService.SearchResult) JSON.deserializeStrict(
                salida,
                ClientIdentificationService.SearchResult.class
                );
        }
        catch(ClientIdentificationService.ClientIdentificationException error)
        {
            expectedError = error;
        }

        Test.stopTest();

        System.assertEquals(null, expectedError, 'Ha de encontrarse el cliente y no saltar ninguna excepción');
        System.assertEquals(true, resultado.existsNationalID, 'Es un cliente del sistema');
        System.assertEquals(true, resultado.existsPolicy, 'La póliza existe y está asociada al cliente');

        System.assertEquals(true, resultado.isValidPolicy, 'La póliza existe y es válida');
        System.assertNotEquals(null, resultado.policyStartDate, 'La póliza tiene una fecha de inicio');
        System.assertNotEquals(null, resultado.policyEndDate, 'La póliza tiene una fecha de fin');
        System.assertNotEquals(null, resultado.policyVersion, 'La póliza tiene una versión');
    }

    /**
     * Método de test que comprueba que el DNI que se le pasa se corresponde con un cliente existente en el sistema, pero la póliza no.
     */
    @isTest
    static void processData_foundClient_noPolicy()
    {
        List<Policy__c> policies = [SELECT Id, PolicyHolder__c, PolicyHolder__r.NationalId__c FROM Policy__c LIMIT 1];
        List<Account> accounts = [SELECT Id, NationalId__c FROM Account WHERE NationalId__c != : policies[0].PolicyHolder__r.NationalId__c LIMIT 1];

        String policyNoExiste = '00000000000000';

        ClientIdentificationService.Client testClient = new ClientIdentificationService.Client();
        testClient.fullName = 'Nombre Apellido';
        testClient.nationalID = accounts[0].NationalId__c;
        testClient.policyNumber = policyNoExiste;

        // Test
        ClientIdentificationService.ClientIdentificationException expectedError;
        ClientIdentificationService.SearchResult resultado;

        Test.startTest();
        try
        {
            String salida = ClientIdentificationService.processData(testClient, 'findByPolicyNumber');
            resultado= (ClientIdentificationService.SearchResult) JSON.deserializeStrict(
                salida,
                ClientIdentificationService.SearchResult.class
                );
        }
        catch(ClientIdentificationService.ClientIdentificationException error)
        {
            expectedError = error;
        }

        Test.stopTest();

        System.assertEquals(null, expectedError, 'Ha de encontrarse el cliente y no saltar ninguna excepción');
        System.assertEquals(true, resultado.existsNationalID, 'Es un cliente del sistema');
        System.assertEquals(false, resultado.existsPolicy, 'La póliza indicada no existe en el sistema');
    }

    /**
     * Método de test que confirma que existe tanto el DNI que nos mandan, como el número de póliza, son correctas
     */
    @isTest
    static void processData_foundPolicyNotClient()
    {
        List<Policy__c> policies = [SELECT Id, InfoPolicyNumber__c, PolicyHolder__c, PolicyHolder__r.NationalId__c FROM Policy__c LIMIT 1];
        String dniNoExiste = '00000000A';

        ClientIdentificationService.Client testClient = new ClientIdentificationService.Client();
        testClient.fullName = 'Nombre Apellido';
        testClient.nationalID = dniNoExiste;
        testClient.policyNumber = policies[0].InfoPolicyNumber__c;

        // Test
        ClientIdentificationService.ClientIdentificationException expectedError;
        ClientIdentificationService.SearchResult resultado;

        Test.startTest();
        try
        {
            String salida = ClientIdentificationService.processData(testClient, 'findByPolicyNumber');
            resultado= (ClientIdentificationService.SearchResult) JSON.deserializeStrict(
                salida,
                ClientIdentificationService.SearchResult.class
                );
        }
        catch(ClientIdentificationService.ClientIdentificationException error)
        {
            expectedError = error;
        }

        Test.stopTest();

        System.assertEquals(null, expectedError, 'Ha de encontrarse el cliente y no saltar ninguna excepción');
        System.assertEquals(false, resultado.existsNationalID, 'El cliente no está en el sistema');
        System.assertEquals(true, resultado.existsPolicy, 'La póliza existe y está asociada al cliente');

    }

    /**
     * Método de test que comprueba el caso en el que ni el DNI ni la Póliza estan en el sistema
     */
    @isTest
    static void processData_clientNotFound()
    {

        String dniNoExiste = '00000000A';
        String policyNoExiste = '00000000000000';

        ClientIdentificationService.Client testClient = new ClientIdentificationService.Client();
        testClient.fullName = 'Nombre Apellido';
        testClient.nationalID = dniNoExiste;
        testClient.policyNumber = policyNoExiste;

        // Test
        ClientIdentificationService.ClientIdentificationException expectedError;
        ClientIdentificationService.SearchResult resultado;

        Test.startTest();
        try
        {
            String salida = ClientIdentificationService.processData(testClient, 'findByPolicyNumber');
            resultado= (ClientIdentificationService.SearchResult) JSON.deserializeStrict(
                salida,
                ClientIdentificationService.SearchResult.class
                );
        }
        catch(ClientIdentificationService.ClientIdentificationException error)
        {
            expectedError = error;
        }

        Test.stopTest();

        System.assertEquals(null, expectedError, 'Ha de encontrarse el cliente y no saltar ninguna excepción');
        System.assertEquals(false, resultado.existsNationalID, 'El cliente no está en el sistema');
        System.assertEquals(false, resultado.existsPolicy, 'No tiene policies asociadas');

    }

    /**
     * Método de test que confirma que no se ha enviado el campo DNI. Ha de devolver una excepción del tipo INVALID_FIELD
     */
    @isTest
    static void processData_noDNIexception()
    {

        // When
        ClientIdentificationService.Client testClient = new ClientIdentificationService.Client();
        testClient.fullName = 'Nombre Apellido';
        testClient.policyNumber = '123456';

        // Test
        ClientIdentificationService.ClientIdentificationException expectedError;

        Test.startTest();
        try
        {
            ClientIdentificationService.validateReceivedInformation(testClient, 'findByPolicyNumber');
        }
        catch(ClientIdentificationService.ClientIdentificationException error)
        {
            expectedError = error;
        }

        Test.stopTest();

        System.assertEquals(ClientIdentificationService.INVALID_FIELD_STATUSCODE, expectedError.statusCode, 'No se ha lanzado la excepción correcta');

    }

    /**
     * Método de test que confirma que el DNI se ha enviado vacío. Ha de devolver una excepción del tipo EMPTY_FIELD
     */
    @isTest
    static void processData_blankDNIexception()
    {
        // When
        ClientIdentificationService.Client testClient = new ClientIdentificationService.Client();

        testClient.fullName = 'Nombre Apellido';
        testClient.nationalID = '';
        testClient.policyNumber = '123456';

        // Test
        ClientIdentificationService.ClientIdentificationException expectedError;

        Test.startTest();
        try
        {
            ClientIdentificationService.processData(testClient, 'findByPolicyNumber');
        }
        catch(ClientIdentificationService.ClientIdentificationException error)
        {
            expectedError = error;
        }

        Test.stopTest();

        System.assertEquals(ClientIdentificationService.EMPTY_FIELD_STATUSCODE, expectedError.statusCode, 'No se ha lanzado la excepción correcta');
    }

    /**
     * Método de test que confirma que la policy se ha enviado vacío. Ha de devolver una excepción del tipo EMPTY_FIELD
     */
    @isTest
    static void processData_blankPolicyException()
    {
        // When
        ClientIdentificationService.Client testClient = new ClientIdentificationService.Client();
        testClient.fullName = 'Nombre Apellido';
        testClient.nationalID = '12345678A';
        testClient.policyNumber = '';

        // Test
        ClientIdentificationService.ClientIdentificationException expectedError;

        Test.startTest();
        try
        {
            ClientIdentificationService.processData(testClient, 'findByPolicyNumber');
        }
        catch(ClientIdentificationService.ClientIdentificationException error)
        {
            expectedError = error;
        }

        Test.stopTest();

        System.assertEquals(ClientIdentificationService.EMPTY_FIELD_STATUSCODE, expectedError.statusCode, 'No se ha lanzado la excepción correcta');
    }

    /**
     * Método de test que confirma que existe tanto el teléfono que nos mandan, como el DNI, y el grupo del producto de la póliza
     */
    @isTest
    static void processData_foundByPhone()
    {

        //String.isBlank(receivedData.nationalID) || String.isBlank(receivedData.phoneNumber) || String.isBlank(receivedData.groupDescription)

        List<Asset> assets = [SELECT Id, Model__c, BrandName__c, PolicyId__c FROM Asset LIMIT 1];

        List<Policy__c> policies = [SELECT Id, Name, InfoPolicyNumber__c, PolicyHolder__c, ProductId__c
                                    FROM Policy__c WHERE Id = : assets[0].PolicyId__c LIMIT 1];

        List<Account> accounts = [SELECT Id, NationalId__c, Phone FROM Account WHERE Id = : policies[0].PolicyHolder__c LIMIT 1];

        List<ContactPointPhone> contactPhones = [SELECT Id, ParentId, TelephoneNumber, ScopeId__c, Scope__c
                                                 FROM ContactPointPhone WHERE ParentId = : accounts[0].Id LIMIT 1];

        List<Product2> products = [SELECT Id, GroupDescription__c FROM Product2 LIMIT 1];

        accounts[0].NationalId__c = '11111111E';
        accounts[0].Phone = contactPhones[0].TelephoneNumber;
        upsert accounts[0];

        policies[0].ProductId__c = products[0].Id;
        upsert policies[0];


        ClientIdentificationService.Client testClient = new ClientIdentificationService.Client();
        testClient.nationalID = '11111111E';
        testClient.phonePrefix = '';
        testClient.phoneNumber = contactPhones[0].TelephoneNumber;
        testClient.groupDescription = GRUPO_MOTOR;

        // Test
        ClientIdentificationService.ClientIdentificationException expectedError;
        ClientIdentificationService.SearchResultLong resultado;

        Test.startTest();
        try
        {
            String salida = ClientIdentificationService.processData(testClient, 'findByPhone');
            resultado = (ClientIdentificationService.SearchResultLong) JSON.deserializeStrict(
                salida,
                ClientIdentificationService.SearchResultLong.class
                );
        }
        catch(ClientIdentificationService.ClientIdentificationException error)
        {
            expectedError = error;
        }

        ClientIdentificationService.SearchResultLong resultado2 = ClientIdentificationService.setInsuredObjectsByPhone(testClient,
                                                                                                                       contactPhones[0].TelephoneNumber, new ClientIdentificationService.SearchResultLong(),
                                                                                                                       new List<ClientIdentificationService.InsuredObject>(), accounts);

        Test.stopTest();

        System.assertEquals(null, expectedError, 'Ha de encontrarse el cliente y no saltar ninguna excepción');
        System.assertEquals(testClient.nationalID, resultado2.nationalID, 'Debe existir un cliente con ese Identificador');

        System.assert ( (testClient.phonePrefix + testClient.phoneNumber == resultado2.phoneNumber || testClient.phoneNumber == resultado2.phoneNumber),
                        'Existe un cliente con ese teléfono' );
    }

    /**
     * Método de test que confirma que existe la matrícula introducida
     */
    @isTest
    static void processData_foundByRegistrationNumber()
    {

        //String.isBlank(receivedData.nationalID) || String.isBlank(receivedData.phoneNumber) || String.isBlank(receivedData.groupDescription)

        List<Asset> assets = [SELECT Id, Model__c, BrandName__c, PolicyId__c FROM Asset LIMIT 1];

        List<Policy__c> policies = [SELECT Id, Name, InfoPolicyNumber__c, PolicyHolder__c, Partner__c FROM Policy__c WHERE Id = : assets[0].PolicyId__c LIMIT 1];

        List<Account> accounts = [SELECT Id, FirstName, LastName FROM Account WHERE Id = : policies[0].PolicyHolder__c LIMIT 1];

        assets[0].RegistrationNumber__c = '1111AAA';

        upsert assets[0];

        ClientIdentificationService.Client testClient = new ClientIdentificationService.Client();
        testClient.registrationNumber = '1111AAA';

        // Test
        ClientIdentificationService.ClientIdentificationException expectedError;
        ClientIdentificationService.SearchResultLong resultado;

        Test.startTest();
        try
        {
            String salida = ClientIdentificationService.processData(testClient, 'findByRegistrationNumber');
            resultado = (ClientIdentificationService.SearchResultLong) JSON.deserializeStrict(
                salida,
                ClientIdentificationService.SearchResultLong.class
                );
        }
        catch(ClientIdentificationService.ClientIdentificationException error)
        {
            expectedError = error;
        }

        Test.stopTest();

        System.assertEquals(null, expectedError, 'Ha de encontrarse el cliente y no saltar ninguna excepción');
        System.assertEquals(true, resultado.existsRegistrationNumber, 'Existe un Objeto Asegurado con esa Matrícula');
    }

    /**
     * Método de test que recorre el camino de error si no llega un selector correcto
     */
    @isTest
    static void processData_foundError()
    {
        // Test

        String salida;

        Test.startTest();

        salida = ClientIdentificationService.processData(null, 'find_error');

        Test.stopTest();

        System.assertEquals(salida, 'error', 'Ha de devolver *error*');
    }

}