force-app/zurich-base/main/default/objects/Account/fields/PreferedContactEnd__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactEnd__c</fullName>
    <label>Horario Cont. Preferente Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/PreferedContactStart__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactStart__c</fullName>
    <label>Horario Cont. Preferente Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/fields/WebId__c.field-meta.xml
<CustomField>
    <fullName>WebId__c</fullName>
    <label>Web ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Lead_Offers__c/Lead_Offers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Ofertas de Lead</label>
</CustomObject>

force-app/zurich-base/main/default/objects/Lead_Offers__c/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>Código de Negocio para las Ofertas del Contact Center.</description>
    <label>Código de Negocio</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Lead_Offers__c/fields/BusinessHour__c.field-meta.xml
<CustomField>
    <fullName>BusinessHour__c</fullName>
    <description>Nombre del registro de Business Hour al que asociar un registro de ContactRequest para el Contact Center.</description>
    <label>Horario de Oficina</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Lead_Offers__c/fields/ContactCenterUser__c.field-meta.xml
<CustomField>
    <fullName>ContactCenterUser__c</fullName>
    <description>Alias del usuario genérico de Contact Center al que asignar Ofertas de Lead.</description>
    <label>Usuario CC</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Lead_Offers__c/fields/DaysToReassignOffer__c.field-meta.xml
<CustomField>
    <fullName>DaysToReassignOffer__c</fullName>
    <description>Número de días transcurridos los cuales se debe reasignar al Contact Center una Oferta de Lead no gestionada por un Mediador. Valor 0 si se desea desactivar la notificación.</description>
    <label>Días Reasignación a CC</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/Lead_Offers__c/fields/VoiceQueue__c.field-meta.xml
<CustomField>
    <fullName>VoiceQueue__c</fullName>
    <description>Nombre de la cola de CTI a la que asociar un registro de ContactRequest para el Contact Center.</description>
    <label>Cola CTI</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/BusinessCode__c.field-meta.xml
<CustomField>
    <fullName>BusinessCode__c</fullName>
    <description>(OCS) Identifica el código de negocio en INFO.</description>
    <label>Business Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/PreferedContactEnd__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactEnd__c</fullName>
    <label>Horario Cont. Preferente Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-base/main/default/objects/Opportunity/fields/PreferedContactStart__c.field-meta.xml
<CustomField>
    <fullName>PreferedContactStart__c</fullName>
    <label>Horario Cont. Preferente Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/zurich-ventas-app/main/default/classes/Batch_LeadOffersToReassignToCC.cls
global with sharing class Batch_LeadOffersToReassignToCC implements Database.Batchable<sObject>,Schedulable
{
    Id defaultUserCC;
    Set<String> userAndAccountIds;
    Set<Id> userIds;
    Set<Id> accountIds;

    public Batch_LeadOffersToReassignToCC() 
    {
        userAndAccountIds = new Set<String>();
        userIds = new Set<Id>();
        accountIds = new Set<Id>();
    }

    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        //Ejecuta la query de registros a procesar del batch: 
        return Database.getQueryLocator((new OpportunitiesSelector()).findZRMtoReassign());
    }

    global void execute(Database.BatchableContext bc, List<Opportunity> scope)
    {
        // 1.- Obtenemos el usuario generico
        String aliasCCUser = Lead_Offers__c.getinstance().ContactCenterUser__c;
        if(String.isNotBlank(aliasCCUser))
        {
            UsersSelector userQuery = new UsersSelector();
            List<User> defaultUser = userQuery.findUsersByAlias(new List<String>{aliasCCUser});

            if(! defaultUser.isEmpty())
            {
                defaultUserCC = defaultUser.get(0).id;
            }
        }

        // 2.- Recorremos las oportunidades y actualizamos información

        List<CallMeBackUtil.CallMeBackFull> cmbToInsert = new List<CallMeBackUtil.CallMeBackFull>();
        for(Opportunity opp : scope)
        {
            // Guardamos datos de la opp
            userAndAccountIds.add(opp.OwnerId+'#'+opp.AccountId);
            userIds.add(opp.OwnerId);
            accountIds.add(opp.AccountId);

            // Actualizamos la opp
            opp.OwnerId = defaultUserCC;
            opp.BusinessCode__c = Lead_Offers__c.getinstance().BusinessCode__c;
            opp.CloseDate = Date.today() + (Integer)Lead_Offers__c.getinstance().DaysToReassignOffer__c;


            // Creamos CMB
            CallMeBackUtil.CallMeBack cmb = new CallMeBackUtil.CallMeBack();
            cmb.name = opp.Account.Name;
            cmb.phone = opp.Account.Phone;
            cmb.bestTimeFrom = DateTime.newInstance(Date.Today(), opp.Account.PreferedContactStart__c.time());
            cmb.bestTimeUntil = DateTime.newInstance(Date.Today(), opp.Account.PreferedContactEnd__c.time());
            cmb.webIdentifier = opp.Account.WebId__c;
            cmb.businessCode = Lead_Offers__c.getinstance().BusinessCode__c;

            // Completamos el objeto con el resto de la información
            CallMeBackUtil.CallMeBackFull cmbFull = new CallMeBackUtil.CallMeBackFull();
            cmbFull.request = cmb;
            cmbFull.queueName = Lead_Offers__c.getinstance().VoiceQueue__c;
            cmbFull.businessHoursName = Lead_Offers__c.getinstance().BusinessHour__c;

            cmbToInsert.add(cmbFull);
        }

        // 3.- Update de Optys
        update scope;

        // 4.- Insertamos las CMB
        CallMeBackUtil.insertCallMeBack(cmbToInsert);

        // 5.- Obtiene si los Mediadores desasignados tienen otras Ofertas con los mismos Leads
        List<Opportunity> lstOpportunities = (new OpportunitiesSelector()).findByAccountAndOwner(this.accountIds, this.userIds);
        if(!lstOpportunities.isEmpty() && lstOpportunities != null)
        {
            for(Opportunity opp : lstOpportunities)
            {
                String toCheck = opp.OwnerId+'#'+opp.AccountId;
                if(userAndAccountIds.contains(toCheck))
                {
                    userAndAccountIds.remove(toCheck);
                }
            }
        }

        // 6.- Elimina los registros de AccountTeamMember correspondientes a los agentes desasignados y sus antiguos Leads
        List<AccountTeamMember> lstATMtoDelete = new List<AccountTeamMember>();
        List<AccountTeamMember> lstAccountTeamMembers = (new AccountTeamMemberSelector()).findByAccountAndUser(this.accountIds, this.userIds);
        if(!lstAccountTeamMembers.isEmpty() && lstAccountTeamMembers != null)
        {
            for(AccountTeamMember atm : lstAccountTeamMembers)
            {
                String toCheck = atm.UserId+'#'+atm.AccountId;
                if(userAndAccountIds.contains(toCheck))
                {
                    lstATMtoDelete.add(atm);
                }
            }
        }
        delete lstATMtoDelete;
    }

    global void execute(SchedulableContext sc)
    {
        database.executeBatch(new Batch_LeadOffersToReassignToCC(), 10);
    }

    global void finish(Database.BatchableContext bc) 
    {}
}