force-app/zurich-base/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/Account/recordTypes/Intermediary.recordType-meta.xml
<RecordType>
    <fullName>Intermediary</fullName>
    <active>true</active>
    <label>Intermediary</label>
</RecordType>

force-app/zurich-base/main/default/objects/KPI__c/KPI__c.object-meta.xml
<CustomObject>
    <description>SDM: KPIs de mediadores</description>
    <label>KPI</label>
    <nameField>
        <label>KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/KPI__c/fields/Income__c.field-meta.xml
<CustomField>
    <fullName>Income__c</fullName>
    <description>Ingresos totales</description>
    <inlineHelpText>Ingresos totales</inlineHelpText>
    <label>Ingresos</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/zurich-base/main/default/objects/KPI__c/fields/Intermediary__c.field-meta.xml
<CustomField>
    <fullName>Intermediary__c</fullName>
    <label>Intermediario</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KPIs</relationshipLabel>
    <relationshipName>KPIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/zurich-base/main/default/objects/KPI__c/fields/PA_PN__c.field-meta.xml
<CustomField>
    <fullName>PA_PN__c</fullName>
    <label>PN (pa)</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/zurich-base/main/default/objects/KPI__c/fields/PA_PoliciesPN__c.field-meta.xml
<CustomField>
    <fullName>PA_PoliciesPN__c</fullName>
    <description>Número de pólizas de producción nueva periodo anterior</description>
    <inlineHelpText>Número de pólizas de producción nueva periodo anterior</inlineHelpText>
    <label>Pólizas PN (pa)</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/KPI__c/fields/PN__c.field-meta.xml
<CustomField>
    <fullName>PN__c</fullName>
    <description>Prima producción nueva</description>
    <inlineHelpText>Prima producción nueva</inlineHelpText>
    <label>PN</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/zurich-base/main/default/objects/KPI__c/fields/PoliciesPN__c.field-meta.xml
<CustomField>
    <fullName>PoliciesPN__c</fullName>
    <description>Número de pólizas de producción nueva</description>
    <inlineHelpText>Número de pólizas de producción nueva</inlineHelpText>
    <label>Pólizas PN</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/KPI__c/fields/TotalLoad__c.field-meta.xml
<CustomField>
    <fullName>TotalLoad__c</fullName>
    <description>Carga siniestral total</description>
    <inlineHelpText>Carga siniestral total</inlineHelpText>
    <label>Carga Total</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/PlanComercial__c.object-meta.xml
<CustomObject>
    <description>SDM: Utilizado para representar el plan de negocio realizado por los directores.</description>
    <label>Plan Comercial</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/AccumulateType__c.field-meta.xml
<CustomField>
    <fullName>AccumulateType__c</fullName>
    <description>SDM: tipo de acumulado con el que se quiere comparar dentro del objeto KPI</description>
    <label>Accumulate type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
                <label>Current month</label>
            </value>
            <value>
                <fullName>YTD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Actual_KPI__c.field-meta.xml
<CustomField>
    <fullName>Actual_KPI__c</fullName>
    <description>SDM: el resultado de KPI calculado de forma automática para el plan de acción a través de todos los criterios establecidos en el mismo</description>
    <label>Actual KPI</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDM: usuario, de tipo RN o consultor, al que irá asociado el registro. Se utiliza de cara a que un Director pueda generar planes para los usuarios de los que es responsable.</description>
    <label>Assigned to</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Solo se puede asignar planes comerciales a usuarios de SDM</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>SDM RN</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>SDM Director</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PlanComercial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>SDM: fecha en la que finaliza el plan de acción (solo aplicable a tipo acumulado YTD)</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <description>SDM: indicador (campo) del KPI con el que se quiere comparar el objetivo</description>
    <label>Indicator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>PoliciesPN</fullName>
                <label>Pólizas PN</label>
            </value>
            <value>
                <fullName>PoliciesInForce</fullName>
                <label>Pólizas en vigor</label>
            </value>
            <value>
                <fullName>Portfolio</fullName>
                <label>Cartera</label>
            </value>
            <value>
                <fullName>APES</fullName>
            </value>
            <value>
                <fullName>Ratio_Retention</fullName>
                <label>% Retention Ratio</label>
            </value>
            <value>
                <fullName>Ratio_Claim</fullName>
                <label>% Sin Total</label>
            </value>
            <value>
                <fullName>Ratio_PNIncrease</fullName>
                <label>% Crec PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesPNIncreas</fullName>
                <label>% Crec Pólizas PN vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PoliciesInForceIncrease</fullName>
                <label>% Crec Pólizas vigor vs pa</label>
            </value>
            <value>
                <fullName>Ratio_PortIncrease</fullName>
                <label>% crecimiento cartera</label>
            </value>
            <value>
                <fullName>Totaldiscount</fullName>
                <label>% Dto. Total</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Intermediary__c.field-meta.xml
<CustomField>
    <fullName>Intermediary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>SDM: mediador sobre el que se quiere realizar la búsqueda de KPIs para el cálculo de las cifras realas para su comparación con el objetivo</description>
    <label>Intermediary</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La cuenta debe ser un agente</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agrupación Mediador, Intermediary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planes Comerciales</relationshipLabel>
    <relationshipName>PlanComercial</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/IsOwnedByHomeOffice__c.field-meta.xml
<CustomField>
    <fullName>IsOwnedByHomeOffice__c</fullName>
    <description>Devuelve true si el usuario propietario del registro es un Home Office</description>
    <formula>Owner:User.UserRole.DeveloperName = &apos;SDMHomeOffice&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Owned By Home Office</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/PAActualKPI__c.field-meta.xml
<CustomField>
    <fullName>PAActualKPI__c</fullName>
    <label>Actual KPI (PA)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>SDM: productos del que se quiere obtener la información de los KPIs</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autos</fullName>
                <label>Cars</label>
            </value>
            <value>
                <fullName>Hogar</fullName>
                <label>Home</label>
            </value>
            <value>
                <fullName>Inmuebles</fullName>
                <label>Estate</label>
            </value>
            <value>
                <fullName>Accidentes</fullName>
                <label>Accidents</label>
            </value>
            <value>
                <fullName>Comercios</fullName>
                <label>Commerce</label>
            </value>
            <value>
                <fullName>Patrimoniales</fullName>
                <label>Patrimonial</label>
            </value>
            <value>
                <fullName>Resp. Civil</fullName>
                <label>Civil liability</label>
            </value>
            <value>
                <fullName>Vida riesgo individual</fullName>
                <label>Individual risk life</label>
            </value>
            <value>
                <fullName>Vida riesgo colectivo</fullName>
                <label>Collective risk life</label>
            </value>
            <value>
                <fullName>Todos</fullName>
                <label>All</label>
            </value>
            <value>
                <fullName>Resto</fullName>
            </value>
            <value>
                <fullName>Communitdades</fullName>
                <label>Communities</label>
            </value>
            <value>
                <fullName>Resto Particulares</fullName>
                <isActive>false</isActive>
                <label>Rest Individuals</label>
            </value>
            <value>
                <fullName>Resto PYMEs</fullName>
                <isActive>false</isActive>
                <label>Rest of SMEs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>SDM: segmento del que se quiere obtener la información de los KPIs</description>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Individuals</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>SMEs</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Large companies</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Life risk</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>All products</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>SDM: fecha en la que comienza el plan de acción (solo aplicable a tipo acumulado YTD)</description>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/zurich-base/main/default/objects/PlanComercial__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zonas_Plan_Comercial</valueSetName>
    </valueSet>
</CustomField>

force-app/zurich-sdm-app/main/default/objects/SDMCommercialPlan__mdt/SDMCommercialPlan__mdt.object-meta.xml
<CustomObject>
    <description>SDM: Configuracion para la relacion de Indicadores de objeto KPI con el calculo del Plan Comercial</description>
    <label>SDMCommercialPlan</label>
    <pluralLabel>SDMCommercialPlans</pluralLabel>
</CustomObject>

force-app/zurich-sdm-app/main/default/objects/SDMCommercialPlan__mdt/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <description>SDM: Valor de picklist del campo Indicator__c del objeto plan comercial</description>
    <label>Indicator</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/globalValueSets/Zonas_Plan_Comercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>11 BARCELONA</fullName>
    </customValue>
    <customValue>
        <fullName>12 CATALUNYA ANDORRA</fullName>
    </customValue>
    <customValue>
        <fullName>13 BARCELONA GRANDES BROKERS</fullName>
    </customValue>
    <customValue>
        <fullName>21 LEVANTE NORTE</fullName>
    </customValue>
    <customValue>
        <fullName>22 BALEARES</fullName>
    </customValue>
    <customValue>
        <fullName>23 CENTRO ARAGÓN</fullName>
    </customValue>
    <customValue>
        <fullName>24 LEVANTE SUR</fullName>
    </customValue>
    <customValue>
        <fullName>31 MADRID</fullName>
    </customValue>
    <customValue>
        <fullName>41 SUR ORIENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>42 CANARIAS</fullName>
    </customValue>
    <customValue>
        <fullName>43 SUR OCCIDENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>51 NORTE ORIENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>52 NORTE OCCIDENTAL</fullName>
    </customValue>
    <customValue>
        <fullName>61 CENTRALIZADOS</fullName>
    </customValue>
    <customValue>
        <fullName>Todos</fullName>
    </customValue>
    <customValue>
        <fullName>21 LEVANTE</fullName>
        <isActive>false</isActive>
        <label>21 LEVANTE</label>
    </customValue>
    <description>Valores de zona a usar como eje para planes comerciales</description>
    <masterLabel>Zonas Plan Comercial</masterLabel>
</GlobalValueSet>

force-app/zurich-sdm-app/main/default/classes/PlanComercialSDMTest.cls
/**
 * Test para la clase PlanComercialSDM
 *
 * @author nts (agonzalezisasi)
 * @date 27/07/2021
 */
@isTest
private with sharing class PlanComercialSDMTest
{
    static final String PLAN_NAME = 'Plan 1';
    /**
     * Metodo comun para todas los metodos de test. Inicializa los datos de prueba
     *
     * @author nts (agonzalezisasi)
     * @date 29/06/2021
     */
    @TestSetup
    private static void makeData() 
    {
        TestDataFactorySDM.PlanComercialSetupData();
    }

    /**
     * Test del metodo que calcula el KPI de una serie de Planes comerciales
     *
     * @author nts (agonzalezisasi)
     * @date 27/07/2021
     */
    @isTest
    private static void testCalculateRealKPI_ok()
    {
        // Se recuperan las planes comerciales
        List<PlanComercial__c> plans = [
            SELECT Id, CreatedById, AssignedTo__c, StartDate__c, EndDate__c, IsOwnedByHomeOffice__c,
                   Indicator__c, Intermediary__c, Product__c, Segment__c, AccumulateType__c, Zone__c
            FROM PlanComercial__c
        ];
        System.assertEquals(4, plans.size(), 'Deberia haber 4 planes antes del test');


        // Ejecucion del Test -------------------------------------------------
        Test.startTest();
        PlanComercialSDM sdm = new PlanComercialSDM();
        // Configuracion de los indicadores de los planes comerciales
        sdm.testSettingsIndicator = new List<SDMCommercialPlan__mdt>();
        sdm.testSettingsIndicator.add(TestDataFactorySDM.generateSDMSettingsPlan(
            'PN', PlanComercialSDM.SETTINGS_CALCULATION_TYPE_SUM, 'PN__c', null, true, 'PA_PN__C'));
        sdm.testSettingsIndicator.add(TestDataFactorySDM.generateSDMSettingsPlan(
            'Ratio_Claim', PlanComercialSDM.SETTINGS_CALCULATION_TYPE_RATIO, 'TotalLoad__c', 'Income__c', false, null));
        sdm.testSettingsIndicator.add(TestDataFactorySDM.generateSDMSettingsPlan(
            'Ratio_PoliciesPNIncreas', PlanComercialSDM.SETTINGS_CALCULATION_TYPE_GROWTH, 'PoliciesPN__c', 'PA_PoliciesPN__c', false, null));
        
        // Calculo del KPI para los planes
        sdm.calculateRealKPI(plans);
        Test.stopTest();


        // Comprobacion del resultado -----------------------------------------
        List<PlanComercial__c> checkPlans = [
            SELECT Id, Name, Actual_KPI__c, PAActualKPI__c FROM PlanComercial__c
            WHERE Actual_KPI__c != null
        ];
        System.assertEquals(4, checkPlans.size(), 'Deberia haber 4 planes');
        // Relacionamos el nombre del plan con el resultado del calculo que deberia dar
        Map<String, Decimal> mapPlanResult = new Map<String, Decimal> {
            PLAN_NAME => 10,
            'Plan 2' => 0.4,
            'Plan 3' => 0.75,
            'Plan 4' => 13
        };

        // Relacionamos el nombre del plan con el resultado del cálculo que debería dar para el periodo anterior
        Map<String, Decimal> mapPlanResultPA = new Map<String, Decimal>{PLAN_NAME => 8, 'Plan 4' => 10};

        // Comprobamos el resultado del calculo de cada plan
        for(PlanComercial__c plan: checkPlans) {
            Decimal planResult = mapPlanResult.get(plan.Name);
            System.assertEquals(planResult, plan.Actual_KPI__c, 'El calculo deberia ser ' + planResult + ' para el plan ' + plan.Name);

            // Si es un plan (Plan 1 y Plan 4) sobre los que se ha calculado el KPI del periodo anterior
            if (mapPlanResultPA.containsKey(plan.Name))
            {
                Decimal planResultPA = mapPlanResultPA.get(plan.Name);
                Assert.areEqual(planResultPA, plan.PAActualKPI__c, 'El cálculo del KPI del periodo anterior debería ser ' + planResultPA + ' para el plan ' + plan.Name);
            }
        }
    }
        
    /**
     * Test del metodo que calcula el KPI de una serie de Planes comerciales
     *
     * @author nts (agonzalezisasi)
     * @date 27/07/2021
     */
    @isTest
    private static void testCalculateRealKPI_no_settings()
    {
        // Se recuperan las planes comerciales
        List<PlanComercial__c> plans = [
            SELECT Id, CreatedById, AssignedTo__c, StartDate__c, EndDate__c, IsOwnedByHomeOffice__c,
                   Indicator__c, Intermediary__c, Product__c, Segment__c, AccumulateType__c
            FROM PlanComercial__c
        ];
        System.assertEquals(4, plans.size(), 'Deberia haber 4 planes antes del test');

        // Ejecucion del Test -------------------------------------------------
        Test.startTest();
        PlanComercialSDM sdm = new PlanComercialSDM();
        // Dejamos la configuracion vacia para que no encuentre el Indicador del plan en la configuracion
        sdm.testSettingsIndicator = new List<SDMCommercialPlan__mdt>();
        // Calculo del KPI para los planes
        sdm.calculateRealKPI(plans);
        Test.stopTest();

        // Comprobacion del restulado -----------------------------------------
        String className = PlanComercialSDM.CLASS_NAME;
        List<Error_Log__c> errorLogs = [SELECT Id FROM Error_Log__c WHERE Source_Class__c = :className];
        System.assertEquals(false, errorLogs.isEmpty(), 'Deberia haber error logs');
    }

    /**
     * Test del metodo que elimina planes anuales de usuarios que ya no tienen visibilidad sobre un mediador
     *
     * @author nts (agonzalezisasi)
     * @date 13/10/2021
     */
    @isTest
    private static void testRemoveAnnualPlans()
    {
        // Recuperamos un ATM
        List<AccountTeamMember> atms = [
            SELECT Id, UserId, AccountId 
            FROM AccountTeamMember 
            WHERE User.Profile.Name = :TestDataFactorySDM.RN_PROFILE
            LIMIT 1
        ];
        System.assertEquals(1, atms.size(), 'Deberia haber al menos 1 registro de ATM');
        // Obtenemos el id de usuario 1
        User rnUser = new User(Id=atms[0].UserId);
        // Y el id de mediador 1 para crear 1 plan
        Account intermediary = new Account(Id= atms[0].AccountId);

        // Creamos el plan comercial anual
        Id rtAnnualPlanId = (new PlanComercialSelector()).rtPlanAnualId;
        List<PlanComercial__c> intermediaryPlans = TestDataFactorySDM.generatePlans(
            new List<Account>{intermediary}, 1
        );
        for(PlanComercial__c plan: intermediaryPlans) {
            plan.Name = PLAN_NAME;
            plan.StartDate__c = Date.newInstance(2021, 1, 1);
            plan.EndDate__c = Date.newInstance(2021, 12, 31);
            plan.AccumulateType__c = PlanComercialSelector.ACCUMULATE_TYPE_YRD;    
            plan.TargetKPICurrency__c = 1;
            plan.AssignedTo__c = rnUser.Id;
            plan.RecordTypeId = rtAnnualPlanId;
        }

        // lo insertamos
        System.runAs(rnUser) {
            insert intermediaryPlans;
        }

        // Comprobamos que existe
        // De nuevo recuperamos los planes anuales con mediadores
        List<PlanComercial__c> plans = [
            SELECT Id 
            FROM PlanComercial__c 
            WHERE RecordtypeId = :rtAnnualPlanId
            AND Intermediary__c != null
        ];
        System.assertEquals(1, plans.size(), 'Deberia haber 1 plan anual');

        // Y lo borramos el primer ATM para comprobar que solo se elimna esa relacion y no ambas
        delete atms;

        Test.startTest();
        PlanComercialSDM sdm = new PlanComercialSDM();
        sdm.removeAnnualPlans(atms);
        Test.stopTest();

        // Comprobamos el resultado del test

        // De nuevo recuperamos los planes anuales con mediadores
        List<PlanComercial__c> existingPlans = [
            SELECT Id 
            FROM PlanComercial__c 
            WHERE RecordtypeId = :rtAnnualPlanId
            AND Intermediary__c != null
        ];
        // Ahora deberia haber 1 plan anual
        System.assertEquals(0, existingPlans.size(), 'Deberia haber 0 planes anuales con mediador');
    }

    /**
     * Test del metodo que elimina planes anuales de usuarios que ya no tienen visibilidad sobre un mediador
     *
     * @author aberuete
     * @date 11/04/2023
     */
    @isTest
    private static void testIfIntermediaryAndUserDeletedEliminatePlans()
    {
        // Recuperamos un ATM
        AccountTeamMember atm = [
            SELECT Id, UserId, AccountId 
            FROM AccountTeamMember 
            WHERE User.Profile.Name = :TestDataFactorySDM.RN_PROFILE
            LIMIT 1
        ];
         // Obtenemos el id de usuario 1
         User rnUser = new User(Id=atm.UserId);
         // Y el id de mediador 1 para crear 1 plan
         Account intermediary = new Account(Id= atm.AccountId);

         // Creamos el plan comercial anual
        Id rtAnnualPlanId = (new PlanComercialSelector()).rtPlanAnualId;
        List<PlanComercial__c> intermediaryPlans = TestDataFactorySDM.generatePlans(
            new List<Account>{intermediary}, 1
        );

        intermediaryPlans[0].Name = PLAN_NAME;
        intermediaryPlans[0].StartDate__c = Date.newInstance(2021, 1, 1);
        intermediaryPlans[0].EndDate__c = Date.newInstance(2021, 12, 31);
        intermediaryPlans[0].AccumulateType__c = PlanComercialSelector.ACCUMULATE_TYPE_YRD;    
        intermediaryPlans[0].TargetKPICurrency__c = 1;
        intermediaryPlans[0].AssignedTo__c = rnUser.Id;
        intermediaryPlans[0].RecordTypeId = rtAnnualPlanId;
        
        // lo insertamos
        System.runAs(rnUser) 
        {
            insert intermediaryPlans;
        }

        Set<String> deletedRelations = new Set<String>();
        deletedRelations.add(atm.AccountId + '#' + atm.UserId);

        Test.startTest();
        PlanComercialSDM sdm = new PlanComercialSDM();
        sdm.ifIntermediaryAndUserDeletedEliminatePlans(intermediaryPlans, deletedRelations);
        Test.stopTest();

        List<PlanComercial__c> existingPlans = [
            SELECT Id 
            FROM PlanComercial__c 
            WHERE RecordtypeId = :rtAnnualPlanId
            AND Intermediary__c != null
        ];

        System.assertEquals(0, existingPlans.size(), 'Deberia haber 0 planes anuales con mediador');
    }

    /**
     * Test que comprueba que se generan correctamente los mapas de intermediarios para calcular posteriormente los kpis
     *
     * @author aberuete
     * @date 11/04/2023
     */
    @isTest
    private static void testGenerateMapIntermediariesToCalculateKpi()
    {
        PlanComercialSDM sdm = new PlanComercialSDM();
        sdm.mapIntermediariesByUserId = new Map<Id, Set<Id>>();
        sdm.mapIntermediariesByUserIdAndAgrupationId = new Map<Id, Map<Id, Set<Id>>>();
        sdm.allIntermediaries = new Set<Id>();

        List<AccountTeamMember> atms = [
            SELECT Id, UserId, AccountId,Account.ParentId 
            FROM AccountTeamMember 
            WHERE User.Profile.Name = :TestDataFactorySDM.RN_PROFILE and Account.ParentId != null
            LIMIT 1
        ];

        Test.startTest();
        sdm.generateMapIntermediariesToCalculateKpi (atms);
        Test.stopTest();

        List<Id> userIds = new List<Id> (sdm.mapIntermediariesByUserId.keySet());
        userIds.add(new List<Id>(sdm.mapIntermediariesByUserIdAndAgrupationId.keySet())[0]);
        List<Id> accountsIds = new List<Id> (sdm.mapIntermediariesByUserId.values()[0]);
        accountsIds.add(new List<Id>((sdm.mapIntermediariesByUserIdAndAgrupationId.values()[0]).keySet())[0]);
        accountsIds.add(new List<Id>((sdm.mapIntermediariesByUserIdAndAgrupationId.values()[0]).values()[0])[0]);

        System.assertEquals(atms[0].UserId, userIds[0], 'El id de usuario del atm debería estar en el mapa de intermediarios por usuario');
        System.assertEquals(atms[0].AccountId, accountsIds[0], 'El id de la cuenta del atm debería estar en el mapa');
        System.assertEquals(atms[0].UserId, userIds[1], 'El id de usuario del atm debería estar en el mapa de intermediario por usuario por agrupación');
        System.assertEquals(atms[0].Account.ParentId, accountsIds[1], 'El id de la cuenta de agrupación del atm debería estar en el mapa');
        System.assertEquals(atms[0].AccountId, accountsIds[2], 'El id de la cuenta del atm debería estar en el mapa de intermediario por usuario por agrupación');
        System.assertEquals(true, sdm.allIntermediaries.contains(atms[0].AccountId), 'El id de la cuenta del atm debería estar en el mapa de todos los intermediarios');
    }
    /**
    * Test que comprueba si se crea correctamente el mapa de kpis por intermediario
    *
    * @author aberuete
    * @date 11/04/2023
    */
    @isTest
    private static void testIfKpisNotEmptyGenerateMapKpiIntermediary()
    {
        PlanComercialSDM sdm = new PlanComercialSDM();
        List<KPI__c> kpis = [Select id,Intermediary__c from Kpi__c where Intermediary__c != null limit 2];

        Test.startTest();
        sdm.ifKpisNotEmptyGenerateMapKpiIntermediary (kpis);
        Test.stopTest();
        
        List<Id> intermediariyIds = new List<Id>(sdm.mapKPIsByIntermediary.keySet());

        System.assertEquals(kpis[0].Intermediary__c, intermediariyIds[0], 'El intermediario debería estar en el mapa');
        System.assertEquals(kpis[0], sdm.mapKPIsByIntermediary.values()[0][0], 'El primer kpi debería de estar en el mapa');
    }

    /**
     * Test que comprueba si se obtiene correctamente los kpis anuales del último mes
     *
     * @author aberuete
     * @date 11/04/2023
     */
    @isTest
    private static void testGetKpisAnualOfTheLastMonth()
    {
        PlanComercialSDM sdm = new PlanComercialSDM();
        Set<String> fields = new Set<String>();
        fields.addAll(PlanComercialSDM.KPI_FILTER_FIELDS);
        List<KPI__c> kpis = new List<KPI__c>();
        Boolean containsYTD = true;
        List<Account> intermediaryList = [Select id from Account where recordtype.developerName = 'Intermediary' ];
        Set<Id> intermediaries = new Map <Id,Account>(intermediaryList).keySet();
        List<KPI__c> kpisToVerify = [Select id from KPI__c where CalcYear__c = '2021' and CalcMonth__c =: sdm.lastMonthOfYear];

        for (KPI__c kpi :kpisToVerify)
        {
            kpi.Temporalidad__c = 'YTD';
        }
        update kpisToVerify;
        
        Test.startTest();
        kpis = sdm.getKpisAnualOfTheLastMonth (intermediaries, fields, containsYTD, kpis);
        Test.stopTest();

        Set<Id> kpisIdsToVerify = new Map<Id,Kpi__c> (kpisToVerify).keySet();
        Set<Id> kpisIds = new Map<Id,Kpi__c> (kpis).keySet();
        System.assertEquals(true, kpisIds.equals(kpisIdsToVerify), 'Los dos conjuntos de ids de kpis deben ser iguales');
    }

     /**
     * Test que comprueba si se obtienen correctamente los campos del métadato SDMCommercialPlan__mdt
     *
     * @author aberuete
     * @date 17/04/2023
     */
    @isTest
    private static void testIfIndicatorSettingNotNUll()
    {
        PlanComercialSDM sdm = new PlanComercialSDM();
        sdm.containsMonths = false;
        sdm.containsYTD = false;
        sdm.userIdsFromPlans = new Set<Id>();
        Set<String> kpiFields = new Set<String>();
        SDMCommercialPlan__mdt indicatorSetting = [Select id,FirstField__c,SecondField__c,ThirdField__c,CalculatedPreviousPeriod__c,PreviousPeriodField__c from SDMCommercialPlan__mdt where Indicator__c = 'PN' limit 1 ];
        PlanComercial__c plan = [Select id,AccumulateType__c,AssignedTo__c from PlanComercial__c where AccumulateType__c != null and AssignedTo__c!= null  limit 1 ];

        Test.startTest();
        kpiFields = sdm.ifIndicatorSettingNotNUll (indicatorSetting, kpiFields, plan);
        Test.stopTest();

        Set<String> kpiFieldsResult = new Set<String>{'PN__c','PA_PN__c'};
        Set<Id> userIdsResult = new Set<Id>{plan.AssignedTo__c};

        System.assertEquals(true, kpiFields.equals(kpiFieldsResult), 'Los campos de kpis deberían ser iguales');
        System.assertEquals(true, sdm.userIdsFromPlans.equals(userIdsResult), 'El id del usuario del plan debería estar en el conjunto de ids de usuarios');
    }

    /**
     * Test que comprueba si se obtienen correctamente los intermediarios asociados a un plan comercial
     *
     * @author aberuete
     * @date 17/04/2023
     */
    @isTest
    private static void testGetIdsIntermediariesOfPlan()
    {
        PlanComercialSDM sdm = new PlanComercialSDM();
        sdm.mapIntermediariesByUserId = new Map<Id, Set<Id>>();
        sdm.mapIntermediariesByUserIdAndAgrupationId = new Map<Id, Map<Id, Set<Id>>>();
        Set<Id> listIntermediaries = new Set<Id>();

        PlanComercial__c plan = [Select id,Intermediary__c,AssignedTo__c  from PlanComercial__c where Intermediary__c!= null and AssignedTo__c != null and Intermediary__r.RecordType.DeveloperName = 'intermediary' limit 1 ];
        PlanComercial__c planWithoutIntermediary = [Select id,Intermediary__c,AssignedTo__c  from PlanComercial__c where Intermediary__c = null and AssignedTo__c != null  limit 1 ];
        
        sdm.mapIntermediariesByUserId.put(plan.AssignedTo__c, listIntermediaries);
        listIntermediaries.add(plan.Intermediary__c);

        Test.startTest();
        Set<Id> intermediaries = sdm.getIdsIntermediariesOfPlan (plan, plan.AssignedTo__c);
        Set<Id> intermediariesNotInPlan = sdm.getIdsIntermediariesOfPlan (planWithoutIntermediary, plan.AssignedTo__c);
        Test.stopTest();

        System.assertEquals(true, intermediaries.equals(new Set<Id>{plan.Intermediary__c}), 'El id de intermediario del plan debería estar en el conjunto de ids devuelto');
        System.assertEquals(true, intermediariesNotInPlan.equals(sdm.mapIntermediariesByUserId.values()[0]), 'El id de intermediario del plan debería estar en el mapa de intermediario por usuario');
    }

    /**
     * Test que comprueba si se obtienen correctamente los kpis de un plan comercial para recalcular su actual kpi
     *
     * @author aberuete
     * @date 17/04/2023
     */
    @isTest
    private static void testGetKpisToCalculate()
    {
        PlanComercialSDM sdm = new PlanComercialSDM();
        sdm.mapKPIsByIntermediary = new Map<Id, List<KPI__c>>();

        KPI__c kpiFromQuery = [Select id,EstructuraUnificada__c,EstructuraDetalle__c,Temporalidad__c,Intermediary__c,CalcYear__c, CalcMonth__c from KPI__c where CalcYear__c = '2021' and CalcMonth__c = '8' limit 1];
        PlanComercial__c plan = [Select id,Segment__c,Product__c,AccumulateType__c,Zone__c,StartDate__c,EndDate__c from PlanComercial__c where Segment__c=: kpiFromQuery.EstructuraUnificada__c and Product__c =:kpiFromQuery.EstructuraDetalle__c and AccumulateType__c=:kpiFromQuery.Temporalidad__c limit 1];
        plan.Zone__c= 'Todos';
        update plan;

        List<KPI__c> kpisOfIntermediary = new List<KPI__c>();
        sdm.mapKPIsByIntermediary.put(kpiFromQuery.Intermediary__c, kpisOfIntermediary);
        kpisOfIntermediary.add(kpiFromQuery);

        Test.startTest();
        List<KPI__c> kpis = sdm.getKpisToCalculate (new Set<Id>{kpiFromQuery.Intermediary__c}, plan);
        Test.stopTest();

        System.assertEquals(kpiFromQuery, kpis[0], 'El kpi debería estar en la lista devuelta');
    }

     /**
     * Test que comprueba si se añade correctamente el plan comercial a actualizar
     *
     * @author aberuete
     * @date 17/04/2023
     */
    @isTest
    private static void testUpdatePlanWithRealKpi()
    {
        PlanComercialSDM sdm = new PlanComercialSDM();
        List<PlanComercial__c> plansToUpdate = new List<PlanComercial__c> ();

        List<KPI__c> kpiFromQuery = [Select id,EstructuraUnificada__c,EstructuraDetalle__c,Temporalidad__c,Intermediary__c,CalcYear__c, CalcMonth__c,PN__c,PA_PN__c from KPI__c where CalcYear__c = '2021' and CalcMonth__c = '8' limit 1];
        PlanComercial__c plan = [Select id,Segment__c,Product__c,AccumulateType__c,Zone__c,StartDate__c,EndDate__c,IsOwnedByHomeOffice__c,Indicator__c from PlanComercial__c where Segment__c=: kpiFromQuery[0].EstructuraUnificada__c and Product__c =:kpiFromQuery[0].EstructuraDetalle__c and AccumulateType__c=:kpiFromQuery[0].Temporalidad__c and Indicator__c = 'PN'  limit 1];
        plan.Zone__c= 'Todos';
        update plan;

        Test.startTest();
        plansToUpdate = sdm.updatePlanWithRealKpi (plansToUpdate,kpiFromQuery, plan);
        Test.stopTest();

        System.assertEquals(plan.Id, plansToUpdate[0].Id, 'El plan debería estar en los planes a actualizar');
    }

     /**
     * Test que comprueba si se actualizan correctamente los planes comerciales tras recalcular sus kpis
     *
     * @author aberuete
     * @date 17/04/2023
     */
    @isTest
    private static void testCalculateRealKpiAndUpdatePlans()
    {
        PlanComercialSDM sdm = new PlanComercialSDM();
        sdm.mapKPIsByIntermediary = new Map<Id, List<KPI__c>>();
        sdm.mapIntermediariesByUserId = new Map<Id, Set<Id>>();
        sdm.mapIntermediariesByUserIdAndAgrupationId = new Map<Id, Map<Id, Set<Id>>>();
        Set<Id> listIntermediaries = new Set<Id>();
        List<PlanComercial__c> plansToUpdate = new  List<PlanComercial__c> ();

        List<KPI__c> kpiFromQuery = [Select id,EstructuraUnificada__c,EstructuraDetalle__c,Temporalidad__c,Intermediary__c,CalcYear__c, CalcMonth__c,PN__c,PA_PN__c from KPI__c where CalcYear__c = '2021' and CalcMonth__c = '8' and Intermediary__c != null  limit 1];
        List<PlanComercial__c> planToUpdate = [Select id,AssignedTo__c,Segment__c,Product__c,AccumulateType__c,Zone__c,StartDate__c,EndDate__c,IsOwnedByHomeOffice__c,Indicator__c,Actual_KPI__c,Intermediary__c from PlanComercial__c where Segment__c=: kpiFromQuery[0].EstructuraUnificada__c and Product__c =:kpiFromQuery[0].EstructuraDetalle__c and AccumulateType__c=:kpiFromQuery[0].Temporalidad__c and Indicator__c = 'PN' and Intermediary__c =:kpiFromQuery[0].Intermediary__c and AssignedTo__c != null  limit 1];
        planToUpdate[0].Zone__c= 'Todos';
        update planToUpdate[0];
        
        List<KPI__c> kpisOfIntermediary = new List<KPI__c>();
        sdm.mapKPIsByIntermediary.put(kpiFromQuery[0].Intermediary__c, kpisOfIntermediary);
        kpisOfIntermediary.add(kpiFromQuery[0]);

        sdm.mapIntermediariesByUserId.put(planToUpdate[0].AssignedTo__c, listIntermediaries);
        listIntermediaries.add(planToUpdate[0].Intermediary__c);

        Test.startTest();
        sdm.calculateRealKpiAndUpdatePlans (planToUpdate, plansToUpdate);
        Test.stopTest();

        PlanComercial__c planAfterUpdate = [Select id,Actual_KPI__c from PlanComercial__c where id =: planToUpdate[0].id ];
      
        System.assertEquals(null, planToUpdate[0].Actual_KPI__c, 'El valor debería ser nulo');
        System.assertNotEquals(null, planAfterUpdate.Actual_KPI__c, 'El valor no debería ser nulo tras actualizarse el plan');
    }

}