force-app/zurich-base/main/default/objects/AdminSetupParameter__mdt/AdminSetupParameter__mdt.object-meta.xml
<CustomObject>
    <description>Metadata configuration for general use. Configured as a Name/Value pair</description>
    <label>AdminSetupParameter</label>
    <pluralLabel>AdminSetupParameters</pluralLabel>
</CustomObject>

force-app/zurich-base/main/default/objects/AdminSetupParameter__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Text to explain the purpose of the configured data.</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/zurich-base/main/default/objects/AdminSetupParameter__mdt/fields/KeyName__c.field-meta.xml
<CustomField>
    <fullName>KeyName__c</fullName>
    <description>The representing text for the configured value.</description>
    <label>KeyName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/AdminSetupParameter__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The configured value</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/zurich-base/main/default/objects/purecloud__PureCloud_Queue__c/fields/IsSurveyable__c.field-meta.xml
<CustomField>
    <fullName>IsSurveyable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que determina si la cola es elegible para encuesta o no</description>
    <inlineHelpText>Campo que determina si la cola es elegible para encuesta o no</inlineHelpText>
    <label>Is Surveyable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/zurich-base/main/default/classes/SendSurveyButtonControllerTest.cls
@isTest
public class SendSurveyButtonControllerTest
{
    @isTest
    static void test_getTransferPollPhoneNumber_ok()
    {
        SendSurveyButtonController.testListPollPhoneNumber = new List<AdminSetupParameter__mdt> {
            new AdminSetupParameter__mdt(
                Label='TestMetadataPollNumber',
                DeveloperName='TestMetadataPollNumber',
                KeyName__c='TestMetadataPollNumber',
                Value__c='+34999999999',
                Description__c='TestDescription'
                )
        };

        Test.startTest();
        String pollPhoneNumberResult = SendSurveyButtonController.getTransferPollPhoneNumber();
        Test.stopTest();

        System.assertEquals(SendSurveyButtonController.testListPollPhoneNumber.get(0).Value__c, pollPhoneNumberResult, 'PhoneNumber is the same');
    }
    
    @TestSetup
        static void makeData()
        {
            List<purecloud__PureCloud_Queue__c> testingGenesysQueues = TestDataFactory.generateGenesysQueues(5);
            testingGenesysQueues[1].IsSurveyable__c = true;
            insert testingGenesysQueues;
        }

    @IsTest
    static void test_getAllQueues_ok()
    {
        List<purecloud__PureCloud_Queue__c> totalQueues = [SELECT Id, Name, IsSurveyable__c FROM purecloud__PureCloud_Queue__c];
    
        Test.startTest();
        List<purecloud__PureCloud_Queue__c> selectedQueues = SendSurveyButtonController.getGenesysCloudQueues();
        Test.stopTest();
    
        System.assertEquals(totalQueues.size(), selectedQueues.size(), 'No hay las colas esperadas');

    }
}